### ISSUE TITLE
AC Meetings should not be scheduled to overlap All WG meetings

### ISSUE THREAD

**Issue by dwsinger** [w3c/w3process#1]
Transferred from https://www.w3.org/community/w3process/track/issues/55
State: Open

**Comment by chaals** [comment]
I am opposed to putting this constraint in the process document, which doesn't define all-group meetings anyway. It might be desirable, but it seems over-prescriptive for Process.

**Comment by dwsinger** [comment]
I also do not see this as a process question, but operational. Can we transfer this to something/someone else?

**Comment by dwsinger** [comment]
Agreed operational.
