### ISSUE TITLE
Should the process allow REC->WD transition directly?

### ISSUE THREAD

**Issue by dbaron** [w3c/w3process#103]
This is a followup to the third of the issues in #95, and is perhaps a bit more subtle than the rest.

The process currently allows transitions from REC to CR in order to develop an edited or amended recommendation.  It also then allows transitions from CR to WD for further work.

But the process does not allow directly transitioning from REC to WD.

It seems to me that either:
1. the process should allow transitioning directly from REC to WD as part of the process of developing an Edited or Amended Recommendation (I can imagine a WG wanting to publish a WD as part of developing an Edited Recommendation because they think a document isn't quite ready for CR), or
2. the transition from CR to WD should be disallowed for CRs that are part of the development of an Edited or Amended Recommendation, on the theory that the process of developing an Edited/Amended Recommendation always keeps the document at CR or higher.

Otherwise it seems odd to allow the WD state as part of the process of developing an Edited/Amended Recommendation, but disallow *starting* the process with that state.

**Comment by dwsinger** [comment]
I love completeness checking. I think the second option is probably the one that matches expectations, but I wonder whether such abstrusities need to be clear (now)?

**Comment by dbaron** [comment]
Yeah, this issue probably isn't high priority, although it's also entirely possible a working group will bring it up.

**Comment by swickr** [comment]
Perhaps #110 would resolve this

**Comment by dwsinger** [comment]
#110 is about confusion about whether an amended rec IS a candidate rec or merely follows the same progression path...why does it help avoiding a bounce through CR on the way from Rec to WD?

**Comment by dwsinger** [comment]
deferred to next year

**Comment by dwsinger** [comment]
leaving hanging until someone thinks it's a problem

**Comment by chaals** [comment]
We should look at dealing with versioned specs in the Process, which might lead to a simplified path from REC vN -> FPWD vN+1 or CR vN -> FPWD vN+1 (without requiring any given numbering scheme).

**Comment by dwsinger** [comment]
I think we need a comprehensive review of document progression and charter management. The process and patent policy were written with a mindset that a WG develops a single Rec. within a single charter period and finishes it and closes, walking away. None of those a true. This is an example of a maintenance gap, but I bet there are others.

**Comment by jeffjaffe** [comment]
> 
> 
> I think we need a comprehensive review of document progression and charter management. The process and patent policy were written with a mindset that a WG develops a single Rec. within a single charter period and finishes it and closes, walking away. None of those a true. This is an example of a maintenance gap, but I bet there are others.

Pointer to the summary of the last time we looked at similar issues --> https://lists.w3.org/Archives/Member/w3c-ac-forum/2016AprJun/0176.html

**Comment by frivoal** [comment]
This has now been resolved by #562. @dbaron, Sorry for the incredibly long wait.
