### ISSUE TITLE
Audit of Members / Quorum?

### ISSUE THREAD

**Issue by edent** [w3c/w3process#107]
I recently tried to contact several UK based AC members.  Many of the individuals I contacted were no longer employed by their organisations.  In all cases, the organisation appeared unaware that they were AC members and had no nominated replacement.

This has a number of implications for process.

> 5% or more of the Advisory Committee support the appeal request

Does that mean 5% of all votes? Or 5% of all members? If the latter, votes are diluted by AC members who are no longer active participants.

> Our experience is that very few AC Representatives attend face to face meetings or vote on ballots

Perhaps a high percentage of **active** AC reps *do* vote.

My suggestion - possibly for a future process update - comprises of two changes.

1. A mechanism to audit AC members.  And, by extension, remove members who are no long participating.
2. That it is made explicit that certain votes require a quorum of (e.g.) 50% of active members.

(Related to #76 and #48 )

**Comment by jeffjaffe** [comment]
Terence, the 5% is 5% of the organizations that are members.  It is not related to votes.

If a member chooses not to be active for any reason - that is there choice - but in the current system they still deserve all rights of membership.

I don't understand what you mean by removing members who do not participate.  If a member "participates" by paying a membership fee, but does nothing else - would you remove them?  More generally, what are your criteria?

**Comment by dwsinger** [comment]
I think there are at least two questions here; do we keep the list of AC Reps up to date, checking that a living person who knows that they are the AC Rep and reads emails is at the end of the email address/ And do we need to have some sort of 'good standing' requirement for some votes at the AC (which one presumes that a zombie would fail)?

**Comment by dwsinger** [comment]
deferring to the team to manage zombies on the AC list; should they try to contact everyone periodically? we don't see a process question.
