### ISSUE TITLE
Voting notice before it starts or before it ends?

### ISSUE THREAD

**Issue by dwsinger** [w3c/w3process#109]
Section 3.4 "notify the group that a vote will be held at least 7 days before voting ends, describing the proposal to be voted on and the mechanism to vote,"

If the vote is open for 14 days, is the deadline to notify the group really half-way through the voting period? Or do we require notice at the earlier of beginning of voting or 7 days before the end? Or do we require notice 7 days before beginning voting? Is there a minimum or maximum period voting is open for (on rather suspects a vote that's open for 10 minutes is not acceptable).

Suggest: votes must be open for voting for at least 7 days, and the group must be notified of the opportunity to vote no later than at the beginning of voting.

**Comment by chaals** [comment]
The deadline is 7 days before the vote ends. For example, if it becomes clear during a face to face meeting that there is an issue which can only be resolved with a vote, then it might be best to record current votes, and when the minutes of the meeting and arguments are available and people have cahtted about the meeting, and the chair or Team contact or whoever is going to do the work has returned to a place where they have the luxury to write emails in peace, inform the group that the voting will remain open for another 7 days.

In general it is probably a good idea to inform the group when the vote is opened, and nothing prevents that happening. Requiring it formally seems like bureaucracy that can conflict with the needs of reality.

**Comment by dwsinger** [comment]
OK, got it, so we should insert the minimum voting period (I think 7 days is reasonable), and otherwise could leave the text as is, with maybe an addition of "it is good practice to alert the group as close to the opening of voting as possible".

**Comment by dwsinger** [comment]
closing, since we reverted the PR #81 that this is commenting on
