### ISSUE TITLE
Team submission consensus

### ISSUE THREAD

**Issue by dwsinger** [w3c/w3process#11]
Transferred from https://www.w3.org/community/w3process/track/issues/169
State: Open

**Comment by delfiramirez** [comment]
Following the 2119  [https://www.ietf.org/rfc/rfc2119.txt]: "SHOULD" or "RECOMMENDED" until there is a consensus of the chairs

**Comment by dwsinger** [comment]
I support adding an rfc2119 MUST indicate the level of Team consensus.

Ralph Swick, 12 Sep 2016, 14:55:47
