### ISSUE TITLE
"Reference Draft" and "Other Charter"

### ISSUE THREAD

**Issue by plehegar** [w3c/w3process#114]
The draft says that "These data must be identified in the charter with the labels "Adopted Working Draft", "most recent Reference Draft", "most recent Candidate Recommendation", and "Other Charter", respectively."

However:
- there are only 3 bullets above. The charter-template itself is a bit confusing since it's using Reference Draft to talk about "Reference Draft or Candidate Recommendation" 
  https://w3c.github.io/charter-drafts/charter-template.html
- "most recent Candidate Recommendation" isn't proper since it's the "most recent  Candidate Recommendation which triggered an Exclusion Opportunity" really
- "Other Charter" seems a strange label. The charter template uses "Produced under Working Group Charter"

It would be nice to come up with a term for "most recent Reference Draft or Candidate Recommendation which triggered an Exclusion Opportunity" that can be then used in all places.

(cc @dontcallmedom and @xfq since they brought this issue to my attention)

**Comment by xfq** [comment]
Yes, I also think the charter-template is a bit confusing. I don't understand why the "Draft state" does not contain Candidate Recommendation (or beyond). Maybe specs in CR or beyond are not considered as "drafts"?

Also, there's only "Adopted Working Draft", but no "Adopted Candidate Recommendation" (or beyond). I don't know if it's intended or not, but it's confusing at least to me...

**Comment by dwsinger** [comment]
Propose the following exact text (which happens to be closer to what PSIG originally wrote):

For every Recommendation Track deliverable that continues work on a Working Draft (WD) published under any other charter (including a predecessor group of the same name), for which there is an existing Reference Draft or Candidate Recommendation, the description of that deliverable in the proposed charter of the adopting Working Group must provide the following information:

The title, stable URL, and publication date of the Working Draft or other Recommendation-track document that will serve as the basis for work on the deliverable (labeled the “Adopted Draft”);
The title, stable URL, and publication date of the most recent Reference Draft or Candidate Recommendation that triggered an Exclusion Opportunity per the Patent Process (labeled the “Exclusion Draft”); and
The stable URL of the Working Group charter under which the most recent Reference Draft or Candidate Recommendation was published (labeled the “Recent Draft”).
All of the above data must be identified in the adopting Working Group’s charter.

**Comment by dwsinger** [comment]
fixed pretty much as documented above.

**Comment by samuelweiler** [comment]
reopening this to resolve the "Other Charter" label issue.  I agree with @plehegar that it's a strange label.

**Comment by fantasai** [comment]
We could call it “Exclusion Charter” maybe? Since it refers to the charter of the “Excluded Draft”.

**Comment by plehegar** [comment]
"Exclusion Charter: could have lots of meaning. How about "Associated Charter"?

**Comment by dwsinger** [comment]
It's the charter where the prior work happened, right? "Previous charter"? "Previous-work charter"?

> The stable URL of the Working Group charter under which the most recent Reference Draft or Candidate Recommendation was published

**Comment by dwsinger** [comment]
agreed May 12th

**Comment by fantasai** [comment]
So, as we're trying to make the edits, it seems like on the call we mixed up the terms, and used "Reference Draft" for "Exclusion Draft". So renaming to "Reference Charter" actually doesn't make sense. Florian and I are proposing "Exclusion Draft Charter" instead: we think this should be sufficiently clear, since it is referring to the charter of what is labelled as the "Exclusion Draft".
