### ISSUE TITLE
Process 2019: TAG Election / Appointment Process , Role of the Director 

### ISSUE THREAD

**Issue by nrooney** [w3c/w3process#118]
These need review for 2019.

**Comment by dwsinger** [comment]
@nrooney can you be a little more specific?

**Comment by nrooney** [comment]
This was more of a reminder to myself to bring this up in 2019. Elements here include:

* Whether the number of appointed TAG seats and elected seats is balanced correctly, given how they have been used in the past
* Review whether TAG seats should be tied to a specific specialism (I'm not sure I like this idea, but it's worth a review)
* Role of Director in the TAG, make sure the TAG is able to adapt to Director being present, not present, or a different person after succession. 

I'll also like to bring up the life-member thing too; you understand I disagree with this, but will happily debate with the rest of the AB to see whether life membership of the TAG is a good idea.

**Comment by chaals** [comment]
@nrooney  asked roughly "Should TAG seats be specialised?"

No. It is far too hard to determine what qualifies, if we do this, and I doubt we get much extra value. If the TAG is lacking skill in a particular area I think they are generally grown-up enough to ask for help...

**Comment by dwsinger** [comment]
@nrooney agree with Chaals, the work to define whether someone is qualified for a specialization is large, and pointless. I think if we want to improve the TAG much more, the way to do it is to make the electorate care more -- give them more power

**Comment by ylafon** [comment]
Maybe it should be another issue, but...
The 2018 text says in 2.5.1:
`A Member organization is permitted at most one participant on the TAG except when having more than one participant is caused by a change of affiliation of an existing participant.`
What happens if a non-member organisation manage to have two people elected ?
Striking 'Member' would solve that.

**Comment by chaals** [comment]
@ylafon pondered:

> Maybe it should be another issue

Yes, it should.

Another aspect of that issue is when an organisation nominates an employee one year, and a non-employee the next. This is not uncommon.

**Comment by ylafon** [comment]
Done, thanks.

**Comment by dwsinger** [comment]
leaving this in the hands of the AB, if they or the community want to change the process, they can come back

**Comment by nrooney** [comment]
discussing within AB for now.
