### ISSUE TITLE
Meeting guests need to respect patent policy

### ISSUE THREAD

**Issue by dwsinger** [w3c/w3process#12]
Transferred from https://www.w3.org/community/w3process/track/issues/170
State: Open

**Comment by chaals** [comment]
This seems like part of #3 - I **suggest** we close this and deal with it there...

**Comment by dwsinger** [comment]
Perhaps; but do we have any way to get an IPR and Copyright commitment from a non-member, independent of meetings and workshops? Is there a form we can ask them to fill in?

**Comment by wseltzer** [comment]
There's https://www.w3.org/2004/01/pp-impl/83482/nmlc 
(which team is working to modernize in implementation)

**Comment by dwsinger** [comment]
Doesn't sound like Meetings and Workshops (#3), though the issue comes up there.

**Comment by dwsinger** [comment]
Waiting for proposed text.

**Comment by dwsinger** [comment]
We do need a way to get a commitment from non-members of WGs (and maybe from non-members of W3C) when they make technical suggestions (fixes, improvements). This is active work in the team; suggest we defer process changes until the team has modernized practice.

**Comment by dwsinger** [comment]
see also #18

**Comment by dwsinger** [comment]
closing in favor of the umbrella issue #67
