### ISSUE TITLE
Process should say how W3T can update NOTES

### ISSUE THREAD

**Issue by tantek** [w3c/w3process#120]
As raised in discussion by Ralph at W3CAB meeting in London.

**Comment by swickr** [comment]
Specifically, when a Group Note is no longer in scope for a chartered group and the Note has errata or may otherwise be in need of revision, the Team should be able to publish an updated Note.   Review of changes in advance of such publication should be encouraged.

**Comment by dwsinger** [comment]
OK by me. Please suggest (asap) text!

**Comment by dwsinger** [comment]
the process CG is open to suggestions -- Ralph, do you have proposed text?

**Comment by dwsinger** [comment]
we need proposed text, or this risks being closed/no-action. @swickr

**Comment by dwsinger** [comment]
we can't say that the team can make Editorial changes because a Note is entirely Editorial (against the formal definition). see #536 

still need a proposed change…

**Comment by frivoal** [comment]
> we can't say that the team can make Editorial changes because a Note is entirely Editorial

We do now have a definition for editorial vs substantive changes to a note.

We also have (in https://www.w3.org/Consortium/Process/Drafts/#publishing-notes):
> If a [Note](https://www.w3.org/Consortium/Process/Drafts/#WGNote) produced by a [chartered group](https://www.w3.org/Consortium/Process/Drafts/#chartered-group) is no longer in scope for any group, the [Team](https://www.w3.org/Consortium/Process/Drafts/#team) may republish the [Note](https://www.w3.org/Consortium/Process/Drafts/#WGNote) with [class 1](https://www.w3.org/Consortium/Process/Drafts/#correction-classes) changes incorporated, as well as with [errata](https://www.w3.org/Consortium/Process/Drafts/#erratum) and [Team corrections](https://www.w3.org/Consortium/Process/Drafts/#team-correction) annotated.

Is this enough, or do we need the Team to be able to make class 2 changes directly?

**Comment by frivoal** [comment]
@plh noted an inconsistency: if we close this issue as is, then the Team has a stronger ability to make changes to RECs without a WG than to Notes without a WG:
* For every type of Technical Report, including Notes, the Team can errata and Team corrections, which are a sub-category of class-2 changes (See https://www.w3.org/2023/Process-20231103/#candidate-amendments)
* For RECs only, the Team can make any class 2 change https://www.w3.org/2023/Process-20231103/#revised-rec-editorial

Also, class-1 changes by the Team are explicitly allowed for Notes, Draft Notes, and RECs, not not for pre-REC maturity stages of the REC track (at least not explicitly).

Proposal: Consolidate all this into one single section ("Technical Report maintenance in the absence of a Chartered Group"?), and allow the Team, for every type of TR document, at every maturity, if there's no group chartered to maintain the document, to make class-1 changes, as well as [errata](https://www.w3.org/Consortium/Process/Drafts/#erratum) and [Team corrections](https://www.w3.org/Consortium/Process/Drafts/#team-correction), but not other class 2 changes (nor class 3 or 4).

**Comment by frivoal** [comment]
Attempting a consolidation of maintenance by the Team into a single section with https://github.com/w3c/w3process/pull/860

**Comment by frivoal** [comment]
Closed by merging https://github.com/w3c/w3process/pull/860
