### ISSUE TITLE
Who at W3C can request publication of an Amended Recommendation?

### ISSUE THREAD

**Issue by palemieux** [w3c/w3process#123]
In the following text, who is _W3C_?

_or if no Working Group is chartered to maintain a Recommendation W3C  may  publish a  Candidate Recommendation , without passing through earlier maturity levels._

**Comment by michaelchampion** [comment]
I'm pretty sure the intent is to say "the W3C Team". Agree it should be explicit.

**Comment by palemieux** [comment]
Thanks for clarifying the intent! I am surprise to see the W3C Team taking on the responsibility for developing and publishing a Recommendation outside of a member-driven group -- how will the W3C Team know they are satisfying a member/industry need, and that the right technical decisions are being made? Has W3C considered making the creation and management of a WG more lightweight, so that an WG can be created for the sole purpose of developing these amendments? Perhaps this is covered somewhere else in the process document?

**Comment by dwsinger** [comment]
This is intended to maintain older pecs where there is an obvious glitch and obvious (probably already adopted) fix. If it's more than that, we should indeed spin up a WG. This is supposed to catch the case when no-one would bother to join a WG if it spun up. The point of AC review is to ensure that.

**Comment by palemieux** [comment]
@dwsinger _obvious glitch_ is the eye of the beholder as you know, and may have very significant impact on interoperability.

> The point of AC review is to ensure that.

I do not think the AC can (and should) be asked to getting involved in technical details: this is what WG exists for :)

> This is supposed to catch the case when no-one would bother to join a WG if it spun up.

If it is a real issue, someone will join right? Is the WG process so heavyweight that joining for the mere purpose of correcting an obvious glitch is too much of a burden?

**Comment by dwsinger** [comment]
No, I am told we have a number of specs where what is deployed in the field doesn't match the spec.  This is precisely for the case where there is no WG, so yes, we are expecting that if an AC Rep sees something questionable here, they will contact their technical people and get them to comment. No, no-one will join just to push an obvious fix.

**Comment by palemieux** [comment]
David, who decides _what is deployed in the field doesn't match the spec_?

**Comment by dwsinger** [comment]
someone brings it to the attention of the team, and it's not a "decision" it's a realization.

**Comment by palemieux** [comment]
What if someone does not agree with the realization? Do they need to bring it up to the entire AC?

It seems risky and burdensome to create a new process, when time-tested process already exists -- the WG process.

Is the issue that the WG process requires a large minimal number of participants that could not be achieved in the case of more routine amendments?

**Comment by palemieux** [comment]
By the way, my only interest is (a) avoid putting the W3C Team in a position to pick between W3C members and (b) avoid creating with a new process if an existing process is sufficient (and can be trivially tweaked) :)

Just a junior member in any case.

**Comment by dwsinger** [comment]
Pierre, you're missing the major point: this is for the case where there is NO WG, and the burden of creating it, and the unlikelihood of anyone joining, are both high. We *must* get better at maintaining our recs, and we have a glaring hole here.

**Comment by palemieux** [comment]
@dwsinger Oh, my point is that WGs should be easier to create... so that no new process is needed -- and all the risks it entails. What is the risks/costs in making WGs easier to create.

**Comment by dwsinger** [comment]
You have to write a charter, get it approved. Then you have to persuade companies to sign up for the IPR commitment that joining a WG entails. If the fix is something trivial, the first is vastly more work than the fix, and the second is vastly larger commitment than the fix. Imagine "this field is documented as taking a URL, but actually people are using URNs, and so it should be documented as a URI". You really want to write a charter, get it AC-approved, persuade people to join a WG, in order to ship that?

**Comment by palemieux** [comment]
> You have to write a charter

For an amendment, the charter can literally be one paragraph: the defect is described and the solution proposed.

> get it approved

A charter is approved unless contested, so there is really minimal overhead. In fact, it is always cheaper to catch issues *before* the amendment is generated, than after during the AC review.

> Then you have to persuade companies to sign up for the IPR commitment that joining a WG entails. 

As defined in the proposed revised process, an Amendment does not add feature that could trigger additional IPR, so a charter limited to an amendment should, by definition, have little to no IPR consequences.

> persuade people to join a WG,

It is ok for only the staff to join the WG, but at least it exists: there is a clear charter, members can join at any time and the work can be tracked like all other work.

**Comment by palemieux** [comment]
>We must get better at maintaining our recs, and we have a glaring hole here.

+1 of course :)

**Comment by dwsinger** [comment]
Unfortunately W3C does not publish amendments, only whole Recs...

**Comment by palemieux** [comment]
> Unfortunately W3C does not publish amendments, only whole Recs...

The proposed revised process defines a "Amended Recommendation", which is what started this thread :)

**Comment by dwsinger** [comment]
Yes, that's an entire Recommendation, not just the delta (not like an amendment), which means that if there were a WG, members would be signing up for IPR on the entire Recommendation (not just the delta)

**Comment by palemieux** [comment]
Good point.

The patent policy states that: _As a condition of participating in a Working Group, each participant (W3C Members, W3C Team members, invited experts, and members of the public) shall agree to make available under W3C RF licensing requirements any Essential Claims *related to the work* of that particular Working Group._

Emphasis on *related work* is mine.

So, assuming the work is limited by the charter, won't the IPR commitment be limited to that work?

**Comment by dwsinger** [comment]
No, it's clear that the commitment is to the deliverable, which is an entire Recommendation. IPR is complicated; making a small change may, when integrated with the existing text, implicate IPR that is not implicated by the change in isolation.

**Comment by chaals** [comment]
@palemieux wrote:

> how will the W3C Team know they are satisfying a member/industry need, and that the right technical decisions are being made?

This is a judgement call. As David said, if there is some small change that would bring the spec into line with what people are really doing, it might be fairly simple to judge.

If it is hard to judge, that is a sign that W3C should not try to produce an Amended Recommendation, but should consider whether there is interest to spin up a Working Group.

> Has W3C considered making the creation and management of a WG more lightweight, so that an WG can be created for the sole purpose of developing these amendments?

Yes. Making it easier for W3C to start trivial Working Groups is not difficult, compared to getting any significant degree of interest in participation. Even if the process were trivial, asking people to do it for nothing more than a trivial obvious change seems excessive.

The assumption is the AC reps check technical questions whose answer they don't know with people who do. But first, many are capable of making the decision themselves, and second there seems little point in asking them to do this at the start and end of the process of making a simple change.

**Comment by dwsinger** [comment]
we hope that we can clarify this as a question of practice. no suggested edits, closing. Somone persuades a team member to start the AR process is the answer

**Comment by palemieux** [comment]
@dwsinger _Somone persuades a team member to start the AR process is the answer_ if this is the answer, than it needs to be captured. "W3C" means nothing as it stands.

**Comment by dwsinger** [comment]
Oh, this text is misleading. Amended Recs follow the same process as Candidate Recs but they are not the same as candidate recs. I will look at cleaning this up editorially today.

**Comment by dwsinger** [comment]
Added to the definition in 6.1.2 "The W3C team guides it through the process." and
