### ISSUE TITLE
What is a "Memorandum of Understanding"?

### ISSUE THREAD

**Issue by dwsinger** [w3c/w3process#13]
Transferred from https://www.w3.org/community/w3process/track/issues/172
State: Open

**Comment by dwsinger** [comment]
VF to discuss and propose.

**Comment by vfournier17** [comment]
It seems that the confusion in this section may be coming from the assumption that "MOU" has a certain legal meaning when it does not.  Please see attached for alternate proposed language that should address this issue.
[W3C_MOU_060217.docx](https://github.com/w3c/w3process/files/1073253/W3C_MOU_060217.docx)

**Comment by dwsinger** [comment]
I think VF's document contains this:

Hello all

Request:
     - provide a definition for our use of the term "Memorandum of Understanding (MoU)" in the Liaisons section.
     https://www.w3.org/2015/Process-20150901/#Liaisons


Rationales:
     - the Team is often asked to sign "MoUs" with other organizations 
that are just simple liaisons from our point of view, that is, they do 
not justify Member review, but because the other parties call them 
"MoU", and insist on doing so, we are often in an unclear situation (is 
it a "real" MoU ? should we inform our members ?).

    - MoU is as good as any other similar name like "Agreement" or 
"Partnership", "Formal liaison", so we only need to provide details for 
our own meaning of the term, and need not to change it.


Proposed modification:
    - no change to the text using the term MoU, only make the term a link 
to a new definition entry, that can be added elsewhere [It needs to be added to this section.]

    - Suggested new definition:

      "In the context of the W3C Process, an MoU is a formal agreement, 
i.e. a contractual framework with W3C rights and obligations, that 
involves joint deliverables, an agreed share of technical 
responsibilities with due coordination, and/or considerations for 
confidentiality and specific IPR. The agreement may actually be called 
something else that an MoU, and something called an MoU may not be a W3C 
MoU in that sense.

9 Liaisons
W3C uses the term "liaison" to refer to coordination of activities with a variety of organizations, through a number of mechanisms ranging from very informal (e.g., an individual from another organization participates in a W3C Working Group, or just follows its work) to mutual membership, to even more formal agreements. Liaisons are not meant to substitute for W3C membership.
All liaisons must be coordinated by the Team due to requirements for public communication; patent, copyright, and other IPR policies; confidentiality agreements; and mutual membership agreements.
The W3C Director may negotiate and sign a  Liaison Agreement with another organization. For purposes of this section, a “Liaison Agreement” is a formal written and binding agreement signed by W3C and another party to establish terms such as the framework of a liaison, the parties’ rights and obligations, ownership of deliverables, intellectual property rights, and confidentiality.  A Liaison Agreement may have a different name, such as a Memorandum of Understanding (MOU), a Letter of Intent (LOI), or another type of document or agreement, while still qualifying as a Liaison Agreement under this section.  Before signing the Liaison Agreement, the Team must inform the Advisory Committee of the intent to sign and make the Liaison Agreement available for Advisory Committee review; Advisory Committee representatives may initiate an Advisory Committee Appeal of the decision to sign the Liaison Agreement. Once approved, a Liaison Agreement should be made public.
The Team may inform the Advisory Committee of the intent to sign non-binding MOUs or LOIs.
Information about W3C liaisons with other organizations and the guidelines W3C follows when creating a liaison [PUB28] is available on the Web.

**Comment by dwsinger** [comment]
I agree to clarify what an MoU is in the process document, using the definition above. We're not sure we need to have a long paragraph about liaisons as well?

**Comment by dwsinger** [comment]
In the context of the W3C Process, an MoU is a formal agreement, 
i.e. a contractual framework with W3C rights and obligations, that
involves joint deliverables, an agreed share of technical
responsibilities with due coordination, and/or considerations for
confidentiality and specific IPR. The agreement may actually be called
something else that an MoU, and something called an MoU may not be a W3C
MoU in that sense.

**Comment by vfournier17** [comment]
I don't have the document with me - what does it say about liaisons?

Virginia Fournier
Sent from my iPhone
Please excuse iTypos

**Comment by vfournier17** [comment]
I don't know why the language about Liaisons is there.  This Is my proposed language:

"The W3C Director may negotiate a Memorandum of Understanding with another organization. For the purposes of the W3C Process a "Memorandum of Understanding" ("MoU") is a formal agreement or similar contractual framework between W3C and another party or parties (other than agreements between the hosts or between hosts and W3C members for the purposes of membership and agreements related to the ordinary provision of services for the purposes of running W3C), that specifies rights and obligations of each party toward the others.  These rights and obligations may include joint deliverables, an agreed share of technical responsibilities with due coordination, and/or considerations for confidentiality and specific IPR. The agreement may be called something other than a  "Memorandum of Understanding," and something called a "Memorandum of Understanding" may not be an MoU for the purposes of the Process.
