### ISSUE TITLE
Editorial improvements to obsolete/superceded

### ISSUE THREAD

**Issue by dwsinger** [w3c/w3process#138]
From Andreas in AC review:

#### Change
* Section 6.9
* Description: A Recommendation can be declared superseded as well as obsolete.

### Comment
The process is not clear enough. Example:

> W3C may obsolete a Recommendation, for example if the W3C Community decides that the Recommendation no longer represents best practices,

Who is the W3C Community?

In general, the requirements to start a process that obsoletes (rescinds or supersedes) a recommendation are not defined well enough.

> [dwsinger] Hm, we define four very specific cases. What is missing?

It may be just a clarification that this is the only way to start the process. You first define the option that W3C may obsolete a Recommendation. Then you describe the process by starting with "The director may recommend ....". It is not clear from the reading that the described steps are the only, exclusive process  steps to come to an obsolete Recommendation. So it may just need an editorial edit to clarify this.

**Comment by tantek** [comment]
I agree that editorial changes would help (which may be fine to resolve and close this issue), however I think we need more than editorial changes as well to improve clarity, expectations, escalation, etc. and have noted that in #141

**Comment by dwsinger** [comment]
Reading it again, I am having a hard time seeing what to edit. @tairt it seems to me that it says that the Director can initiate (on his own) or that he MUST do so when asked by the process following. Can you point out what's missing or could be improved? Thanks

**Comment by tairt** [comment]
@dwsinger When I read 6.9 for the first time I read the listing at the start of the section as part of the process flow:
 
> W3C may obsolete ..
> W3C may declare a Recommendation Superseded ...
> W3C may rescind a Recommendation ....

But this part provides more (non-exclusive?) requirements to start a procedure.

So to seperate the first part from the process/procedure you could add a sentence before

> The Director may recommend obsoleting,

This sentence may just say: "The process/steps/procedure to obsolete, etc.  is as follows: ...."

You should also be more explicit that there are two options to initiate the procedure: either the director decides to recommend to obsolete etc. a specification or one of the listed five stakeholders submit a proposal to the director to obsolete etc. a specification.

For the second step it not clear if a AC review is also mandatory if you take the first option (director recommendation). If this is the intent you should add something like "After the start of the procedure (regardless if the director recommends to obsolete a specification or if there was a proposal) the Director MUST begin an AC review.

**Comment by dwsinger** [comment]
Got it, thank you. We will work on improved text.

**Comment by chaals** [comment]
I note that the definitions of the states are already in the maturity states at the start of the section, so there is a whole lot of redundancy...

**Comment by dwsinger** [comment]
Note that this is not a 2018 (current process) edit...

**Comment by frivoal** [comment]
The corresponding pull request has been accepted and merged a while back. Closing.
