### ISSUE TITLE
Community Groups

### ISSUE THREAD

**Issue by jeffjaffe** [w3c/w3process#139]
Should CGs be discussed in Process 2019?

**Comment by chaals** [comment]
See also #17

**Comment by chaals** [comment]
> Should CGs be discussed in Process 2019?

IMHO, yes

**Comment by dwsinger** [comment]
@jeffjaffe is this a dup of #17 or is it asking a new question?

**Comment by jeffjaffe** [comment]
It's a dup.  Which Chaals noticed right away. See above.

**Comment by dwsinger** [comment]
closing as a duplicate of #17
