### ISSUE TITLE
Differentiate recharterings

### ISSUE THREAD

**Issue by caribouW3** [w3c/w3process#142]
Hi,
Currently there are 2 kinds of situations: "rechartering", or "charter extension": the first with AC review, the other without (team decision). Since write/reviewing new charters has become potentially a bit longer and painful, while all new charters don't imply new Patent Policy commitments (i.e. deliverable list unchanged), it would be easier to differentiate "rechartering with AC review" into different cases.
Possibly something like:

1. no change in patent commitments (no new deliverable, no new adopted spec) : Charter extension with AC review.

2. new deliverable (unpublished yet) but no new adopted spec: Addition of future work in charter

3. new adopted specs (change from previous charter of the same WG), with or without new deliverable in the same charter: (default case): Proposed Charter (call for review) = current form

Removing specs only could fall back into the 1st category. That way, I think the 3rd case would probably no longer be the default.
Simple charter extension without AC review would still be possible.

**Comment by vfournier17** [comment]
I'm not sure what the difference is between 2 and 3?

**Comment by caribouW3** [comment]
In 2. there are no commitments upon joining the group, there will be commitments only when the FPWD of the new deliverable is published (and at CR again, of course)
In 3. there are immediate commitments upon joining, wrt the latest published draft of the adopted specs. (I meant "with or without new deliverable" rather than "and/or new deliverable", let me edit that)

**Comment by dwsinger** [comment]
I am not entirely comfortable with doing changed charters (reduced deliverables) without AC review. The lost deliverables may be important to some other part of the community, for example. We also don't like charter extension without review very often; groups should get periodic community scrutiny.

This seems the opposite to what the AB is asking ("don't extend, review").

**Comment by frivoal** [comment]
@caribouW3 I am preparing a Disposition of Comments for this year's iteration on the Process. It was decided not to address this in Process 2019. Since you raised the initial issue, I would appreciate if you can let us know if this is something you can live with, or if you wish to object to.

**Comment by caribouW3** [comment]
Can live with it. Thank you.
