### ISSUE TITLE
Can't update process as if it were a Rec

### ISSUE THREAD

**Issue by chaals** [w3c/w3process#146]
There is no call for implementations, etc, so offering the Rec track as an alternative path makes no sense.

**Comment by vfournier17** [comment]
what does this refer to?  Asking for a friend.

**Comment by dwsinger** [comment]
follow the link to the commit; this phrase "W3C may also modify a Process Document by following the processes for modifying a Recommendation" doesn't seem to make sense

**Comment by nrooney** [comment]
For the process document for busy people I stated this as:

"The W3C Process Document is updated similar to any W3C document. Every year, the Process Community Group amends the document based on comments expressed by the community, then sends the document for AC Review. On a successful AC Review, the new process will be announced to the AC."

This isn't a perfect statement, but we could use this a basis for the rewrite here.

**Comment by chaals** [comment]
That's more or less what it says already. There is an extra bit that says it **may** also be updated following the Rec track process. The PR removes that, because in the current process it defies logic and is pointless.

**Comment by chaals** [comment]
As the first comment says, the Rec track process does not apply. In particular, implementation experience is not likely to be demonstrated in advance of adopting a new process. Since this is only mentioned as an alternative possibility, the mention should just be removed. Which is what the Pull Request does.

**Comment by dwsinger** [comment]
discussed on the last call, and we agree, which is why we assigned you as you have the associated PR...

**Comment by dwsinger** [comment]
assigning the editor so we don't have un-assigned open issues (but it can be merged and closed at her discretion)
