### ISSUE TITLE
Automatic WD publishing tool may change the W3C center of gravity around WGs

### ISSUE THREAD

**Issue by dwsinger** [w3c/w3process#15]
Transferred from https://www.w3.org/community/w3process/track/issues/126
State: Raised

**Comment by dwsinger** [comment]
Mike Champion to see whether we should make this active

**Comment by michaelchampion** [comment]
I don't believe this is a process issue, although I understand that the ease of publishing Working Drafts with minimal consultation with WG members or chairs does create problems in practice.  

From the process document: 
"6.1.2 Maturity Levels
Working Draft (WD)
A Working Draft is a document that W3C has published for review by the community, including W3C Members, the public, and other technical organizations ..Working Drafts do not necessarily represent a consensus of the Working Group, and do not imply any endorsement by W3C or its members beyond agreement to work on a general area of technology."

It would take a substantial change to the process document to require consensus before publishing working drafts.  If there is an operational problem with too-frequent WD publications that make wider review more difficult / less likely, the Chair has the power to replace an editor who creates such problems.  

So, I believe this is an issue on the operation of W3C's staff and how they work with chairs, not a process issue.

**Comment by dwsinger** [comment]
I agree.  I think that we should clarify that we expect that the editors produces WDs that they believe represent group consensus, or roughly so, and that (given the ease of making variants in GH) proposals should be PRs based on variants. I think it's appropriate to allow a group to work with a trusted editor, who can be trusted to push regular WDs that they think represent consensus, as long as the group can and does monitor for errors and correct them in a timely fashion. This is all practise.

**Comment by dwsinger** [comment]
we don't see a process change here; this is a procedural/practice problem

**Comment by chaals** [comment]
The process says that drafts *should* be published when there are real changes that benefit from review. Automatic publishing enables publishing to be held back to match this, or to be more frequent, happening on every day that any change at all is made.

In the latter case, there is no obvious signal for periodic review, and unless the Status of the Document is kept updated - as required by Process but often ignored in practice - there is little helpful information to someone who actually looks at the latest Working Draft.

This is, however, a question of practice not process, and we agreed to close it at the [meeting of 12 July 2017](http://www.w3.org/2017/07/12-w3process-minutes.html).
