### ISSUE TITLE
Editing, deleting, or replacing a member submission

### ISSUE THREAD

**Issue by dauwhe** [w3c/w3process#154]
What happens if one wishes to update, delete, or replace a member submission? Asking for a friend.

**Comment by chaals** [comment]
Historically the answer has been that without an agreement from the original submitter it cannot be done and you need to make a new distinct Member Submission that says it updates the other one.

According to a friend.

**Comment by dwsinger** [comment]
I think that the answer is that it either is agreed to become the basis of work in a working group, and hence mutable there; or you make a new submission

**Comment by nrooney** [comment]
@dauwhe going to close this as the question was answered. If you feel like the process doc needs to evolve here feel free to comment and reopen the issue! Thanks for the q!
