### ISSUE TITLE
Maturity Levels

### ISSUE THREAD

**Issue by nrooney** [w3c/w3process#155]
6.1.2 lists maturity levels as starting with "Working Draft". But other sections of the document refer to "First Public Working Draft" as being a maturity level (e.g. 6.2.2). We should revise the maturity levels to see if we wish to expand them to include variations of working drafts. Otherwise, documents may be incorrectly labelled.

**Comment by vfournier17** [comment]
We should also make sure "First Public Working Draft" is defined and used consistently.  Currently, the proper usage is "first public Working Draft," as the term is not defined.

**Comment by nrooney** [comment]
Is the first public working draft just a working draft which is [1] first and [2] public?! All subsequent working drafts are also public, but are no longer first. Right?

**Comment by dwsinger** [comment]
I fear we may need to review this phrase. Are there "private" working drafts any more? (WDs that the group decides to keep member-only). Essentially, this is the first draft adopted by the group as its own WD (as opposed to non-status editor's drafts), which has to be public to allow comment...I think? Insights?

**Comment by vfournier17** [comment]
A first public working draft is more than "first" and a "draft," because it triggers an exclusion opportunity.

**Comment by nigelmegitt** [comment]
It's true though that all subsequent WDs are public, so the question really is why we ever use the term "Working Draft" rather than "Public Working Draft", for consistency, if I've understood @nrooney correctly. Or are there actually non-public working drafts? Even Editor's Drafts are generally public!

**Comment by nrooney** [comment]
I'm going to wait till today's call to discuss this - then make the change given whatever we discuss!

**Comment by frivoal** [comment]
While it is true that it is a little strange, given today's practices, that one term uses the word public and the other not given that everything is public, I don't think we should change them at this point. Fixing this minor inconsistency is not worth the costs in terms of everybody relearning / explaining new terminology that is almost but not quite the same as the previous one.

To me, it doesn't seem that we have an actual problem, and the process seems clear to me, and I think we can close with no change. But if you want to 100% explicit, adding (at the beginning of section 6.3.1?) something like this would be OK with me:

> The first Working Draft of a technical report is called the &lt;dfn>First Public Working Draft&lt;/dfn>.
