### ISSUE TITLE
Can we improve input from 'horizontal' groups (WAI, I18N, ...)

### ISSUE THREAD

**Issue by dwsinger** [w3c/w3process#16]
Transferred from https://www.w3.org/community/w3process/track/issues/127
State: Raised

**Comment by chaals** [comment]
[From the old (old old) issue](https://www.w3.org/community/w3process/track/issues/127):

> What seems to be needed is a working mechanism that allows Horizontal Groups (which are often very resource limited) to effectively understand when a WG's document is complete enough (understandable) to allow a review, but not so complete that changes to fix discovered issues are difficult or impractical.

This generally doesn't seem like a Process requirement, but questions of procedure and of clarity in [the Guide](https://www.w3.org/Guide) - @plehegar @r12a @michael-n-cooper ?

In passing I note that procedures seem to be improving. i18n has a nice mechanism for flagging stuff for review early, which I have found helpful in getting at least some stuff cleared, or examined, before we're even thinking about CR…

**Comment by dwsinger** [comment]
Closing as a question of practice, not process
