### ISSUE TITLE
define "transition request"

### ISSUE THREAD

**Issue by samuelweiler** [w3c/w3process#160]
The term "transition request" should be defined to help those new to W3C. It first appears in section 6.2.2 without any introduction.

**Comment by nrooney** [comment]
Hmmm. Let's have a stab at this:

## Transition Requests
A document progressing through the [W3C Technical Report Development Process](https://w3c.github.io/w3process/#Reports) will need to go through each [maturity level](https://w3c.github.io/w3process/#maturity-levels) on it's way to becoming a W3C Recommendation. To move from one [maturity level](https://w3c.github.io/w3process/#maturity-levels) to the next the Working Group will need to make a **Transition Request**. Each [maturity level](https://w3c.github.io/w3process/#maturity-levels) stage has common and unique **Transition Request** requirements.

**Comment by jeffjaffe** [comment]
Looking at 6.2.2, I believe that Transition request is defined implicitly in the sentence where it is introduced.  Perhaps a small modification (such as using the words "defined as") is a sufficient change.

**Comment by dwsinger** [comment]
agree with Jeff, maybe change
For all Transition Requests, to advance a specification to a new maturity level other than Note,
to
For all requests to transition a specification to a new maturity level other than Note (called "Transition Requests"), 

but this seems moderately pedantic if harmless. we don't have a terms and definitions section.
