### ISSUE TITLE
Should the Process define Business and Community Groups?

### ISSUE THREAD

**Issue by dwsinger** [w3c/w3process#17]
Transferred from https://www.w3.org/community/w3process/track/issues/130
State: Raised

**Comment by dwsinger** [comment]
Mike to discuss

**Comment by dwsinger** [comment]
Yes, it's time to look at integrating all our xGs into the process, but not 2018

**Comment by chaals** [comment]
This shouldn't have been closed, must have done it by accident somehow.

**Comment by dwsinger** [comment]
Moving the entire documentation of CGs and BGs into the process seems like a lot of work. There are some edge questions here (e.g. does the Director's authority to dismiss someone apply to CGs and BGs if they are not mentioned). perhaps a pointer admitting of their existence?

**Comment by dwsinger** [comment]
I think the answer to the question posed is 'no', because CGs and BGs are open to non-members, and the process document is for running Member business. 

Having said that, I think that (a) CGs and BGs should be mentioned in the Process document, by adding to the end of Section (1) Introduction "The W3C also operates Business and Community Groups, which are open to non-members and do not produce normative Recommendations. They are described by the Business and Community Group [process https://www.w3.org/community/about/agreements/].

I also think that the CG/BG process should contain identical provisions in a few cases, and should be edited. That includes mirroring the provisions of 3.1, especially the material added in Process2018:
"Participants in any W3C activity must abide by the terms and spirit of the W3C Code of Ethics and Professional Conduct and the participation requirements described in section 6 of the W3C Patent Policy.

The Director may suspend or remove for cause a participant in any group (including the AB and TAG), where cause includes failure to meet the requirements of this process, the membership agreement, or applicable laws."
Possibly 3.3 Consensus should be mentioned somehow, but the text in the process is quite specific to members.
Possibly 3.5 Appeal of a Chair's decision (yes, it should be possible to appeal to the Director for a BG/CG decision).

That's all I see, and it's mostly updating the CG/BG process rather than the process document.

**Comment by vfournier17** [comment]
I agree that CGs and BGs should have their own process document, and that such process should be synched up with the WG process in certain areas.  I also agree that this is now a Process 2019 candidate, but where should it go?

**Comment by dwsinger** [comment]
So, in general we need to sort out which parts of the process actually ought to apply to CGs and BGs. For example, conforming to the code of ethics and professional conduct probably does, and the Director's ability to dismiss for cause. Section 3 says "These policies apply to participants in the following groups: Advisory Committee, Advisory Board, TAG, Working Groups, and Interest Groups." 

I think we need to say in the introduction at the end of section 1 "The W3C also operates Community and Business Groups, which are separately described in their own process document." and link to <https://www.w3.org/community/about/agreements/>. Those pages probably need an update to include "Dismissal from a community or business group" and allow the Director to dismiss for cause. Do we need conflict of interest policy links in the CG/BG process?

**Comment by dwsinger** [comment]
see also #180
