### ISSUE TITLE
Review the role of the Director in the process document

### ISSUE THREAD

**Issue by dwsinger** [w3c/w3process#173]
We need to track places where the process assigns responsibility to the Director but perhaps this no longer tracks reality. (This issue is a blanket to catch thoughts towards more specific edits, which will get their own issues; and the AB also has this as a long-term action).

**Comment by dwsinger** [comment]
see also https://www.w3.org/Member/Board/track/issues/34

**Comment by Kometo2** [comment]
Then wrote 2d expresion, that wrotten in same respect as you act, I was thinkin how far
how far this generating can go, i was trying to find endpoint there semantic cant generate new content. So if I can have question i may ask, it seems like with each time getting lack of "generated". So there Director do actions wirh enlarge content rotating or stop the user,but its not actually needed. But how about Chanmpionship like Desert Bus for charity. Anywhere, i see in this some Express Psychological Help app potential use,money and it perfect broken web mirror to see oh urself? if it be more specilized to it. 
Anywhere Director can just ask me of the info u maining so long, then u see i just pull all xml triggers, and show as primitive as i preform, so what was actual goal? if there non, so no questions to director, if it was laughs it can be makes in more ways. I dont get this events, if they can be rejected cause they just generated to death.

Well, generate actions, contrubuting generations, its not mistake that way.

**Comment by frivoal** [comment]
This is a whole project of its own now (see https://w3c.github.io/w3process/director-free/ and https://github.com/w3c/w3process/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Adirector-free). I suggest closing this umbrella issue. @dwsinger ?

**Comment by dwsinger** [comment]
yes, agreed, it can be closed.
