### ISSUE TITLE
Contrast 'immediately' vacated seats and seats vacated at the next election

### ISSUE THREAD

**Issue by dwsinger** [w3c/w3process#175]
in 2.5.3 this section appears to define the four ways a seat gets vacated:
"An Advisory Board or TAG participant's seat is vacated when:

* the participant resigns, or
* an Advisory Board or TAG participant changes affiliations such that the Advisory Board and TAG participation constraints are no longer met, or
* the Director dismisses the participant for failing to meet the criteria for participation in section 3.1, or
* their term ends."

However, this sentence immediately after adds another. 

"If a participant changes affiliation, but the participation constraints are met, that participant's seat becomes vacant at the the next regularly scheduled election for that group."

This should be clarified by inserting "immediately" into the sentence before the bullets:
"An Advisory Board or TAG participant's seat is vacated immediately when:"

**Comment by chaals** [comment]
That would be contrary to long-standing practice, and I think unhelpful. The result would be to force a special election or to reduce the number of people on the relevant body by one until the next regular election has taken place, 

Given that it is a responsibility of TAG and AB members to represent the best interests of the Web and W3C, and **not** their sponsor, and they are therefore elected on that basis, this seems unnecessarily bureaucratic.

It also runs counter to the last change we made to this area, in which TAG participation requirements were loosened specifically to avoid this happening in the common case.

**Comment by dwsinger** [comment]
You're right, bullet point (2) is no longer an immediate vacation.

I'm trying to make sure that the document is clear and readable, not change anything.

An Advisory Board or TAG participant's seat is vacated when:

* the participant resigns, or
* an Advisory Board or TAG participant changes affiliations such that the Advisory Board and TAG participation constraints are no longer met, or
* the Director dismisses the participant for failing to meet the criteria for participation in section 3.1, or
* their term ends, or
* the participant changes affiliation, but the participation constraints are met."

But actually, after a change of affiliation: 
* when the constraints aren't met, we resolve at the next election
* when the constraints are met, the seat is vacated at the next election.

We could simplify the text further.
"An Advisory Board or TAG participant's seat is vacated when:

* the participant resigns, or
* an Advisory Board or TAG participant changes affiliations, or
* the Director dismisses the participant for failing to meet the criteria for participation in section 3.1, or
* their term ends."

and we keep the following sentence, verbatim:
"If a participant changes affiliation, but the participation constraints are met, that participant's seat becomes vacant at the the next regularly scheduled election for that group."

**Comment by Kometo2** [comment]
I love too watch how it work,so i cant be part of it. Stop the elections, i have a seat alredy!

**Comment by chaals** [comment]
No, because your second bullet now seems to confuse "the seat is vacant today because you changed affiliation" with "the seat will be vacant as of the next scheduled election (in e.g. 9 months time)".

Perhaps we should structure it for more similarity:

> A seat is vacated when
> * the participant resigns
> * ...
> * A change of affiliation means AB/TAG participation constraints are not met (see [details]() of which one goes)
>
> A seat is vacated **at the next regular election** when
> * A TAG/AB member changes affiliation


?

**Comment by dwsinger** [comment]
The point is that *both* changes of affiliation and dual representation are resolved at the next election...maybe "when" implies "immediately"

"An Advisory Board or TAG participant's seat is vacated following:

* resignation by the participant (on the resignation date); or
* a change of affiliation by an Advisory Board or TAG participant, or
* dismissal by the Director for failing to meet the criteria for participation in section 3.1 (on the date chosen by the Director), or
* the end of their term, (at the end of the term)."
and we keep the following sentence, verbatim:
"If a participant changes affiliation, but the participation constraints are met, that participant's seat becomes vacant at the the next regularly scheduled election for that group."

**Comment by frivoal** [comment]
@dwsinger we closed the pull request without merging. I think we also meant to close this issue entirely, and not meant that we should write a new pull request. Can you confirm (and close)?

**Comment by dwsinger** [comment]
confirmed.
