### ISSUE TITLE
Working Group and Interest Group charter extension

### ISSUE THREAD

**Issue by vfournier17** [w3c/w3process#177]
Clarify in Section 5.2.5 of the Process Document that an "extension" really is just a date change, and there should be no substantive changes to the charter (maybe fixing typos, etc. is ok).  The "extension" process is being misused by members, who rewrite large portions of a charter and then call it an "extension."  This is presumably to avoid the "kick members out/members rejoin/exclusion opportunity process" that comes with the recharter/new WG.  On the other hand, maybe we just need to start enforcing what the policy says now.

5.2.5 Working Group and Interest Group Charter Extension

To extend a Working Group or Interest Group charter with **no other substantive modifications**, the Director announces the extension to the Advisory Committee. The announcement must indicate the new duration. The announcement must also include rationale for the extension, a reference to the charter, the name(s) of the group's Chair(s), the name of the Team Contact, and instructions for joining the group.

**Comment by chaals** [comment]
I think we should just be enforcing what the Process says.

**Comment by wseltzer** [comment]
I'd be interested in examples. 
Other changes I'd expect to call non-substantive: changing chairs or team contacts; updating timelines/milestones.

**Comment by vfournier17** [comment]
Yes, I'd agree that those are non-substantive for the most part.  What do you mean by updating milestones - the date or the deliverable?

**Comment by dwsinger** [comment]
milestones == dates. changes of deliverable would be major...

**Comment by vfournier17** [comment]
ok, got it.

**Comment by nrooney** [comment]
Not sure there is a change needed here unless @dwsinger finds examples.

**Comment by dwsinger** [comment]
practice seems to have improved enough that we probably don't need document changes. will continue to monitor and if we see problems, re-open. closing.
