### ISSUE TITLE
TAG, AB vacated seat text change

### ISSUE THREAD

**Issue by nrooney** [w3c/w3process#179]
If a participant changes affiliation, but the participation constraints are met, that participant's seat becomes vacant at the the next regularly scheduled election for that group.

Should be "for that seat"

**Comment by chaals** [comment]
Where? If you mean at the end of the sentence, that would be a change in practice - if someone changes affiliation their seat is opened at the next regular election, even if it would otherwise have held to the following one.

e.g. Joe is nominated by their employer to the TAG, elected, and 2 months later leaves for a better job, so now representing "MuchBetter.org". Although' Joe's would normally be elected for 2 years, at the next election Joe's seat is open for election again.

**Comment by dwsinger** [comment]
No, it's a premature termination. Saying that their term ends when their terms ends would be a tautology. So I think we don't agree.

If Amalasuentha changes affiliation from Visigothic to Vandal, we want the AC to vote *at the next opportunity* (e.g. the upcoming election) on whether she should stay on the elected body.

**Comment by nrooney** [comment]
Sorry - I was typing quickly - to be clear, I actually don't mind either way, but I got to thinking about this line and it's impact. 

In the process document it reads like a person can be "affiliated" with more than one organisation; in which case there could be a situation when: 

A person is mainly affiliated with Company A, and Company B start paying that person for consultancy. Both Company A and Company B are W3C members. This means the person is affiliated with both Company A and Company B and this statement is true: "If a participant changes affiliation, but the participation constraints are met..." as the person's affiliation has changed (they are now affiliated with two organisations) and they are *still eligible* to be the AB or TAG (as neither Company A or Company B have a representative in the AB or TAG).

The next part of the statement reads "that participant's seat becomes vacant at the the next regularly scheduled election for that group.”. Which is the next election for that group, not that seat. Ergo, the group in question loses an elected individual, who *is eligible* to be in the group, but is kicked because someone else is paying them as well as their main employer.

Secondly; if this happens the right amount of times the elections may become very unbalanced, with multiple seats going up for election one year and very few the following year (although I naturally believe this will correct itself over time). 

Like I said, I actually I don't mind either way - just throwing a situation out there. This actually may mean we need to harden the definition of "affiliation", which is loosely described.

**Comment by cwilso** [comment]
I believe this text should remain as "next scheduled election", not "for that seat".  1) I believe it's appropriate, and 2) otherwise nothing should be said - it's a no-op.  That seat will be up for election anyway.

**Comment by nrooney** [comment]
Seems like people agree - so perhaps we should just close?

**Comment by dwsinger** [comment]
agreeing with Natasha and closing...
