### ISSUE TITLE
Document how to move work from a Community Group into a WG Rec Track document

### ISSUE THREAD

**Issue by dwsinger** [w3c/w3process#180]
This is undefined, and some wonder if FSAs apply, some wonder about Member Submission

**Comment by jeffjaffe** [comment]
This is a good issue and should be taken up.  I note that CGs are not defined in the W3C process, and if we take up issue #180, we probably need to also take up that broader issue.

**Comment by dwsinger** [comment]
see also #17

**Comment by nrooney** [comment]
Let's give this a shot:

## Transfer of Community Group Work Items to a Working Group
Community Groups or the W3C may wish to elevate a Community Group Work Item to become a W3C Recommendation Track document. In order for this to happen, either the Community Group must become a Working Group (see Working Groups `@todo add link`) or the Community Group Work Item must be adopted by a W3C Working Group. For a Community Group Work Item to become adopted by a Working Group:

* The Working Group selected must have a charter of work which fits with the Community Group Work Item `Note: I do not like this sentence - but you see what I was trying to say, any suggestions on how to make it better?`
* The Working Group team contact and chair/s must notify the members of the Working Group; Working Group members are given 28 days to object to the adoption of the Community Group Work Item
* The Working Group team contact must notify the AC through the AC mailing list; AC members are given 18 days to object to the adoption of the Community Group Work Item

If no objections are received the Community Group Work Item becomes a deliverable of the Working Group `and added to the charter?`. If objections are received the Working Group team contact and chair/s should seek consensus on whether to adopt the Community Group Work Item.

Thoughts?

**Comment by jeffjaffe** [comment]
Thanks, Natasha for getting us started on this.

I wonder whether we can simplify adoption when the charter already covers the CG work item.  After all, not every deliverable in a WG is even mentioned in the charter.  Can't we just say that if the new item is within scope, then a WG can decide by consensus to add it.  (And the messy details of how that consensus works need not be stated in the process document.)

**Comment by vfournier17** [comment]
We would need to make sure we capture the IP commitments for the CG (under a CLA) work coming over to a WG (under the PP).

**Comment by dwsinger** [comment]
"The Working Group selected must have a charter of work which fits with the Community Group Work Item" -> "The working group must have a document matching the Community Group Report, as a chartered deliverable."

But I think the IPR question is the most thorny. 
a) The community group needs to be able to show that Contributions were all made under the CLA (and they didn't just accept ideas from Uncle Tom Cobbley and all).
b) Best practice is to have the CG members complete an FSA before the transfer (otherwise if Fred contributed Bill's patented idea, and vice versa, we're not covered., or all members of the CG that Contributed also become members of the WG.

I don't think the CG gets formal veto power; they made reports under a liberal license. Maybe they can be part of the consensus process.

We need to discuss what happens if the CG keeps incubating, in the hope of further chicks, when some of the chicks have been taken to the WG.

**Comment by dwsinger** [comment]
There is quite a bit in the CG process.  see for example https://www.w3.org/community/about/agreements/ "Transition to…" and section 9 of https://www.w3.org/community/about/agreements/cla/

**Comment by dwsinger** [comment]
I think we should close this and note that the required documentation is in the CG docs, not the process.

**Comment by frivoal** [comment]
I'm inclined to agree with @dwsinger, because:
* the Process does not talk about CGs, and from a WG's point of view, whether a new deliverable comes from a CG or some place does not make any diffirence as to what's needed to add new work
* While some specs from some CGs have graduated to some WGs, it isn't clear to me that there is broad agreement yet on the exact mechanics and timing for graduation, nor that it is necessarily well established that this is a path that works for all WGs. So I think we should be careful not to cast anything in stone (or in Process) to at this stage.

**Comment by frivoal** [comment]
Agenda+ to propose closing this, as @dwsinger suggested.

**Comment by dwsinger** [comment]
In #17 we suggested saying in the introduction at the end of section 1 "The W3C also operates Community and Business Groups, which are separately described in their own process document." and link to https://www.w3.org/community/about/agreements/.

**Comment by frivoal** [comment]
Sounds like a good idea. I'll make a PR for that too.

**Comment by frivoal** [comment]
PR here: https://github.com/w3c/w3process/pull/221
