### ISSUE TITLE
What are the rights and obligations of non-member participants in the creation of a member submission?

### ISSUE THREAD

**Issue by dwsinger** [w3c/w3process#19]
Transferred from https://www.w3.org/community/w3process/track/issues/139
State: Raised

**Comment by vfournier17** [comment]
I think there's some overlap here with #67.

**Comment by dwsinger** [comment]
I think that this issue may end up covering the entire question of getting IPR grants for 'Contributions' to a Rec-track spec by non-members of the WG that owns it.

**Comment by dwsinger** [comment]
see also #67

**Comment by dwsinger** [comment]
Process covers this in 10.2 and refers to PP 3.3 which says "all Submitters and any others who provide patent licenses associated with the submitted document must indicate whether or not each entity (Submitters and other licensors) will offer a license according to the W3C RF licensing requirements “ (PP) 3.3
