### ISSUE TITLE
Acronyms & Terms Section

### ISSUE THREAD

**Issue by nrooney** [w3c/w3process#198]
multiple suggestions that we need one, including in #86

**Comment by frivoal** [comment]
As I have mentioned in a couple of other issues, I think the best way to solve this is to convert the Process Document to bikeshed, use `<dfn>` everywhere appropriate, to cover both acronyms and terms, make liberal use of bikeshed's ability to cross reference terms, and let it automatically generate the appendix which lists all terms defined in the document.

**Comment by frivoal** [comment]
I'm happy to help with the bikeshed conversion if we decide in its favor. There is however one minor annoyance: using bikeshed means that we modify a source document, and generate the html from it.

For the final official process at https://www.w3.org/Consortium/Process/, this is fine. But for the work in progress visible form https://w3c.github.io/w3process/, this is a tad more annoying, as it means we should either commit the output as well as the source, or set up some server side thing to auto-generate the output every time we push a new change.

I suggest that for now we start with: don't commit the output in pull requests + regenerate and commit the output after merging. We can look into building infrastructure later. This seems to me to be the path of least resistance.

(cc @tabatkins, as the author of bikshed, for best practice suggestions)

**Comment by tabatkins** [comment]
Yeah, lots of people have set up auto-build-and-commit files for Travis CI. I haven't yet distilled them down into a form suitable for Bikeshed's docs to recommend, but I really need to do so. I recommend it for everyone, tho.

**Comment by dwsinger** [comment]
My sense is that this is something to keep in our pocket. I think there is some value in the document being readable/workable in people's copies of the repo without having to run a tool.

**Comment by tabatkins** [comment]
That's what Makefiles that curl out to the API version are for. ^_^

**Comment by frivoal** [comment]
We have [switched to bikeshed](https://lists.w3.org/Archives/Public/public-w3process/2019Feb/0000.html), so there is now an [index of Terms defined by this specification](https://w3c.github.io/w3process/#index-defined-here).

This problem is now solved. If there are problems with the index we now have, please raise as separate issues.
