### ISSUE TITLE
CSI Document

### ISSUE THREAD

**Issue by nrooney** [w3c/w3process#201]
Hi Process CG - the Working Group Effectiveness Task Force created a "Common Standards Issues" document which details some common issues working groups may experience when working on standards. The document lists "symptoms" of issues, a "result" of these symptoms (which are the core issues experienced), and ways to solve these by defining a list of qualities for a "Successful Working Group".

The group suggested we send these to you to take a look at - to see if there's anything which is worth including or noting in the process document. I'm not sure myself, but happy to cover the bases. 

https://github.com/w3c/wg-effectiveness/blob/master/CSI.md

**Comment by vfournier17** [comment]
What is the import of this document?  I suggest we include a statement stating that it is informative only, and in the event of a conflict with the Process Document or the Patent Policy, the latter documents govern.

**Comment by dwsinger** [comment]
Now we've alerted the process CG, we can close, and point them at the AB task force on working group effectiveness.
