### ISSUE TITLE
Should the AB and maybe TAG have lower/upper bounds for membership?

### ISSUE THREAD

**Issue by dwsinger** [w3c/w3process#204]
At the moment, the TAG and AB have defined participation numbers. (See #190 for the most recent change).

In the past, we had unopposed elections when the numbers were smaller. With an increased size, we run the risk of (in quieter times, if they ever happen again) of having trouble filling the larger committee. This can be alleviated by defining that these committees have "at least N and no more than M". In a sense, today, N=M.

I believe that the handling of this is unaffected by the voting system, though some have expressed concern to the contrary. 

I believe that the following apply under any voting system, and whether M=N or M>N.

1. At any election, if there are fewer nominations than needed to maintain the committee at at least N, then continue to do whatever we do now (I think our process is that we delay until enough nominations are received).
2. If the election system does not permit rejecting candidates, and the number of nominations is less than the number of free seats, then the candidates are elected unopposed (the resulting committee has <=M occupied seats).
3. If the number of nominations is greater than the number of free seats, then an election is held to appoint to fill exactly M seats.
4. If the election system were to permit rejecting candidates, then an election is always held. If the result is that fewer than N seats become occupied (too many rejected candidates), then the introduction of that voting system will have to describe what happens (the election is void and nominations re-opened? we open a second round for the unfilled seats?). We do not have, and have not had in the past, such an election system, so this should be dealt with if we ever introduce such.

Effectively at each election, we look at the number of seats not open for re-election, and subtract that from N and M (e.g. if N=9 and M=11 and 5 seats are not open for re-election, then we say we are looking to elect between 4 and 6 people).

**Comment by frivoal** [comment]
Given that we have staggered elections there's two ways of doing this: either have N&M defined for the total AB, or per election cycle.

The risk if we do it on the total, is that we may drift to really unbalanced cycles:
* N=9 and M=11
* 5 seats are not open for re-election, then we say we are looking to elect between 4 and 6 people
* 6 get elected
* next election 6 are not open for re-election, so we're looking for 3 to 5
* 3 get elected
* next election 3 are not open for re-election, so we're looking for 6 to 8
* 8 get elected
* next election 8 are not open for re-election, so we're looking for 1 to 3
* 1 gets elected
* next election 1 are not open for re-election, so we're looking for 8 to 10
* 10 gets elected
* next election 10 are not open for re-election, so we're looking for 0 or 1
* …

Most likely, this self corrects, and isn't that bad a problem. But saying , for instance, each cycle has 4 to 6.

Also, both in the case of total M/N, and per cycle M/N, we should consider what happens to short terms. Is there a short term vacancy everytime someone has to vacate their elected position before the end of that their term, or only if that would bring the number of representatives below N?

**Comment by chaals** [comment]
@frivoal said

> The risk if we do it on the total, is that we may drift to really unbalanced cycles:

That risk is why there is a provision for giving elected members a short term to ensure the next election puts half(ish) the seats up again.

**Comment by frivoal** [comment]
@chaals I think you missed my point. Look at the hypothetical scenario there. Nobody is terminated half-mandate, so the existing short-term clauses would not kick in.

**Comment by dwsinger** [comment]
You are right. 

Solution 1. Each election has to cap the seats at ceiling(m/2). So if only 3 get elected one cycle, we have to elect 6 the max) in the next. 

Solution 2. The seats are named odd-year and even-year seats, and unfilled seats in an odd-year election are open to be filled in an even-year election, but only for a 1 year term.

2 matches what happens when we have someone resigning mid-term just before an election.


(Though as you say, you have to have a run of unlikely events to get here.

**Comment by dwsinger** [comment]
I didn't answer the second question; what happens when someone resigns, is there an election? I think you are right, it only forces an election if we would drop below N.

**Comment by dwsinger** [comment]
Revised. I believe that the following apply under any voting system, and whether M=N or M>N.

1. There is a two-year cycle in the elections. At each election, half the seats are open for an election to a two-year term, and any vacant seats from the prior year (caused by recent resignation, or failure to fill in the prior year) are open for a one-year term.
2. At any election, if there are fewer nominations than needed to maintain the committee at at least N, then continue to do whatever we do now (I think our process is that we delay until enough nominations are received).
3. If the election system does not permit rejecting candidates, and the number of nominations is less than the number of free seats, then the candidates are elected unopposed (the resulting committee has <=M occupied seats).
4. If the number of nominations is greater than the number of free seats, then an election is held to appoint to fill exactly M seats. They are filled in the order of two-year terms first, and then one-year terms.
5. If the election system were to permit rejecting candidates, then an election is always held. If the result is that fewer than N seats become occupied (too many rejected candidates), then the introduction of that voting system will have to describe what happens (the election is void and nominations re-opened? we open a second round for the unfilled seats?). We do not have, and have not had in the past, such an election system, so this should be dealt with if we ever introduce such.
6. If there is a resignation mid-cycle, then a special election is held if the committee would drop below N; otherwise, the seat is eligible for re-filling at the next scheduled election. At any special election, all vacant seats are eligible to be filled. There is no provision for a special election to fill vacant seats at other times.

**Comment by frivoal** [comment]
I've made https://github.com/w3c/w3process/pull/216 to address this.

Notes:
* I did not include the conditional logic suggested by @dwsinger that did different things depending on whether the election system used allowed for rejecting candidates or not. The current one does not, so there's not need to talk about that. We can update the text if that ever changes.
* I introduced a cap on the maximum number of full terms seats open at any one time, to avoid the system getting too far off balance.

**Comment by dwsinger** [comment]
I think it might be easier to express that the seats are divided into even and odd year seats (counts that differ by at most 1), and that in an odd year:
* all odd year seats are vacated and open for election to two-year terms;
* all vacant even year seats are open for election to one-year terms;
and that elected representatives fill the seats in that order. (And similarly for the even years).

agree on leaving out "nun of the above".

**Comment by chaals** [comment]
(Except that I think we should still have the "no other candidate" option)

@frivoal the current system assigns a short term more or less on the lines of David's proposal - if more than the magic number x of seats are open, then all those beyond number x are fille for only one year instead of two.

**Comment by frivoal** [comment]
@dwsinger 
> I think it might be easier to express that [...]

Hmmm. I am not convinced that'd be easier / clearer. Evidence number 1: I am not sure understand how your proposal actually works.

@chaals 
The system I proposed assigns short terms exactly the same way the current system does, since I did not change that part: if we're have exactly the right number of candidates (in the new system: >= than the max, <= than the min), everybody is elected, and we draw straws for the short terms. If we have more candidates than seats, run the election the lowest ranked winner(s) get the short terms. This is unchanged.

**Comment by frivoal** [comment]
> agree on leaving out "nun of the above".

vs 

> (Except that I think we should still have the "no other candidate" option)

I'm not taking a stance on this in this issue. The edit proposed here assumes no change compared to the current practice: the option may be offered in the vote, but there's no provision for actually electing Nobody-san. If we want to discuss that, let's do that in a separate issue.

**Comment by dwsinger** [comment]
My text is a simpler replacement for the arithmetic in "<p>The number of seats open for election each year is determined as follows:". Similarly the minimum number of required candidates is the minimum size less the number of seats that are remaining filled after the seats are vacated. I think we have a fair number of people who don't like arithmetic ways of expressing things.

**Comment by frivoal** [comment]
In general, I don't love writing algorithms when descriptive text would do. But if we are about calculating something, I do find math easier to read than English.

I'm still not exactly sure what https://github.com/w3c/w3process/issues/204#issuecomment-426468400 means, or whether it is equivalent to https://github.com/w3c/w3process/issues/204#issuecomment-426501139

From either or both of these descriptions, can you let me know how you get to the number of open seats in the next AB election? Hypothesis:
* we currently have 9 participants
* 4 will be at the end of their term, 5 who are mid-terms
* Let's say that 1 of the mid-term is vacated prior to the election, leaving 4 continuing participants
* We will now allow 9 to 11 seats total.

Here's how mine goes:
```
c = 5
i = 1
m =  9-c =  9-5 = 4
n = 11-c = 11-5 = 6
minimum = m+i = 4 full terms + 1 short term = 5
maximum = n+i = 6 full terms + 1 short term = 7
```

How does your phrasing give a range of open seats for next year?
Do you get to 4&6 full terms thanks to "counts that differ by at most 1" compared to the continuing 5? Does that mean we'd get between 3 and 5 if we had 4 seats reaching the end of their term? If so, we're no longer between 9 and 11, but between 7 and 9 for that year. If not, then I don't understand what "counts that differ by at most 1" means.

**Comment by frivoal** [comment]
If you prefer an English phrasing instead of math, the following should be equivalent to what I wrote in the PR. I prefer the arithmetic.

> The minimum of full term seats to be filled in a given election is the minimum of total seats (9) minus the number of seats that have not yet completed therm term (including both continuing participants and vacated seats).
> 
> The maximum of full term seats to be provided in a given election is the maximum of total seats (11) minus the number of seats that have not yet completed therm term (including both continuing participants and vacated seats), capped at 7. <strong>Note: </strong>This cap is to avoid the cycles getting too unbalanced, ensuring that the maximum number of available full term seats is never lower than 4.
> 
> The number of incomplete terms to be filled due to vacated seats is added to both numbers to get to the total minimum and maximum numbers to be filled in that election.

**Comment by dwsinger** [comment]
The number of open seats is the number of seats allocated to this year (5) plus the number of seats vacant from the previous year (which is 2, one unfilled at the last election, and 1 who has resigned). This is correct, we can fill at most 7 seats. The minimum is 9 (the minimum) less the continuing filled seats (4), which is 5. If we will 7, one person gets a short straw as the number of seats allocated to this year is 6.

**Comment by dwsinger** [comment]
> If you prefer an English phrasing instead of math, the following should be equivalent to what I wrote in the PR. I prefer the arithmetic.
> 
> > The minimum of full term seats to be filled in a given election is the minimum of total seats (9) minus the number of seats that have not yet completed therm term (including both continuing participants and vacated seats).
> > The maximum of full term seats to be provided in a given election is the maximum of total seats (11) minus the number of seats that have not yet completed therm term (including both continuing participants and vacated seats), capped at 7. **Note: **This cap is to avoid the cycles getting too unbalanced, ensuring that the maximum number of available full term seats is never lower than 4.
> > The number of incomplete terms to be filled due to vacated seats is added to both numbers to get to the total minimum and maximum numbers to be filled in that election.

This doesn't seem right.  If everyone from last year's cycle resigns, we have to elect 9, not 7; 6 to two-year terms, and 3 to one year.

**Comment by frivoal** [comment]
> This doesn't seem right. If everyone from last year's cycle resigns, we have to elect 9, not 7; 6 to two-year terms, and 3 to one year.

That's not what I said (and I think it was easier see in math)

If we have 5 who should have been continuing, we have 4 (9-5) to 6 (11-5) full seats even if the 5 did resign, plus 5 short term, because they did resign. 4+5=9, 6+5=11, we're good. The cap is on n, not on n+i.

**Comment by frivoal** [comment]
As to your https://github.com/w3c/w3process/issues/204#issuecomment-426509734 comment, I agree with the calculation you describe, I just don't see how it follows form the text you propose to add.

As for my "capped at 7" provision, it's supposed to kick in i a year like that:

Total on currently on the AB: 10. 3 mid term, 7 terms expiring.
c = 3
i = 0
m = 9-c = 9-3 = 6
n = cap 11-c at 7 = cap 11-3 at 7 = cap 8 at 7 = 7
  => elect between 6 and 7 (instead of 6 and 8), so that next year we get 2-to-4 rather than 1-to-3.

We could say 6 instead of 7 if we want the cycles to be even more balanced, but I don't know if it is necessary. With a cap a 7, the lowest range is 2-4 and the highest one is 7-7 With a cap at 6, he lowest range is 3-5, and the highest is 6-6.

I'm not sure what your proposal says. Ignoring vacated seats, are you saying that every year is alternating between 4-5 and 5-6? If so, I suggest stating the numbers directly would be clearer. If not, I still don't understand.

And if that is indeed what you mean, it means that in any given election, we can only go up by 1 participant, even if we were at 9, and have a glut of candidates (or only go down by 1, even if we were at 11 and have a dearth of candidates).
My approach allows for bigger swings, (and the cap avoids getting too far off balance).

**Comment by chaals** [comment]
No, if there are 3 continuing members then 6-8 seats are up for election, but only 5 of those elected will have a 2-year term, with the rest having a one-year term so at least 5 seats are open for election again in a year's time.

This is how it has worked for the last couple of decades.

**Comment by frivoal** [comment]
> This is how it has worked for the last couple of decades.

No, we have not had a variable range of candidates, so precedent cannot be used to explain how variable ranges have worked.

> No, if there are 3 continuing members then 6-8 seats are up for election, but only 5 of those elected will have a 2-year term, with the rest having a one-year term so at least 5 seats are open for election again in a year's time.

I'm not saying that there are just 3 continuing members out of 4 previously elected. I'm saying last round, we could elect 3 to 5 (because the round before we did elect 6 to full terms, which is a valid thing to do when there are 9 to 11) and only 3 ran, so we elected 3. what now.

For instance, here is a whole series that gets us there (and beyond), starting from the current configuration, with no vacated seats ever.

1. total = 9 (5 mid term, 4 expiring next)
    c = 5
    m = 9-5=4
    n = 11-5=6

    We can elect 4 to 6,  6 (or more) run, 6 win

2. total = 11 (6 mid term + 5 expiring next)
    c=6
    m= 9-6=3
    n=11-6=5

    We can elect 3 to 5,  4 run, 4 win


3. total = 10 ( 4 mid term, 6 expiring next)
    c=4
    m=9-4=5
    n=11-4=7

    We can elect 5 to 7,  7 (or more) run, 7 win

4. total = 11 (7 mid term, 4 expiring next)
    c=7
    m=9-7=2
    n=11-7=4

    We can elect 2 to 4,  3 run, 3 win


5.  total = 10 (3 mid term, 7 expiring next)
    c=3
    m=9-3=6
    n=11-3=8, but 8 is more than the 7 cap, so n=7

    We can elect 6 to 7,  7 (or more) run, 7 win

6. total = 10 (7 mid terms, 3 expiring next)
    c=7
    m=9-7=2
    n=11-7=4

    We can elect 2 to 4,  2 run, 2 win

7. total = 9 (2 mid term, 7 expiring next)
    c=2
    m=9-2=7
    n=11-2=9->7

    We can elect 7,  7 (or more) run, 7 win

If you rules are different (I think they are), can you explain how it would run this series, and from which step it would start to be different and why?

**Comment by frivoal** [comment]
Ok, maybe I understand now. It looks like you're saying that 
* in addition to however many were vacated mid mandate,
    - on even years we can elect at most 5 full terms
    - on odd years we can elect at most 6 full terms 
* on any year, we must elect at least 9 minus however many are actually continuing their term.
* Regardless of the max and min, I also think you're saying that however many were vacated is the number of short terms.

If that's what you mean, then:
1. yes, that can work
2. it is different from what you had proposed in the opening comment, and neither is it a simpler rephrasing of the arithmetic, but actually a different system. Which is why it took me so long to understand what you meant.
3. I prefer my method, as it allows for more rapid increases and decreases of the AB size depending on the number of candidates, while keeping the same bounds, and preventing strongly unbalanced cycles, but I would not object to your approach if it has the favor of the majority.

If that's not what you mean (and even if it is), I will have to insist that actual math is clearer, cause I still don't get it.

**Comment by frivoal** [comment]
>     Regardless of the max and min, I also think you're saying that however many were vacated is the number of short terms.

Actually, I think that's what you mean, but probably chaals meant that that the number of short terms is only the number in excess of 5 (in even years) or 6 (in odd years).

I still would like to see one (or several, if you disagree) rigorous definitions of what your proposal(s) are.

**Comment by dwsinger** [comment]
Your last two together catch it, I think.

Max/2 seats are assigned to each year, differing at most by one (so, 6 and 5 in the case Max is 11).

In any given year, the seats allocated to that year are vacated and eligible for two-year terms. Any seats that are currently vacant from the prior year are also eligible for election, but for one year terms.

We must elect enough (have enough nominations) that when the elected seats are added to the occupied seats from the prior year, we have min (9) or greater occupied seats.

We only run an actual election if the number of nominees plus the number of occupied seats from the prior year exceeds Max.

If someone resigns, we only call for nominations, and potentially hold a special election, if the committee would go below Min. If we do, then all unoccupied seats become eligible for filling. The same condition applies for running the actual election; that the number of nominees plus the number of occupied seats exceeds Max.

(I'm trying to match as closely as possible what the current process and practice are, where min=max, and only changing which of those two values are referred to.)

**Comment by frivoal** [comment]
Alright, I think that does work.

Again, I prefer mine as it allows going from 9 to 11 or 11 to 9 in one election in case of a candidate surge / dearth, while yours only allows adding 1 at a time. Also because I think mine is easier to phrase precisely. Do you want to try and write down yours as a PR to make sure it is precisely nailed down, then we straw-poll the group for which is preferred?

**Comment by dwsinger** [comment]
> If you prefer an English phrasing instead of math, the following should be equivalent to what I wrote in the PR. I prefer the arithmetic.
> 
> > The minimum of full term seats to be filled in a given election is the minimum of total seats (9) minus the number of seats that have not yet completed therm term (including both continuing participants and vacated seats).
> > The maximum of full term seats to be provided in a given election is the maximum of total seats (11) minus the number of seats that have not yet completed therm term (including both continuing participants and vacated seats), capped at 7. **Note: **This cap is to avoid the cycles getting too unbalanced, ensuring that the maximum number of available full term seats is never lower than 4.
> > The number of incomplete terms to be filled due to vacated seats is added to both numbers to get to the total minimum and maximum numbers to be filled in that election.

I confess to not understanding this. Particularly starting with "(including both continuing participants and vacated seats)". why are we subtracting vacant seats?

**Comment by frivoal** [comment]
> I confess to not understanding this

I find it hard to read myself, hence the preference for arithmetic

> why are we subtracting vacant seats?

because we're counting the number of **full term seats** available, and that does not depend on how many seats have been vacated. The vacated seats are added back at the end, for short term seats.

**Comment by frivoal** [comment]
I've made a new PR to close this: #224.
This is in line with the Proposal from @dwsinger and @chaals , and supersedes my earlier attempt (in PR #216 )
