### ISSUE TITLE
What are the requirements to update a CR?

### ISSUE THREAD

**Issue by dwsinger** [w3c/w3process#207]
cloned from #172  https://github.com/w3c/w3process/issues/172#issuecomment-413196028

Do we need to describe what conditions need to met to *update* a CR with a 'second CR'? One school says "same as entering CR", but another points out that maybe the CR has more than one problem, identified since CR entry, and perhaps it should be legitimate to update the CR to fix some but not all.

Or maybe that's what WG working drafts are for?

**Comment by frivoal** [comment]
Proposed solution to this in https://github.com/w3c/w3process/pull/215

**Comment by frivoal** [comment]
This should not be on the agenda as long as #172 hasn't been solved, since it is a follow up. Removing the label.
