### ISSUE TITLE
Removal of "Member" from 2.5.1: unintended consequences

### ISSUE THREAD

**Issue by wseltzer** [w3c/w3process#208]
The removal of "Member" from 2.5.1 bullets appears to prohibit W3C from having a chair/participant and a Team Contact: "An organization is permitted at most one participant on the AB" (and TAG, with term consideration). Should the text read "An organization other than W3C..."?

**Comment by dwsinger** [comment]
Is the W3C "an organization" under the terms of the process? not clear (it doesn't sign the membership agreement, doesn't exist as a legal entity, …).

I'd be fine with (other than the W3C itself) being inserted, however.

**Comment by frivoal** [comment]
I don't think this correction is needed or helpful. 2.5.1 is ostensibly about elected/appointed seats, so talking about W3C participation is not relevant, and 2.3.1 ("Advisory Board Participation") already states that:

> The Advisory Board consists of nine elected participants and a Chair. The Team appoints the Chair of the Advisory Board, who is generally the CEO. The team also appoints a Team Contact for the AB

With equivalent phrasing for the TAG in 2.4.1

The addition of "other than the W3C itself" may instead make it look like that W3C staff is not only eligible to elections, but can actually hold multiple elected/appointed seats. I don't think we want to suggest that.

**Comment by frivoal** [comment]
Agenda+ to suggest closing as WONTFIX

**Comment by chaals** [comment]
@frivoal said

> The addition of "other than the W3C itself" may instead make it look like that W3C staff is not only eligible to elections, but can actually hold multiple elected/appointed seats. I don't think we want to suggest that.

In the TAG, it is true that W3C staff are eligible for election and that multiple W3C staff can be appointed as "director's picks". likewise there is a pretty strong argument that the director has appointed more than one person from the same *non*-W3C organisation to the TAG in the past.

I agree that the "other than W3C' language is not the answer - I think instead we should say something along the lines of

> ...at most one **elected** participant...

**Comment by dwsinger** [comment]
In the current process it's clear that the Director cannot appoint someone from the same organization as an elected member. If you insert 'elected' that would no longer be true. I do not agree with this relaxation. I think this is a tarpit; is w3c one organization or four (MIT, ERCIM, Beihang, Keio)? Is there a practical problem here?

**Comment by wseltzer** [comment]
Practical problem: don't leave an opportunity for someone to complain that W3C is violating its newly-updated process by having a chair and team contact both from W3C.

**Comment by dwsinger** [comment]
I don't think the team contact occupies a 'seat' under the terms of 2.5.1.

**Comment by dwsinger** [comment]
why don't we change participant (undefined) to 'seat' (which is what the section is talking about)?

"An organization is permitted to hold at most one seat on the AB" (we should match the change into the TAG?)

**Comment by frivoal** [comment]
WFM I'll make a PR.

**Comment by frivoal** [comment]
Made https://github.com/w3c/w3process/pull/220 based on the above.

**Comment by frivoal** [comment]
(btw, in case anyone's looking for it, the original change that caused this was https://github.com/w3c/w3process/commit/e1788267a674a33dedcb9e9b951edca0e2f05ad4)

**Comment by swickr** [comment]
While I concur with the intent of #220, I believe that the wording leads to unintended confusion when considered in conjunction with the (new) text in 2.5

> Individuals elected or appointed to the Advisory Board or TAG act in their personal capacity

The intent of 2.5 is to be very clear that AB and TAG participation is _not_ an organizational seat.  Therefore using "organization" and "seat" in the same phrase in 2.5 dilutes this.  I suggest that better wording for 2.5.1 would be

> Two participants with the same primary affiliation per 2.5.2 may not both occupy elected seats ...

**Comment by frivoal** [comment]
As far as I can tell, the normative consequence of both phrasings would be the same, but I agree that the one you suggest is better, for the reason you mentioned.

I've made https://github.com/w3c/w3process/pull/227 to propose adding this change.

**Comment by dwsinger** [comment]
I don't mind the improvement, but I note that those three bullets are pre-existing from process 2018 (and before).
