### ISSUE TITLE
RFC2777 is obsolete

### ISSUE THREAD

**Issue by frivoal** [w3c/w3process#233]
The Process invokes the [RFC2777](https://tools.ietf.org/html/rfc2777) to define the [Verifiable Random Selection Procedure](https://www.w3.org/2018/Process-20180201/#random). RFC2777 is obsolete, and replaced by [RFC3797](https://tools.ietf.org/html/rfc3797) (using W3C vocabulary, we would say that RFC2777 is superseded by RFC3797).

[The Change section](https://tools.ietf.org/html/rfc3797#page-16) does not seem to indicate any difference that would be problematic for us.

We should update accordingly.

**Comment by dwsinger** [comment]
agreed

**Comment by frivoal** [comment]
This is an easy fix, but we're late in the cycle. Would you rather fix this for Process2019 or next year? No strong preference from me.
