### ISSUE TITLE
Change informal uses uses of the word "dissent"

### ISSUE THREAD

**Issue by frivoal** [w3c/w3process#239]
In the Process, “dissent” is unambiguously defined (in [section 3.3](https://w3c.github.io/w3process/#Consensus) as:
> The following terms are used in this document to describe the level of support for a decision among a set of eligible individuals:
> [...]
> Dissent: At least one individual in the set registers a Formal Objection. 

However, the same word is used in a couple of places without apparent intent to refer to Formal Objections. In such cases, it should be replaced with a different word, possibly "disagreement".

* In [section 3.4](https://w3c.github.io/w3process/#Votes)
  > When simple majority votes are used to decide minor issues, the minority are not required to state the reasons for their **dissent**, and the group is not required to record individual votes.

   Disagreeing with a proposal that is being put to a vote isn't the same as raising a format objection. Thus, the word “dissent“ is the wrong one here. “disagreement“ or “opposition“ would do fine.

* In section [6.2.5](https://w3c.github.io/w3process/#correction-classes)
  > Corrections that do not affect conformance
  > [...]
  > If there is any doubt or **dissent** as to whether requirements are changed, such changes do not fall into this class. 

  Given that it is combined with “any doubt or”, it seems clear hear that ordinary disagreement is sufficient to trigger this clause, and that formal objections are not required. “disagreement“ would do better.

**Comment by nigelmegitt** [comment]
Surely the same rule applies to all voters, whether they are in the majority or the minority, and that rule is that they are not required to state the reasons for their voting position, or "vote"?

On 6.2.5 I agree with your take @frivoal .

**Comment by chaals** [comment]
An alternative approach would be to keep "dissent" having its plain english meaning, and state the term "Formal Objection" where that is what is meant.

**Comment by frivoal** [comment]
fixing incorrect uses of dissent is less work that replacing all (correct) existing uses with references to formal objections, so unless you feel strongly that using formal objection everywhere, I'm inclined to take the easy way.

I feel weakly that using formal objection everywhere would be more readable and more obvious, but then again their might be external documents referring to dissent, so I am a little bit concerned about breaking that usage. Not a lot concerned, but just enough to overcome my editorial preference for using Formal Objection everywhere, and I'm back to siding with the lazy approach. But I can probably be convinced to otherwise if you have stronger feelings.

**Comment by frivoal** [comment]
> Surely the same rule applies to all voters, whether they are in the majority or the minority, and that rule is that they are not required to state the reasons for their voting position, or "vote"?

Presumably those who proposed the thing people are voting on explained why they want it, otherwise they're going to have a hard time convincing people. I think this is trying merely saying that you're allowed to disagree without saying why. I don't think it'd be terribly useful to say that you're allowed to propose something without justifying it. Even then, I agree with you that this is clumsy phrasing, and we can further simplify the sentence:

> When simple majority votes are used to decide minor issues, voters are not required to state the reasons for votes, and the group is not required to record individual votes.

**Comment by nigelmegitt** [comment]
> When simple majority votes are used to decide minor issues, voters are not required to state the reasons for votes, and the group is not required to record individual votes.

@frivoal works for me.

**Comment by frivoal** [comment]
Agenda+ to (try to) approve the PR (#256) made to reflect the above discussion.

**Comment by dwsinger** [comment]
Fine with this; and I'd be fine with removing the word dissent entirely and saying Formal Objection when we mean that, and disagreement when we mean that.

**Comment by dwsinger** [comment]
agreed on the March call
