### ISSUE TITLE
Patent policy and TAG participation

### ISSUE THREAD

**Issue by frivoal** [w3c/w3process#241]
As a matter of course, The TAG gives feedback to working groups on specifications, and Working Groups acting on that feedback may change their specifications. The TAG member or members at who are at the origin of the feedback that lead to a spec change are often not members of the Working Group in charge of that spec.

However, there doesn't seem to be anything in the patent policy covering that.

The Process itself has two things:
* The newly introduced section [6.2.6 Contributor license Grants](https://w3c.github.io/w3process/#contributor-license) which arguably could cover this case, but I don't believe it has been used this way, and asking the team to reach out to TAG participants one by one every time they comment on a spec from a new working group doesn't seem to scale.

* In [section 2.5](https://w3c.github.io/w3process/#AB-TAG-participation):
  > TAG participants [...] their participation does carry the responsibilities associated with Member representation, Invited Expert status, or Team representation (as described in the section on the AB/TAG nomination and election process). See also the licensing obligations on TAG participants in section 3 of the W3C Patent Policy [PATENT-POLICY], and the claim exclusion process of section 4.

  However, neither section 3 or 4 (or any other section) of the patent policy mention tag participants, nor does section on the AB/TAG nomination mention the patent policy. So it is unclear to me what are the patent policy implications on TAG participants and on the company they are affiliated.

I suggest that we add to something like this to the process (in addition or instead of the “See also the licensing obligations [...])” sentence):

> For the purpose of the Patent Policy, TAG participants are deemed to be participants of all Working Groups active during their term (or during any part of their term). In the case of Invited Expert, they are deemed to be participating to the Working Groups as Invited expert (section 3.4 of the Patent Policy); in the case of individuals affiliated with a Member Organization, the Member Organization is deemed to be participating to the Working Groups (section 3.1 of the Patent Policy). Participation starts on at the beginning of the TAG participant's term in the case of Groups whose charter start before that date, and when the Group is [created](https://w3c.github.io/w3process/#cfp) for Groups whose charter start after the beginning of the TAG participant's term.
>
> As long as an individual affiliated with a Member Organization remains on the TAG, that Member Organization cannot [resign](https://w3c.github.io/w3process/#resignation) from any working group nor use the “Exclusion and Resignation From the Working Group” mechanism specified in section 4.2 of the Patent Policy.
>
> If a TAG participant affiliated with a Member Organization resigns from the TAG, the Member Organization is released from the above constraint. The same is true if they change affiliation, 

We should probably also add an exception allowing a TAG participant may recuse themself from commenting on all specifications produced by a particular Working Group, thereby allowing the company they are affiliated to not to be deemed a participant of that group. If we don't companies may shy away from allowing their employees to run for the TAG, which isn't the intended effect. I'm happy to try drafting that too, but this is long enough already, so I'd like some feedback on the above before I go too far down this rabbit hole.

**Comment by michaelchampion** [comment]
I'm skeptical this can be done in the Process rather than the patent policy.  And I fear it will a showstopper for some key members considering nominating someone for the TAG is that is implicitly signing up their lawyers to monitor all W3C WGs and process calls for exclusion.

I vaguely recall that this has been a perennial PSIG topic and a solution has been elusive.

**Comment by chaals** [comment]
The topic has indeed come up before in member-private groups, a number of times over the last half-decade or so, and agreement has indeed been elusive.

It essentially boils down to whether there is more value in the patent commitments made over review comments than in the potential chilling effect on certain people running for TAG, or electing not to take part in a TAG review. As a value judgement about the future, that makes it very hard to determine the right answer based on data.

It would be nice if there were a mechanism whereby TAG (and other review group) members could make a formal commitment if they are proposing contributions to the specification. While putting it into the Patent Policy would be the obvious thing, it can in fact be done in Process by requiring a Patent commitment equivalent to that of a Working Group member over a spec for which a non-member of a Working Group makes a commitment. This basically matches existing proposals to tighten up the requirements on contributions from people who are not members of a Working Group, althought given the high volume of review some groups do, it's more relevant to the participants and probably has a greater impact on them than the case of a casual substantive contribution.

**Comment by michaelchampion** [comment]
OK, requiring an RF commitment on a TAG members' individual *contributions* to specs in WGs that their employers are not members of is arguably something that could be done via the Process.     That's not what was proposed in this issue, "TAG participants are deemed to be participants of all Working Groups active during their term", however.

**Comment by dwsinger** [comment]
Anything here is going to take PSIG discussion. I think the proposed fix is, as discussed here, unworkable. How often does the TAG propose specific technology to a draft? Most often, they critique, no?

**Comment by frivoal** [comment]
Maybe for context, it helps to explain why I raised this. When I raised #242, I ran into a puzzle: as you can see in that issue, for people who're affiliated with a member, "resigning from a group" is defined to be something that AC reps do. Which doesn't seem to make sense for the TAG and the AB. So I was about to suggest we amend that text to make it clear that TAG and AB members can just resign on their own, and was about to justify that by saying that "there's not IP implication anyway", but then I wasn't so sure anyway that there was indeed no IP implication. The paragraph that said "See also the licensing obligations on TAG participants in section 3 of the W3C Patent Policy [PATENT-POLICY], and the claim exclusion process of section 4." seems to claim there is, but since the things it claims to refer to in the Patent Policy don't actually exist, I was back to being confused.

Granted, my proposed solution for this is blunt and not terribly practical. But the current situation is quite strange.

**Comment by dwsinger** [comment]
I agree that those links need clarifying or removal as they don't seem to apply. 

I think we need to clarify that cross-functional groups should not make specific proposals of any significance, but instead provide confine to review comments. Beyond that, I don't want a cure that is worse than the problem; the idea that a member company will inject essential IPR into a document while not a member of the WG, through cross-functional review, and then refuse to license it, seems extreme; whereas requiring the cross-functional reviewers to be under a license obligation would have a serious chilling effect.

**Comment by frivoal** [comment]
Having though about it some more, I think we don't need to require it, and can simply assume that cross-functional groups will generally not make specific proposals of any significance, but instead provide confine to review comments. In the rare cases when they would make direct contributions, we can invoke the terms of [6.2.6. Contributor License Grants](https://w3c.github.io/w3process/#contributor-license).

Based on that, I think we should just remove the broken references to section 3 and 4 of the patent policy from section 2.5

**Comment by dwsinger** [comment]
we propose to delete "See also the licensing obligations on TAG participants in section 3 of the W3C Patent Policy [PATENT-POLICY], and the claim exclusion process of section 4." from 2.5, but welcome PSIG input.

**Comment by dwsinger** [comment]
Referred to PSIG, awaiting input

**Comment by wseltzer** [comment]
Thanks @dwsinger. PSIG does not object to deletion of the sentence you identify [above](https://github.com/w3c/w3process/issues/241#issuecomment-490511402).

**Comment by dwsinger** [comment]
I believe we are approved to merge; agenda+ for the next meeting to confirm

**Comment by frivoal** [comment]
Pull request created: https://github.com/w3c/w3process/pull/282

My suggestion would be to merge, because we lose nothing by deleting a sentence that invokes text that does not exist.

After that, if some of us are concerned that we need some additional IPR mechanism for TAG participants, they can open a new issue about that. (Given that we have https://w3c.github.io/w3process/#contributor-license, I think we're good and don't need anything else, but we can talk).

**Comment by frivoal** [comment]
Resolution recorded here: https://www.w3.org/2019/05/22-w3process-minutes.html
