### ISSUE TITLE
Resignation of AB and TAG members is illdefined

### ISSUE THREAD

**Issue by frivoal** [w3c/w3process#242]
[Section 2.5.3 on AB and Tag vacated seats](https://w3c.github.io/w3process/#AB-TAG-vacated) talk about the possibility of a participant on the AB or TAG resigning, and links this "resigning" to [section 3.6](https://w3c.github.io/w3process/#resignation), which defines resignation from a group as something an IE can do on their own behalf, or that an AC-Rep can do on behalf of their company. There isn't anything there saying how an individual affiliated with a member can resign from a group. This could be misconstrued as implying that AC-Reps can retire the participation of individuals elected to the TAG or the AB who are affiliated with them.

We should either we stop linking the "resign" in 2.5.3 to 3.6 and simply rely on the plain English sense of the word "resign", or we should amend 3.6 to cover this case as well.

I'd generally be tempted to go with the former, but depending on the implications on the patent policy (See https://github.com/w3c/w3process/issues/241 for an open issue on that topic), we might need to be specific about how resignations work, at least for TAG members.

**Comment by dwsinger** [comment]
indeed, unlink it. resign here has its plain english meaning, IMHO, not the process for having AC Reps resign people on their behalf.

**Comment by chaals** [comment]
+1 to @dwsinger - unlink it. Currently, neither the TAG nor the AB produce W3C Recommendations, so resignation doesn't have patent policy implications. If the TAG takes up the effort of revising the Architecture of the World Wide Web Recommendation, we probably need to deal with the patent policy implications of the fact that people are in the group by virtue of being elected, and how to resign is a relatively straightforward variant of not being re-elected IMHO.

**Comment by frivoal** [comment]
PR here: https://github.com/w3c/w3process/pull/283

**Comment by frivoal** [comment]
@dwsinger I think this is trivial enough that you might want to call it resolved without waiting for next call. If you do want to wait, that's fine by me though.

**Comment by dwsinger** [comment]
unlinking is trivial.  do it.
