### ISSUE TITLE
Undefined term: member-visible

### ISSUE THREAD

**Issue by frivoal** [w3c/w3process#244]
[Section 7.2](https://w3c.github.io/w3process/#ACAppeal) talks about making the archive of statements made by AC reps during an Appeal “Member-visible“, but that term isn't defined. Is that supposed to be the same as “Member-only“ which is [defined](https://w3c.github.io/w3process/#Member-only) (if so, we should use that term), or is it supposed to mean something different, such as “at least member-only, possibly also public“?

**Comment by dwsinger** [comment]
No, member-only says it's NOT public.  Member-visible means it's NOT team-only. Suggest we replace it with a phrase

The archive of these statements must be visible to at least the Advisory Committee representatives.

**Comment by dwsinger** [comment]
Agreed May2019 that we'll define it as member-only, as defined.

**Comment by dwsinger** [comment]
resolved: to change to “visible member-only”

**Comment by nigelmegitt** [comment]
https://github.com/w3c/w3process/issues/249#issuecomment-490557889 refers to this issue, and says the resolution is to change to "visible Member-only".

**Comment by dwsinger** [comment]
(The usual rules would apply to making something public that was member-only; widespread consent and no opposition)
