### ISSUE TITLE
Incorrect use of the specialized term "publish"

### ISSUE THREAD

**Issue by frivoal** [w3c/w3process#245]
[Section 6.1](https://w3c.github.io/w3process/#rec-advance) says:
> Publishing as used in this document refers to producing a version which is listed as a W3C Technical Report on its Technical Reports page https://www.w3.org/TR

However, [Section 10 on member submissions](https://w3c.github.io/w3process/#Submission)
>After review, the Team may **publish** the material at the W3C Web site.

Given that member submissions are not included in /TR (as correctly pointed out in a note further down in the same section), publish is the wrong verb to use in that sentence. I suggest replacing with "may make the material available at the W3C website".

**Comment by frivoal** [comment]
Agenda+ to (try to) accept PR #257 to fix this issue.

**Comment by dwsinger** [comment]
agreed in march
