### ISSUE TITLE
Does the “Team Submission“ mechanism still serve a purpose?

### ISSUE THREAD

**Issue by frivoal** [w3c/w3process#246]
The [team submission Process](https://w3c.github.io/w3process/#TeamSubmission) has been used once in the last 10 years. The Team certainly has useful things to say, and shouldn't be prevented from doing so, but it is not clear that this specific mechanism is still relevant or needed to enable that.

Given that the Team Submission process offers no Patent Policy coverage, it seems that between a the Team's Blog for opinion pieces, CGs (or WGs) for technical work, /Guide, https://w3c.github.io/..., or and the fact that the Team maintains the W3C website at large anyway, there's enough means for Team members to express themselves.

I wonder if we couldn't simplify the W3C Process a little by doing away with Team Submissions entirely (existing content can of course stay).

**Comment by nigelmegitt** [comment]
Team members can also be WG members, so it follows that in a sense they are in fact _members_, so why can they not simply use the member submission process?

**Comment by frivoal** [comment]
Members refer to Member Organizations. Team contacts are WG participants, not WG members. The member submission process isn't open to them.

**Comment by chaals** [comment]
A formal pathway that allowed the technical staff to make submissions would in principle be useful. In practice they have to go through review by the management. 

I don't see the value over the ability of team to e.g. comment in working groups, on repos, or through their own blogs etc. A team member can also work to get an idea published by an IG or WG as a Note. I think that's enough.

A slightly regretful +1 to removing this from the process.

**Comment by frivoal** [comment]
Made a tentative PR (#255) for this. Agenda+ to discuss. Would appreciate getting more input from a broader range of people.

**Comment by michaelchampion** [comment]
Hmm. I feel a rant coming on, sorry...
I fear we're discussing a number  of Process changes recently that don't address real-world problems, but seem intended to remove "cruft" from the process document.  Sure the process document has lots of cruft in it, nobody remembers why it's there, but IT MIGHT HAVE BEEN PUT THERE FOR A REASON WE WILL PAINFULLY RE-DISCOVER SOMEDAY.  (This was inspired by my recollection of https://www.joelonsoftware.com/2000/04/06/things-you-should-never-do-part-i/  -- code gets messy when bugs are fixed, cleaning up code often re-introduces bugs).

Is the Team Submission process doing anyone any harm?  Consider the only recent example, https://www.w3.org/TeamSubmission/2017/SUBM-sdbp-20170302/ :  What purpose was the team trying to achieve making it a Submission?  Was that objective achieved?  If not, is that because the team submission process is useless, or  because there's no mechanism to drive a decision on what to do with submissions?  Would that document have had the same impact if it were a blog post or a GitHub issue or a Twitter thread?  Shouldn't someone formally ask @plehegar and other team members what they think???

I don't object to removing this feature from the process *if* the team agrees they have no need for it anymore, but I'd prefer the Process CG focus on bits of the process that are causing problems or preventing them from getting fixed.

**Comment by dwsinger** [comment]
No problems. We are getting ready for the trial edit to work out what the process might look like if there were no Director. Not sure this section is particularly in the way, but...

**Comment by frivoal** [comment]
> we're discussing a number of Process changes recently that don't address real-world problems, but seem intended to remove "cruft" from the process document.
> [...]
> Is the Team Submission process doing anyone any harm?
> [...]
> I'd prefer the Process CG focus on bits of the process that are causing problems or preventing them from getting fixed.

Correct, this is mostly intended to clean up cruft, rather than attempting to solve an acute problem. Whether this particular section is cruft is up for discussion, but I want to defend the interest of cleaning up cruft.
* “the process is already too long” is often used as an argument against otherwise useful additions. If keeping the process short to enhance its readability is a goal (and I agree it should be), then I don't think it is reasonable to apply that logic only to new additions, while allowing needless parts to remain. It remains valid to argue whether any one part is needed, but if we conclude something is cruft, removing it is the right thing to do.
* I just converted the process from plain HTML to bikeshed, and in the process, read everything top to bottom and checked all cross references, and along the way found quite a lot of places where the process is messy, inconsistent, or self contradictory. This negatively affects both the ability to read and understand it, as well as the ability to make progress on edits for substantial issues we do want to address for their own sake. Trying to make a change (even minor) to a problematic sentence tends to get you entangled in the whole spaghetti ball of fixing the underlying contradictions. Similarly, when you want to change the definition of a particular term, you need to check how that term is used, and when it's used inconsistently or incorrectly, that makes us go down in rabbit holes we had no interest in.

So, I think cruft cleaning is a valuable activity.

As to whether this particular bit is cruft or valuable:
1. It is hardly used anymore: once in 10 years. You are right, we should absolutely hear from the team (and especially @plehegar who used it last) about whether they think this still has value. I didn't mean to rush this deletion, just to stimulate discussion as to whether this was worth deleting. Apologies for not making that clear.
2. It involves the Director making decisions. As @dwsinger mentioned, we have started the exercise of evaluating what the Process could look like if there was no Director. If we don't remove this, we need to figure out what the alternative decision process is. If Team submissions are still useful, this is worth doing. If they're not, this is unnecessary overhead.
3. It uses words inconsistently with their definition: it claims that it enables the team to ask the Director to **publish** things. Publishing is defined in [6.1](https://w3c.github.io/w3process/#rec-advance) as “producing a version which is listed as a W3C Technical Report on its Technical Reports page https://www.w3.org/TR”. Then it goes on to say that Team Submissions are not part of TR, effectively contradicting itself. Now, this particular contradiction is not particularly hard to resolve, but if Team Submissions no longer serve a purpose, maintaining that text is unnecessary overhead. (And keeping know-to-be-incorrect statements is sloppy practice).
4. I have heard some members express concern about Team Submissions and their possible use to kick start REC track documents, due to the lack of IP protection. Given how little they are used, I am not convinced this is a pressing issue, but if they no longer exist, we don't have to worry about it.

**Comment by dwsinger** [comment]
propose to leave this hanging a little longer with its agenda+ for more opinions.

**Comment by frivoal** [comment]
Agenda+ is not good at drawing the attention of people who're not otherwise paying attention. If we think we want the input of specific people, we should bring them into the conversation. Just waiting does not sound the most efficient. I don't think we necessarily need to close this during next call, but I would like either to find out what we need to do to close it one way or another, or to decide that we're already at that point and try to make the decision.

Input from @plehegar would be interesting. Alternatively, maybe @jeffjaffe can comment whether the Team as a whole has good uses for this.

As for me, given that the Team already has the ability to put stuff up on the W3C website anyway, having a process by which the Team can ask the Director to allow them to put stuff up on the website, knowing that the Director will generally delegate that decision back to the team anyway, sounds completely superfluous. It does not grant extra IP protection, it does not grant extra authority, so I'd like to do away with it.

**Comment by plehegar** [comment]
I agree that the team has many venues for publishing specifications, including CGs. If removed from the Process, we'll keep maintaining https://www.w3.org/TeamSubmission/ and continue to only add to it if approved by the Director but I agree the Process doesn't need to deal with it anymore. So 👍 to remove it.

**Comment by caribouW3** [comment]
On the same grounds we could simply remove the Member Submissions as well. It would nicely clean up the "cruft" in the process document, it is no longer in use since in practice incubation superseded this way of doing things.

However, I agree with @michaelchampion 's comment
https://github.com/w3c/w3process/issues/246#issuecomment-464979340

**Comment by dwsinger** [comment]
member submissions carry an implied or explicit grant to IPR (copyright and patents), important before a WG forms and we get 'internal' grants as a result of our process and agreements.

so I'd rather retain them.

**Comment by jeffjaffe** [comment]
We've used the member submission feature at times as a convenient way to move specs into W3C space with IPR protection; e.g. EPUB.

**Comment by nigelmegitt** [comment]
> it is no longer in use since in practice incubation superseded this way of doing things.

@caribouW3 I don't think this is correct, for two reasons: 
1. Incubation is not an equivalent to member submission and 
2. Member submissions are still being made from time to time.

The frequency of member submissions as a whole does not have any relationship to the value of each individual member submission or indeed the value of the process feature that allows them.
