### ISSUE TITLE
Define "Working Group Decision"

### ISSUE THREAD

**Issue by chaals** [w3c/w3process#249]
There is a large section on Consensus and decision making, but it fails to actually define what constitutes a "Working Group Decision", despite that term being important to various fundamental stages of the process.

There should be a clear definition of how such a decision comes to exist and the grounds and procedures under which it can be challenged, or we should clearly require that it is defined in charters.

**Comment by nigelmegitt** [comment]
Some groups have a decision policy in their Charter (e.g. the [TTWG Charter](https://www.w3.org/2018/05/timed-text-charter.html#decisions)) which I guess defines _decision_ in the context of that WG.

Perhaps we could state that whatever a "Working Group decision" is SHOULD be defined in the WG Charter, otherwise [default definition], where [default definition] is "anything declared as a WG decision by the Chair".

**Comment by chaals** [comment]
@nigelmegitt proposed

> Perhaps we could state that whatever a "Working Group decision" is SHOULD be defined in the WG Charter, otherwise [default definition], where [default definition] is "anything declared as a WG decision by the Chair".

Yes, that's about what I think the whole section should be boiled down to, alongside the stuff that says votes are a last resort and technical decisions should be by consensus. (Maybe making votes appealable makes them sufficiently unappealing to avoid being used for real issues).

**Comment by frivoal** [comment]
We could draw the same distinction between a "Chair's Decision" and a "Group Decision" as currently exit between a "Director's Decision" and a "W3C Decision".
* a "Director's Decision" is when the director decides something on his own
* a [“W3C decision is one where the Director (or the Director’s delegate) has exercised the role of assessing consensus after an Advisory Committee review.”](https://frivoal.github.io/dirlessproc/#def-w3c-decision)

Similarly, we could have:
* a "Chair's Decision" is one where the Chair has the prerogative to decide something on their own (e.g. inviting an I.E., Appointing an Editor…)
* a “Group decision” is one where the Chair has exercised the role of assessing consensus of their WG. How that is accomplished depends on the work mode of the particular group, and could involve a CfC, a synchronous decision in a meeting, a straw-poll, a formal vote, and informal assessment by the Chair… Charters may constrain what are acceptable ways of taking decisions, but they shouldn't have to.Regardless, it is meant to reflect the collective will of the WG as assessed by the Chair, not the sole opinion of the Chair.

I am not 100% sure that the terms are currently used in that way (although a cursory look suggests that they are), but it seems like a useful distinction to draw, and if we agree on the definition, we can then make sure it is used correctly.

**Comment by chaals** [comment]
I like @frivoal's proposed Group Decision above, and think that is what is meant where it is used elsewhere in the process.

I'm not sure that we need a "chair's decision" defined, and if not, I would skip doing so and simply refer in plain language to the fact that chairs may do certain things without needing a group decision.

**Comment by nigelmegitt** [comment]
I like @frivoal 's distinction too, makes a lot of sense to me.

**Comment by dwsinger** [comment]
editor is asked to check and make a specific pull request along the lines of https://github.com/w3c/w3process/issues/249#issuecomment-473199841 and clarify that both decisions can be appealed

**Comment by nigelmegitt** [comment]
https://github.com/w3c/w3process/issues/249#issuecomment-490557889 is at least partially attached to the wrong issue :-(

**Comment by frivoal** [comment]
PR created (#270). Feedback appreciated.
