### ISSUE TITLE
Unneeded sentence fragment

### ISSUE THREAD

**Issue by frivoal** [w3c/w3process#250]
In [Section 2.5.1](https://w3c.github.io/w3process/#AB-TAG-constraints), there's this:

> Two participants with the same primary affiliation per §2.5.2 Advisory Board and Technical Architecture Group Elections must not both occupy elected seats on the AB. If, for whatever reason, these constraints are not satisfied (e.g., because an AB participant changes jobs), one participant must cease AB participation until the situation has been resolved. If after 30 days the situation has not been resolved, the Chair will declare one participant’s seat to be vacant. **When more than one individual is involved**, the verifiable random selection procedure described below will be used to choose one person for continued participation. 

It seems to me that the "When more than one individual is involved" part of sentence is useless, as there is always more than one individual involved in resolving the situation where two particiants end up having the same situation. So I think we should delete that bit. Or does it actually do something?

**Comment by chaals** [comment]
agreed. I suggest s/Chair will declare one participant’s seat to be vacant. When more than one individual is involved, the verifiable random selection procedure described below will be used to choose one person for continued participation./Chair will apply the verifiable random selection procedure to choose one person for continued participation and declare the other seat(s) vacant./

**Comment by frivoal** [comment]
Agenda+ to get approval for the proposed phrasing by @chaals in https://github.com/w3c/w3process/issues/250#issuecomment-461744375, unless someone before then comes up with a reason not to.

**Comment by dwsinger** [comment]
agreed in March
