### ISSUE TITLE
Affiliations (and links) of editors

### ISSUE THREAD

**Issue by koalie** [w3c/w3process#253]
In looking at the spec-metadata section, I noted that Natasha isn't affiliated as "Invited Expert" and request that change. @nrooney please work with @frivoal if he makes the change, to supply any link.

Also, looking further, I see that the links used for previous editors go respectively to the websites of Yandex for @chaals and of W3C for @ianbjacobs, who may prefer a different link be used.

**Comment by frivoal** [comment]
I'll happily make the change as soon as the interested parties confirm.

**Comment by chaals** [comment]
I'm good with the Yandex link. That was the case at the relevant time. Any time you are talking about me since August last year, the affiliation should be ConsenSys.

**Comment by frivoal** [comment]
@ianbjacobs are you good as is or should I change something?

@nrooney any objection to changing the way you're listed to say "Invited Expert"? Do you want your name to be a hyperlink? Where should it point to?

**Comment by ianbjacobs** [comment]
> On Feb 14, 2019, at 12:44 AM, Florian Rivoal <notifications@github.com> wrote:
> 
> @ianbjacobs are you good as is or should I change something?
> 
> @nrooney any objection to changing the way you're listed to say "Invited Expert"? Do you want your name to be a hyperlink? Where should it point to?

Sorry for the delay. 

I am ok with the current link. Thank you for checking!

Ian
--
Ian Jacobs <ij@w3.org>
https://www.w3.org/People/Jacobs/
Tel: +1 718 260 9447
