### ISSUE TITLE
Editorial change to "after ac review" section

### ISSUE THREAD

**Issue by koalie** [w3c/w3process#259]
Under [section 7.1.2 "after review"](https://www.w3.org/2019/Process-20190301/#ACReviewAfter):

> The Advisory Committee should not expect an announcement sooner than two weeks after the end of a Proposed Recommendation review period. If, after three weeks, the Director has not announced the outcome, the Director should provide the Advisory Committee with an update.

Given this is about all AC reviews (including charters), I suggest:

s/Proposed Recommendation //

**Comment by dwsinger** [comment]
agreed in March

**Comment by koalie** [comment]
👍
