### ISSUE TITLE
Affiliate Memberships are undefined in the Process Document

### ISSUE THREAD

**Issue by dwsinger** [w3c/w3process#26]
Transferred from https://www.w3.org/community/w3process/track/issues/173
State: Raised

**Comment by chaals** [comment]
Process does not define different classes of Membership - the underlying assumption is that all Members have the same rights and obligations, and the price they pay for Membership is a detail of geography, wheeling and dealing, and other historical accidents.

**Comment by dwsinger** [comment]
Chaals, you are missing that this paragraph in 2.1 

W3C does not have a class of membership tailored to, or priced for individuals. However, an individual may join W3C as an Affiliate Member. In this case the same restrictions pertaining to related Members apply when the individual also represents another W3C Member.

talks about affiliate members, when there is no such category (is there)? We should retain only the first sentence.

**Comment by chaals** [comment]
I'm not sure why we should retain the first sentence either, actually.

**Comment by dwsinger** [comment]
It happens to be true, though I don't really know whether it needs saying.

**Comment by dwsinger** [comment]
At minimum we should shrink the paragraph to remove the mention of Affiliate. A re-write is welcome.

**Comment by dwsinger** [comment]
we note that the FAQ disagrees.  Team to to look into harmonization!

**Comment by wseltzer** [comment]
See PR https://github.com/w3c/w3process/pull/64

**Comment by chaals** [comment]
closed by #64
