### ISSUE TITLE
FYI - for your research on Evergreen Standards proposal

### ISSUE THREAD

**Issue by jorydotcom** [w3c/w3process#263]
Hello there 👋 

Per the request from @dwsinger & @michaelchampion I wanted to pass along some links to the TC39 process and share what I thought might be interesting about it to the evergreen standards proposal:

* [TC39 Process Document](https://tc39.github.io/process-document/)
* [Contributing.md](https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md)

Additionally we're working on a 'How We Work' repo which is currently private, but I expect that will be opened up very soon.

What I find interesting about it:
- Actual proposal development is very iterative; use of the calendar as a forcing function is interesting/unique (also, kind of an interesting idea from a behavioral psych standpoint _"we have a deadline, let's go team!"_)
- specific requirements for a number of implementations, tests, docs  
- broad feedback explicitly needed at the earliest stages (maybe could work some horizontal review checks at each stage?)
- it's actually pretty simple in practice

What I don't like about it:
- As @dbaron says, the consensus pattern they use can be weaponized a bit, might encourage a more aggressive tone in discussion
- Can be easy to undermine & there aren't a lot of tools to correct that bad faith action

**Comment by frivoal** [comment]
agreed to close on Jan 29th call, as a separate Evergreen track is no longer being pursued.
