### ISSUE TITLE
EVERGREEN:  Evergreen should be a maturity state, not a separate track

### ISSUE THREAD

**Issue by michaelchampion** [w3c/w3process#267]
The Evergreen Track seems overly complex,  so it will be difficult to build consensus on, explain, deploy, and maintain.  A simpler way to achieve its goals would be to have a single Recommendation track, and give WGs that have produced a reasonably mature spec with prototype implementations, tests, wide review plans, etc. an option to either:
- Publish an Evergreen Recommendation and maintain it continuously with a different patent policy and wide review criteria, just like in the current draft.
- Go through the traditional CR/PR/REC process

WG charters MAY declare an intention to develop an Evergreen Recommendation, and probably SHOULD if they intend to produce a registry, but any WG can decide whether to move a mature spec to Evergreen status or take an Evergreen Recommendation to CR. 

Specific changes
- throughout, remove the term "track" to describe the Evergreen process; Evergreen Recommendations are a maturity state not a separate track.
- in 5.2.6 don't require charters to state whether the group anticipates working on an Evergreen Recommendation. The language about workmode / procedural consensus should apply to all charters.
- in 6.1.1, drop the first sentence, and change step 3 to "Publication of a Candidate Recommendation or Evergreen Recommendation".  Move the rationale for ER to the Evergreen Recommendation section under Maturity Levels. 
- 6.1.2 probably isn't needed, a WG can move from CR, PR, or REC to Evergreen Recommendation whenever they wish. 
- 6.1.3 and 6.8: remove Preliminary Draft; the distinction between a PD and a WD is insignificant.
- 6.2.3.1.2. change "Evergreen Track" to "Evergreen Recommendation", but the section is still needed. I question whether the sengence "Yet it is still expected that those documents will ultimately move to the Recommendation track to achieve a more complete wide review, horizontal review, AC review, and Director approval" should be in the Process." 
- The referenced Evergreen Track Patent Policy is a stub now, just rename it to Evergreen Recommendation Patent Policy.  I envision many of its provisions such as requirements for a contribution license and the option of doing periodic snapshots with exclusion opportunities to apply to the whole Process., so would be moved to the main patent policy document.

**Comment by dwsinger** [comment]
Hi Mike, thanks for the thoughtful input.  Inline.

> Specific changes
> 
> * throughout, remove the term "track" to describe the Evergreen process; Evergreen Recommendations are a maturity state not a separate track.

The problem is that if we want the living edge to be a Recommendation, that really is qualitatively different from today, where only things that have been through the publication-approval-mill are Recommendations. The current process HAS a maintenance track, for example, and ES really is different. We could abandon the old way and simply switch, but I doubt that's prudent.

> * in 5.2.6 don't require charters to state whether the group anticipates working on an Evergreen Recommendation. 

That's there so that lawyers, cross-functional groups, and so on, know which repos they should watch for changes that are ES. It also has a useful side-effect that it applies a natural throttle on adoption of ES while it's experimental. But I have no problem in saying all charters should document the GH repo locations (and Discourse, and the like), directly or indirectly.

> The language about workmode / procedural consensus should apply to all charters.

OK

> * 6.1.2 probably isn't needed, a WG can move from CR, PR, or REC to Evergreen Recommendation whenever they wish.

I think that's complex; we have to ensure the same quality no matter when groups switch.

> * 6.1.3 and 6.8: remove Preliminary Draft; the distinction between a PD and a WD is insignificant.

I agree, WDs before FPWD and Prelim Draft are the same thing.

> * 6.2.3.1.2. change "Evergreen Track" to "Evergreen Recommendation", but the section is still needed. I question whether the sengence "Yet it is still expected that those documents will ultimately move to the Recommendation track to achieve a more complete wide review, horizontal review, AC review, and Director approval" should be in the Process."

I don't like it; I don't think we should put expectations in a formal process, and I don't agree with it anyway.

> * The referenced Evergreen Track Patent Policy is a stub now, just rename it to Evergreen Recommendation Patent Policy.  I envision many of its provisions such as requirements for a contribution license and the option of doing periodic snapshots with exclusion opportunities to apply to the whole Process., so would be moved to the main patent policy document.

Let's see what PSIG comes up with. If indeed they adopt these needed revisions to the general PP, the diffs for ES might be slight.

**Comment by michaelchampion** [comment]
@dwsinger wrote:
>>throughout, remove the term "track" to describe the Evergreen process; Evergreen >>Recommendations are a maturity state not a separate track.

> The problem is that if we want the living edge to be a Recommendation, that really is
>  qualitatively different from today, where only things that have been through 
> the publication-approval-mill are Recommendations.

Hmm, it doesn't seem to me that simply calling Evergreen a separate "track" would mitigate the confusion between Recommendations that have been through the mill and "Evergreen Recommendations" that have not.  I'm not at all wedded to "recommendation" being in the term to describe the evergreen maturity level.  Maybe we should just call them W3C Living Standards ...The criteria to accept a feature into a WHATWG LS are very very similar to the criteria to become an Evergreen Recommendation.   If it's a branding thing, let's not confuse the poor consumers with completely different labels for almost the same thing.  

I'm OK with calling Evergreen a "track" if it's just an alternative to the "maintenance track".  My substantive objection the separate tracks for Rec and ER  to a) forcing the static / evergreen decision to happen at charter time rather than when a spec is mature enough so that the community knows whether it's feasible to stabilize all features; and b) adding the confusing distinction between a Working Draft and a Preliminary Draft. 

Likewise I'm OK with waiting to see a draft of the new patent policy and then see how much is specific to evergreen status and how much can apply to the whole Process. But let's not constrain them to make a patent policy ONLY for the evergreen track or whatever we call it. 

I don't feel strongly about whether 6.1.2 is needed, and agree that we need to think harder about when and how WGs can move back and forth between ER and CR/PR/REC maturity levels.

**Comment by michaelchampion** [comment]
OK, I'll create separate issues for my various concerns.

**Comment by frivoal** [comment]
agreed to close on Jan 29th call, as a separate Evergreen track is no longer being pursued.
