### ISSUE TITLE
Can records of appeals ever be made public?

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/w3process#268]
resolved: to change to “visible member-only”

_Originally posted by @dwsinger in https://github.com/w3c/w3process/issues/244#issuecomment-490520494_

The previous wording in [Section 7.2](https://w3c.github.io/w3process/#ACAppeal) included a subtle ambiguity, in that it could be read as requiring _at least_ members to have visibility of the archive of statements of an appeal. I think it's likely that most readers thought the old wording meant "member-only" but some could have thought it meant "not team only, members do need to be able to see it". That alternative reading in turn could be interpreted as permitting, by some undocumented decision process, the archive of statements to be made not just visible to members but also to the public.

With the resolution of #244, it will be _prohibited_ for the archive of statements to be made public. Is this correct? Is there ever/never a circumstance when it should be possible to make the archive of statements about an appeal public? If it is a possibility, new wording is needed to allow for it, though it is unclear who should be able to make such a decision.

**Comment by dwsinger** [comment]
it wouldn't be prohibited, but it would take work to make public something that people believed was member-only. I would support needing widespread consent and no opposition...

**Comment by frivoal** [comment]
[Section 4.1.1](https://w3c.github.io/w3process/#confidentiality-change) already describes how the team may change the confidentiality level of information if it needs to make it more broadly available than it's initial confidentiality level. I think this covers the case you're talking about, and that no further change to the process is needed to handle that.

**Comment by nigelmegitt** [comment]
@frivoal OK, that works I think. Thank you! I'll close this issue now, but if there are any other contrary views, please comment and re-open.
