### ISSUE TITLE
Does the decision to allow the Evergreen state need to be made in the Charter?

### ISSUE THREAD

**Issue by michaelchampion** [w3c/w3process#271]
I would say NO, but apparently others disagree.  I don't think there is enough evidence to determine whether a spec can get to a stable state net minor maintenance until roughly the CR phase.  Having to recharter to allow an Evergreen state once it becomes clear that the spec needs continuous evolution seems unduly burdensome.

**Comment by dwsinger** [comment]
It's there for two reasons, both manageable in other ways.

1) To enable 'harvesting' of Github URLs by those wanting/needing to watch.

2) To provide a little back-pressure to the adoption of Evergreen while it's experimental.

I actually think that having all rec-track work have their repos in charters would help, which means reason #1 would be moot. And there are other ways to manage ES adoption.

**Comment by jeffjaffe** [comment]
I think that David's second reason is the most important - this is experimental and putting in the charter allows us to carefully meter what projects are Evergreen and assess progress.

Another reason to put it in the Charter is to allow the AC have a say as to whether they are comfortable with certain specs moving to the Evergreen model.

I could support removing the requirement to put it in the charter after we have incubated this new approach for several years.

Although I prefer having Evergreen as part of the Charter, if there is strong support for adding the Evergreen model and having it a WG decision, I would not object.

**Comment by michaelchampion** [comment]
[speaking only for myself, not wearing a Microsoft , WHATWG SG, or W3C AB hat, just relaying what I sense in the community]

@jeffjaffe I'm afraid it's too late to "carefully meter what projects are Evergreen" and "allow the AC to have a say whether they are comfortable with certain specs moving to the Evergreen model".  I'm pretty sure there WILL be further movement of specs to WHATWG in the next year if WGs can't move to an Evergreen mode when *they* choose given *their own* needs.  

If the community wants to keep the existing web platform work at W3C,  I think that requires a strong statement of direction from W3M  (and the AB? Process CG?) that groups can recharter under the current process and be able to  use the Evergreen mode whenever it is approved WITHOUT RECHARTERING.   

The more difficult we make it to work at W3C the way people want to work, the easier it is for them to choose to work elsewhere.

**Comment by jeffjaffe** [comment]
Thanks @michaelchampion .  I think you're making some good points.

These same good points say to me that we need to accelerate the Evergreen track proposal, rather than wait until we fix the REC track which will take much longer and might not satisfy those that want a Living Standards approach.  Can you help me make that case to @frivoal and @cwilso who seem strongly opposed to having an Evergreen track?

**Comment by dwsinger** [comment]
I think we are seeing both of (a) we need to work on Evergreen independently and urgently, and not try to merge that with improving the Rec. track, as that will slow down Evergreen (and put all our eggs into one basket with some experimental weaving) and (b) we need to improve the Rec. track urgently, and not let the shiny new Evergreen track be a distraction that takes our attention away from fixing the leaks in that basket. 

I suspect the right answer consists of a lot of things that are improvements/tools to both approaches.

**Comment by michaelchampion** [comment]
We need to accelerate having an Evergreen *option*.  I personally think (and I hope @cwilso generally agrees) the fastest/easiest way to do that is simply 
- add an Evergreen state to the Rec Track Process somewhere between FPWD and CR, 
- make relatively small IPR Policy changes to require a CLA on all contributions to WGs as well as CG, and make broad patent commitments binding once any exclusion opportunity has passed. 

WHATWG (plus the WHATWG-W3C MoU) already has lawyer-vetted language for all this that can be harvested by W3C, then tweaked to make it more aligned with W3C's sense that specs need wider community buy-in and not just implementations and tests.

There is work to do on defining the ER wide review criteria, the tooling to optimize the cost/benefit of wide review on Evergreen Recommendations, and discussions about how much must be done before entering the Evergreen state.  But I think it's "the best is the enemy of the good enough" to delay approval of an Evergreen option until all the horizontal review issues and tooling to address them are sorted out.   The Process itself can be more Evergreen -- ever-changing to address real needs and concerns, less concerned with addressing hypothetical corner cases -- especially while we still have a Director to make judgment calls when things fall thru the cracks.

**Comment by dwsinger** [comment]
Um, an evergreen option -- an alternative -- is exactly what we are exploring. yes, we're debating where it can be used, under what conditions, but that's expected. 

The WHATWG starting point is exactly what we've suggested PSIG use for the IPR policy, as well, with a fix for the missing exit commitment, and possible other minor changes. Whether we need urgently a Contribution IPR commitment, and whether it can be done without a Membership Agreement change, is work in progress.

WHATWG does not have a concept of horizontal, AC, Director, or formal wide, Review; that's the hardest part to add and where we've spent the bulk of our time.

I am frustrated a little because when we get to specifics, you're helping clarify all the things we wanted to clarify, and agreeing with the idea it's an option. Thanks! But then your general message is that we're on the wrong track.

**Comment by jeffjaffe** [comment]
We agreed in today's call that at our next call (in three weeks) we would compare two approaches: Evergreen track and "fix the REC track".  As I understand it, @michaelchampion is suggesting a third approach - "Evergreen option within the REC track".  I could be wrong, but that feels a bit different from the "fix the REC track" proposal.  It has more continuous review; more editor empowerment, etc.  Could someone possibly write that down as a third approach that we can evaluate compared to the other two.  If so, I think that would address @dwsinger 's comment above.

**Comment by michaelchampion** [comment]
@dwsinger wrote
> and not try to merge that with improving the Rec. track, as that will slow down Evergreen 

I fear we've slowed down both arguing about which approach is slower :-( .  Sorry for my part in that, but I really don't think the "experimental Evergreen track" proposal on the table is a good starting point for several reasons (most of which I've raised in issues). 

I have acknowledged that the WHATWG doesn't value horizontal review as much as W3C, and that's where the most work is needed.  But the W3C won't have a Director for long, the AC is not a good proxy for the Real World in determining whether a spec really works on the web, and sporadic formal review is not a good proxy for continuous improvement as real problems are found, reported, and fixed.   If we create an Evergreen process that is just as complex and "bureaucratic" as the Rec Track, it won't address the reasons work is moving to WHATWG.

**Comment by michaelchampion** [comment]
@jeffjaffe I believe my suggestion is consistent with the "fix the Rec track" approach.   @frivoal and @fantasai might focus on other problems with the Rec track that need to be fixed besides the lack continuous review, I'm not sure, I await their proposal. 

The fundamental reason work moves to WHATWG is its much better track record for maintenance; I'm open to other approaches to fix that besides a Living Standards / Evergreen Recommendation state.  But the simplest way forward would seem to be to adopt WHATWG's process/IPR innovations and improve on them.

To be clear, I am not necessarily advocating more "editor empowerment" in the W3C Process even though that is probably part of WHATWG's secret sauce.  I think WGs operating by consensus driven by a Chair, with the editor implementing that consensus, could work in the Evergreen state in W3C.  So that's not one of the WHATWG innovations I'm talking about here, I'm mainly talking about "continuous review" and the IPR policies to support it.

If Elika/Florian's proposal ends up being substantially incompatible with what I've sketched out, I will write my proposal down in comparable level of detail.

**Comment by fantasai** [comment]
@michaelchampion Initial draft https://www.w3.org/wiki/Maintainable_Standards

**Comment by frivoal** [comment]
agreed to close on Jan 29th call, as a separate Evergreen track is no longer being pursued.
