### ISSUE TITLE
What is the difference between a PD and a WD?

### ISSUE THREAD

**Issue by michaelchampion** [w3c/w3process#272]
If there is a difference, is the distinction worth making in the Process?

**Comment by fantasai** [comment]
I think you mean "if there isn't a difference".

I agree. If there is no practical difference, then we should make not distinction. If there is a difference, that difference should be intentional and well-justified.

**Comment by dwsinger** [comment]
I don't think there is any difference, at least up to FPWD (Rec Track) and ES.

**Comment by frivoal** [comment]
@dwsinger did you mean CR rather than FPWD? WDs after FPWD still seem identical to PDs (CR does not).

**Comment by dwsinger** [comment]
I'm pretty sure about pre-FPWD. I'd have to think hard about pre-CR. Post-FPWD has a defined IPR policy on the Rec. track, for example.

**Comment by michaelchampion** [comment]
Shouldn't the Evergreen track or whatever we call it include FPWD or a close equivalent?  FPWD is really just an IPR step, and something equivalent is present in the WHATWG process (the snapshots with exclusion opportunities every 6 months) and probably is needed in the Evergreen IPR process too.

**Comment by dwsinger** [comment]
It does already. Documents before snapshots start are called PDs, after that Evergreen Recs. So the first ER is the thing that triggers the start of snapshotting. This thread is all about whether we need a new name.

**Comment by frivoal** [comment]
I forgot this bug existed, and opened a new one. I closed that one as a duplicate. Reposting the comments here:

[From me:]([https://github.com/w3c/w3process/issues/300#issue-471069833):
> Prior to issuing Evergreen RECs, the [evergreen process](https://w3c.github.io/w3process/evergreen/) enables WGs to produce Preliminary drafts. While this seems to be intended to serve as a parallel to Working Drafts on the traditional REC track, it is unclear what purpose they serve and how they are expected to be used on the Evergreen Track, because the Evergreen Process imposes no maturity criteria or any constraint on transitioning from PD to ER. It seems that nothing prevents a Group from using only ERs, no matter how immature the sec is, nor does there seem to be anything forcing the group from switching from PD to ERs ever.
>
> As currently framed, patent Coverage for PDs is unclear (see point 7 in https://lists.w3.org/Archives/Public/www-archive/2019Jul/0003.html), and the various safeguards and requirements placed on the WG and Editor are also absent.
>
> PD should probably either be removed entirely, or if it is meant to serve a particular role, beefed up so that it can consistently fulfill that role.

[Response from @dwsinger:](https://github.com/w3c/w3process/issues/300#issuecomment-514375027)
> I don't think there is any reason to call them anything other than WDs of the WG.

[Response from me:](https://github.com/w3c/w3process/issues/300#issuecomment-514609033):
> Works for me. If they are regular WD, of which there is a first, that also clarifies the patent situation at the beginning of the evergreen track, which is currently fuzzy/buggy (see issue 9 in https://lists.w3.org/Archives/Public/www-archive/2019Jul/0001.html).
>
> That still leaves a question open: when do you switch from WD to ER? Whenever the Working Group feels like it? Some other criteria? If so, how are these criteria checked/enforced?

**Comment by dwsinger** [comment]
You switch when you meet the quality requirements; it is effectively a 'change' from nothing to something, and the same rules for changes apply (commitments, consensus, etc.)

**Comment by frivoal** [comment]
> You switch when you meet the quality requirements

Which quality requirements? For CR / REC and friends, the quality requirements are explicit. For ER, the only quality requirement seems to be that the group has consensus.

> the same rules for changes apply (commitments

Same rules as what? What commitments?

**Comment by michaelchampion** [comment]
I reiterate my concern that having a different name for something that is essentially the same as a Working Draft causes unnecessary duplication and confusion.

**Comment by dwsinger** [comment]
> Which quality requirements?

The ones for making any change to a living spec. If you're saying they need to be stricter and/or more explicit, that's a related but maybe different issue.

**Comment by frivoal** [comment]
The quality requirements for publishing a PD are:
* having consensus of the WG to publish

The quality requirements for publishing an Evergreen Rec are:
* having consensus of the WG
* "met their requirements satisfactory for a new standard" (what are these requirements? without definition, it boils down to "has consensus")
* "a level of substantial review" (what level? without definition, it boils down to "has consensus")

So, while they are described slightly differently, both publishing as a PD and as a Evergreen REC just require consensus of the WG, and it is largely left to the people who participate in these consensus to decide what they feel is appropriate. I suspect interpretation of what the means will vary from WG to WG, or even from individual to individual, with some thinking that the quality needed for an Evergreen REC is roughly what we expect of FPWDs, some thinking it's roughly what we expect of CRs (or even maybe of RECs?), and some falling somewhere in between. WG to WG inconsistencies may make it hard for the general public to know how much faith to put in the Evergreen REC label. Individual to Individual inconsistency may make it hard for WG to reach consensus.

Besides, none of this still gives an answer to how PDs are different from WDs. The requirements are the same: has consensus of the WG to publish, does not yet meet criteria for further advancement.

Tentative answers:
* PD and WDs are the same. Just call them WDs
* The intended maturity of post-WD/post-PD Evergreen Recs is roughly equivalent to CR-or-later. Say so somewhere (in terms that don't necessarily refer to CR/, but make the expectations explicit), even if the evaluation of that maturity is entirely left to the WG.

Alternative answers:
* The intended maturity of Evergreen RECs is roughly equivalent to FPWD-or-later. Say so somewhere.
* PD are intended to be the same as a working draft, with the only difference being that it is not covered by the patent Policy. I strongly doubt this is useful or desirable, but if it were, I see no reason it should be unique to the Evergreen Track. I'd say it is equality undesirable for both tracks to create a maturity level whose goal is to evade the patent policy while still granting some level of W3C status.

**Comment by frivoal** [comment]
agreed to close on Jan 29th call, as a separate Evergreen track is no longer being pursued.
