### ISSUE TITLE
Generalize FO-handling

### ISSUE THREAD

**Issue by frivoal** [w3c/w3process#276]
The section about handing Formal Objections is invoked not just for Formal Objections, but also for Group Decision Appeals, Chair Decision Appeals, and Member Submission Appeals. Some editorial rephrasing is probably needed to make it clear how it applies in all cases.

We need at least some better terminology, and maybe some other tweaks.

See https://www.w3.org/Consortium/Process/Drafts/director-free/#addressing-fo

**Comment by dwsinger** [comment]
1) Make a section "W3C Council" after the AB and TAG are defined, and move this sentence in there.

Together with the [=CEO=} and the members of the TAG, members of the Advisory Board hear and adjudicate on Submission Appeals, Chair Decision Appeals, Group Decision Appeals, and Formal Objections. These are Council Questions.

2) Keep 3.3.2 as specific to FOs, but terminate it by saying that FOs are Council Questions and resolved by Council decisions.

3) add a new section Council Decisions, which takes the rest of what is 3.3.2, and makes it general.  Start with "The Team considers the Formal objection, researches the question, " but change to "The Team considers the Question, researches it, …"

I think the other edits then follow. For recusal, it has to be the person who made the original decision, or the person who called it into question (e.g., they filed the formal objection).

**Comment by frivoal** [comment]
This was resolved as part of merging the director-free branch
