### ISSUE TITLE
CEO recusal while handling FOs

### ISSUE THREAD

**Issue by frivoal** [w3c/w3process#277]
In the case of Formal Objections, if the CEO needs to recuse themself, they are probably not the best person to pick the alternate chair. As an alternative, in case of CEO recusal, the Objection Decision Committee could pick its own chair by instant-runoff voting.

See https://www.w3.org/Consortium/Process/Drafts/director-free/#addressing-fo

**Comment by dwsinger** [comment]
If we don't trust the CEO to do a clean recusal and pick someone who is perceived to be outside the dispute and fair, we have much bigger problems than FO handling.

**Comment by nigelmegitt** [comment]
Agreed @dwsinger and that's a good reason for not giving the CEO the opportunity to choose. If the FO is not well founded, then fine, things will be reverted naturally, but if the FO is well founded then it's important that the process does the right thing. If we _do_ have big problems, we should fix them as quickly as we can.

**Comment by dwsinger** [comment]
@nigelmegitt you say 'agreed' at the beginning and then come to a different conclusion. My vision is that the CEO would say "this directly concerns a decision I made; I recuse myself; I think the person who can be respected and most trusted to chair the committee, and has the necessary skills, is X". If we cannot trust the CEO to make such a reasonable choice, but chooses someone obviously unacceptable, we have wide-ranging problems all over the consortium; the CEO is making bad judgments. So, I think having the CEO recuse and name an impartial replacement is fine.

**Comment by nigelmegitt** [comment]
@dwsinger What if the very reason for the CEO choosing someone unacceptable has the same cause as the objection being dealt with?

**Comment by dwsinger** [comment]
Take it to the Director, or the Board (when it forms). The CEO is no longer trustworthy and their management needs to act.

**Comment by cwilso** [comment]
I'm in agreement with David on this.  If we're this deep down the rabbit hole, it will end up being irrelevant.

**Comment by avneeshsingh** [comment]
The process and rules of the organizations are obviously important for smooth working but it also form the perception. So, it would be much better to allow the committee choose its own chair in such a case.

**Comment by dwsinger** [comment]
I'm concerned that a free choice of chair in a group of ~20 people is an exhausting process. Perhaps the ODC should ratify/confirm their chair as their first order of business? That way, if the CEO or the substitute they nominated are spectacularly inappropriate, we'll find out immediately on a failure to confirm. This raises the question of who stands/nominates in the failure case, but perhaps it can be iterative; at some point the CEO will nominate someone acceptable, or we go to the board.

**Comment by avneeshsingh** [comment]
Having board of directors can take care of many issues which we are debating. I feel that we should seriously explore the option of aligning directless process with formation of BOD.
Thinking specifically about the objection decision committee, there is another concern. The advisory group consisting of the team will first try to resolve the objection, if they fail then they will send it to objection decision committee, but there is a good overlap between the participants of advisory group and objection decision committee. So, how can we ensure that objection decision committee will not be influenced by the existing decision of the advisory group?

**Comment by dwsinger** [comment]
> Having board of directors can take care of many issues which we are debating. I feel that we should seriously explore the option of aligning directless process with formation of BOD.

That's the current thinking; that in the wholesale changes to member agreements, process etc. that forming a legal entity involves, we'll wrap this in, possibly with a transitional stage with the Director as a back-stop until he retires.

> Thinking specifically about the objection decision committee, there is another concern. The advisory group consisting of the team will first try to resolve the objection, if they fail then they will send it to objection decision committee, but there is a good overlap between the participants of advisory group and objection decision committee. So, how can we ensure that objection decision committee will not be influenced by the existing decision of the advisory group?

I don't follow at all.  The AG (team) tried to resolve the situation amicably, which would result in the objection being withdrawn. That failed, so now a formal Decision is needed, which goes to this formal committee. We absolutely expect that the committee will get a briefing: what's the question, what's the background, what are the considerations, and what were the attempts to resolve without a formal decision, and what recommendation(s) does the team have for the Decision itself. But the committee can, of course, ask more questions, and decide to balance things in a different way, and issue a different decision -- just like the Director can today.

**Comment by dwsinger** [comment]
I think the furthest we need to go is that the Council formally confirms their chair by (majority) vote when they form. If they reject the chair, the CEO must nominate someone else, and the process repeats.

But honestly, I am OK with with the text Florian drafted. Close?

**Comment by frivoal** [comment]
The CEO no longer picks the council chair, making this issue invalid.
