### ISSUE TITLE
What can the Objection Decision Committee actually decide?

### ISSUE THREAD

**Issue by frivoal** [w3c/w3process#279]
Should the Objection Decision Committee be able to do more than just sustain of overrule? For instance, when it sustains an objection, in the case FO during charter reviews, instead of merely sending the charter sending for additional work, could it decide what to change the charter to and publish it?

See https://www.w3.org/Consortium/Process/Drafts/director-free/#addressing-fo

**Comment by dwsinger** [comment]
Yes and no. Their choices are the same as the CEO today, notably (a) to support the proposal or (b) return the proposed resolution for further consideration (c) make a different decision, after deliberation, (d) form whatever study groups they like. I don't think what I initially drafted implied anything else...

**Comment by michaelchampion** [comment]
I don't see c) as an option in a director-less organization.  NOBODY in my vision of a director-less organization has the power to make a different decision; sustaining a formal objection means "return the  matter to the group for further consideration."   The Objection Decision Committee could presumably appoint a group to help find a resolution that they would not sustain an objection to.

**Comment by dwsinger** [comment]
OK, I wasn't clear. I meant "making a decision different from what the team advised", not "making a decision different on the original question."

**Comment by frivoal** [comment]
> (a) to support the _proposal_ or (b) return the proposed resolution for further consideration (c) make a different _decision, after deliberation, (d) form whatever study groups they like.

Yes, but.

I am not really counting your option (b) and (d), because while these are things the ODC can do, they feel more like steps towards a decision rather than a decision itself. "forming a study group" isn't a finally decision, and "return the proposed resolution for further consideration" (to the Advisory Group, if I understand you correctly) isn't either. Eventually it's going to come back to (a) or (c).

So the question is what can the **proposal** or **decision** be. Are they limited to "sustain the objection and send the work back / overturn the decision" or "overrule the objection and publish / let the decision stand"? Or can the the **proposal** / **decision** be: "change the charter in such a way that would address the objection", or "replace the decision being objected to with a different decision".

Mostly, I think it should just be sustain/overrule, but it gets a little complicated at the edges.

I think the general case is easy: if someone objects to a decision, you can overrule the objection and let the decision stand, or sustain it and overturn the decision, putting us back in the state prior to the decision being made. Also, if someone objects to publishing something, and the ODC overrules the objections, we publish, and that's that.

But when the ODC wants to sustain an objection to a publication, it can get a little more hairy: the simple case it to just send back the spec/charter/process to the group that made it (or maybe merely go back to the set of AC reps who voted) and tell them to work harder at finding consensus, possibly with some advice on how to achieve it. But if the only changes to the document that would lift the Objection cause someone else to raise another objection, it's not clear to me whether it's a good thing that the group that tries to find consensus and the group that rules on whose objection is least serious are separate. Maybe it is a feature, as it forces the drafting group to work real hard at trying to achieve consensus. Or maybe it pushes them to try and read tea leaves to figure out what non-consensual alternative is most acceptable to the ODC. In that case, it might be a feature that the ODC works with the various objectors / potiential objectors, and decides on its own how to solve the problem. Or maybe not.

Another question is when the objection is being sustained, can the ODC decide between "try harder" and "abandon the work", or can it only ask people to try harder, and if they cannot figure how, they may decide to abandon.

I am leaning towards saying that the only possible decisions are sustain or overrule

**Comment by dwsinger** [comment]
The short answer to the posed question is "whatever the Director could decide today". The ODC is a slide-in replacement for the Director, takes the same advice and support, and has the same powers. Do we need any more explanation?

**Comment by chaals** [comment]
@dwsinger the Objection Decision Committee essentially gives an elected subset of the AC a powerful decision-making role, instead of the advisory role they generally play. While in principle they are subject to election some time in the next two years, there's a pretty diffuse sense of accountability there for any individual (except people like you and me who advocate positions rather than just voting). Even the CEO in this proposal has far less direct responsibility than the director currently takes.

@frivoal is suggesting, and I am inclined to agree, that given this diffusion of responsibility there should *perhaps* be a commensurate reduction in the scope of allowable decisions, from "anything" to "find that the Working Group's proposal is solidly backed, or return it to them for further work until they produce something that can get a consensus".

**Comment by dwsinger** [comment]
Ok, sorry to be dense. So you are saying that we restrict the possible outcomes to (a) After discussion, a harmonious solution is found and the FO is withdrawn without needing a decision; (b) The FO is denied and the decision/action that was objected to is affirmed or (c) The FO is sustained and the decision/action objected to is reversed.  ? We would need to require that all FOs are formulated in a way that makes what (b) and (c) mean unambiguously clear, and if they are not, no decision will be made at all.

**Comment by michaelchampion** [comment]
I see the possible outcomes as:
 (a) After discussion, a harmonious solution is found and the FO is withdrawn without needing a decision; 
(b) The FO is denied and the decision/action that was objected to is affirmed or 
(c) The FO is sustained and the decision/action objected to is sent back to the group for find a solution all can live with (or admit defeat and stop trying to find a solution)

The ODC's scope is only the objection, it's not really a slide in replacement for the Director.  They can't prescribe any action other than "don't do what was objected to."

**Comment by dwsinger** [comment]
So, this rules out "partially sustained", for example. If the FO objects to something in principle and says "and therefore if this FO is sustained, we do X, Y, and Z", where Z is (for example) issuing a Press Release, you're saying that we either do all of X,Y, and Z or none of them? This is HTML-like decision (we take exactly one of the options, and decide on it). Not sure I am comfortable. Neither the Director nor the ODC can make decisions outside the scope of what the FO is about, but I don't see why they shouldn't be at liberty to say that both the original decision, and the proposed resolution in the FO, are flawed, and our decision is "solomonic". I think we're over-constraining if we restrict any more than saying that the decision of an FO, well, decides about the Objection.

**Comment by michaelchampion** [comment]
@dwsinger wrote
> I don't see why they shouldn't be at liberty to say that both the original decision, and the proposed resolution in the FO, are flawed, and our decision is "solomonic

Hmm, I see your point. But Solomon's are few and far between these days. If we had a person or process we trusted to make  solomonic decisions, we would use that for the Director and not be having this discussion.  

I'm not sure there is a substantial difference between "The FO is sustained and the decision/action objected to is sent back to the group to find a solution " and "The FO is makes some good points but is not fully sustained,  and the decision/action objected to is sent back to the group to find a solution."  In any case I do agree that the ODC should be empowered to *suggest* a solution in their message back to the group whose decision triggered the FO.

**Comment by frivoal** [comment]
Leaving aside the fact that I don't think press releases is something that can currently be objected to, if a FO bundles objections to multiple  objectionable things, I wouldn't have an issue with the ODC rulling sustain/overrule on the sub topics individually.

Let me take an exaggerated example to illustrate the sort of things I would have an issue with: Let's say someone objected to the publication of a CSS spec I edit, on the grounds that I and the CSSWG had done a terrible job of it. Even if the ODC agrees I botched the job, and that I did so intentionally on the basis on conflicts of interests, and that the chairs are terrible chairs for letting me get away with it, and that the Team contact should have noticed but turned a blind eye, the ODC should not be able to decide to:
* revoke my status as an invited expert
* Appoint new chairs to replace those who have done a poor job
* Impose a pay downgrade on  the Team contact who let that happen without raising red flags
* rewrite to their liking the sections of the spec that were poorly written, and publish that without going to the WG
* Close the WG
* ...

All it should be able to do is to agree with the objector, and deny publication. In its comment why, it can and should detail how their investigation uncovered that I was a terrible person and that chairs were corrupt, recommend that the Team look into that, and make suggestions to the WG on how to fix the spec. But at as far as decisions are concerned, all it can do is say "yep, this is bad, objection sustained, publication blocked".

**Comment by nigelmegitt** [comment]
Here's an alternative for consideration: 

Rather than ruling on specific FOs, the ODC could instead rule on the relative merit of the rationales of competing FOs.

Taking a step back, what is an FO?
* A statement of non-acceptability to the objector of some proposal
* A rationale for why the proposal is not acceptable
* A proposed remedy

If any of those features of an FO is omitted, can we argue that the FO is not well formed and can be dismissed? (I might flex a little on the last one)

Non-consensus in a WG is likely to need escalation if the WG cannot work around it and if two opposing views are mutually incompatible. In that case, they are in general being made with competing rationales. 

I'd argue in this case that the ODC's role should be to assess which of the competing rationales is more important for the mission of the W3C and adjudicate on that basis, sending the ODC's decision back to the WG to resolve.

A hypothetical concrete example might be useful: Our hypothetical WG discovers that there's an accessibility issue and a member proposes a solution. Another member objects that the solution impacts privacy. The WG cannot conceive of any other alternative solutions that don't suffer from the same problem. Now we have two competing FOs that need higher level adjudication. The Director might assess the relative importance of the rationale's for the FO now - is accessibility or privacy more important for this issue? In future, the ODC could decide which seems more important and send that back to the WG, giving a route to breaking the deadlock.

**Comment by frivoal** [comment]
I agree that @nigelmegitt's case is an important one. The ODC could rule on these by considering the FOs one by one, sustaining the first until it sees the second, and then either overrulling the second, or sustaining it too with a comments saying that "actually, if that's all we can do, the first alternative was better", but needing multiple rounds of objecting and adjudicating for this kind of situation seems bad, so we should leave enough flexibility that this sort of exercise can be done without artificial back and forth. But even in that case, the ODC shouldn't substitute itself for the WG, and they shouldn't just make up new spec text directly without involving the WG and publish that.

**Comment by dwsinger** [comment]
Perhaps we can deal with @frivoal 's concern by simply stating that the ODC's decision is strictly scoped to the FO and the decision or action being objected to. Guys, if they stray outside that, then you go to the board (and anyway, if no-one believes the decision is valid, it'll be ignored). I don't believe we need to rat-hole here; the team, CEO, and so on, are surely going to stop crazy stuff happening.

@michaelchampion no, if an FO is sustained, then the decision/action is not only sent back, but in the meantime it is REVERSED. The charter is not approved, the publication is not published, the chair is not appointed, and so on. That's the essence.

 @nigelmegitt I agree, we can and should advise that if your FO doesn't delineate (a) the precise decision/action being objected to (b) why you object and (c) what can be done to address your objection, i.e. some plausible proposed remedy, then you are less likely to get satisfaction.

**Comment by frivoal** [comment]
[By email](https://lists.w3.org/Archives/Group/ab/2019JulSep/0216.html), @dwsinger said:

> I think we are converging to a point where the council:
> * decides that the original decision stands, or the the original decision is overturned and the objection upheld (this should be binary in most cases)
> * gives their rationale
> * gives their suggestions and thoughts on how to make further progress, what might happen next

That was my initial position, and I remain convinced that it will be appropriate in many cases to keep it at that, and not attempt to overconstrain the problem.

However:

1. When there are multiple entrenched camps with irreconcilable differences, there can be cases where no "advice" will result into something that has the consensus of the working group. If the WG nonetheless attempts to get consensus on the advice of the Council or close variants, it could get stuck. If the chairs and a majority of the WG disagree with the advice, they may also chose to ignore it, leaving the objectors with no other option than to object again, possibly for no better result. The opposite could happen as well: the chairs apply the "advice" of the council as is, without attempting to get consensus, those who disagree with the advice file a new round of formal objections, arguing (correctly if you ask me) that the whole point of giving advice rather than orders is to make them non binding, so that working groups can attempt to refine the advice or to find a better path, and that not attempting to do that is working in bad faith, which is ground for new FOs. If the Council concludes that the question has been insufficiently studied, and should go back to the drawing board, merely issuing advice can be the right. But when the question has been studied thoroughly, that the Working Group cannot reach consensus, that any possible way forward would generate FOs, and the Council has reached a conclusion on what the right thing to do is, merely issuing advice doesn't actually solve the problem.

2. There are cases where the decision already take will have had consequences already. Since we don't have a time machine to go back before it was taken, when mere advice might have sufficed, I expect there will occasionally be cases where advice is not sufficient, and mandating some corrective action can prove necessary.

Example: The working group resolved to add feature FOO, and to publish a CR. Nobody objected at the time, and the CR is published. Implementor X starts implementing, and finds that FOO is a major privacy concern, and would like the decision reverted. The group flippantly disagrees. X files a formal objection. The council agrees with X, and asks the group to revert the resolution to add FOO. First, as discussed in 1, the WG may drag feet in actually reverting FOO (or equivalently, may re-resolve to do FOO). If that happened before publication as CR, the council could use the ability to block CR until objections are resolved to gain leverage over the Working Group and to get its desired outcome. But in this scenario, since the CR was already published (and the REC may be a few years off due to insufficient implementation experience), the Council does not have that leverage. Even if it declares the decision to accept feature FOO overturned, If it cannot mandate that a CR be republished with FOO removed, the previous CR, with privacy leaking feature FOO included, continues to stand, and may mislead other implementors into implementing and shipping it.

I have not yet found a way to phrase the ability for the Council to mandate (not just advise) a particular course when necessary, without at the same time granting it undesirable powers, and while making sure that we allow mandating things while recommending that it merely issues advice when that is sufficient. But it does seem to me that if we don't give it, at least in some cases, the ability to mandate solutions, the Council is at risk, in the most thorny cases, to be unable to actually resolve the issue.

**Comment by dwsinger** [comment]
@frivoal 

1. I think you are mixing "advice" and "decision". The council (Director today) issues a decision. If the group et al. don't abide by that decision, then we have other problems.
2. An FO can only happen with respect to an active decision, so I think your scenario would have to be

- something is in a CR and has been for a while, no-one objects
- I discover a problem, and ask that the feature be removed
- the group formally decides not to remove it, despite the problem
- I formally object to the group/chair decision

and under these circumstances, if the council agrees it should be removed, and the group refuses, we have a failure mode we have not previously experienced. I would expect the team to pull the CR from being published, or edit it themselves, or something.

The council might advise what to do next, how to address the concern, and so on. Or indeed, they might turn down the FO but advise the group to add an erratum and work on revising the feature to remove the concern, and so on. The **advice** and the **decision** are separate.

**Comment by dwsinger** [comment]
we need to (a) verify that we believe a binary ruling (uphold the decision, or uphold the objection and un-make the decision) is always possible and (b) that there have not been cases of non-binary rulings in the past.

**Comment by michaelchampion** [comment]
@frivoal wrote
> But it does seem to me that if we don't give it, at least in some cases, the ability to mandate solutions, the Council is at risk, in the most thorny cases, to be unable to actually resolve the issue.

The Council as currently conceived can really only mediate and advise, not decide.  If you want a Decider, figure out how to find an authoritative Director with the technical acumen and "political" neutrality to make decisions in corner cases.

Finding a BDFL to replace TimBL is probably an impossible task, but having the Board hire (and fire) a  Technical Director who can step in during these rare situations and issue an authoritative decision may not be.     I think that idea is worth exploring given that the Council idea seems more and more problematic the deeper we explore it.  If that is impractical too, just learn to live with the  possibility of non-binary outcomes where the community essentially votes with its feet if the AC or WG disagree with the Council after deep discussion.

**Comment by chaals** [comment]
The director can currently tell a non-functional group (such as the case outlined by @frivoal above) that they have lost their mandate to write a W3C specification and they have to stop work. This has happened in the past, and it is an intensely political issue. The only equivalent I see in proposals so far is that the council could say "we don't think we will approve anything and expect all futher work to be a waste of time" - which is not quite the same thing, and **could** (subject to the outcome of #290) be changed by the AC as the result of an election.

**Comment by dwsinger** [comment]
@chaals do you mean the hypothetical in https://github.com/w3c/w3process/issues/279#issuecomment-520510739 or https://github.com/w3c/w3process/issues/279#issuecomment-494863182, and in either case, what would the hypothetical decision and FO be?

**Comment by dwsinger** [comment]
ping @chaals

**Comment by fantasai** [comment]
@dwsinger In your example in https://github.com/w3c/w3process/issues/279#issuecomment-520728252 the group might not have made any decision, they might be just ignoring the commenter. In which case there technically isn't a decision to object against...

**Comment by dwsinger** [comment]
@fantasai You're right; the the scenario then is

* something is in a CR and has been for a while, no-one objects
* I discover a problem, and ask that the feature be removed
* the chair doesn't ask for or get a group decision on my request, but ignores me, so it stays in

at this point, I guess I have to file an FO on the original decision to include; or on the chair's action in deciding to not consider my problem. And I have to work out what's a reasonable timeout (in the absence of the chair telling me that he's ignoring me). This is ugly but do-able, I think.

**Comment by frivoal** [comment]
@dsinger, I think the problem is actually at the next stage: you filled an FO against the chair turning you down (or ignoring you for too long), the Council has ruled in your favor and sustained your objection, and now, either of these happen:
1. The chair/WG do nothing. => repeatedly re-file the FO, until either the chair does something or the Team appoints a new chair?
2. The chair/WG fix the editor's draft, but "forget" to update the CR. => repeatedly re-file the FO, until either the chair does something or the Team appoints a new chair?
3. The chair/WG fixes the editor's draft, but don't have consensus to update the CR, so they don't. => you're stuck, the Council does not have the power to mandate that a CR be published, and neither can the Team do so without a WG consensus.
4. the chair observes that the WG has no consensus on doing what the objector prefers, so they do nothing. => you're stuck, the Council does not have the power to mandate that a CR be published, and neither can the Team do so without a WG consensus.

1 / 2 can arguably be dealt with on a disciplinary basis, as this is just disregarding the process. The Team Council would still not have the authority to fix it themselves, but it'd be possible replace the WG chair with one who will actually do the Job.

3 / 4 are much more tricky: arguably, the whole point of the Council not mandating things is so that the WG can discuss further and chose their own path. Failing to reach consensus is therefore a possibility, and doesn't require anyone to act in bad faith. Which means that if the council cannot mandate things, if the Council is in consensus about something, but the WG is not, status quo will prevail and the Council will not be able to enforce a solution.

**Comment by dwsinger** [comment]
@florian I don't see how ignoring, or being unable to follow through on, the council decision would be a new problem, distinct from ignoring the Director's decision today. Isn't that a different problem and question from this issue?

**Comment by frivoal** [comment]
You're right, the Director cannot force people to do many things, but I think one difference is that the director currently has the authority to unilaterally change the content of a spec / charter that is being published at the end of an AC review, even in the absence of consensus about the change that he is applying (and at the moment, without even having to check whether there is consensus), and as chaals pointed out, the director also has the ability to shut down a working group. These give more teeth to Director's rulings.

Today, if the Group decided to publish A, someone objects and prefers B, the Director can chose to publish A, to publish B, or even make up and publish C.

A Council would be able to allow publishing A (objection overturned), or to decline publishing A (objection sustained), but unless there's actually a consensus in the WG for B or C, they could not get that published.

Then again, the Team will still have the ability to shut down (dysfunctional), so even if indirect, that could probably still put pressure in the bad faith cases.

So I guess it boils down to this: if the TAG+AB+CEO are in consensus that something is the right thing to do, but the WG isn't, do we consider staying with the status quo (whatever that is) a feature or a bug?

**Comment by fantasai** [comment]
I believe this issue was closed by merging in the definition of the Council and in particular this additonal follow-up pull request on mitigations: https://github.com/w3c/w3process/pull/645
