### ISSUE TITLE
CEO is part of the AB, and ex-officio participant in Objection Decision Committee

### ISSUE THREAD

**Issue by chaals** [w3c/w3process#284]
Currently, the Process says

> The Advisory Board consists of nine to eleven elected participants and a Chair

CEO participation in the ODC should be clarified - presumably they are not there both as a voting member of the AB and with a separate tie-breaking vote as chair of the ODC...

see also #225

**Comment by frivoal** [comment]
I think the CEOs participation in the ODC is well defined in [section 3.3.2](https://w3c.github.io/w3process/director-free/#WGArchiveMinorityViews):

> The Objection Decision Committee consists of the following, with the exception of any who recuse themselves:
> * the CEO, who serves as the Chair of the Objection Decision Committee
> * the members of the Advisory Board
> * the members of the Technical Architecture Group
> 

Yes, they double qualify given that they're part of the AB and called out explicitly, but I don't think that anyone will interpret that to mean that they need to show up twice :)

The fact that the CEO ought to be a member of the AB even when they're not chairing it should be clarified (regardless of the mechanism used to pick the Chair of the AB), but that seems independent of this [director-free] exercise.

**Comment by frivoal** [comment]
Unless I am missing something, I suggest re-purposing this issue to fix the fact that the Process doesn't currently make the CEO an ex-officio member of the AB.

**Comment by chaals** [comment]
I would be more inclined to hold it open dependent on how #225 works out. I agree that it's actually a very small issue, but there isn't an obvious way to label as such.

**Comment by dwsinger** [comment]
Let's leave this hanging. 

Once the ODC (or something like it) is approved, we can tell if that causes any cleanup, and if we change the process so that the CEO is not chair of the AB, we can decide whether the CEO is still ex-officio a member.

**Comment by chaals** [comment]
That seems like the best plan. I just wanted to note the issue so we don't forget to clean it up at the appropriate time.

**Comment by fantasai** [comment]
Suggested rewrite to fix this:
- the CEO or the CEO’s designated Team representative
- the elected members of the Advisory Board
- the elected and appointed members of the Technical Architecture Group

Avoids the issue of whether the CEO is a member of the AB or not. :) Also, I was thinking the CEO might want to delegate the job, would be good to allow that.

**Comment by chaals** [comment]
I don't think it makes sense to have the CEO on the review board. Proposals that can get a formal objection are made in the name of W3C. While many times the CEO might not have personally taken the decision, there still seems to be a clear conflict, meaning the CEO should recuse themselves.

Like the related discussion about recusal in #278 I would be fine with the decision committee requesting input from W3C (and in many cases think that if they didn't they were not doing their job properly) but I lean against having the CEO pas a member of the committee.

I do not think it is appropriate for the CEO to delegate to some other team member in any event - both because I think the same conflict is there and because I don't think that we accept members of the TAG or AB delegating their tasks to someone else, and if the CEO is a member of the AB that should hold.

**Comment by jeffjaffe** [comment]
@chaals I would appreciate if you could clarify what you mean when you say that "proposals that can get a formal objection are made in the name of W3C".

For example, I have oft-heard that when people object to a Charter, they are essentially objecting to a Charter created by the Team in the name of the Director.  Indeed, that was once true.

But today, increasingly, charters are developed by a WG or CG in GH with only gentle direction from the Team.  Would you still consider that a "proposal in the name of W3C"?

And in a proposed "director-free" future, it is not even clear that charter development would remain a Team responsibility at all.  Here, even more so, would a charter be a "proposal in the name of W3C"?

**Comment by dwsinger** [comment]
Currently defined in the draft Process that the Council explicitly includes the CEO. Close?

**Comment by plehegar** [comment]
I believe this can be closed indeed. If this needs revisit, it can always be re-opened.
