### ISSUE TITLE
"W3C Council" may have to hear information in confidence

### ISSUE THREAD

**Issue by chaals** [w3c/w3process#291]
The nature of formal objections means that in principle there can be team-only information provided by an objector. The Director is currently expected to hold such information in confidence, but use it to inform the decision-making.

The document should be clear that this may still occur, and the council are required to hold that information in confidence, or change that to prohibit the use of confidential information.

**Comment by frivoal** [comment]
The proposed text already says that 

> The deliberations of the W3C Council <file:///Users/florian/src/w3process/index.html#w3c-council> are confidential to the W3C Council <file:///Users/florian/src/w3process/index.html#w3c-council>.

Then we also have the general clauses about confidentiality.

Do you think we need something in addition to that?

**Comment by dwsinger** [comment]
ping @chaals  to see if we need anything more

**Comment by frivoal** [comment]
I agree we can close

**Comment by dwsinger** [comment]
We can also respect an FO filed in confidence, and deal with the objection without knowing its origin or being able to interview the objector. that would be the objector's choice. The team must verify in this case that the objection is valid (if there is any possibility of an invalid objection).
