### ISSUE TITLE
[director-free] Should the Council be all TAG+AB, or smaller and separately elected?

### ISSUE THREAD

**Issue by dwsinger** [w3c/w3process#293]
Forked from https://github.com/w3c/w3process/issues/290

2. Contentious working groups manage with a membership quite a bit larger than 22.

3. Part of the credibility is that indeed there are enough people to represent a diversity of opinion, and that it's both the AB (notionally process and procedure and operations experts) and TAG (notional technology and architecture experts). I would be strongly opposed to both the overhead of a separate election, and to having 'too small' a group.

4. You seem entirely happy to live with the WHATWG that is governed by, and issues are decided by, a small and completely unelected group, yet seem strangely resistant to having the elected groups at the W3C decide issues.

5. Good luck finding people who are willing to serve on a separately elected council that only exists to decide hard FOs and the like. It's a thankless job. Saying it comes with the turf for AB and TAG makes some sense.

**Comment by TzviyaSiegman** [comment]
> Contentious working groups manage with a membership quite a bit larger than 22.

I think this Council will need to work differently than a WG, ideally very quickly and with decisive action.

> Part of the credibility is that indeed there are enough people to represent a diversity of opinion, and that it's both the AB (notionally process and procedure and operations experts) and TAG (notional technology and architecture experts). I would be strongly opposed to both the overhead of a separate election, and to having 'too small' a group.

If we create a process that selects representatives of AB+TAG that reflect this diversity and relevant expertise, I think we are still safe. A group of 5 (for example) can still be diverse. I don't think we ought to rely on random selection but on a combination of expertise in the relevant area, availability, and striving for good representation. We will need to flesh out exactly what the makeup of each council should be, 

> Good luck finding people who are willing to serve on a separately elected council that only exists to decide hard FOs and the like. It's a thankless job. Saying it comes with the turf for AB and TAG makes some sense.

+1 I don't think it's a good idea to set up a unique body that is devoted to resolving FOs.

**Comment by mnot** [comment]
I agree that a separate body is not a good idea here. Still, I wonder if it's useful to have the entire body rule on everything; do we really want the AB ruling on technical matters, or the TAG ruling on process matters?

Would it be possible to designate a FO as 'process' or 'technical', and have the appropriate body weigh in? 

Failing that, could we create a norm that when a FO doesn't relate to your general area of authority, you abstain?

An aside -- 
It would be especially unfortunate if a company that had a strong opinion on a matter had a representative on both the AB and TAG; that could undermine the legitimacy of the process. Should there by guidance on recusal in this situation?

**Comment by frivoal** [comment]
> do we really want the AB ruling on technical matters, or the TAG ruling on process matters?

When discussing this in the AB, we concluded that many "interesting" Formal Objections had components of both technical and non-technical matters, making joint deliberation important.
We do expect that on primarily technical questions, the Council will primarily head the advice of its TAG members, and that of its AB members for primarily non-technical objections.

But since drawing a strict distinction over which is which, that is better dealt with with guidelines and best practices than hard rules in the Process.

**Comment by dwsinger** [comment]
I think and hope that the council will delegate small groups to do research and come back with analysis and recommendation. I think it makes sense for the whole AB+TAG to 'double check' their work and that the Decision is issued with the consent of all of them.

I think your aside is probably more significant; indeed, should we require that there is only one vote per member on the council, in the case that a member has more than one representative on the Council? (This might happen due to AB+TAG or in the relaxation of TAG rules over change of affiliation).

**Comment by frivoal** [comment]
This issue is no longer current, and has been addressed already. See https://www.w3.org/Consortium/Process/Drafts/director-free/#council-composition
