### ISSUE TITLE
Add reference to Code of Ethics and Professional Conduct (CEPC) in the Process Document

### ISSUE THREAD

**Issue by dwsinger** [w3c/w3process#30]
Transferred from https://www.w3.org/community/w3process/track/issues/178
State: Raised

**Comment by chaals** [comment]
From [the old issue](https://www.w3.org/community/w3process/track/issues/178):

> We should have a reference to the Code of Ethics and Professional Conduct (CEPC)
https://www.w3.org/Consortium/cepc/ in the Process Document. Perhaps in 3.1 Individual participation critieria, "Participants must abide by W3C's Code of Ethics and Professional Conduct [CEPC]."

It's there. Closing

**Comment by dwsinger** [comment]
The request was for “Participants must abide by…” whereas the Process only says “See also…”


> On May 9, 2017, at 3:40 , chaals <notifications@github.com> wrote:
> 
> Closed #30.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

David Singer
Manager, Software Standards, Apple Inc.

**Comment by chaals** [comment]
Clarify that *among* the requirements for participation is a specific requirement to abide by the terms of CEPC... Which becomes a substantive change.

**Comment by dwsinger** [comment]
We probably want to say that participants in any activity of the W3C must abide by the CEPC, which means we don't have to enumerate WGs, elected Gs like AB and TAG, AC, IGs, CGs, BGs, or even gee-gees.

**Comment by vfournier17** [comment]
I agree with making this a normative requirement, otherwise it's not legally enforceable.
