### ISSUE TITLE
[evergreen] Role of PD

### ISSUE THREAD

**Issue by frivoal** [w3c/w3process#300]
Prior to issuing Evergreen RECs, the [evergreen process](https://w3c.github.io/w3process/evergreen/) enables WGs to produce Preliminary drafts. While this seems to be intended to serve as a parallel to Working Drafts on the traditional REC track, it is unclear what purpose they serve and how they are expected to be used on the Evergreen Track, because the Evergreen Process imposes no maturity criteria or any constraint on transitioning from PD to ER. It seems that nothing prevents a Group from using only ERs, no matter how immature the sec is, nor does there seem to be anything forcing the group from switching from PD to ERs ever.

As currently framed, patent Coverage for PDs is unclear (see point 7 in https://lists.w3.org/Archives/Public/www-archive/2019Jul/0003.html), and the various safeguards and requirements placed on the WG and Editor are also absent.

PD should probably either be removed entirely, or if it is meant to serve a particular role, beefed up so that it can consistently fulfill that role.

**Comment by dwsinger** [comment]
I don't think there is any reason to call them anything other than WDs of the WG.

**Comment by frivoal** [comment]
Works for me. If they are regular WD, of which there is a first, that also clarifies the patent situation at the beginning of the evergreen track, which is currently fuzzy/buggy (see issue 9 in https://lists.w3.org/Archives/Public/www-archive/2019Jul/0001.html).

That still leaves a question open: when do you switch from WD to ER? Whenever the Working Group feels like it? Some other criteria? If so, how are these criteria checked/enforced?

**Comment by frivoal** [comment]
Just realized this is probably a Duplicate of https://github.com/w3c/w3process/issues/272. Closing this, and reposting the comments there.
