### ISSUE TITLE
[evergreen] two types of wide review?

### ISSUE THREAD

**Issue by frivoal** [w3c/w3process#302]
[6.2.3.1.2. Wide Review for the Evergreen Track ](https://w3c.github.io/w3process/evergreen/#wide-review-er-track) claims that evergreen specs are expected eventually to move to the Recommendation track "to achieve a more complete wide review, horizontal review[...]".

I find this claim problematic. Being on the Rec track doesn't cause wide or horizontal review to happen. It does have checks to confirm that it did happen, but that's different. A working group who wants review can solicitate review, regardless of track, so it seems misleading to say that a wg would switch tracks in order to achieve it. Saying that the AC could require switching track to enforce stricter criteria on review may be a more meaningful claim, but it is a different one.

Without any benefit to the WG itself, it seems doubtful that a spec developed on the evergreen track would spontaneously switch.

This phrasing also suggest that developing things to stability quickly and without much review and then seeking deeper review when things are stable and can no longer change much, is a pattern to be encouraged. While I recognize that we don't always get as much review and feedback as we would like early on when things are still malleable, it is something we should still strive to do.

All in all, I think the distinction between Wide Review for the Evergreen Track and Wide Review for the Rec Track is not useful to draw. As the evergreen track lacks transitions and the associated constraints, the practicality of how we achieve wide review, and how soon we do so, may vary between the two tracks, but the goal of wide review is the same, the constraint imposed by the cost of changing implementations or by web compatibility is the same, the desire for tooling to facilitate wide or horizontal review is the same.

**Comment by dwsinger** [comment]
I have long opposed this (a) as an expectation (it's merely a possibility) and (b) as a claim that somehow better review is done. I think RTec status has two aspects:
* the whole document has achieved a uniform level of review and acceptance;
* it presents a unmoving target e.g. for reference or other purposes

**Comment by frivoal** [comment]
agreed to close on Jan 29th call, as a separate Evergreen track is no longer being pursued.
