### ISSUE TITLE
The process does not include any disposition for updating the Patent Policy

### ISSUE THREAD

**Issue by frivoal** [w3c/w3process#305]
The process does not include any disposition for updating the Patent Policy. Effectively, I suppose this means it can (and can only) be done by the director's fiat, but that's probably not ideal. An alternative understanding would be that since the Patent Policy is normatively referenced by the Process, and since the AB is in charge of the Process, then it is in charge of the Patent Policy as well.

I'd suggest explicitly stating that the Patent Policy can be updated in the same way as the Process can: prepared by the AB, then proposed to an AC Review (which implies a director's approval as well, as long as there is a Director). We might also want to say that PSIG ought to be involved, but then again, PSIG's existence is not mandated by the Process, so I'm not sure. Even if we don't mention them explicitly, so long as PSIG exists in its current form, I'd expect the AB to consult with them, and for the Team / AC / Director to push back if they haven't.

I don't expect updating the Patent Policy will be a frequent occurrence, but that doesn't mean we shouldn't know how to update it when we want/need to.

**Comment by chaals** [comment]
Given the Patent Policy is part of the Process, I think it's OK to leave the whole thing as "you update the Patent Policy as if it were part of the Process" . 

We have made one update in 15 years, that was developed through PSIG as a proposal, and effectively it was proposed to the AC in an AC review, and then adopted.

**Comment by michaelchampion** [comment]
I fear we are spending too much time picking nits that aren't causing tangible problems out of the Process Document.  Let's focus on fixing problems that arise from the execution of the process as it is understood, not on fixing the language of the document itself unless it is creating actual misunderstandings.

**Comment by frivoal** [comment]
I feel that the Patent Policy hasn't been updated in years in part because we want it to be stable (which is a good thing), but also because it doesn't have a clear owner, and so most of the time nobody thinks it's their job to even consider what fixes might be desirable. I'd prefer to establish clear ownership, and it seems to me that this can either be the Director, or the AB. I'd rather go with the later.
