### ISSUE TITLE
CR change documentation requirement should be for substantive changes only

### ISSUE THREAD

**Issue by fantasai** [w3c/w3process#307]
“must document the changes since the previous Candidate Recommendation”

s/changes/substantive changes/ because making editors document all their editorial fixes is annoying, and the changes list is actually more useful if it's operating at a higher level. If someone really wants to see every single change in wording, they can run HTMLdiff.

**Comment by LJWatson** [comment]
Suggested text:
"... MUST document substantive changes since the last Candidate Recommendation. If editorial changes have been made, this SHOULD be indicated, but details are not required."

**Comment by frivoal** [comment]
Updated the pull request (#308) with @LJWatson 's wording.

Waiting for chair resolution to merge.
