### ISSUE TITLE
Should we have a nomination committee seeking candidates for the AB and TAG?

### ISSUE THREAD

**Issue by dwsinger** [w3c/w3process#31]
Transferred from https://www.w3.org/community/w3process/track/issues/179
State: Raised

**Comment by chaals** [comment]
I'd be quite happy for a nomination committee - or even better, several, unofficially - to seek candidates. But wildly opposed to one that actually determined who the candidates would be.

**Comment by dwsinger** [comment]
I agree with Chaals. The possible vision I see is of a committee that ensures that there is a slate of candidates (at least enough to fill the open positions), but it can't be a gating function. I do worry when we have elections with only just enough people...that's scarily close to not enough people.  A typical way to form that committee is by automatically enrolling in it, the people who are stepping down, probably having some team on it, and taking volunteers...

**Comment by chaals** [comment]
Hmm. Mostly, I don't think the process should mandate one - so I'd like to close this issue without a change to the Process...

**Comment by dwsinger** [comment]
That's a discussion to have with the CG and AB: if, for example, there are people who are automatically made members of the NomCom, that probably is a Process issue...

**Comment by chaals** [comment]
Right. So here is input to the discussion:
We should not formally institute a committee with responsibility to chase candidates. If such a committee forms, or if several such committees form, without any process-backed mandate, well and good.

I certainly do not believe that we should oblige people standing for AB election to commit to find candidates in the future. I am not even convinced that this is a good way to ensure an AB that represents the members, which is the base of my opposition to a process-mandated nomination committee.

**Comment by michaelchampion** [comment]
I think this idea is worth pursuing. Right now we have a de facto NomCom consisting of Brian Kardell :-), seeking out new candidates and vetting those who do run.  There's something to be said for at least carefully reviewing how the IETF NomCom works https://www.ietf.org/nomcom/ .  I don't like the idea of a NomCom *selecting* the actual TAG or AB, but having a randomly selected set of active W3C participants vet credentials and maybe recommend a set seek qualified people that the AC can choose among doesn't seem like a bad idea on the face of it, especially if there are term limits that encourage turnover.

**Comment by dwsinger** [comment]
Yes. I would be opposed to a NomCom that *controlled* nominations, but am cautiously optimistic about having a NomCom that ensures that there is a slate of candidates at all (in addition to any nominations from other members).

**Comment by dwsinger** [comment]
It seems that there are (at least) two definitions of a NomCom. (1) A group that ensures that there is a diverse, competitive, slate of candidates for each election, and nominates additional candidates as needed. (2) A group that identifies who should fill each vacant seat, and presents that slate for confirmation. The IETF has to use the latter as they have no membership. I would not be in favor of it for TAG/AB.

**Comment by nrooney** [comment]
Yup they use [2].

Natasha


Natasha Rooney | Web Director | Web Team | GSMA | nrooney@gsma.com<mailto:nrooney@gsma.com> | +44 (0) 7730 219 765 | @thisNatasha | Skype: nrooney@gsm.org<mailto:nrooney@gsm.org>

On 8 Dec 2017, at 17:44, David Singer <notifications@github.com<mailto:notifications@github.com>> wrote:


It seems that there are (at least) two definitions of a NomCom. (1) A group that ensures that there is a diverse, competitive, slate of candidates for each election, and nominates additional candidates as needed. (2) A group that identifies who should fill each vacant seat, and presents that slate for confirmation. The IETF has to use the latter as they have no membership. I would not be in favor of it for TAG/AB.

**Comment by dwsinger** [comment]
leaving this with the AB for now as a policy question, not a document question

**Comment by dwsinger** [comment]
Discussion continues at the AB but removing the AB2019Candidate label.

**Comment by frivoal** [comment]
Tying this together with the question of "the role of the director" (in the sense of Timbl being unique and irreplaceable as an individual, so for the process to be able to function without him, we need to replace a lot of instances of "the director [...]" with something else), I think there's another possibility:

The question of diversity on the TAG goes beyond just making sure that all constituencies are reasonably represented (whether our election system effectively does that is a question to be resolved separately), but also that the participants themselves are diverse, cover a broad range of technical expertise and of perspectives. The Director's 3 nominees are a way to achieve that, and replacing that with an IETF-style nomcom (i.e. present to the AC a slate of candidates for confirmation) would make sense to me.

**Comment by dwsinger** [comment]
Closing at the AB Nov 2018 meeting

**Comment by frivoal** [comment]
For the record: This is closed as a quasi duplicate of https://github.com/w3c/w3process/issues/230. This issue is broader, that one is more specific, and proponents of a NomCom are arguing in favor the the more specific one.
