### ISSUE TITLE
TAG chair selection timing

### ISSUE THREAD

**Issue by mnot** [w3c/w3process#310]
In the director-free branch:

> Participants in the [=TAG=] chose by consensus their Chair or co-Chairs

However, when this happens is not specified. Currently, the Chairs serve at the pleasure of the Director, but if the TAG is going to select its own chairs, it seems best to specify that at the beginning of each term (i.e., once a year), a chair or chairs is selected from the members of the TAG. 

Otherwise, the chair selection doesn't ever reflect the consensus of the *current* TAG; just a past one.

In normal operation, a TAG would select one or more chairs to continue service, unless there was some reason to select a new one. 

For what it's worth, this is roughly what the IAB does.

**Comment by dwsinger** [comment]
I believe that the TAG should select or confirm or choose their chair after every regular (not special) election.
