### ISSUE TITLE
Filling appointed TAG seats that have been vacated

### ISSUE THREAD

**Issue by mnot** [w3c/w3process#311]
In the Directorless branch:

> When an appointed TAG seat is vacated, the TAG Appointment Committee appoints a replacement. 

This doesn't say *which* TAG Appointment Committee does so; is it the one that originally appointed that person, the last operative TAG-AC, or a newly formed one?

**Comment by dwsinger** [comment]
I think a new one has to form at that time. They are episodic and don't exist between elections, normally.

**Comment by fantasai** [comment]
This is covered as @dwsinger says in the 2nd paragraph of https://w3c.github.io/w3process/director-free/#tag-appointment-committee

I think the confusion comes from a lot of "the" instead of "a". I'll ask @frivoal to fix those...

**Comment by frivoal** [comment]
Done. Please reopen if that's not good enough for some reason.

**Comment by mnot** [comment]
Just for reference / context; the IETF does it slightly different with the NOMCOM. There's always at least one sitting NOMCOM, and the rules for determining which is used are documented here:
  https://tools.ietf.org/html/rfc7437#section-3.5

AIUI the thinking is that by using the same people that made the original appointment, you're more likely to get continuity / context.

**Comment by frivoal** [comment]
I guess that is another possibility.

However, the IETF NOMCOM has more bodies to nominate people onto, so it is already expected that its members will have to work at multiple nomination events, and adding just one more doesn't seem to be a problem. Here, most of the time, we expect to need it once a year for a single body, and only more often if TAG participants vacate their seats. We could keep it open until the next one is formed, but most of the time that would make no difference, and for the few times where it would, I'm concerned concerned that confirming that the people who were on it for the intial round are still available for the new round isn't less work that forming a whole new NOMCOM.

**Comment by mnot** [comment]
> However, the IETF NOMCOM has more bodies to nominate people onto, so it is already expected that its members will have to work at multiple nomination events, and adding just one more doesn't seem to be a problem. 

Not really; a NOMCOM makes all of its (normal) nominations at the same time.

**Comment by samuelweiler** [comment]
> ...We could keep it open until the next one is formed, but most of the time that would make no difference, and for the few times where it would, I'm concerned concerned that confirming that the people who were on it for the intial round are still available for the new round isn't less work that forming a whole new NOMCOM.

@mnot addressed part of this (quite correctly); I'm going to take on another piece.

I'm not worried about "confirming availability" - spinning up a new nomcom would necessarily involve that same step - plus quite a bit more.  (And in my experience of serving on more than one IETF nomcom, "making sure people are (still) available" is not a huge deal.  Spinning up a new nomcom is (at least in their process) quite a bit heavier-weight - and slower.)

**Comment by dwsinger** [comment]
> > However, the IETF NOMCOM has more bodies to nominate people onto, so it is already expected that its members will have to work at multiple nomination events, and adding just one more doesn't seem to be a problem.
> 
> Not really; a NOMCOM makes all of its (normal) nominations at the same time.

Now I am confused. You're saying that the IETF NomCom stands until the next one forms, to deal with resignations and off-cycle replacements, and then you say that it makes all its nominations at the same time.

We only have a few TAG seats. Mid-cycle resignations are moderately rare. The committee doesn't form if the election is within 2 months, and in the remaining 10 months we can choose any TAG participant since none are up for re-election/re-appointment.

Eligibility and willingness to serve may have changed, as well. I suppose we could say after

> When formed to fill vacated seats out of a regularly scheduled election, a TAG Appointment Committee is formed as soon as possible after the seat is vacated, unless a regular Call for Nominations is scheduled within 2 months.

that

> The initial composition of the appointment committee in this case is the membership of the prior appointment committee, adjusted as needed to compensate for those no longer available, eligible, or willing to serve.


I'd be OK with that.

**Comment by frivoal** [comment]
(Tagging as invalid, as this issue is no longer relevant: the TAG Appointment Committee it was about is no longer our approach to TAG nominations)

**Comment by frivoal** [comment]
@mnot as you opened the issue, I'd like to confirm: are you OK with this issue being closed, for the above reason?

**Comment by mnot** [comment]
Well, it appears to be overcome by events, so I suppose yes.
