### ISSUE TITLE
Suspension / Removal for cause

### ISSUE THREAD

**Issue by mnot** [w3c/w3process#312]
In the directorless branch:

> The CEO may suspend or remove for cause a participant in any group (including the AB and TAG ), where cause includes failure to meet the requirements of this process, the membership agreement, or applicable laws.

This seems like a fair amount of power, and it isn't well-defined:

* Does "the requirements of this process" mean violating a RFC2119 requirement in this document, or something else? 
* Either way, can some examples of things that are cause be given? 
* Should this decision be appealable (e.g., to the W3C Council)?

( echoes of #23 )

**Comment by frivoal** [comment]
The main branch of the process has the same text, with the Director instead of the CEO. I don't necessarily disagree that this could use some improvements, but if so, I think they would be as relevant for the main branch as for the directorless one.

> * Does "the requirements of this process" mean violating a RFC2119 requirement in this document, or something else?

I think this is primarily intended for violations of the [CEPC](https://www.w3.org/Consortium/cepc/) (adherence to which is mandated by the process), as well as other egregious behavior that is incompatible with normal professional conduct. Not for failing to follow some detail of the process once.

> * Either way, can some examples of things that are cause be given?

Seems like a fair request to me. I wonder if @wseltzer sees a downside to listing examples here.

> *    Should this decision be appealable (e.g., to the W3C Council)?

I'm torn. On the one hand, Formally Objecting to this kind of decisions seems fair at first, and could bring accountability on the CEO's actions in this regard. At the same time people rarely get suspended with their consent, so we can expect lots of formal objections in this area, and while the Council is not a bad body for ensuring accountability, it is not a great one to deal with discipline. I'm tempted to say that a good CEO ought to be aware of the gravity of such disciplinary actions, and therefore not to take them lightly or without having consulted relevant stakeholders. And a "bad" CEO is something the board of directors (which we expect to have before we go director-free) should take care off.

**Comment by mnot** [comment]
Fair enough re: scope.

If it's about the CEPC, it should definitely say so; that wasn't obvious on first reading (especially with the loaded use of "requirements"). 

That said, I wonder if having CEPC enforcement being performed directly by the CEO is a good idea; in most organisations, there's some sort of ombudsperson/team that tries to handle those sorts of issues and perform restorative justice (or another favoured technique) before recommending the ban-hammer. Having that level of indirection would take some of the heat off of the CEO in contentious situations -- especially if that team is representative of the community. 

That would also help to answer the appeal question.

**Comment by frivoal** [comment]
> If it's about the CEPC, it should definitely say so;

+1

> [...] ombudspersons [...]

We have ombudspersons (and are working on improving that further). But as you said, kicking people out when everything else has failed isn't their remit. Hopefully we don't need that often, but that possibility needs to exist too (if only to motivate the offenders to pay attention to the ombuds).

**Comment by dwsinger** [comment]
> * Should this decision be appealable (e.g., to the W3C Council)?

I think we have written it that any formal Decision can be Appealed. I hope so.

**Comment by frivoal** [comment]
> I think we have written it that any formal Decision can be Appealed. I hope so.

I proposed that in https://github.com/w3c/w3process/pull/299, but got push back, not so much on the principle, but rather on the details of how to state that without going too broad. Suggestions welcome in that PR to help solve that issue.

**Comment by jeffjaffe** [comment]
Today's ombudspeople have a facilitation role, not a decision role.  We are trying to ease the Team out of the ombuds role and have that done by the broader community.  Most people that would volunteer to facilitate might not feel comfortable in a decision role.

**Comment by michaelchampion** [comment]
FWIW, I support simply replacing  ‘Director’with ‘CEO’ here. Somebody has to make a hard decision and be accountable for the consequences, that’s why CEOs do.  And it’s consistent with my view of the Team’s role as consensus facilitator, not technology decision maker.

**Comment by mnot** [comment]
I think having the CEO make the decision is fine. If the omsbudspeople were to recommend or make a report to the CEO, that might give them some "air cover" in making such decisions.

**Comment by dwsinger** [comment]
I think that's what a CEO would/should do to protect themself; take advice, consult, get recommendations, make sure they have heard all sides, be seen to be fair, and so on.

In general, there's a whole lot that we let the team 'just do' with the implicit backstop that if they start acting in arbitrary on unreasonable ways, we have other recourse (like leaving, complaining to the Director (now) or Board (in future)). We don't need to write explicit backstops and protections into every possible action that they can take.

**Comment by mnot** [comment]
@dwsinger, on the broader point: those remedies seem like very high bars indeed, especially when the Team's activities are often less than transparent, and when the Membership is anything less than extremely active.

I think in this particular case it might be reasonable, but as @michaelchampion pointed out elsewhere, when applied to technical decisions, that's inappropriate.

**Comment by dwsinger** [comment]
I think it means violations of requirements of the process that apply to the actions of individuals. Perhaps that's all that needs to be clarified?

"The CEO may suspend or remove for cause a participant in any group (including the AB and TAG), where cause includes failure to meet the any of the requirements on individual behavior in (a) this process, (b) or the membership agreement, (c) or applicable laws."

**Comment by frivoal** [comment]
Iterating some more:

> The CEO may suspend or remove for cause a participant in any group (including the AB and TAG), where cause includes failure to meet the any of the requirements on individual behavior (and in particular the CEPC) in (a) this process, (b) or the membership agreement, (c) or applicable laws.

**Comment by fantasai** [comment]
I think the CEPC parenthetical has to go after the word “process” (which should maybe be capitalized) not before it, since the idea was that it is incorporated by reference through the Process not the Membership Agreement or Applicable Laws? :)

**Comment by frivoal** [comment]
Overall, this looks good to me. I do wonder if it's still a little too strong, and may still make it look like you could be kicked out for minor failures to follow the process (e.g. didn't republish a draft within 6 month to update the status, even though the Process says must). I'm sure no CEO would do that, but then we don't need phrasing that suggests that they could.

**Comment by dwsinger** [comment]
If we want to say "repeated or gross failures" to meet the requirements, to make it clear that this is a pretty dramatic step, I'd be OK with that (or something like it).

**Comment by dwsinger** [comment]
process CG: we'll address the substance questions in PR 432, and would like a new issue on Director-free

**Comment by dwsinger** [comment]
should this be closed? do we have the new issue on D-F discipline?

**Comment by samuelweiler** [comment]
> We have ombudspersons (and are working on improving that further). But as you said, kicking people out when everything else has failed isn't their remit.

Is it a problem that the CEO is both a Ombuds and, in this proposal, the kicker-out?  (I think it is, since one of the people one could consult for "facilitation" (Jeff's word) might ultimately have to rule on the matter.)

**Comment by dwsinger** [comment]
I don't see a problem, myself, but anyone who does is free to contact a different ombudsperson. If there is a problem, I'd prefer to see an adjustment of the ombuds list. We need someone with the power to eject if ultimately needed, and I have a problem working out who else that could possibly be.

**Comment by TzviyaSiegman** [comment]
The CEO (or any person in a leadership position) as ombudsperson is one of the issues being addressed by PWE

**Comment by samuelweiler** [comment]
> We need someone with the power to eject if ultimately needed, and I have a problem working out who else that could possibly be.

Maybe we can get inspiration from other self-governing bodies.

While the IETF designates individuals for restricting posting to single lists (see below), they have a novel approach for revoking posting privileges to _all_ IETF mailing lists.  Such a bold action must be ["...discussed by the community..." and "... using the usual consensus-based process, it is decided upon by the IESG."](https://tools.ietf.org/html/rfc3683#section-2)  I'm not sure W3C is ready for suspensions to be discussed by the whole community.  :-)  But it's a novel approach.  (In our case, I imagine the AB being the closest analogue to the IESG.)

For individual WGs, the person is ["the Area Director, with the approval of the IESG"](https://tools.ietf.org/html/rfc2418#section-3.2).

For the IETF discussion list, it's ["[t]he IETF Chair, the IETF Executive Director, or a sergeant-at-arms appointed by the Chair"](https://tools.ietf.org/html/rfc3005).

(All of these processes are over 15 years old!)

Not to say that we should adopt any of this, but there are other examples in the wild for us to learn from.  I note that a paid staff member (the Exec Director) is one of the deciders for only one of the IETF's lists - suspensions to all other lists are adjudicated by community-selected leaders with limited terms.

**Comment by jeffjaffe** [comment]
> Is it a problem that the CEO is both a Ombuds and, in this proposal, the kicker-out? (I think it is, since one of the people one could consult for "facilitation" (Jeff's word) might ultimately have to rule on the matter.)

+1 to @TzviyaSiegman that this is being addressed by PWE.
+1 to @dwsinger that anyone who would not like to choose the CEO as ombudsperson is welcome to do so.

I would add that if the community feels that it is inappropriate for the CEO to even be a candidate ombudsperson, I would have no issues stepping down from that role.

**Comment by dwsinger** [comment]
I'm unsure what action we are arriving at here.

**Comment by frivoal** [comment]
As discussed early on in the issue, the problem here wasn't really CEO vs Director, but that the underlying text in general was poorly phrased. This has now been cleaned up on the main branch through PR https://github.com/w3c/w3process/pull/432.

With that in place, I believe all there remains to do for this issue is to rebase the director-free branch on top of the latest main branch, and with the now cleaner text, replacing the Director with the CEO should now be just fine.

(redesigning the ombudsperson program is an interesting question, but a separate one)

**Comment by dwsinger** [comment]
waiting for D-F to rebase

**Comment by fantasai** [comment]
#432 handled consolidation of discpline-related text and some amount of rephrasing, but it doesn't seem to have included consideration of the proposed edits in the above sequence of comments starting at https://github.com/w3c/w3process/issues/312#issuecomment-530108119

Those would look like the following edits:

> The [Director|CEO] may suspend or remove for cause a participant in any group (including the AB and TAG) where cause includes failure to meet the requirements <ins>on individual behavior in (a)</ins> this Process <ins>(and in particular the CEPC)</ins>, <ins>or (b)</ins> the Membership agreement, <ins>or (c)</ins> applicable laws.

I think the question remains open, whether or not we want to take these proposed changes.

**Comment by fantasai** [comment]
Florian points out I was diffing against the old text. :/ The above needs to be rebased over the new text.
