### ISSUE TITLE
TAG Appointment Committee composition

### ISSUE THREAD

**Issue by mnot** [w3c/w3process#315]
In the directorless process, the TAG appointment committee is comprised of one team member, two current TAG members, and four WG chairs.

It seems like this could lead to undesirable results. In particular, some areas of interest in the W3C have multiple WGs, and so we could end up with an over-emphasis on expertise in a particular area, rather than breadth of experience across the Web -- especially if one or both of the TAG representatives are also such specialists.

While the consensus process in the TAG-AC might be a bulwark against this, that presumes that the TAG and Team representatives have the will to forestall it, and resist any "horse-trading' that happens (since there are multiple seats to fill).

A few suggestions that might counterbalance this tendency:

* [ ] Make the TAG-AC bigger; more chairs, and more TAG members.
* [ ] Add some non-voting advisory members to keep things on the rails (e.g., ex-TAG members, and AB representative).
* [ ] Disqualify appointed TAG members from the pool.
* [ ] Add a confirmation step (e.g., by the AB) as a sanity check.

Since I think this design came from #230, I'll point out that the NOMCOM is large (this year, 10 voting members), has advisory members, and its decisions are confirmed by the countervailing body (IESG for IAB, IAB for IESG).

**Comment by masinter** [comment]
Would you add non-voting advisory members from other organizations  as https://www.ietf.org/about/groups/nomcom/  seems to? I'm thinking of orgs whose specs are essential parts of the web platform -- ECMA, IETF(IAB/IESG), WHATWG

**Comment by mnot** [comment]
It's an interesting idea.

**Comment by mnot** [comment]
For context, see:
  https://tools.ietf.org/html/rfc7437#section-4.3
... and some of the following sections.

**Comment by dwsinger** [comment]
we have simplified this to being a team appointment with prior consultation

**Comment by frivoal** [comment]
The AB (with advice from the TAG) has resolved not to have a TAG Appointment Committee anymore.

**Comment by fantasai** [comment]
FWIW, we did adopt most (all?) of these proposals in the TAC draft. :) But currently the process (requested by the TAG) is community input into Team appointment with incoming TAG ratification.

**Comment by frivoal** [comment]
@mnot as you opened the issue, I'd like to confirm: are you OK with this issue being closed, for the above reason?

**Comment by mnot** [comment]
Since this issue is about balance in the TAG appointment process, I'd like to keep it open.

Currently, the draft process has the Team making the appointments, with only one counterbalance:

> The [Team](https://www.w3.org/Consortium/Process/Drafts/#team)'s choice of appointee(s) is subject to ratification by secret ballot by two thirds of the [TAG](https://www.w3.org/Consortium/Process/Drafts/#technical-architecture-group).

Having a body ratify such a large proportion of its own membership seems problematic to me; it reinforces the 'insider' tendency. It makes it harder for the Team to 'shake things up' if it feels it necessary.

Why not have another body, such as the AB ratify the selections here?

**Comment by frivoal** [comment]
I'd argue that is a different issue, even if it is a related topic. This was filed about the composition of the TAG Appointment Committee, not the TAG itself, and that is a body we eventually decided not to have. We cannot agree or disagree with you about how a body that doesn't exist should be composed.

The question you raise in your comment above seems legitimate to me, but I think it's a separate issue. I think it would be preferable to file it separately.

**Comment by frivoal** [comment]
@mnot since you did open a new issue to discuss the rest of this, I take it that you agree that this particular is acceptably closed the way it is. Please say so if that is a misunderstanding.
