### ISSUE TITLE
The Team should have a role in the Process evolution

### ISSUE THREAD

**Issue by jeffjaffe** [w3c/w3process#318]
Section 11 of the director-free Process document describes Process evolution.  It provides no role to the Team; either to review, consent, raise issues, etc. with this exercise.  This is a mistake and should be fixed.

It is true that this section is a copy from the current Process document.  But currently, the Director approves changes to the process and the Team advises him along the way.  Once we remove the Director, we have pulled the Team out of the process, except for a mechanical role.

**Comment by frivoal** [comment]
(tentatively) addressed by https://github.com/w3c/w3process/pull/309

**Comment by frivoal** [comment]
Closed by https://github.com/w3c/w3process/pull/309
