### ISSUE TITLE
Evolution of documents that are linked to the process

### ISSUE THREAD

**Issue by jeffjaffe** [w3c/w3process#319]
There are documents, e.g. CEPC, which are referenced by the process document but are evolved separately.  The process document should make clear what the approval path is for changes.

In truth, this issue applies to the current process document as well as director-free.  It is more urgent, in my view, to fix it in the director-free time frame.

**Comment by frivoal** [comment]
(tentatively) addressed by https://github.com/w3c/w3process/pull/309

**Comment by frivoal** [comment]
Closed by https://github.com/w3c/w3process/pull/309
