### ISSUE TITLE
"Implementation experience" description should clearly identify likelihood of broad acceptance

### ISSUE THREAD

**Issue by dwsinger** [w3c/w3process#32]
Transferred from https://www.w3.org/community/w3process/track/issues/180
State: Raised

**Comment by dwsinger** [comment]
This seems like a broader policy change that should have both substantial discussion at the AC, and consensus on defining what 'broad acceptance' means. We'd then need a text proposal, but we seem miles from one now.

**Comment by tantek** [comment]
I believe improving this would help us reduce the number of specs we have to obsolete in the future.

**Comment by wseltzer** [comment]
Do we need a "not-yet-Rec" status?

**Comment by chaals** [comment]
@wseltzer:

> Do we need a "not-yet-Rec" status?

We have Candidate Recommendation, and that's enough IMHO. Some specs are there very briefly, some spend a long long time there. What would a new status do to justify the complication it introduces?

**Comment by wseltzer** [comment]
Two additional features we might want: 
* Distinguishing "awaiting implementation experience" from other reasons something might still be in CR, which we could do with a different kind of flag: 
* Ability to get patent commitments sooner

**Comment by michaelchampion** [comment]
@wselter is there anything we could do about n the Process to get patent commitments sooner then Rec without changing the Patent Policy?

I suppose we could tweak the semantics of”Recommendation” the way we tweaked the semantics of CR when eliminating LC.???   

I think we want to lower the bar on triggering patent commitments but raise the bar on  “Recommendation” if we want to reduce the number of Recs that get obsoleted and make Recommendation literally mean “you can use this to build your website/app with high confidence it will work in the web ecosystem.” I don’t see how to do all that just within the Process. Does anyone else?

**Comment by dwsinger** [comment]
On patent commitments, the exclusion opportunities have mostly passed. True, the commitments don't formally become a license until Rec status, but is anyone really going to sue over a patent they will license RF at Rec status? (It is a contradiction in our processes that we ask for implementations before we grant a license, but, well...)

I honestly think it's for the AC and team to push back on specs that are unlikely to get implementation, well before the CR->Rec transition. We shouldn't be chartering groups to make such specs. It's too late when the spec. is written.

**Comment by chaals** [comment]
@michaelchampion asked

> @wselter is there anything we could do about n the Process to get patent commitments sooner then Rec without changing the Patent Policy?

No.

> I suppose we could tweak the semantics of”Recommendation” the way we tweaked the semantics of CR when eliminating LC.???

Only at the price of making it easy to produce a Recommendation that wasn't, and maybe wasn't likely to ever be implemented. I think that is a serious step in the wrong direction.

> I think we want to lower the bar on triggering patent commitments but raise the bar on “Recommendation” if we want to reduce the number of Recs that get obsoleted and make Recommendation literally mean “you can use this to build your website/app with high confidence it will work in the web ecosystem.” I don’t see how to do all that just within the Process. Does anyone else?

I don't think we can square that circle. I don't think it is critically important to get the patent commitments enacted earlier, primarily for the reason @dwsinger outlines above.

**Comment by dwsinger** [comment]
seems like a likely question for the AB to give us guidance on.

**Comment by dwsinger** [comment]
we'll analyze this with #172, #130, #167

**Comment by wseltzer** [comment]
I suggest that Charters should preview the exit criteria for their work: what implementation/adoption do they expect is necessary to call the work "successful"? how and when should we measure it? (through interop testing? at CR, or at some point after the draft spec is completed?) what ecosystem must cooperate for the work to succeed? 
(some of this is explored in team's pre-charter [evaluation](https://github.com/w3c/strategy/blob/master/3.Evaluation.md), )

At Transitions, the Director should review and enforce these Charter provisions.

**Comment by dwsinger** [comment]
We are unable to work out what we can do to address the issue, and we're not sure we understand it. Closing, but re-open (preferably with more clarity) if you disagree.

**Comment by frivoal** [comment]
@dprophet I am preparing a Disposition of Comments for this year's iteration on the Process. The AB in its last Tokyo meeting has decided not to address this in Process 2019. Since you raised the initial issue, I would appreciate if you can let us know if this is something you can live with, or if you wish to object to.
