### ISSUE TITLE
Do we need a lighter-weight process for superseding when it's "obvious"?

### ISSUE THREAD

**Issue by dwsinger** [w3c/w3process#324]
Forked from https://github.com/w3c/w3process/pull/213

There seem to be three cases of interest.

1. Only one document actually appears on /TR, the 'latest version' link in all of them point to that document. No action needed, you have effectively superseded. The WG or team can edit the old ones if they like and can (without changing their name or date or URL), but the existence of a different document at the Latest link should be enough warning to readers.

2. Both documents exist on /TR but one is clearly later, e.g. BadThing 1.7 and BadThing 2.0. They have the same specification name, and so on. 

3. There is a document on /TR which has been superseded by something that's non-obvious or perhaps not even a W3C document (e.g. IETF has taken over work in this area). The process in the process should be proceeded with to ensure correct process procedure.

Case 1 is the subject of that issue/pull-request: (no, the formal supersedes process is pointless and un-needed here, and that pull will clarify it.)
Case 3 is covered by the existing full "do the AC and Director and everyone agree?" process.

But the process for case 3 might be much too heavy for case 2. Do we really need to ask the AC and Director to approve labeling BadThings 1.7 as no longer current and superseded by BadThings 2.0? Could we perhaps allow the WG to decide when that label would be helpful to readers of BadThings 1.7 (that if you're coming in new and without any reason to stay at 1.7, we think you ought to move to 2.0)?

What are the edges of that authority? That the specs were issued by the same WG and have (except for version number) the same name?

**Comment by frivoal** [comment]
I think it can be valid for 1.7 and 2.0 to both continue to exist and be maintained (and therefore for 1.7 not to be declared as superseded), for instance if 2.0 has an expanded scope, a some users of the specification count on it having a fixed scope (and be maintained). This is generally not terribly important for the web itself (https://www.w3.org/2001/tag/doc/evergreen-web/), but other industries linking into our specifications sometimes care. If we don't maintain 1.7, marking it as superseded seems the right thing to do, since 2.0 has all the bug fixes in addition to having all the new features.

Wwho gets to make the call that we will, or will not, maintain 1.7? That sort of feels like an AC decision, but at the same time, if a WG can't/won't do the actual maintenance, maintaining the fiction that 1.7 isn't superseded isn't really helping anyone.

**Comment by dwsinger** [comment]
> I think it can be valid for 1.7 and 2.0 to both continue to exist and be maintained 

right.  it is a choice. SMIL1.0 was used much more than SMIL2.0, for example.

>If we don't maintain 1.7, marking it as superseded seems the right thing to do, since 2.0 has all the bug fixes in addition to having all the new features.

Right, the normal (and uncontroversial) case is that 2.0 is the best thing to read if you are coming in fresh.

> Wwho gets to make the call that we will, or will not, maintain 1.7? That sort of feels like an AC decision, but at the same time, if a WG can't/won't do the actual maintenance, maintaining the fiction that 1.7 isn't superseded isn't really helping anyone.

I almost wonder whether the AC should be involved if the WG has done something that 1.7 _is_ still a viable spec.  That's the odder case.

**Comment by dwsinger** [comment]
So, I propose: In the case of two specifications issued by the same Working Group, where the name of the specifications differs only in the version number, the working group alone _may_ decide that the later supersedes the earlier; neither AC nor formal Director Review are needed.

**Comment by chaals** [comment]
David Singer <notifications@github.com> wrote:

> So, I propose: In the case of two specifications issued by the same  
> Working Group, where the name of the specifications differs >only in the  
> version number, the working group alone may decide that the later  
> supersedes the earlier; neither AC nor formal >Director Review are  
> needed.

This makes a lot of sense.

-- 
Using Opera's mail client: http://www.opera.com/mail/

**Comment by frivoal** [comment]
The Process doesn't have a well defined notion of version number (this might be something we want to fix as well, but for now it doesn't). So I'd suggest tweaking your proposal not to rely strictly on it. With a couple of extra tweaks, maybe something like:

> In the case of two <del>specifications</del><ins>Recommendations</ins> issued by the same Working Group, where the name of the specifications clearly indicates that one succeeds the other (such as differing only in the version number), the Working Group alone may decide <ins>by consensus</ins> that the later supersedes the earlier; neither AC nor formal Director Review are needed.

**Comment by chaals** [comment]
Hmm. In order to publish a new Recommendation, there is already a review. The extra work to note that another spec will be superseded, as part of that review, is trivial - about as lightweight as you can get.

So I am not sure we are solving a problem by adding this extra piece of process machinery.

**Comment by dwsinger** [comment]
@chaals this is roughly what we're asking; in cases where it's obvious — like the WG producing and sending to PR and Rec an obvious new version — we surely don't need the full Director and AC review we use today.  I'm not sure it even needs saying in AC review of the new Rec. I'd like the WG to be able to say that JSON LD 1.1 supersedes JSON LD 1.0, as indeed the opposite — that we continue to Recommend the older spec. in addition to the newer one — is the odder case.

**Comment by jeffjaffe** [comment]
I believe the point (in David's example) is that when the WG takes JSON LD 1.1 to the Director/AC for approval as REC, by merely "saying" that it supersedes 1.0 they are getting Director/AC approval with no extra work.  So the process machinery does not buy you anything.

**Comment by chaals** [comment]
+1 to @jeffjaffe . Supporting the use case mentioned (the "obvious one") basically requires a sentence in the transition request noting that one document supersedes another, the team to ensure that is in the AC review request, and the editorial work to prepare for that to be implemented, with no new process required.

**Comment by dwsinger** [comment]
It's possible, indeed that a sentence that the request to supersede may be combined with the PR progression of the superseding document, would suffice as well. But that would the case where the progression happened without this sentence, alas, which might be quite a bit of cleanup (both of history, and for WGs that forget to ask this on their PR progressions).

So, two choices (so far):

> In the case of two Recommendations issued by the same Working Group, where the name of the specifications clearly indicates that one succeeds the other (such as differing only in the version number), the Working Group alone may decide by consensus that the later supersedes the earlier; neither AC nor formal Director Review are needed.

or

> The request to mark a Recommendation as superseded may be combined with the PR progression request of the superseding document.

**Comment by dwsinger** [comment]
Actually we can combine this: make the future simpler and enable cleanup of the past.

> The request to mark a Recommendation as superseded may be combined with the PR progression request of the superseding document. For existing Recommendations issued by the same Working Group, where the name of the specifications clearly indicates that one succeeds the other (such as differing only in the version number), the Working Group alone may decide by consensus that the later supersedes the earlier; neither AC nor formal Director Review are needed.

**Comment by dwsinger** [comment]
pointed out that the AC should nonetheless know and be able to object:

> The request to mark a Recommendation as superseded may be combined with the PR progression request of the superseding document. For existing Recommendations issued by the same Working Group, where the name of the specifications clearly indicates that one succeeds the other (such as differing only in the version number), the Working Group may propose by consensus, with notification to the AC, that the later supersedes the earlier; neither AC nor formal Director Review are needed in the absence of objection.

**Comment by dwsinger** [comment]
still some doubt over whether we need the second part...

**Comment by dwsinger** [comment]
and since the first part is practice, does it need mention? close?

**Comment by jeffjaffe** [comment]
+1 to closing
