### ISSUE TITLE
W3C Council should be limited to one vote per member organization

### ISSUE THREAD

**Issue by dwsinger** [w3c/w3process#327]
forked from #293 

should we require that there is only one vote per member on the council, in the case that a member has more than one representative on the Council? (This might happen due to AB+TAG or in the relaxation of TAG rules over change of affiliation)?

There are cases where a member has 3 votes (when the relaxed TAG rule means that they temporarily have two TAG members, and they also have an AB member).

**Comment by fantasai** [comment]
If it comes down to a formal vote, yeah, I think it makes sense to have this restriction.

**Comment by dwsinger** [comment]
Change 
>Decision of the W3C Council should be unanimous. If despite careful deliberation the W3C Council is unable to reach consensus, the Chair of the W3C Council may instead resort to voting. In that case, the decision is made by simple majority, with the Chair of the W3C Council breaking ties.

to

Decision of the W3C Council should be unanimous. If despite careful deliberation the W3C Council is unable to reach consensus, the Chair of the W3C Council may instead resort to voting. In that case, the decision is made by simple majority, with the Chair of the W3C Council breaking ties. A W3C member that has more than one representative on the W3C Council (e.g. because they have both a TAG and AB representative) has only one vote.

**Comment by cwilso** [comment]
If there is a consensus that multiple Council reps with the same affiliation should not have separate votes (FWIW, I disagree, as both TAG and AB members are supposed to be serving independent of their affiliation, but my disagreement is not an Objection) - the process should simply prevent such same-affiliated members from getting selected to the Council, because otherwise their votes will always be nullified.

**Comment by fantasai** [comment]
@cwilso The Council largely works by consensus, this is just about formal votes. It doesn't mean that both members can't have a say in what's happening. (Note, we apply the same rules to WG participation.) Wrt “because otherwise their votes will always be nullified”, they don't get nullified unless the two reps from the same company can't agree on which way to vote.

**Comment by dwsinger** [comment]
I think we need to be super-careful about the appearances here. I really hope that voting is rare on the council, but if there is dissent and a vote is needed, I fear we need to be scrupulous to avoid even a whiff of anything. I completely agree with what Chris says about the participants being individual experts, but an organization that pays their salary may be behind them, and we can't ignore that that may have some influence (as well as normal loyalty to one's employer).

**Comment by jeffjaffe** [comment]
I agree that we need to be careful about appearances so I support limiting each organization to a maximum of one vote per council.

**Comment by frivoal** [comment]
I think it is fine for two members of the council to come from the same org, and it is fine for both these people to express opinions. There's not particular need to require them to speak with one voice. In the end, we hope the council will come to consensus, and when everybody agrees, it doesn't particularly matters how many people are in agreement: it's all of them. If we fail to have a consensus, need to vote, and these two people from the same organization vote in different ways, that's also not really a problem. It's unfortunate when any two members disagree, but there's nothing particularly concerning about them coming from the same company.

The only problematic case is when we lack consensus, need to have a vote, and they both vote the same way. If we end up on one side of a threshold when counting both, but on the other side had we counted only one, there could be an appearance that one company is having excessive influence.

So:
> If the council needs to resort to a vote, and if two members of the council who share the same affiliation cast an identical ballot, then for the purposes of evaluating whether a majority has been reached, their ballots count as a one vote, not two.

**Comment by frivoal** [comment]
This is included in https://www.w3.org/Consortium/Process/Drafts/director-free/#council-deliberations
