### ISSUE TITLE
Re-craft and re-insert the 60-day delay between charter review and Call for Participation

### ISSUE THREAD

**Issue by dwsinger** [w3c/w3process#33]
Transferred from https://www.w3.org/community/w3process/track/issues/181
State: Raised

**Comment by dwsinger** [comment]
VF to propose?

**Comment by vfournier17** [comment]
We want to revisit the previously-discussed 60-day time period between Charter Review and Call for Participation, during which a prospective member could review the proposed charter and conduct its patent analysis. This issue will need to be coordinated with PSIG.  We should revisit the 60-day language that PSIG and the Process CG had previously worked on together, and which was dropped from the Process Document 2017 right before it was published.  Thanks.

**Comment by vfournier17** [comment]
We're proposing to add the following at the end of Section 5.2.3 (Advisory Committee Review of a WG or IG Charter):
"With respect to any new or substantively modified Working Group or Interest Group, an Advisory Committee representative may request that there be at least 60 days between (a) the date on which the Director issues a Call for Review for such a group, and (b) the date on which the Director issues a Call for Participation for such a group."

**Comment by chaals** [comment]
I think you sahould clarify when and how such a request can be made, and that the Director must, on request by an AC member in such conditions, ensure the gap.

If that's done reasonably I think I can live with this.

**Comment by vfournier17** [comment]
That seems reasonable.  Let me see what I can come up with.


Best regards,

Virginia Fournier
Senior Standards Counsel
 Apple Inc.
☏ 669-227-9595
✉︎ vmf@apple.com <mailto:vmf@apple.com>






On Aug 13, 2017, at 8:51 AM, chaals <notifications@github.com> wrote:

I think you sahould clarify when and how such a request can be made, and that the Director must, on request by an AC member in such conditions, ensure the gap.

If that's done reasonably I think I can live with this.

**Comment by dwsinger** [comment]
Here's a try for you:

With respect to any new or substantively modified Working Group or Interest Group charter, on the request of any Advisory Committee representative made before the close of the charter review, the Director will ensure that there are at least 60 days between (a) the date on which the Director issues a Call for Review for such a group, and (b) the date on which the Director issues a Call for Participation for such a group.

**Comment by vfournier17** [comment]
what does "charter review" mean?

**Comment by vfournier17** [comment]
Here's the new language, to be added to the end of Section 5.2.3:

“With respect to any new or substantively modified Working Group or Interest Group charter, any Advisory Committee representative may request that there be at least 60 days between (a) the date on which the Director issues a Call for Review for such a group, and (b) the date on which the Director issues a Call for Participation for such a group (an “Extended Review Period”).  

A request for an Extended Review Period must be sent to the Director by email and, upon receipt of such request, the Director must ensure that there are 60 days between the Call for Review and the Call for Participation.  The request for an Extended Review Period must be made prior to the end of the Advisory Committee review of such charter.”

**Comment by michaelchampion** [comment]
I would appreciate understanding the rationale here better.  If I recall the previous discussion, the idea is to give members sufficient time *if they need it* to check patent portfolios against charter scopes and decide whether to exclude any patents upon joining a WG.  Is that correct?  If not, why is this change needed?

If I have the rationale correct, why should this change apply to IGs (which don't trigger patent commitments) as well as WGs?

**Comment by vfournier17** [comment]
Yes, that's the correct rationale.  If we don't need the reference to IGs, we can remove it.  But I'm wondering, then, why we do AC reviews of IG charters?

**Comment by dwsinger** [comment]
We do AC review of IG charters to make sure that it's something we want the W3C to be spending resources on; focused, appropriate, etc.  Indeed, maybe here we don't need the mention, as it's purely IPR

**Comment by dwsinger** [comment]
With respect to any new or substantively modified Working Group charter, any Advisory Committee representative may request that there be at least 60 days between (a) the date on which the Director issues a Call for Review for such a group, and (b) the date on which the Director issues a Call for Participation for such a group (an “Extended Review Period”).

A request for an Extended Review Period must be sent to the Director by email and, upon receipt of such request, the Director must ensure that there are 60 days between the Call for Review and the Call for Participation. The request for an Extended Review Period must be made prior to the end of the Advisory Committee review of such charter.

**Comment by wseltzer** [comment]
Agree it's only WG charters

**Comment by jeffjaffe** [comment]
email should be sent to a canonical place but not the Director.

**Comment by dwsinger** [comment]
The current director is not known for reading email. We suggest that the request must be made as part of AC comments in the charter review form.

**Comment by vfournier17** [comment]
That seems fine. 

Virginia Fournier
Sent from my iPhone
Please excuse iTypos

**Comment by chaals** [comment]
Note that I had understood this only to be about charters where we're adding work that has been ongoing elsewhere, so the wording I merged does that. If you think we should have allowed extended review for any charter, please reopen the issue. Making the change to allow this for all charters is pretty trivial.

**Comment by dwsinger** [comment]
I think the intent as offered was to offer it for all charters, yes. Does anyone either disagree or object?

**Comment by chaals** [comment]
I'll make a PR. Feel free to merge it when you decide we have consensus. I'm moderately opposed, but not enough to really object. I would not like to see routine requests to delay small charters, but understand that reviewing the scope of e.g. CSS or Web Platform might be quite a lot of work.

**Comment by vfournier17** [comment]
why did my post from 45 mins ago not show up here?

**Comment by vfournier17** [comment]
Here is our proposed text:

"With respect to any new or substantively modified Working Group charter, any Advisory Committee representative may request that there be at least 60 days between (a) the Call for Review and (b) the Call for Participation for such a group (an “Extended Review Period”).

A request for an Extended Review Period must be submitted with a Member’s comments in response to the Call for Review.  Upon receipt of such request, the Director must ensure that there are 60 days between the Call for Review and the Call for Participation. The request for an Extended Review Period must be made prior to the end of the Call for Review.

**Comment by chaals** [comment]
Please comment on the [actual text in the Editor's draft document](https://w3c.github.io/w3process/#CharterReview):

> In an Advisory Committee review of a charter _**that continues work on a Working Draft (WD) published under any other Charter,**_ any Advisory Committee Member may request an "extended review". If this occurs, the Director must not issue a Call for Participation for the proposed group until at least 60 days after announcing the Call for Review.

plus Pull Request #74 which deletes the restriction to only charters picking up existing work - the text emphasised above. 

Note that the reason the analagous proposal was not put into the last version of Process is because it was explicitly rejected by the AC, so it is possible that they will again reject it, although it is also possible that they will change their minds this time.

**Comment by dwsinger** [comment]
The integrated text bears little resemblance to the text agreed in the CG. I would ask all participants, including the editor, to bring their opinions to the discussion so that we can arrive at consensus text. In this case, we did.

The AC rejected an automatic 60-day interval. This is, in contrast, on-request, and our hope is that such requests will be rare. If that turns out not to be the case, and this becomes a common operational problem, we may have to think again. And yes, the consensus text, as it stood when the editor was asked to integrate it, was general for any charter with new work (not just adopted work).

**Comment by dwsinger** [comment]
Specifically, I as chair request all members of the group, including the 'team contact' (CEO) and editor and myself, to discuss text until we reach consensus, either in the issues, or in the pull requests, or in our monthly calls. So no, in this case, do NOT comment on the editor's draft as it does not correspond to the current working consensus. Chaals -- anyone, indeed -- if you would like to change the text, please enter the discussion with rationale and proposed changes on the current working consensus.

We reached consensus on text that was to be integrated, in this case. Further discussion needs to use that text as a basis for discussion, or we'll all go crazy.

**Comment by chaals** [comment]
I apologise. I apparently misunderstood the outcome of the last meeting to include a directive for the editor to incorporate the sense of what appeared to be resolved. Based on that misunderstanding I failed to clarify in advance that I do not agree to the specific text that is proposed above, although I will not bother with a formal objection.

My main objection to the specific text proposed by @vfournier17 is that it is unnecessarily repetitive. 

A minor objection is that the process document does not use the style "some time requirement between (a) one event and (b) another event", but constructions like " event a must be at least time constraint before (or after) event b", and maintaining a similar editorial style is helpful.

Please @dwsinger clarify whether the text is still under discussion, or whether I should simply incorporate the text @vfournier17 proposed most recently.

**Comment by dwsinger** [comment]
Hi Chaals, thanks

my goal is to have visible consensus on a text that's good enough to merge, and then you merge it with minimal changes (editorial, punctuation, maybe the odd word change, and so on).

I think we're fine with having proposals to improve text, and yes, I think shorter is often better. But we do need to see it, because there are nuances (and this text in particular is trying to provide a conceptual link without actually mentioning it, so the nuances are subtle).

I doubt that re-organizing a sentence to be as you say is controversial, but it's enough of a change to have people know you've done it.

The text of the process is, from a formal point of view, under discussion until voting starts at the AC level. But we hope it's decreasing discussion and increasing convergence.

I think at this point there are two choices (a) integrate the consensus text from above (which I will reproduce in this comment) and open discussion on simplification or (b) open the discussion first. As editor, you are always at liberty to say "I'd prefer not to integrate this as proposed, but would prefer to simplify X to Y" and so on. (Either of these follow a revert).

I think Virginia's comment above has the text, though the last sentence is probably superfluous since one cannot make a request in a ballot after it has closed:

"With respect to any new or substantively modified Working Group charter, any Advisory Committee representative may request that there be at least 60 days between (a) the Call for Review and (b) the Call for Participation for such a group (an “Extended Review Period”).

A request for an Extended Review Period must be submitted with a Member’s comments in response to the Call for Review. Upon receipt of such request, the Director must ensure that there are 60 days between the Call for Review and the Call for Participation."

and we probably don't need to say "The request for an Extended Review Period must be made prior to the end of the Call for Review."

Offering a slightly shortened version, and taking into account the style point about periods you made above, we could see if the following is OK:

"With respect to any new or substantively modified Working Group charter, any Advisory Committee representative may request that there be at least 60 days between (a) the Call for Review and (b) the Call for Participation for such a group (an “Extended Review Period”).

Such a request must be submitted with a Member’s comments in response to the Call for Review. Upon receipt of any such request, the Director must ensure that the Call for Participation occurs at least 60 days after the Call for Review."

Process CG members, how does this sound?

**Comment by jeffjaffe** [comment]
I agree with David.  And the second version indeed appears to be more succinct with no loss of information.

**Comment by vfournier17** [comment]
Dave’s updated version looks fine to me.  You can take out the definition "(an “Extended Review Period”)” because now it is not used again.


On Sep 7, 2017, at 8:11 AM, jeffjaffe <notifications@github.com> wrote:

I agree with David. And the second version indeed appears to be more succinct with no loss of information.

**Comment by chaals** [comment]
I think we can readily delete

> that there be at least 60 days between (a) the Call for Review and (b) the Call for Participation for such a group

From the first para, and just say "ask for an extended review". The second paragraph defines exactly what th result of a request is, so we don't need to make a formal definition of the term, and its normal english meaning is clear and in line with the statement.

**Comment by dwsinger** [comment]
This is a taste question; do we prefer to state the interval twice, or define a new term and use it to mean the interval? I don't mind. We don't like repetitive repetitions of repeated material, and we try not to do NewTermDefinification...  So I am happy to let the editor's taste pick the least distasteful.

**Comment by dwsinger** [comment]
which would be something like, putting the first sentence into the preferred interval terms:

"With respect to any new or substantively modified Working Group charter, any Advisory Committee representative may request that the Call for Participation for that group occurs at least 60 days after the Call for Review of the charter (an “Extended Review Period”).

Such a request must be submitted with a Member’s comments in response to the Call for Review. Upon receipt of any such request, the Director must ensure that there is an Extended Review Period."

**Comment by chaals** [comment]
My taste would be to say that you can request an "extended review period" (as a plain english term, much like saying "can I please have a deadline extension because the dog ate my homework), and then having the specific nature of what is granted be in the second para as you had it before (Yes, you will get until Monday morning).

**Comment by dwsinger** [comment]
trying again!

With respect to any new or substantively modified Working Group charter, any Advisory Committee representative may request an extended review period.

Such a request must be submitted with a Member’s comments in response to the Call for Review. Upon receipt of any such request, the Director must ensure that the Call for Participation in the working group occurs at least 60 days after the Call for Review of the charter.

**Comment by chaals** [comment]
Since "Advisory Committee Review" is already a defined thing, it makes sense to simplify the first couple of sentences, something like

"As part of the AC review of a charter, an AC rep may request an extended review period in their review comments".

**Comment by dwsinger** [comment]
feel free to word-smith to match terminology (IMHO)

**Comment by vfournier17** [comment]
Ok, so I think this is where we are:

As part of the Advisory Committee review of any new or substantively modified Working Group charter, any Advisory Committee representative may request an extended review period.

Such a request must be submitted with a Member’s comments in response to the Call for Review. Upon receipt of any such request, the Director must ensure that the Call for Participation for the Working Group occurs at least 60 days after the Call for Review of the charter.

**Comment by chaals** [comment]
Believe that #93 fixed this, so closing
