### ISSUE TITLE
Survivability of registries

### ISSUE THREAD

**Issue by mnot** [w3c/w3process#330]
One of the benefits of the IETF/IANA split is that the registries will survive if the defining organisation were to become defunct for some reason. 

Just something to think about.

**Comment by fantasai** [comment]
The current drafts of a registry process include provisions for designating a custodian other than the originating WG, so I think that covers it, no?

(As for if W3C itself becomes defunct, we can at that time adopt a provision mass-reassigning custodianship to another organization. Short of a massive global catastrophe, in which case this is unlikely to be a serious priority for anyone, we should have the time to do that.)

**Comment by frivoal** [comment]
Regardless of how we set things up and who we decide is the organization that will host the files, there is a possibility that that organization might go out of business. W3C isn't particularly likely to go out of business, but it could happen. The same is true of any organization we could delegate the hosting to.

Specs (and registries, as currently proposed) are files/documents, not things that involve server side components. Even if W3C was not only to go out of business, but to go out of business suddenly, with no time to prepare, and all the publications went offline without prior notice, we'd still have a fully restorable copy at archive.org.

In the long run, all human creations suffer from the passage of time. In the very long run, we can't do anything against entropy and heat death of the universe. But within reasonable time scales and reasonable risk prevention, I think we're fine.

**Comment by dwsinger** [comment]
I think there are several questions:
1. survivability of the registry publication itself. We want it hosted in a way that the W3C can ensure it can continue to publish.
1. survivability of the registry maintenance site. We want to be sure we don't lose the backing site (e.g. Github repo).
1. survivability of the management process; e.g. if acceptance of entries is defined as a WG decision, what happens after the WG closes? Can new entries be added?

**Comment by frivoal** [comment]
The overall PR for registries (https://github.com/w3c/w3process/pull/335) has been merged. In the approach we adopted, registries are technical report, making their survivability identical to that of specifications. To me, as per https://github.com/w3c/w3process/issues/330#issuecomment-545757916, this means we don't have a problem, so I'd like to close this issue. @mnot is that OK with you?

**Comment by frivoal** [comment]
Agenda+ to suggest closing

**Comment by samuelweiler** [comment]
Noting that I missed the original discussion: why aren't we just asking IANA to host these registries in the first place?  They know how to do it.  It works...

That said, I support closing this issue.

**Comment by mnot** [comment]
My goal was to make sure it was considered; it seems like it has been. So if people are comfortable with that, I support closing.
