### ISSUE TITLE
Please reconsider director-free formal objection handling

### ISSUE THREAD

**Issue by michaelchampion** [w3c/w3process#331]
I generally agree with the goal of getting the Director out of the loop on routine business.  I also generally agree with the AB/CG thinking on TAG nominations and PAGs.  But I don't think the proposed Council is a viable way to resolve formal objections.

My concerns include:
.
22 is too large a group to really work on something as complex and nuanced as most unresolved formal objections are.  That will mean in practice that  FO resolution will be an exercise in factional politics, not the kind of neutral, detailed analysis Tim did.

There are lots of devils in the details, such as about who has to recuse themselves if there is a financial (or ideological?) conflict of interest, how to handle multiple TAG/AB members with the same employer. It will be very time consuming, at a time the AB has lots of other stuff on its plate, to resolve these and develop the guidelines about fairness, transparency, etc.

The voting system used to select AB and TAG members does a fine job of increasing diversity, but that diversity makes consensus all the harder to achieve.  So I disagree with the "Legitimate, with broad expertise to cover everything W3C" bullet point.  Under STV, the AB is a "legitimate" set of advocates for a diverse set of viewpoints, but not a legitimately neutral body with the expertise to adjudicate FOs.

I could live with a *supermajority* voting rule in the event of no consensus, but not a simple majority.  But that allows confusing outcomes if a simple majority but not a supermajority support some proposed resolution. 

The AB quite sensibly determined that finding another person to replace Tim as Benevolent Director for Life is probably not feasible.  But it didn't explore the idea finding a much more narrowly scoped Adjudicating / Mediating / Technical Director for the handful of Director roles that really can't be passed on to the team or AC,  such as FO resolution. 

I don't have strong feelings about how such a Technical Director would be chosen.  Perhaps an appointment/hire by the Board of Directors, similar to how the CEO will presumably be chosen.  Or perhaps elected by the membership, with candidates vetted by some sort of nomination committee?  Or maybe the "Technical Director" could be similar to the IETF IAB, chosen by a NomCom and verified by a supermajority of the AC?

**Comment by fantasai** [comment]
My understanding is that the AB has not yet concluded on whether to move to a Director-free Process or to find a new Director, but to develop the Director-free Process so that such a decision can be taken with full information about what the two options would look like. Therefore, considering a new Director is a bit out-of-scope for the Director-free project.

As for convening another body to handle FOs, it seems that at least half the AB and [also formally the full TAG](https://lists.w3.org/Archives/Public/public-w3process/2019Sep/0029.html) agree that the deciding body should be the TAG + AB, so I suspect it would not make sense for us to redraft the proposal with some other body in place of the Council. :)

**Comment by jeffjaffe** [comment]
Thanks, @michaelchampion for these thoughts.  I do agree with you that the Council is a bit bulky for handling formal objections.  But I'm struggling with the alternatives.

A primary reason, imho, that the Advisory Board is exploring the director-free path is skepticism that we could find a replacement Director whose decisions could be widely respected.  Your proposal that we find a Technical Director just for settling formal objections (but without the other powers of the Director) would similarly be difficult for the same reason.  I think it would be even harder to find a superlative individual to be a limited TD.  If we could find someone really great for that role - they would likely also want other authority currently vested in the Director.

**Comment by michaelchampion** [comment]
Well, there are currently 213,962 people on LinkedIn with the title Technical Director, it's not self-evident that none of them are superlative individuals with a deep understanding of the web but without aspirations to be the BDFL of W3C.

The W3C Director hasn't had much actual authority for the last 10 years or so.  Tim, and now Ralph's, power comes from the ability to mediate disagreements in a technically informed way and find an outcome that people of good-will should be able to live with, and which is consistent with fundamental principles of the web.  One challenge they face, e.g. in the EME kerfuffle, is there is no wide consensus on the "fundamental principles of the web."  If they were written down and had general consensus across the membership -- perhaps enshrined in the member agreement -- the Technical Director's job wouldn't entail either having internalized TimBL's worldview and ask "What would TimBL say?" (which is the current  mode of operation AFAIK) or have enough personal gravitas to make an opinion stick.

My larger point isn't to argue for a Technical Director but to re-think the question of how to resolve formal objections.  I could imagine something like the IAB https://en.wikipedia.org/wiki/Internet_Architecture_Board, a small number of people chosen for their expertise rather than popularity.   I could imagine a subset of the TAG+AB+W3M that is willing to commit the time needed and to follow some agreed-upon principles rather than making them up on the fly.  I can imagine the Board of Directors hiring a Technical Director (for a limited term?). I might possibly agree to W3M selecting a Technical Director, but definitely for a limited term

And whatever the selection mechanism, there should be an approval ballot by the AC to ensure there is *broad* support for the individuals as well as the process.   Not to harp on my favorite issue #60 :-), but Meek STV has proven to be a useful way to get strong, diverse viewpoints in front of the CEO/Director, but it hasn't proven to be a good way of selecting people who can come to a consensus on hard questions.

**Comment by mnot** [comment]
Since the IAB has been invoked a few times, [this](https://www.iab.org/appeals/) and the link to RFC2026 there might be useful reading.

The IAB does have an appeal function, but it's part of a much larger system of appeal handling / dispute resolution; first you appeal with the WG chair, then the AD, then the IESG, then the IAB.

IAB also isn't necessarily small; right now we're 13 voting members, with 5 additional liaison / ex-officio participants.

**Comment by cwilso** [comment]
I think this issue should also suffice to cover "The director-free FO handling should not be handled by an STV-elected body."

**Comment by dwsinger** [comment]
The counter-argument to "STV selects for diversity, whereas what we want is moderate centrism" is that it is precisely the diversity that gives decisions weight: we have people from X and Y and Z, who could represent many aspects of the question, who approached it from quite different angles, and yet they decided. 

The worry is not the legitimacy of such a decision; it's the difficulty of reaching a decision.

**Comment by frivoal** [comment]
After considerable debate, the AB has resolved, on the basis of recent experience with the prototype council, to continue with this direction.
