### ISSUE TITLE
Decisions

### ISSUE THREAD

**Issue by jeffjaffe** [w3c/w3process#338]
Section 3.3 of the Process Document provides the location for reaching decisions: "Decisions may be made during meetings (face-to-face or distributed) as well as through email."  Should we allow other venues such as in github threads?

**Comment by mnot** [comment]
FWIW in the IETF, we confirm consensus of closing issues on the WG mailing list, since our process requires us to call consensus on the list. It's cumbersome, but is good for assuring everyone is on the same page -- some people don't follow Github.

Perhaps the Process could say something like "Groups MAY designate another venue for forming consensus, as long as that change itself has consensus."

**Comment by fantasai** [comment]
We also need to require that the venue be a) accessible to all members and b) archived on w3.org

**Comment by dwsinger** [comment]
It's not even clear if that is an exhaustive list (these are the only places you can make decisions) or an explicit call-out of one possibility (yes, you are allowed to make decisions in X, among other places, in case you wondered).

we should probably re-write as a set of conditions for making a valid decision (that all stakeholders are made aware, that they have time, that the question, responses, and decision are archived and recorded, and so on)?

**Comment by dwsinger** [comment]
I suspect that this is awaiting a volunteer. It's also associated with the (undocumented) "where are you allowed to do w3c business and discussions?" (email, IRC, CVS, Github, Slack, Converse…?)

**Comment by jeffjaffe** [comment]
I suggest we defer to P2021.

**Comment by dwsinger** [comment]
> I suggest we defer to P2021.

It's not assigned to P2020, which means it's now in the indefinite future. You want it addressed (a) in 2021 or (b) sometime in the indefinite future?

see also #322

**Comment by jeffjaffe** [comment]
@dwsinger This is not urgent.  If P2021 is a quick spin edit-pass, then this can be deferred further.

**Comment by chaals** [comment]
Perhaps as part of where they can be recorded, we could actually describe how you know that there has been a Working Group decision.

**Comment by dwsinger** [comment]
@chaals who is "you"? I'm not sure if you are saying more than I say about [valid decisions in my comment](https://github.com/w3c/w3process/issues/338#issuecomment-550546663)

**Comment by chaals** [comment]
@dwsinger the additional piece is that there is no clear definition of how to know that there is a Working Group decision. It is meant to be done by consensus, unless the chair calls a vote, and there's some nice stuff about how consensus isn't exactly unanimity.

I think the answer is probably something like "the chair declares in a written record there is a decision", and the question of where that record can be is the one you have asked. But now it's just convention / "obvious" that there has to be a written record, and that if the chair says it is so they somehow have the authority to make that true.

**Comment by dwsinger** [comment]
This also links to questions of Minutes, as raised in #511 ?

**Comment by frivoal** [comment]
Right. I think https://github.com/w3c/w3process/pull/512 would actually solve this.

**Comment by frivoal** [comment]
I believe this has now been solved by merging https://github.com/w3c/w3process/pull/436 and https://github.com/w3c/w3process/pull/512. I suggest closing. Agenda+ to make sure we don't miss it (If @dwsinger as chair thinks this can be closed without discussion on the call, fine by me).

**Comment by jeffjaffe** [comment]
> I believe this has now been solved by merging #436 and #512. I suggest closing.

Could you clarify how #436 (tooling) and #512 (minutes) addresses #338 (venues for decisions)?

**Comment by frivoal** [comment]
#512 (minutes) clarifies that decisions must be recorded in minutes. #426 (tooling) says (with a must) what kind of archival/retention is expected of minutes, and is explicit that it's not limited to email. Preexisting text (such as https://www.w3.org/Consortium/Process/Drafts/#decisions) say how decisions are arrived to. So all in all, if you make a decision according to these sections, record it in your minutes, and have your minutes published and archived correctly, you're good.

However, I now think you're right that we're not actually done. I think that what I just referred to would be enough, but the sentence you quoted ("Decisions may be made during meetings (face-to-face or distributed) as well as through email.") overconstrains the problem. Maybe we should just delete it.

**Comment by jeffjaffe** [comment]
If #512 clarifies that decisions must be recorded in minutes, does that mean that decisions made in GH are not decisions until there is actually some meeting in which the decision is recorded?

Or are you saying that #426 defines minutes in a way that a GH decision can be considered a "minuted recording"?

**Comment by fantasai** [comment]
@jeffjaffe #512 clarifies that decisions made _during meetings_ must be recorded in the minutes; it doesn't say anything about decisions made outside of meetings. Tooling #436 says that all decisions (regardless of whether in the minutes or not) must be archived by W3C for future reference.

**Comment by frivoal** [comment]
Just added a pull request (#519) to fix up the original offending sentence, rather than delete it as I earlier suggested. I think that ought to make things clear.
