### ISSUE TITLE
Decoupling Notes and REC track

### ISSUE THREAD

**Issue by frivoal** [w3c/w3process#342]
This issue is not about Notes when they are used as a retirement path for abandoned REC Track documents. I'm talking about Notes that are meant from the start to be Notes.

Notes can be updated in place, so they don't necessarily need to go through a WD phase first. But the process does allow that. However, the first such Working Draft would be a FPWD. This has patent implications, which are uncessary for a document not meant to try and become a REC, but still technically binding.

We end up in the strange situation where we have to ask lawyers to review a draft to check if they want to exclude any patent when it becomes a REC, while the status section says that it won't become a REC.

We should remove that work mode (and update the Process accordingly), possibly by simply publishing preliminary versions of Notes as Notes (rather than as WDs), or by creating a special maturity that signals the lack of maturity ("Preliminary Note"? "Draft Note?").

**Comment by dwsinger** [comment]
WD means Working Draft; can we have working draft of something other than a Rec.? If not, we need a term for drafts of Notes, and I suggest … "Note Draft"

**Comment by frivoal** [comment]
> can we have working draft of something other than a Rec.

Currently, yes, we can have a Working Draft of a Note, and I think it's weird, since by virtue of being a Working Draft it invokes the patent policy, even if we already know it will not be turned into a publication where the patent policy actually matters. Many groups publish Notes as Notes from the get go, and skip the draft phase, but some (e.g. i18n) do use WD->Note.

> If not, we need a term for drafts of Notes, and I suggest … "Note Draft"

+ 1. Or  maybe "Draft Note" rather than "Note Draft".

**Comment by hober** [comment]
"Draft Note" sounds good to me.

**Comment by dwsinger** [comment]
It's minor, but I tried to leave the word "Draft" as the second, to match Working (of a rec.) Draft.

But actually, what we ought to do is call them Draft Recommendations, which would be MUCH clearer.

Draft
Candidate
Proposed
[Published]
all + Recommendation

**Comment by frivoal** [comment]
Currently, two bridges exist between the Note track and the REC track:
* FPWD/WD -> NOTE (used for drafting notes before officially issuing them as NOTEs)
* FPWD/WD/CR/PR -> NOTE (used for retiring REC track documents when not rescinding)

This is already a source of complications and messiness today:
* The drafting stage of Notes is only available to WGs, since IGs cannot produce Working Drafts (or any other REC-track status, which is protected by the Patent Policy)
* Publishing the FPWD triggers a call for exclusions, which is useless for documents that aren't meant to ever become REC. (We are currently required to ask something that boils down to: "when this document which we plan not to publish as CR is published as CR, will you be willing to issue a patent license for it?")
* There's nothing in the Process banning a Note-which-is-a-discontinued-CR from being evolved as a Note prior to being restored on the REC track, but the how the patent policy applies in such cases is unclear. Nor is it clear whether that note should be counted as a WD for the purpose of members joining of leaving the group while it is a Note.

As we try to extend the Note track (1) to allow the AB & TAG to publish notes and (2) to add an "AC approved" stage, these messy interactions with the REC track complicate defining the Process. Keeping the whole thing vague and ambiguous and hoping we just don't run into issues doesn't sound like a very good approach. Defining what happens in various odd cases that nobody ever wants to use doesn't seem useful, but neither does addding a bunch of ad-hoc prohibitions to rule out the odd cases while growing the system that makes these cases possible in the first place.

![1track](https://user-images.githubusercontent.com/113268/107492128-66153400-6bcf-11eb-96d7-97442917d506.jpeg)


Everything gets much simpler if draft Notes can be their own Draft Notes status, and if abandoned REC-track documents get their own status, distinct from Notes. All these nonsensical interactions just disappear.

![2tracks](https://user-images.githubusercontent.com/113268/107491267-43365000-6bce-11eb-9cb2-b49264ee66c5.jpeg)



The question was, is it worth making the system more complex and the process longer for that. I think complexity is not a matter of how many words, or even how many statuses, but of how many interactions, how many transitions, how many paths in the system. By isolating things that have no need to interact, we make the whole thing simpler.

Another way to look at the problem is that when I tried to write an edit allowing the AB & TAG to publish notes and to introduce an "AC approved" stage without disentangling the two tracks first, I kept on confusing myself and on rewriting things because they didn't quite makes sense.

**Comment by michael-n-cooper** [comment]
+1 to the general direction. In addition (outside Process of course) I strongly recommend separating style and boilerplate of Rec-track vs Note-track documents to help distinguish them, as many people outside W3C (the vast majority of our stakeholders) will never attempt to understand W3C process and currently confuse them.

**Comment by fantasai** [comment]
We posted to [ac-forum](https://lists.w3.org/Archives/Member/w3c-ac-forum/2021JanMar/0067.html) and [spec-prod](https://lists.w3.org/Archives/Public/spec-prod/2021JanMar/0018.html) about the proposed changes. Here are some of the responses (the ones that aren't wading into the Patent Policy side-track):

[Jeffrey Yasskin](https://lists.w3.org/Archives/Public/spec-prod/2021JanMar/0019.html):
> I support this change.
>
> I believe this will help the process for https://w3cping.github.io/privacy-threat-model/, which otherwise would need to live as just an Editor's Draft all the way until it's ready for publication as a Note. Thank you!

[Marcos Caceres](https://lists.w3.org/Archives/Public/spec-prod/2021JanMar/0020.html):
> I also support this change. Having a "Discontinued Draft" status is a really good idea - as is the new "Draft Note" status. Clarifies things quite nicely.  

[Robin Berjon](https://lists.w3.org/Archives/Member/w3c-ac-forum/2021JanMar/0070.html):
> overall I am very supportive of these changes. Some of them I've wanted 
since the XBC WG.
> ...
> [Wrt transitions between tracks] I think that having a clear transition between the tracks would prove useful. If we don't have it someone will just copy and paste, and then do it anyway.
> ...
> [Wrt hesitation about introducing two more possible document statuses] It's not a finite space, so I'm not too worried about this. If the concern is cognitive load I think that ship has already sailed :)

[Arnaud Le Hors](https://lists.w3.org/Archives/Member/w3c-ac-forum/2021JanMar/0071.html):
> Sounds good to me. I agree with Robin:
> 1) how is "restart on the other track" different from doing a copy/paste? Don't think you can prevent it. 
> 2) the benefit of adding the new statuses outweighs the cost.

[Phil Archer](https://lists.w3.org/Archives/Member/w3c-ac-forum/2021JanMar/0072.html):
> I definitely support this change too. Many groups' documents are only ever conceived of as Notes and I've always found the link with the Rec Track process confusion/unhelpful. Notes have drafts, comments and final versions just as much as Recs, so Draft Note makes sense to me as a status.

Michael Champion [1](https://lists.w3.org/Archives/Member/w3c-ac-forum/2021JanMar/0083.html) [2](https://lists.w3.org/Archives/Member/w3c-ac-forum/2021JanMar/0079.html):
> I’m glad [that simplifying the process is] the intent; maybe I’m just not seeing the simplification that results from the changes.  (But I note that fantasai mentioned “hesitation” because this "Introduces two more possible document statuses”).
> 
> I do think the AB should somehow assure themselves that the broad community who do not understand the process in detail would see this change as making the process easier to engage in.   Note the parallel discussion of how to “onboard” new community members; making the process / policies / culture of W3C easier to understand would reduce the barriers to entry into the community.
> ...
> I also share the “hesitation” about introducing more complexity into the Process Document.  At the risk of revealing too much information about my declining intellectual abilities, I no longer understand the Process well enough to easily advise someone about how it works in practice.  The intent of 2020 updates makes sense, but I have to refer back to the documents to recall the details of what the terminology means and what specific actions need to be taken when.  Adding more states and formal terminology will be discouraging to old-timers as well as newbies getting onboard W3C.

There was also a side-track on ac-forum about whether and how transitions between the tracks should be allowed, and what the patent policy implications might be. I think we landed on WD->NOTE is simple and would be good to keep, and NOTE->FPWD might be nice but there's varying opinions on how to handle the patent policy implications if someone does WD->NOTE->WD. The possibilities discussed included:

- WD->NOTE->WD is allowed: Patent Policy just ignores the NOTEs as if they were never published.
- WD->NOTE->WD is disallowed: if you want to do double-back, you have to copy-paste into a new document.
- WD->NOTE->FPWD: if you go back to REC track, we pretend it's a new document with no patent policy history, we just preserve the shortname for convenience.
- Some hybrid of 1 and 3 depending on whether you were in the WG or not during a previous exclusion opportunity.

I personally think this last one (the hybrid) is impractical. I'm OK with any of the others, but the least work for us would be one of the first two options.
