### ISSUE TITLE
Should W3C adopt the EverTeal modifications to the REC track?

### ISSUE THREAD

**Issue by fantasai** [w3c/w3process#344]
The modifications described in [Process 2020 Summary](https://www.w3.org/wiki/Process2020) consist of the following parts:

1. Creating an amendment process for adopting substantive changes into RECs (without changing the entire spec's status)
2. Using that same amendment process for adopting new features into RECs
3. Updating the Patent Policy to provide license obligations, not just promises, to CRs as well as to RECs.
4. Splitting CR-phase publications into periodic _Snapshots_ (which, as currently, require Director's approval and have IPR implications) and potentially continuous _Update Drafts_ (which can be published by the WG directly and have no IPR implications, like a WD) in between the snapshots.
5. Allowing an automated alternative to manual Director's Approval in the obviously acceptable cases.

_Note: The Director's approval process currently reviews formal objections, and checks that the WG has received wide review and formally addressed feedback._

Please see [Process 2020 Summary](https://www.w3.org/wiki/Process2020) for details on each of these parts and their implications.

Should we adopt these parts (or some subset of these parts)?
(See also #345 wrt adding new features to RECs, specifically.)

<hr>

Summary of community feedback:
* Many editors and WG participants attended presentations on the proposed changes at TPAC. Feedback was largely positive, and multiple WGs and editors were excited to try the new Process.
  * There was some concern about making sure requirements to document changes are not too onerous for editors.
* Some AC reps had concerns about patent obligations for essential claims which become no longer essential as a result of changes
  * This needs to be addressed in the details of the patent policy; the concern is common to all approaches to continuous development that W3C might want to adopt.
* Horizontal Working Groups had a joint meeting to discuss improving agility and fidelity in light of the increasing agile spec development processes as well as the increasing volume of work for their limited staff.  
  * They noted that many groups continue to forget to solicit Horizontal Review, leading to a lot of scrambling when this requirement is checked for at CR transition. See [minutes](https://www.w3.org/2019/09/16-i18n-minutes.html#item09). There is interest from the HRG community for the Process therefore to include some minimum requirements for wide and horizontal review e.g. at FPWD and CR transitions that serve as a backstop for when HR fails to happen organically.
  * There was some concern from Horizontal Groups that it is difficult to review continuously developing specifications without summary of changes, particularly of new features.

Concerns raised about adopting these modifications were:
* Can we adopt a new Patent Policy for the main REC track?
  * There was strong opposition to the statement that the Patent Policy should not be updated (38 vs 2)
  * Between changing the policy unilaterally and allowing experimentation by charter, slightly more were for just changing the policy. Most found either option acceptable, a few (~10%) only found one of these options acceptable, and only one respondant found both of these options unacceptable.
* Do these changes create a REC track that is too confusing to editors and WGs?

**Comment by wseltzer** [comment]
Please see #346

**Comment by dwsinger** [comment]
Resolved to merge into the working copy on teh Process CG call Jan 8 2020, closing
