### ISSUE TITLE
Streamlining horizontal reviews

### ISSUE THREAD

**Issue by lknik** [w3c/w3process#347]
Hi,

I read with great interest the Process2020 proposal. Exciting times. Good job!

I wonder though what may be the implications of "**Automatic Update Approval**" for certain specs/features, foreseeing skipping of parts of reviews, specifically in case of security and privacy (so also the TAG level).  

For example I would expand "Making these “streamlined” updates truly streamlined will require some coordination and documentation" to include that it is good to think through (in advance) how to approach the problem, creating clear process in case of each HRG.

<details>
<summary><strong>Edited: this part seems to be somewhat distinct from there rest, and separate issue has been open to track it separately: #394</strong>. Expand for details.</summary>
I am also wondering if we could take this opportiunity to somewhat formalise HRG (here mostly focusing on security/privacy, i.e. as foreseen in <a href="http://ceur-ws.org/Vol-1873/IWPE17_paper_18.pdf">this paper</a>, see e.g. _Section V_) as mandatory by default, subject to the exceptions formed by "<strong>Automatic Update Approval</strong>"? I am simply a bit wary of a situation where a change in one feature, possibly in conjunction with other features or changes in them, unexpectedly open an undesirable consequence for the Web.
</details>

**Comment by dwsinger** [comment]
This seems related to #130

**Comment by frivoal** [comment]
The last paragraph in the opening comment seems to be somewhat distinct from there rest, and separate issue has been open to track it separately: https://github.com/w3c/w3process/issues/394

**Comment by frivoal** [comment]
As per the AB meeting of 2020-05-22, and the Process CG meeting of 2020-05-27, this is deferred to a Process 2021. We do want to address this issue, and note good progress on the related pull request, but weren't able to address within the time constraints of Process 2020.

**Comment by dwsinger** [comment]
should we close as part of #130 , or as practise?
