### ISSUE TITLE
Steps to advancing to Recommendation

### ISSUE THREAD

**Issue by jeffjaffe** [w3c/w3process#352]
Section 6.1.1 of the Process Document describes the steps to advance to recommendation.  It states that the first step is the FPWD.

At times (e.g. HTML and DOM), a document may come in at the CR stage.  We should make it explicit that in circumstances where there is a mature document that we can have CR=FPWD.

**Comment by michaelchampion** [comment]
When negotiating the WHATWG-W3C MoU, I recall an informal understanding that the FPWD could also be a CR, since nothing in the Process forbids that.  But making this explicit in the Process document seems useful and straightforward.

**Comment by nigelmegitt** [comment]
> the FPWD could also be a CR, since nothing in the Process forbids that

A CR has to have had wide review (I'm assuming that's not open to question in the new process!). How would you demonstrate wide review of a document that has not yet been published? It seems logically impossible that on the day of first publication a document could be both FPWD and CR simultaneously. Of course an FPWD may be republished without substantive changes as a CR, but that's a different thing I think?

**Comment by jeffjaffe** [comment]
The idea @nigelmegitt is that you could have CR=FPWD if you achieved wide review of a document published outside of W3C.

**Comment by nigelmegitt** [comment]
@jeffjaffe OK I can see that might be feasible in special cases. Two follow-on points:

1. We should define what it means for the document to be "the same" (or conversely, what differences might invalidate this approach).

2. Some other publishing organisation that isn't W3C may not have the same degree of attention externally, so it would be useful to be really clear about what the requirements are for demonstrating wide review of a non-W3C document aimed at achieving FPWD=CR state, and if they are different in any way to a W3C Working Draft's wide review requirements.

**Comment by wseltzer** [comment]
https://www.w3.org/2003/12/22-pp-faq#fpwd-lcwd describes a FPWD+CR in the current process

**Comment by nigelmegitt** [comment]
Thanks for trying @wseltzer ! That link points to a FAQ with a lot of questions related to the patent policy, and specifically to question 43. It doesn't cover wide review requirements and therefore doesn't answer my questions in https://github.com/w3c/w3process/issues/352#issuecomment-563138278.

**Comment by fantasai** [comment]
@wseltzer That's an FAQ, not the Process document or the Patent Policy. What it suggest makes a lot of sense, if such a thing existed! But there's nothing in the Process that defines a publication which is simultaneously a First Public Working Draft and a Candidate Recommendation. Whether W3C has published such things or not despite it not existing in the Process notwithstanding.

**Comment by plehegar** [comment]
Nothing says in the current Process that you cannot publish a FPWD and a CR on the same day either.  If you can fulfill the requirements of FPWD and CR, I don't see why we would prevent it. So, while FPWD/CR isn't listed in the Process, it's not prohibited. Having said that, we never published one so far.

**Comment by frivoal** [comment]
Nothing in the Process says you cannot publish a FPWD, and 10 minutes later a CR if you have fulfilled the criteria. There are rules about how to publish either of these things, and they don't mandate any minimum wait time. However, a single document that is both simultaneously isn't a type of publication that exists. The process defines how it is you get to CR, and the **previous** step is always a FPWD and zero or more WD, from which you transition to CR.

Assuming all the criteria are fulfilled (which is pretty rare, as getting wide review on a document that has not been published yet is tricky outside of cases like the WHATWG cooperation), I don't think there'd be anything wrong with a FPWD+CR in a single publication, so I'm perfectly happy to amend the process (and if necessary the Patent Policy) to enable it, but it isn't currently a thing that exists.

Until it does, I don't think there's any practical problem with the WHATWG agreement. We can be true to it without making things up by publishing FPWD and CR immediately after each other.

**Comment by dwsinger** [comment]
Is there really a problem with filing the FPWD and then almost immediately requesting the team to do the CR transition, and showing evidence that it's justified? Are we solving an actual problem here?

**Comment by plehegar** [comment]
As I said before, while I've been asked about it in the past, no group has requested such status. We did define this type of publication in pubrules ([FPCR](https://www.w3.org/pubrules/doc/rules/?profile=FPCR), but never used it. Ditto for the [PSIG FAQ](https://www.w3.org/2003/12/22-pp-faq#fpwd-lcwd). The transition requirements doesn't mention this type of publication, which explains [issue 13](https://github.com/w3c/transitions/issues/13). My take is to leave things as-is, ie continue to not prohibit it in the Process, and let things as they are. If a Group does come forward with such document, we'll apply the transition requirements for FPWD and CR. If the case stops being an exception, we'll fix [issue 13](https://github.com/w3c/transitions/issues/13) to make things clearer.

**Comment by nigelmegitt** [comment]
@dwsinger please take a look again at https://github.com/w3c/w3process/issues/352#issuecomment-563138278 : there is no principle problem filing a FPWD and then a CR transition, but the implication is that wide review on a necessarily not-quite-identical document published by another organisation is considered identical to wide review on a W3C publication. That worries me, if we do not set any boundaries on the conditions for considering the document  a) to be "the same" and b) to have wide review.

**Comment by plehegar** [comment]
This is not necessarily the case. If the document comes from WICG, it's not another organization.

**Comment by dwsinger** [comment]
@nigelmegitt I'm trying to address the question of whether need a document status that is a FPWD+CR, and my hypothesis is no. I'm not trying to address the question of how quickly one can demonstrate wide review on a specification, which seems to me to be related but different. Presuming that you satisfy the CR criteria, filing FPWD and then very rapidly asking for the formal CR transition seems to be unproblematic, to me.

Whether you can or do satisfy the CR transition criteria should be considered separately "Can a new draft be considered to satisfy CR criteria, or does it need to remain in WD status for some minimum length of time?". (I think the answer is that you're welcome to try, and we shouldn't actually open this issue, but you may disagree).

I therefore think that the answer to the question posed is that there is no such thing as a single document that is simultaneously FPWD and CR, but that there is no reason in principle in the way of publishing FPWD and then immediately asking for CR transition on the same content, as long as the CR transition criteria are met.

**Comment by nigelmegitt** [comment]
@dwsinger ok I see your point. When you look at it in that way, my question is really just another iteration of the recurring question: "what constitutes wide review?".

**Comment by chaals** [comment]
It seems we are talking about making something explicit that is implicit, and actually only sort of arises in one weird case (the publications where we rubber-stamp WHATWG's work, which as far as I understand doesn't exactly match anyway).

I don't think this addition is useful, and I think we should close the issue.

**Comment by chaals** [comment]
First Public Working Draft is a Working Draft that happens to be the first one for some document, and therefore has some special extra conditions attached related to Patent Policy. CR is also a Working Draft with some special extra conditions attached. They are both Working Drafts and we don't need some new state of they both happen to be the same Working Draft.

**Comment by frivoal** [comment]
> CR is also a Working Draft [...]

Citation needed.

**Comment by chaals** [comment]
@frivoal replied to me:

> > CR is also a Working Draft [...]

> Citation needed.

Sorry, to be clear, I meant conceptually - it is a document that may well change before Recommendation (although the **expected** changes are relatively constrained). The Process indeed has them as distinct "maturity levels".

**Comment by frivoal** [comment]
Agenda+ to decide if we should address as part of Process 2020 or defer to a subsequent cycle.

**Comment by dwsinger** [comment]
or close with no action...we don't need a dual-state in the process when it's logically possible to do a CR transition 'soon' after FPWD (if you've met all the criteria, which seems unlikely). it's a corner case and we don't need cruft for corner cases.

**Comment by dwsinger** [comment]
no action in 2020, but keeping open since there is debate

**Comment by jeffjaffe** [comment]
Seems like there is general agreement that you can do FPWD and CR in close succession.
