### ISSUE TITLE
Where are registries published?

### ISSUE THREAD

**Issue by dwsinger** [w3c/w3process#353]
Background email at <https://lists.w3.org/Archives/Group/ab/2019OctDec/0306.html>

Should the Registry Publication (the actual viewable data table) be done, as is done today for specs, by copying static resources to the /TR section of the W3C website, or be addressable by a W3C URL?

**Comment by dwsinger** [comment]
I asked myself what we get from publishing on /TR, and I think it’s 
* that the target now has an official W3C URL; 
* /TR keeps history, and is backed up, 
* and is served from servers owned by the W3C, 
* and that that ‘copy’ step gives us a ’throttle’ that we can turn off (we can refuse to copy to /TR if process has not been followed). 

The cost of copying need not be high, but it is today and would be perceived as such by many today; one has to either use Echidna or ask the team to do the publication (on every update, no matter how small); and if your development site is a Wiki (as it is today for some groups) you have to be able to ’scrape’ the Wiki into static resources (HTML, CSS, scripts) for publication, and be sure that when copied to a new location it all works. Even if you’re on Github, using Github.io, this might not be straightforward.

Noting that we should require that Registry development maintain history and be backed up by the W3C, and that /Guide is actually published directly from Github through a W3C proxy, I don’t think we need the copy, and that requiring it will be, today, in the absence of serious tooling improvements, a real impediment to adoption. So, I believe we should allow use of a W3C Github repo, or a W3C Wiki, or any other W3C backed-up and history-maintaining site, as the place where the Registry values are published.

I think the division between development site and publication site perpetuates a schism which is not a helpful mindset; the idea that where you look at the history, comments, issues, and plans, for something is wholly dissociated from the official place it's published.

**Comment by chaals** [comment]
I think it is important that there is a W3C URL for a W3C registry, and agree that a backup mechanism is critical.

The source can be elsewhere, indeed a registry may be shared with some other standards organisation or set of them.

I don't think it is a problem that the source and issue discussions are in a location that isn't the same as that of the table, although there should be clear linkages that are easy to follow. In many cases, users of the registry just need to know where to find the official table and notification of updates, and the rest isn't interesting to them.

I do agree that there needs to be a minimum of friction in making updates, and that this means we need to consider the current possibilities and what tooling is required for a new plan.

**Comment by wseltzer** [comment]
I'd say "be addressable by a W3C URL" is sufficient, even if that URL is simply a link, redirect, or proxy to an external resource. That external resource must have sufficient assurance of global accessibility and archival permanence (which can be achieved either in-place, or by W3C backup).

**Comment by dwsinger** [comment]
Yes, we need to require that any W3C deliverable is developed in a place that (a) maintains history (b) is backed up by the W3C and (c) allows for notifications of changes etc.  If those are met, we could then allow a proxy/redirect to that as the publication location. (This covers the two major cases: W3C Wikis and W3C Github.)

We've never formally said this (it's been assumed) for specs, but we have proto-registries that are outside this envelope and they, alas, will need to change. And we'll clarify this for all deliverables in teh coming year, I hope. (There are also quite a few proto-registries within this envelope as well.)

**Comment by fantasai** [comment]
I would like us to require the following for the publication of registry tables, as we already do for other specifications (as is provided by the current publication process in /TR):

- accessible worldwide and across disabilities
- free of tracking cookies and similar privacy invading mechanisms
- maintains history such that readers can view the set of values as of a given date
- dated, to permit cross-referencing of corresponding rules and values
- allows for notifications on changes 
- is hosted or backed-up by the W3C and is served from a *.w3.org URL such that W3C can seamlessly take over hosting should it be necessary **without undue maintenance burden on the systems team, with the same guarantees of longevity as any other W3C technical report**

**Comment by LJWatson** [comment]
It's a minor point but I'd note that there is a usability win for a URL like w3.org/registries over w3.org/tr.

**Comment by wseltzer** [comment]
re
> is hosted or backed-up by the W3C and is served from a *.w3.org URL such that W3C can seamlessly take over hosting should it be necessary without undue maintenance burden on the systems team, with the same guarantees of longevity as any other W3C technical report

I'd say that it's critical to have a persistent archival backup that preserves all information, but it need not be a direct replica of the live system. If a spec dies, a snapshot and history of a once-dynamic registry lookup would seem adequate.

**Comment by fantasai** [comment]
@wseltzer It's fine to archive a dynamic system into a static one, but only if the information (including historical lookups) continues to be available and no URLs break. This isn't a backup of our work-in-progress, which is OK to be in some awkward format: this is the actual publication of the spec. The same availability guarantees we give for the character entity tables of the HTML4.01 spec should apply to the contents of any official W3C Registry.

**Comment by swickr** [comment]
I mostly concur with @fantasai 's [list](https://github.com/w3c/w3process/issues/353#issuecomment-567513218) :
> 
> I would like us to require the following for the publication of registry tables, as we already do for other specifications (as is provided by the current publication process in /TR):
> 
>     * accessible worldwide and across disabilities

+1

>     * free of tracking cookies and similar privacy invading mechanisms

+1
 
>     * maintains history such that readers can view the set of values as of a given date

+1 
 
>     * dated, to permit cross-referencing of corresponding rules and values

I don't think this ought to be a requirement; some registries might not need explicit versioning (e.g. an append-only registry) and some registries might provide all the necessary detail in the history.

>     * allows for notifications on changes

Nice to have (perhaps even "strongly encouraged") but should not be a requirement.  In fact, I'd rather see a general-purpose mechanism that allows any Web user to 'watch' any Web resource for changes.

>     * is hosted or backed-up by the W3C and is served from a *.w3.org URL such that W3C can seamlessly take over hosting should it be necessary **without undue maintenance burden on the systems team, with the same guarantees of longevity as any other W3C technical report**

I think this should be encouraged and supported but not required.  While we might choose to require that the registry policy be published on /TR, the proposed publication location and change policy for the registry content instantiated by a W3C Recommendation should be described during Wide Review of that specification and the community should decide whether it supports or objects to the proposed registry mechanisms.  If the community concurs that it is appropriate in some instance to host and serve the registry content from some place other than *.w3.org I think W3C should permit that.

**Comment by fantasai** [comment]
>  I'd rather see a general-purpose mechanism that allows any Web user to 'watch' any Web resource for changes.

IMHO this would count. :)

>  If the community concurs that it is appropriate in some instance to host and serve the registry content from some place other than *.w3.org I think W3C should permit that.

I think it's appropriate for registry content to be hosted somewhere other than W3C, in a more convenient form, and linked from the /TR report; but I also think /TR should be hosting all the official content of anything we publish as a spec, including the contents of the registry, even if it's just as a series of data files published alongside Overview.html, because /TR is where we publish all our official specifications and I think we should preserve the idea that the full contents of the canonical copy of W3C's technical reports are published at w3.org/TR

I also think it's extremely important that the contents of the registry don't disappear when some external service is discontinued.

> some registries might not need explicit versioning (e.g. an append-only registry)

I think even append-only registries should have a way to see the state of the registry as of a given date.
