### ISSUE TITLE
Director-less issues

### ISSUE THREAD

**Issue by danield06** [w3c/w3process#360]
Posted at https://lists.w3.org/Archives/Public/public-w3process/2020Jan/0000.html

copied here:
Hello all,

the fate of W3C without Tim has been on my mind long before leaving W3C, so
I'll give my 2 cents on the recent proposal.

I'm looking at

https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fw3c.github.io%2Fw3process%2F&doc2=https%3A%2F%2Fw3c.github.io%2Fw3process%2Fdirector-free

I'm concerned by two things:
 - the added complexity with two new "committees"
 - the power now residing in the CEO hands.

On the second point, there are now hundreds of references to the CEO and
Team as decision-makers and with the Team under full control of the CEO,
this effectively puts all the process decisions into one person's hands,
which could become an issue in the future if this person is not able to
handle all this power correctly.

I think we should try to categorize the current Director's functions along
their level of Web technicality, draw a line, and give the most technical
pieces to someone else than the CEO. Not sure to whom, maybe not a single
person. You could argue that the CEO could delegate these (or whatever)
pieces and create such a Technical Director function but I'd rather see
this implemented transparently based on due process.

On the first point, new committees, if there is such a TD function, then no
need for a new W3C Council providing a higher authority for some of the
ex-Director/new CEO decisions. Given the AC appeal mechanism already in
place, and if the main technical items are separated, this should not be
necessary.

Same idea for the new TAG committee created to select the "Director" TAG
seats: it should not be necessary with a appealable Technical Director
function selecting them. And it would be better than a pure TAG co-optation
procedure..

So IMO having ome sort of  Technical Director function, or a Web
Architectural Board, would effectively solve both the CEO power
concentration and the added committees issue. Maybe this function could be
implemented by a trio: one staff, one TAG, one AB, selected by each
constituency for a given period, or maybe just one person, e.g. the chair
of the TAG (since it's for Technical stuff). Or maybe by one TAG and a W3C
CTO (from staff).

Anyway, I also think someone should be assigned to do a quick external
study on how other relevant SDOs implement their own Technical Director
function/Arbitrage, and also how organizations (non-profit or commercial)
deal with their structural issues when the Creator (of the technology and
the organization) leaves.

Take care.

**Comment by michaelchampion** [comment]
This is similar to #316 and #331 .  Not being on the  AB anymore  I'm not sure how much consensus there is for the W3C Council proposal, but I urge the AB to engage the larger community in this important topic before locking down a Process proposal.  The ideas of a Technical Director (elected for a limited term or hired by the Board of Directors with no expectation that it is a "for life" appointment) or fairly small Architectural Board (elected or chosen by some mechanism similar to that IETF uses) deserve to be explored in some depth.

I strongly agree with @danield06 that "someone should be assigned to do a quick external
study on how other relevant SDOs implement their own Technical Director function/Arbitrage".  @mnot has contributed thoughts about IETF's structure in this thread that can be explored.  I believe @tantek recently attended an ECMA TC39 meeting and came away with the impression that W3C could learn from their experience. Likewise there was a TPAC 2019 breakout https://www.w3.org/2019/09/18-future-minutes.html where several speakers made comparisons to similar standards organizations (and IIRC OSS projects that touch on the web). Some relevant resources include:
https://tools.ietf.org/html/rfc2026#section-6.5
https://nodejs.org/en/about/governance/

IMHO, this is not a task for someone on the Team, but one that needs a broader set of participants from the AB, AC, Team, and external stakeholders.  Maybe a Community Group?  Or just an issue in this GitHub repo?

**Comment by jeffjaffe** [comment]
Thanks, @michaelchampion .  I'll try to schedule time in the next few months for the AB and other stakeholders (e.g. you, Daniel, Mark, and Tantek to discuss these issues.

**Comment by dwsinger** [comment]
Thanks for the feedback. At a rough level, 
* we were trying NOT to create new committees, so the W3C Council, while it serves a new function, is not separately formed but instead is AB+TAG. (What's the second new committee?).
* we were trying to recognize current reality in what we documented as being team/CEO, for the most part — places where the old process said Director, and the function was either routine (announcements etc.) or required a person (discipline, for example).

We clearly, in your view, went too far in the second. Most trade and standards bodies I know don't have a technical director as such; they expect the members to provide technical direction. Even a body like the TAG is unusual; though the IETF has roughly similar (IAB, Dispatch).

Are there other examples of bodies that formed around a single person and had to work out how to live without them?

**Comment by michaelchampion** [comment]
> Most trade and standards bodies I know don't have a technical director as such; they expect the members to provide technical direction.

It's worth looking at other organizations that don't have a technical director to see how they deal with dissent / non-consensus.  TC 39 comes to mind ... https://tc39.es/process-document/

> Are there other examples of bodies that formed around a single person and had to work out how to live without them?

The most-discussed example of an organization losing a BDFL is  Python after Guido van Rossum stepped away https://mail.python.org/pipermail/python-committers/2018-July/005664.html . See also https://discuss.python.org/t/comparison-of-the-7-governance-peps/392, https://medium.com/@herveberaud.pro/python-after-guido-bdfl-the-future-of-the-governance-of-python-2969bab19c7e

I'm not sure about other cases... is Linus still BDFL of Linux?

There's also https://blog.leafe.com/why-openstack-failed/ , an argument that OpenStack is less successful than it would have been if it had a BDFL

**Comment by dwsinger** [comment]
I would like this split into specific issues that have more descriptive finer-grained titles.

**Comment by frivoal** [comment]
Agreed to close in the 2022/10/28 Process-CG meeting.
