### ISSUE TITLE
Setup document management for director-free matters

### ISSUE THREAD

**Issue by LJWatson** [w3c/w3process#366]
At the AB meeting in August 2019 it was agreed that a document management system was needed for director-free matters other than the Process itself, and that the best location for that would be this repo.

Transferred from the AB's private repo w3c/ab-private#94 because it seems this is the logical place for the issue to be taken up.

**Comment by dwsinger** [comment]
we have a director-free of the process, which is what we're responsible for; closing

**Comment by frivoal** [comment]
The Process part of the director free project is being addressed here. The rest is out of scope for the Process-CG.

**Comment by frivoal** [comment]
@LJWatson As we are wrapping up this Process cycle, and you're the one who opened this issue, I'd like to ask you to confirm: are you OK with this issue being closed as out of scope, for the reason given above?

**Comment by LJWatson** [comment]
Yes, I'm OK for this to be closed. Apologies, I missed your ping on this.
