### ISSUE TITLE
TAG appointed participants announcement by Director

### ISSUE THREAD

**Issue by koalie** [w3c/w3process#368]
Section "2.4.1. Technical Architecture Group Participation" states:
> The Director may announce the appointed participants after the results for the Advisory Committee election of participants have been announced.

Section "2.5.2. Advisory Board and Technical Architecture Group Elections" states:
> The Director should announce appointments no later than the start of a nomination period as part of the Call for Nominations.

I'd suggest we keep the most conservative and broadest of the two statements (the first occurence) and remove the other one (in practice, it's been several years since we were able to announce Tim's appointees as part of the call for nominations.)

**Comment by dwsinger** [comment]
agreed. and the AB has always hoped that the Director would use appointment to balance the TAG after the election.

**Comment by chaals** [comment]
The ability for the Director to add expertise and diversity to the TAG **after** the election seems more important than the original motive of members being able to "balance" the Director's choices through the election. Especially given the Director and his choices are a minority on the TAG.

That said, I think it is a failure case that the Director is "unable" to name appointees before the election, and that should not be a rationale for a decision here.

I do think it is important that we communicate how we are resolving the difference so the AC are requested to actively approve this "change" (again).

**Comment by frivoal** [comment]
This is non editorial, and applies to a part of the process that isn't new in the 2020 cycle. As agreed with the CG chair, marking it as deferred, to handle it in a subsequent cycle.

**Comment by dwsinger** [comment]
We should address as part of Director-free, as TAG appointment by the Director is going away

**Comment by frivoal** [comment]
This inconsistency has been fixed, see https://www.w3.org/Consortium/Process/Drafts/#TAG-appointments
