### ISSUE TITLE
Should the Guidelines for Disciplinary Action be member-confidential

### ISSUE THREAD

**Issue by michaelchampion** [w3c/w3process#389]
Section 2.1.1 of the current Process links to https://www.w3.org/2002/09/discipline, which is member-confidential.  That is an impediment to potential members who want to understand what they are committing to before they join, and prevents unaffiliated people from fully understanding how W3C works and contributing to the (public) Process CG.

Is making this document member-only a deliberate choice by the AB/Process CG or an administrative glitch which the Team should rectify?

**Comment by frivoal** [comment]
This is a historical glitch, and a known issue (that's been harder to put to rest than I would have expected). This is already being discussed at https://github.com/w3c/w3process/pull/274.

Closing as duplicate.
