### ISSUE TITLE
Diagrams in Process2020 are not up to date

### ISSUE THREAD

**Issue by dwsinger** [w3c/w3process#390]
and when updated, need to be accessible

**Comment by LJWatson** [comment]
If someone is able to update the SVG (preferably without substantial 
rewriting), I'll take a run at the ARIA that underpins them.

**Comment by frivoal** [comment]
@LJWatson Can you have a look in https://w3c.github.io/w3process/#rec-track to check if the accessibility of the diagram is fine? (giving a few minutes to build first, if you're looking at this imediately after I post this comment)

**Comment by LJWatson** [comment]
It seems to be ok, yes. The flowchart still appears to make sense and 
seems to reflect the process as I understand it.
