### ISSUE TITLE
CR Draft boilerplate

### ISSUE THREAD

**Issue by plehegar** [w3c/w3process#405]
This issue is here for the CG to iterate on the CR Draft boilerplate.

[[
This document was published by the Web Performance Working Group as a Candidate Recommendation Draft.

GitHub Issues are preferred for discussion of this specification.

W3C publishes a Candidate Recommendation Draft to allow for wider review of the changes and for ease of reference to the integrated specification.

Please see the Working Group's implementation report.

Publication as a Candidate Recommendation does not imply endorsement by the W3C Membership. This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.

This document was produced by a group operating under the W3C Patent Policy. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.

This document is governed by the XX XXXX 2020 W3C Process Document.
]]
https://htmlpreview.github.io/?https://github.com/w3c/tr-pages/blob/master/p2020mockup/cr-6.2.8.2.html

**Comment by dwsinger** [comment]
I'd like us to consider having an identical sentence in the SOTD and in the Process, that describes what a document _is_. For CR, the first sentence here from <https://w3c.github.io/w3process/#maturity-levels> would seem suitable if not ideal, and perhaps the whole text:

> A Candidate Recommendation is a document that satisfies the technical requirements of the Working Group that produced it and their dependencies, or makes substantive corrections to a Recommendation that is not maintained by a Working Group, and has already received wide review. W3C publishes a Candidate Recommendation to
> * signal to the wider community that it is time to do a final review
> * gather implementation experience

**Comment by nigelmegitt** [comment]
> A Candidate Recommendation is a document that satisfies the technical requirements of the Working Group that produced it and their dependencies, or makes substantive corrections to a Recommendation that is not maintained by a Working Group, and has already received wide review. 

I think we can drop "that is not maintained by a Working Group". The Process allows a WG maintaining a Rec to go from Rec -> CR directly. This is what TTWG did recently when making TTML2 2nd Edition CR, based on the first edition's Rec.

**Comment by plehegar** [comment]
A few considerations for boilerplate language for our documents:
1. Some parts are inflexible: no endorsement from the AC (WD, CR, PR), Patent Policy status (all)
2. Some parts are flexible: level of consensus of the publishing Group
3. Some parts are in between: we ask Groups to point to where issues should be raised but allow GitHub, mailing lists, or both.

At the end of the day, the Groups needs the flexibility but the oversight is done by the Team to ensure that the SOTD makes sense. We always attempt to strike a balance between the complexity of our tooling (avoiding too many  and/or obscure options in the UI), the flexibility requested by the Group, and the fact that we have an automatic publication system (the Team isn't checking manually all publications).

**Comment by plehegar** [comment]
Keeping in mind that this is the boilerplate of a CR Draft (and not a CR):
[[
A Candidate Recommendation Draft integrate changes from the previous Candidate
Recommendation that the Working Group intends to include in a subsequent
updates. This allows for wider review of the changes and for ease of reference
to the integrated specification.

@@not necessarily may be omitted in the paragraph below:

Publication as a Candidate Recommendation Draft does not necessarily represent
a consensus of the Working Group and does not imply endorsement by the W3C
Membership.

@@choose one of the 2 following paragraphs:

This is a draft document and may be updated, replaced or obsoleted by
other documents at any time. It is inappropriate to cite this document as other
than work in progress.

This is a document that is maintained and updated at any time. Some parts of
this document are work in progress.
]]

**Comment by fantasai** [comment]
> GitHub Issues are preferred for discussion of this specification.
> Please see the Working Group's implementation report.

This information should go in the header, not in the SOTD. Also not unique to CRD.

**Comment by fantasai** [comment]
> Publication as a Candidate Recommendation Draft does not necessarily represent
a consensus of the Working Group and does not imply endorsement by the W3C
Membership.

Publication as a CRD *does* imply consensus of the Working Group (but does not imply endorsement by the W3C Membership).

**Comment by fantasai** [comment]
Wrt https://github.com/w3c/w3process/issues/405#issuecomment-634802633 and the boilerplate of a CR: I think it's too long. SOTD should be short. If we want to include a description of CR, I think just the first sentence should be acceptable *and* we should delete “or makes substantive corrections to a Recommendation that is not maintained by a Working Group” in favor of a special template in the rare case that such a document is published.

(But also, acknowledging plh's point that this issue is about CRD, and such a sentence doesn't belong in CRD anyway.)

**Comment by chrisn** [comment]
> [...] for ease of reference to the integrated specification.

What does "integrated" mean here? Can this be simplified to "for ease of reference to the specification"?

**Comment by plehegar** [comment]
How about:
[[
This document was published by the Web Performance Working Group as a Candidate Recommendation Draft.

Publication as a Candidate Recommendation does not imply endorsement by the W3C Membership. A Candidate Recommendation Draft integrate changes from the previous Candidate Recommendation that the Working Group intends to include in a subsequent updates.

(@@choose one of the 2 following paragraphs)
This document may be updated, replaced or obsoleted at any time. It is inappropriate to cite this document as other than work in progress.

This document is maintained and updated at any time. Some parts of this document are work in progress.

This document was produced by a group operating under the W3C Patent Policy. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.

This document is governed by the 15 September 2020 W3C Process Document.
]]

The links to GH/email/implementation report have been moved to the headers.

[[
Implementation report:
  <a href='https://wpt.fyi/hr-time/'>https://wpt.fyi/hr-time/</a>
Participate:
  <a href='https://github.com/w3c/hr-time/issues/'>File a bug</a>
]]
https://htmlpreview.github.io/?https://github.com/w3c/tr-design/blob/gh-pages/p2020mockup/cr-6.2.8.2.html

**Comment by plehegar** [comment]
(note that the banner on the left top side will need to be updated to say "Candidate Recommendation Draft")

**Comment by frivoal** [comment]
This has been handled in the various relevant repositories. Closing.
