### ISSUE TITLE
For the purposes of appealing adverse actions and exhausting administrative remedies is Web Platform Tests a Working Group or Interest Group under W3C?

### ISSUE THREAD

**Issue by guest271314** [w3c/w3process#407]
WPT does not have _any_ public documentation indicating an official appeals process exists for the organizations' actions, while Web Platform Tests actions can include references to w3.org sites, implying Web Platform Tests is a subsidiary of W3C organization, or at least possesses the administrative power to restrict access to site associated with W3C, therefore it is impossible to actually file an appeal at Web Platform Tests repository contesting adverse actions taken by that body, in clear violation of the Due Process Clause of the United States Constitution, Amendment 14, which guaratees Substantive and Procedural Due Process within the Jurisdiction of the United States. GitHub, Web Platform Tests repositoty, and W3C all operate in the Jurisdiction of the United States, where the Constitution of the U.S. is the Supreme Law of the Land.

> Due to your continued conduct in web-platform-tests, you are being permanently excluded from web-platform-tests project spaces.  This exclusion includes all repositories under the web-platform-tests GitHub organization, the #testing channel on irc.w3.org, and the public-test-infra@w3.org mailing list.

> - The WPT Core Team

for reminding WPT the organization has not replied to the duly filed NOTICE OF APPEAL for the arbitrary and capricious revocation of Membership in WPT and 30-day  ban that entity imposed (https://github.com/web-platform-tests/rfcs/issues/55) -   in the United States - which is a prima facie reprisal for exercising Rights guaranteed by the U.S. Constitution.

This site links to a document which does describe an appeals process:

3.5. Appeal of Chair Decisions and Group Decisions https://w3c.github.io/w3process/#WGAppeals

For the purpose of verifying administrative remedies (evidently non-existent in this case), is Web Platform Tests https://github.com/web-platform-tests a Working Group or Interest Group under W3C or its own independent organization?

**Comment by chaals** [comment]
It would appear the reference to the US Constitution is to the first amendment, adopted some time ago, that says

> Congress shall make no law respecting an establishment of religion, or prohibiting the free exercise thereof; or abridging the freedom of speech, or of the press; or the right of the people peaceably to assemble, and to petition the Government for a redress of grievances.

It doesn't seem that Congress has made any such law in relation to what WPT does, so I think the immediate issue is moot.

It also seems the Web Platform Tests project doesn't have a formal status as either a W3C Interest Group or W3C Working Group. I coudn't find the reference to the W3C Process, but in any event, W3C isn't Congress either.

I propose we close this process issue without further action - I don't see how it demonstrates anything to change in the Process.

**Comment by guest271314** [comment]
> It would appear the reference to the US Constitution is to the first amendment, adopted some time ago, that says

Including, but not limited to the First Amendment, as posted in every communication, Double Jeopardy, Substantive and Procedural Due Process which is discussed by this body

> The Team Contact must inform the Director when a group participant has raised concerns about due process.

> It doesn't seem that Congress has made any such law in relation to what WPT does, so I think the immediate issue is moot.

That is not true and correct. WPT operates in the Jurisdiction of the U.S., where Due Process is guaranteed by that document, whether the venue is an administrative process or municipal process or federal process, et al.

> It also seems the Web Platform Tests project doesn't have a formal status as either a W3C Interest Group or W3C Working Group. I coudn't find the reference to the W3C Process, but in any event, W3C isn't Congress either.

That is what asked. 

That must mean that WPT does not have a Team Contact with W3C in any documents.

**Comment by frivoal** [comment]
WPT is a project in which W3C participates, but it is not administered by W3C, and it is not a Working Group or an Interest Group. If you believe that WPT leadership has taken unjust action, and find yourself unable to resolve this by discussion, I suspect that reaching out to W3C ombuds may be useful: https://www.w3.org/Consortium/pwe/#ombuds. Even if WPT isn't under the jurisdiction of W3C, it is neighborly enough that discussion should be possible.

Note that the role of ombuds is not to take or overturn decisions, merely to help mediate.

**Comment by guest271314** [comment]
@frivoal 

> Message blockedYour message to ombuds@w3.org has been blocked. See technical details below for more information. | Message blockedYour message to ombuds@w3.org has been blocked. See technical details below for more information. | Message blocked | Your message to ombuds@w3.org has been blocked. See technical details below for more information.
> -- | -- | -- | --
> Message blockedYour message to ombuds@w3.org has been blocked. See technical details below for more information. | Message blocked | Your message to ombuds@w3.org has been blocked. See technical details below for more information.
> Message blocked
> Your message to ombuds@w3.org has been blocked. See technical details below for more information.
> The response from the remote server was:550 sender envelope address guest271314@gmail.com is locally blacklisted here. If you think this is wrong, please contact abuse-human

**Comment by guest271314** [comment]
Does it make sense to block messages to Ombuds?

**Comment by guest271314** [comment]
@frivoal 

> 
> Message blocked
> --
> Your message to xiaoqian@w3.org has been blocked. See technical details below for more information.
> 
> Message blocked
> --
> Your message to jeff@w3.org has been blocked. See technical details below for more information.
> 
> Message blocked
> --
> Your message to caroline@w3.org has been blocked. See technical details below for more information.
> 
> Message blocked
> --
> Your message to ralph@w3.org has been blocked. See technical details below for more information.
> 
> Message blocked
> --
> Your message to ralph@w3.org has been blocked. See technical details below for more information.
> 
> 

It does not make sense to block access to Ombuds by automation. The result is contrary to the purpose of having an Ombuds at all, or at least pretending to have Ombuds. 

Thank you for your reply. However, am not "satisfied" with the actual result. If possible, kindly remove that label from the issue, as that is not the case.

WPT is still blocking use to a w3.org site. W3C cannot be contacted. This is the same behaviour exhibited by WPT.

**Comment by dwsinger** [comment]
We're aware of the ombuds problem and looking into ways of addressing it.

**Comment by guest271314** [comment]
@dwsinger 

> We're aware of the ombuds problem and looking into ways of addressing it.

At least you acknowledge the problem of claiming to have an Ombuds body and process yet block access to that body and individuals.

The fix is simple. 

Do not block access to Ombuds or stop claiming to have Ombuds.

The alternative you maintain the status quo, acknowledge the problem without fixing the problem, and in the process turn then term ombuds on its head internationally.

**Comment by guest271314** [comment]
@jeffjaffe Have _**not**_ received a "Message blocked" email.
