### ISSUE TITLE
Name for Proposed Changes under patent review

### ISSUE THREAD

**Issue by fantasai** [w3c/w3process#408]
Process 2020 provides for an amendment process for RECs:
1. Changes are "proposed" by marking them into the spec so that they can be reviewed / evaluated / tested.
2. At some point a "last call for review of proposed changes" is issued identifying specific proposed changes for review by the AC and the lawyers.
3. Provided the changes are then accepted, the proposed changes are folded inline as in an updated REC.

We don't have a name for the identified changes, which can be a subset of all the proposed changes in a spec. It might be nice to have a name for them, to help us identify them as being the changes under review.

**Comment by dwsinger** [comment]
Since this is an amendment process, how about Amendment of Recommendation?

The words "draft", "candidate", "proposed", etc. can be used in front of this as needed; but we never publish an amendment per se, we publish an amended rec.

**Comment by fantasai** [comment]
Not sure I understand your comment. "Proposed Change" is currently a defined term, and when annotated inline, has to be marked as such. https://w3c.github.io/w3process/#proposed-changes

Problem is when some of these "proposed changes" are submitted for patent/AC review, we don't have a distinct name to mark them up with.

The issue with using [ draft | candidate | proposed ] is that we don't actually have three distinct stages, only two: A) WG approves the change, asks for wide review B) WG asks for AC/patent/Director's approval simultaneously so that it can be incorporated into an upcoming REC.

**Comment by dwsinger** [comment]
My suggestion is "Amendment of Recommendation". 

It can have any status keywords in front of it that we like (draft, editor's draft, proposed, revised, …)

**Comment by dwsinger** [comment]
If we don't want a name for the *bundle* but only for 'a change that we are asking to be approved' I think perhaps we need to keep the word 'proposed' for the step that asks for approval — it's been proposed to the AC for acceptance. 

Perhaps we need to use a pair of adjectives that we can apply to change:
* "candidate change" – the WG has consensus on the change, and is requesting implementation experience and comment;
* "proposed change" – the change has been sent to the AC for approval, and forms part of a PRD.

Inline changes marked as issues/errata and not formally identified as candidate or proposed changes are implicitly draft changes. A formal term is not needed (conceptually, they are something like "draft" changes).

Note that there may be inline issues warning of bugs or intended features that don't even have a draft change.

(I think 6.1.4 needs slight edits as well, but that should be separate).
