### ISSUE TITLE
Fast Track Submission to PR

### ISSUE THREAD

**Issue by sandhawke** [w3c/w3process#41]
I propose the creation of a "Fast Track Submission" process, in which one or more W3C members could submit a document, like a Member Submission, but including complete documentation of having following an open development process as good or better than W3C Rec Track.  This might be done in a CG, or somewhere else.  The documentation would be examined and verified by the Director (just like with normal Rec Track transitions, but with more verification), and if it passes, the document would be published as a Proposed Recommendation.  It would go through the normal AC review, and if it passes, it would become a normal Recommendation.

The horizontal and wide review requirements would prevent a FTS from coming completely out of the blue.   There might be other notification requirements, like the members declaring an intent to submit 90 days in advance, or something.

I can also imagine there might be a fee associated with the submission, or a minimum number of co-submitting members, to avoid this process being overly burdensome.   (Maybe this would happen before horizontal review, where some of the costs would be incurred.)

One staff member I mentioned this to said, "this will put me out of a job", to which I replied, "you can get a job consulting for these CGs".    But, really, don't think this will reduce the demand for WGs, just allow us to tap another kind of energy in producing Recs.

**Comment by dwsinger** [comment]
The current track means that the Patent Policy applies, and we go to some lengths to try to ensure broad membership of relevant bodies in the WG, so the commitment 'means something'. Would anyone be on the hook for the normally-RF commitment?  This feels a bit like the PAS process at ISO, as well, which hasn't worked too well for us. Lastly: is there a specific case that has arisen where this could work?

**Comment by michaelchampion** [comment]
I'm not clear on what problem a Fast Track to Rec would solve.  In JTC1, the Fast Track solves the problem of industry standards that have de facto credibility but are not de jure standards, hence can't be mandated for procurement etc.  W3C Recommendations don't have de jure status; any credibility they have is earned in the real world.  I'm not sure there's an actual problem of CG specs that have de facto support, the proponents want to turn into Recommendations, but the process is too burdensome.  Well-incubated specs that solve real problems and aren't burdened with a lot of politics can become Recommendations fairly quickly, as the Web Performance WG (for example) has shown.

The real value of W3C Recommendations as opposed to widely adopted CG specs (or "stuck in CR" WG specs) is the strong royalty-free patent commitment.  As @dwsinger notes,it seems unlikely that Fast Track specs will get broad patent commitments.  

So, I'd like to understand the rationale and "business case" for this proposal before considering it seriously.

**Comment by azaroth42** [comment]
As the chair of a CG that was fortunate enough to have the ear and support of @iherman at the critical moment of being almost finished with our work, but without an appropriate WG to feed into, I would say that yes there are indeed CG specs with support that benefit greatly from becoming a REC.  If it were not for the tireless efforts of our staff contacts, the Web Annotation WG that successfully concluded in February would not have had a chance.

I understand and support the royalty-free patent commitment. Exactly how any fast track process should work I leave to the process experts here, but anything that improved the odds of good work obtaining the support to either be pushed through a lighter weight process, or even get started more easily on the current process, I feel would be a great benefit to the community.

And to grind a particular axe, if it were easier to get into REC track and we could have more such tracks at any given time, we would have fewer kitchen-sink WGs that produce many little, overlapping and not-entirely-consistent specifications that have exactly two implementations each. Instead each of the specs could go through the same track separately and be evaluated on their individual merits.

**Comment by dwsinger** [comment]
I guess if the entire CG that developed the spec. were to sign the FSA, we then have a similar patent commitment from the group that developed the spec.  We'd need the same level of x-functional wide review, and the implementation commitment, tests and so on, and maybe it could work...

**Comment by chaals** [comment]
I'm unconvinced. While there are lots of specs that would benefit from becoming a Recommendation, the critical test is whether the Web would benefit from those specs becoming a Recommendation.

Key aspects in finding an answer are:
* the decision to charter formal rec-track work on those, which is taken after input from W3C as a whole;
* the wide review mandated by W3C Process, to ensure that there aren't obvious problems for the **world Wide** Web in adopting the specification;
* the requirement to demonstrate implementation experience and likely interoperability as part of the transition to Proposed Recommendation - and see also #32;

If the problem to be solved is that W3C is not proposing Rec-track work on important specifications, then I think the solution is to fix the operation of the Stategy area of W3C, whose responsibility this is, rather than circumvent the processes through a community group.

In particular, Community Groups are not answerable to the Process requirement for member review on whether work *should* be on the Rec track, and trying to scale the W3C horizontal review processes to cover the work of Community Groups who *may* put their work into such a fast track seems like a poor way to manage scarce but important resources that are part of the W3C "commons".

Were an FSA commitment to be provided by all participants, the IPR issue would indeed cease to be a problem, but that isn't the most serious concern I have with the proposal anyway.

**Comment by dwsinger** [comment]
I didn't want to imply that I was convinced (either way). I agree, there are a whole host of questions:
a) IPR (probably solved by an FSA, if it could be signed by all)
b) test vectors
c) wide review and cross-functional review
d) AC agreement that it should be a Rec
e) implementation experience
My guess is that the CG document would enter at the CR stage, not PR, and I am not sure that's much help. You may as well get the FSA and charter a WG to take it to Rec.

**Comment by sandhawke** [comment]
a) IPR: yes, the CG members could agree to something, and it might choose to set itself an even higher bar, including certain non-CG members who are seen as potentially having relevant IPR.

b) There's nothing about testing and interop that a WG does that a CG can't do just as well, and since that's already in the process for transitioning to PR, that would apply just the same.

c) Review is an interesting challenge.  More below.

d) AC agreement: well, yes, of course, that's why it's going in as a PR instead of instantly becoming a REC, so the AC can do their review-during PR thing.    It does raise an interesting question: assuming no objections, how many yes votes would be needed, and why?

e) Implementation experience -- same as (b), a CG can do this just as well as a WG, if it had the right expertise and motivation.

So, the only things I can see that a WG does that can't be done by a CG (or non W3C group, really) are (1) get public attention via W3C announcements and presence in /TR, and (2) demand the attention of a the horizontal review WGs. 

What's interesting about those two problems is they both scale rather poorly, as it is, within the REC track.  

On (1): in my experience, reviews virtually never come from people just reading w3.org.  If you're a WG who wants wide review, you have to make a real effort to reach out to the communities that care about whatever you're working on.  When you go to the transition meeting, you need to tell the Director all the venues you used to solicit review, and show you got that review.  Those are all things a CG (or whatever) could also attempt.  It might not succeed in getting sufficient attention without the blessing of a Charter, but I imagine if it were a serious enough effort, it still could.  In any case, this is a burden the CG would take on knowingly: "we're going to have to get wide review".

On (2): I don't have a great solution here.  So far, the Consortium has managed on the hard work of Addison Phillips and a few other die-hard horizontal-review volunteer experts.   (Is there a plan for the day Addison retires from this task? [Maybe start with a cake with ingredients from 196 countries?])  Two alternative models are self-review, like we do for security, and some kind of certification, with paid external professionals, like lots of other industries use.  But, bottom line, this could also be left to the group to convince the Director and then the AC that it has, in fact, had high-quality horizontal review in all the necessary areas.

Several people have asked me about the use case for this issue.  @azaroth42 gave one.  The one that opened my eyes to it is choosing not to come forward at this time.  

But really, my motivation here is my usual motivation: reducing unnecessary central control.  By its nature it's is stifling and, I think, corrupting.  It's like if Michelin only gave its stars to restaurants that also happened to hire its reviewers in the off-season. Controlling both production and certification, in a market without active competition, leads to an eventual decrease in quality.  The McDonalds stamp of approval, ... not so revered.

What I'm really proposing is a deep self-disruption, opening up the the spec-development part of W3C to competition.  This would require a significant strengthening of the spec-approval part of W3C, so that we could be sure of the quality without having been sitting in the kitchen the whole time.  That would be a lot of work.  It would, I think, pay off in the quality of specs (with real adoption) and magnitude of industry impact, but right now I don't see anyone who would want to fund that kind of investment.

**Comment by sandhawke** [comment]
Reviewing this, the blocking issue I see to this proposal are (1) the concern that it will over-tax the horizontal review resources and (2) it doesn't fit with the patent policy.

So here's a revised proposal: waive the requirement that a charter have support of 5% of the membership for groups that start with a Submission that is ready for PR, give or take horizontal review.

In other words, if a member has a spec that's already had wide review and has multiple interoperable implementations, and all the other things we expect to see in a PR, then they can charter a WG even if no other members support the charter.  The charter would basically say: wait as long as necessary for patent policy time-lines, while continuing to solicit and address public comments.  Staff resources would be minimal.

Still worried about resources?   How about a staff-resources + horizontal-review-resources fee, on the order of $20k?

**Comment by michaelchampion** [comment]
I'm still struggling to understand the problem this proposal would solve.  As @chaals notes above, "While there are lots of specs that would benefit from becoming a Recommendation, the critical test is whether the Web would benefit from those specs becoming a Recommendation."  This seems to be lowering the bar on that critical test.

Furthermore the proposal "How about a staff-resources + horizontal-review-resources fee, on the order of $20k?" is drifting too close to "buy a W3C rubber stamp to make your spec look more credible" for my tastes.  

IMHO  "a spec that's already had wide review and has multiple interoperable implementations, and all the other things we expect to see in a PR" is a NECESSARY condition for starting a WG going forward, not a sufficient condition.

**Comment by chaals** [comment]
@michaelchampion wrote

> Furthermore the proposal "How about a staff-resources + horizontal-review-resources fee, on the order of $20k?" is drifting too close to "buy a W3C rubber stamp to make your spec look more credible" for my tastes.

Agreed. If there is insufficient support in the membership for doing something along normal lines, making it easier to fast-track it for a cash payment seems to get all the incentives wrong.

I also continue to see this as solving a hypothetical problem, and by essentially providing a postitive motivation to doing work outside the Process, and then arguing that something is shipped and can't be changed, I think the proposal is more likely to bring additional problems for no real benefit.

**Comment by sandhawke** [comment]
@michaelchampion, you say

> IMHO "a spec that's already had wide review and has multiple interoperable implementations, and all the other things we expect to see in a PR" is a NECESSARY condition for starting a WG going forward, not a sufficient condition.

By "going forward" you mean this as a change in policy?  Clearly most charters to date haven't crossed this bar.  That would be quite an interesting change.

Does that mean that WG's will no longer be able to make substantive changes to a WD, in practice?   Or do you expect all the implementors to keep tracking all those substantive changes?  In my experience, folks are much less likely to support proposals that go against what they've already implemented and found to work just fine.

**Comment by jeffjaffe** [comment]
I don't see where Sandro has convincingly answered the skeptical comments from Mike, Chaals, or David.  I recommend that we close this issue.

**Comment by chaals** [comment]
Closed per agreement in call 2017-08-23
