### ISSUE TITLE
Remove the term "blacklisted" from W3C communications

### ISSUE THREAD

**Issue by guest271314** [w3c/w3process#415]
Include a Note in the specification that for any and all communication or list as defined in https://w3c.github.io/w3process immediately cease and desist using the term "blacklist" or "blacklisted" which implies "black" means "bad" or "no good", and if used "whitelist" or "whitelisted" which implies "white" means "good" or "not bad". 

Since the fraud of "race" theory has not been vetted in the United States, individuals and instritutions not infrequently use the terms "black" and "white" when referring to natural persons, while not bothering to look up the official definitions, where the only rational conclusion is that there is no such thing as either "black" "people" or "white" "people" or a "black" "race" or a "white" "race" based on the official U.S. definitions (no "white" "race" or "black" "race" officially exists in either France or Germany, those are archaic remnants of "the peculiar institution" of "custom of the country" in the U.S. that have literally life and death consequences on a second by second basis - right now), though nonetheless still use the terms and by doing so continue the ignorance and outright fraud associated  with the invented political classes "white" and "black", in brief see [The theory of “Black” “race” in the United States: “black racial groups of Africa” do not exist](https://medium.com/@guest271314/the-theory-of-black-race-in-the-united-states-black-racial-groups-of-africa-do-not-exist-d056f5ef82b8).

**Problem:**
The email address guest271314@gmail.com is blocked by W3C servers. A W3C Omsbud sent a message using their @w3g.org email and not the ombuds@w3c.org email. Clicked Reply in Gmail and received this email

> Delivery Status Notification (Failure)
> 
> Mail Delivery Subsystem <mailer-daemon@googlemail.com> 
> 
> 
> Message blocked
> --
> Your message to jeff@w3.org has been blocked. See technical details below for more information.
> 
> The response from the remote server was:
> 
> 550 sender envelope address guest271314@gmail.com is locally blacklisted here. If you think this is wrong, please contact abuse-human 

![Screenshot_2020-06-15_23-23-30](https://user-images.githubusercontent.com/4174848/84715639-933a1580-af60-11ea-90b3-f10127e4e480.png)

The term "blacklisted" is actually redundant in the communication. The header clearly states: "Message Blocked", thus negating the need to state that again in the manner printed, using the term "blacklisted", as if that term has an immutable negative connotation, and it is impossible for the user to simply re-define the term to mean "powerful", "beautiful", and by doing so take control of the term of art.

In order to not have such a schism, just use the term "blocked", or as already printed "Message blocked".

**Status quo and reform:**
Chromium is affirmatively taking a stand on the matter and working to cease and desist using such language from their source code [Issue 842296: Avoid the racially-charged terms "blacklist" and "whitelist"](https://bugs.chromium.org/p/chromium/issues/detail?id=842296). 

**Alternative:**
Continue using the terms "blacklisted", and if applicable, "blacklisted" in W3C  communications, under the proposition of Free Speech, which means that there are no "offensive" words, and thus, words are just words and left to the interpreter to determine if _they_ individually are "offended" oor not, and even if they happen to become emotionally affected by the term or terms, W3C is not in the business of determining what is "acceptable" or "not acceptable", meaning literally any and all supposed "Code of Conduct" and the like are moot due to that fact that there are no banned words in the English language, and no individual should be offended by mere words, therefore, logically, there is no "conduct" that any "code" can govern, nor any body that can tell another individual or institution which arbitrary words are "good" or "bad", because no such criteria objectively exists, which is also a rational conclusion

> Goebbels was in favor of free speech for views he liked. So was Stalin. If you’re really in favor of free speech, then you’re in favor of freedom of speech for precisely the views you despise. Otherwise, you’re not in favor of free speech. -Noam Chomsky

however, you cannot do both at the same time and not be hypocrites.

**Solution:**
Remove any and all usage of the terms "blacklisted" or "whitelisted" from W3C communications and lists, including but not limited to mailing lists and blocked messages.

**Comment by dwsinger** [comment]
We have dealt with the access to the ombudsman. We do not use these terms in formal communications. Since this issue does not raise anything that needs addressing in the process document, I am closing it.

**Comment by guest271314** [comment]
> We have dealt with the access to the ombudsman.

You did not do any favors by unblocking access to ombuds.

You merely conformed to a rational standard by allowing access to that body which should not have been blocked in the first place given the international understanding of the term ombuds.

That does not mean that you do not have other problems that you are failing to address. 

> We do not use these terms in formal communications.
That is not true. The evidence is in the issue. 

Have no other choice than to tell you directly that you individually and as an agent of the W3C organization are wrong, and in this case clearly hypocrites, as was blocked for using the term "nigger" while your organization uses the term "blacklisted".

**Comment by chaals** [comment]
I request that we re-open this issue. Who raised it is irrelevant, and the issue of access to the ombudspeople is irrelevant.

As the message clearly shows, we *do* use the term in at least the body of our 550 message responses - content that is designed as human-readable text to be presented as an explanation.

**Comment by chaals** [comment]
Made a request to the systems team regarding the specifics, and a request to the comms team in general.

**Comment by dwsinger** [comment]
thx

**Comment by chaals** [comment]
And the specific technical issue has now been fixed (there might be others, but there is someone watching for them now).

Thanks to W3C systems team for a fast response.

**Comment by LJWatson** [comment]
>That does not mean that you do not have other problems that you are failing to address.>

Just because they are not being addressed in this repository does not mean they are failing to be addressed. The W3C Inclusion and Diversity  Community Group is actively looking at a number of different actions that can be taken to address inequities like the one you mention.
