### ISSUE TITLE
Consolidate discipline-related elements

### ISSUE THREAD

**Issue by koalie** [w3c/w3process#418]
Hi!

In digging for information relating to discipline, I found two such places in Process 2019:

* [Section 3.1 Individual Participation Criteria](https://www.w3.org/Consortium/Process/#ParticipationCriteria)
* [Section 2.1.1 Rights of Members](https://www.w3.org/Consortium/Process/#MemberBenefits)
This is in this section that contains a link to “[Guidelines for Disciplinary Action](https://www.w3.org/2002/09/discipline)”

While the latter needs an update and I have followed-up separately with W3M to do so, I would like to raise the question of consolidating the two Process document places that touch on discipline. 

I think it would make more sense to do so in section 3.1 Individual Participation Criteria which is broader than 2.1.1 Rights of Members.

**Comment by dwsinger** [comment]
Indeed this in 2.1.1:

>The rights and benefits of W3C membership are contingent upon conformance to the processes described in this document. The vast majority of W3C Members faithfully follow the spirit as well as the letter of these processes. When serious and/or repeated violations do occur, and repeated attempts to address these violations have not resolved the situation, the Director may take disciplinary action. Arbitration in the case of further disagreement is governed by paragraph 19 of the Membership Agreement. Refer to the Guidelines for Disciplinary Action.

could become

>The rights and benefits of W3C membership are contingent upon conformance to the processes described in this document. Arbitration in the case of further disagreement is governed by paragraph 19 of the Membership Agreement. Disciplinary action for anyone participating in W3C activities is _described below_.

and 3.1 was
>Participants in any W3C activity must abide by the terms and spirit of the W3C Code of Ethics and Professional Conduct and the participation requirements described in section 6 of the W3C Patent Policy.
>The Director may suspend or remove for cause a participant in any group (including the AB and TAG), where cause includes failure to meet the requirements of this process, the membership agreement, or applicable laws.

and becomes:
>Participants in any W3C activity must abide by the terms and spirit of the W3C Code of Ethics and Professional Conduct and the participation requirements described in section 6 of the W3C Patent Policy.

>When serious and/or repeated violations do occur, including failure to meet the requirements of this process, the membership agreement, or applicable laws, and repeated attempts to address these violations have not resolved the situation, the Director may take disciplinary action, including suspending or removing for cause a participant in any group (including the AB and TAG). Refer to the Guidelines for Disciplinary Action.

The text in 3.1 before 3.1.1 could usefully have a section title.

**Comment by nigelmegitt** [comment]
> could become
> 
> > The rights and benefits of W3C membership are contingent upon conformance to the processes described in this document. Arbitration **in the case of further disagreement** is governed by paragraph 19 of the Membership Agreement. Disciplinary action for anyone participating in W3C activities is _described below_.

Yes if we remove the text I emphasised in bold above: "in the case of further disagreement". The reasons why arbitration might be needed are hard to write down, and I think are not needed. The point is that there _is_ an arbitration term, and a pointer to it is useful.

What drew me to this was when I read "further disagreement" I couldn't work out what the disagreement was further _to_. I thought, perhaps this means "unresolved disagreement", but that sounds weird. Maybe "ongoing disagreement" is closer, but how long is "ongoing"? And this wording doesn't give the sense that you don't go for arbitration if you have two mutually incompatible views on some specification wording - it's about something else altogether more serious than that kind of disagreement.

**Comment by frivoal** [comment]
The above makes sense to be. While we're at it, I'm also wondering if the beginning of 3.1 (the 2 paragraph and the number list before the part that @dwsinger quoted) actually do anything useful. Maybe we can get rid of them while we're at it?

**Comment by dwsinger** [comment]
I think they are appropriate; they put a responsibility on AC Reps to make sure they send suitable people.

**Comment by koalie** [comment]
(While I'm tuning to related some disciplinary action documentation, I'd like to note this issue is related to #274)

**Comment by dwsinger** [comment]
Indeed, if there is anything in #274 worth salvaging, we could deal with it at the same time.

**Comment by frivoal** [comment]
Created a PR doing the things discussed above: https://github.com/w3c/w3process/pull/432

I addition, we could:
* drop the references for Guidelines for Disciplinary Action, as suggested in #274 as discussed inhttps://github.com/w3c/AB-private/issues/96
* drop the beginning of 3.1.1, as suggested in https://github.com/w3c/w3process/issues/418#issuecomment-657918156, though @dwsinger disagrees in https://github.com/w3c/w3process/issues/418#issuecomment-658214438. Personally, I don't think that text is wrong, but it feels like a micro-CEPC, and since we have a full one, I don't think it accomplishes much, so we could trim a bit. But it I'm alone in this view, I'll yield, this isn't important to me.
