### ISSUE TITLE
What's the point of what the Process has to say about Liasons?

### ISSUE THREAD

**Issue by frivoal** [w3c/w3process#422]
The first two paragraphs and the last paragraph of [Section 9](https://w3c.github.io/w3process/#Liaisons) speak about Liaisons.

Given that Liaisons are defined to cover a broad range of possible relationships with other organizations, and that no particular kind of relationship with other organizations has to be called Liaisons, it's not clear to me that "All liaisons must be coordinated by the Team" (which is the only normative statement) has any teeth.

I suspect we could delete these three paragraphs from the Process and not notice that anything has changed. Given the complains about the process being too long, maybe we should indeed remove them.

A page like https://www.w3.org/2001/11/StdLiaison does a better job of explaing what Liasons are, which one currently exist, and how to set up new ones. It probably would benefit from more visibility on the W3C website, but the w3c website redesign is probably a better means of surfacing it than advertising it in the Process.

**Comment by jeffjaffe** [comment]
@frivoal I agree that we should simplify Section 9.  The first two and last paragraph can probably be collapsed into one paragraph - the current second paragraph is the one with normative importance.

W3C is accustomed to working in an informal fashion which might hide the benefit of the second paragraph, but we work with a vast array of other organizations.  For those who are more formal, the linkage in the process is significant.

We should also explore whether we need an entire section on Liaisons, or whether this better fits (e.g.) as a part of 2.2.

**Comment by nigelmegitt** [comment]
Seems like a sensible area to look at. I believe W3C has an agreement with ISO/IEC about the standing of Recs as international standards. We should check that changing or removing the liaisons section has no impact on that agreement.

**Comment by dwsinger** [comment]
Um, W3C isn't very liaison oriented, true, but they mean a lot to other organizations and maybe therefore to us.

A liaison relationship usually gives reciprocal rights to join groups and attend meetings, outside normal membership rules. It also enables each organization to provide documents (I know, W3C is not contribution-document-based in its workflow) into the other group.

So, you'll have people attending meetings not as an IE, or as a member rep., but as a liaison rep. from a liaison organization; and we could (and probably should in some cases) appoint a liaison rep. the other way, someone who can attend their meetings on behalf of the W3C.

**Comment by frivoal** [comment]
@dwsinger no question that Liaisons are important. What I'm questioning is the existing text about them: seems a lot of words with very limited normative effects.

Took a first stab at the suggestion from @jeffjaffe in https://github.com/w3c/w3process/pull/433. For now, I've only collapsed/move the part about Liaisons themselves, leaving the text on MoUs unchanged. Maybe we can reduce that as well.

**Comment by frivoal** [comment]
> A page like https://www.w3.org/2001/11/StdLiaison does a better job of explaing what Liasons are, which one currently exist, and how to set up new ones. It probably would benefit from more visibility on the W3C website, but the w3c website redesign is probably a better means of surfacing it than advertising it in the Process.

The website has been redesigned, and I think that the page now does indeed do a better job of explaining Liaisons than the Process does.

I remain of the opinion that while Liaisons are a good thing, what the Process has to say about them does not achieve anything.

Here is everything it has on the topic :
> W3C uses the term liaison to refer to coordination of activities with a variety of organizations, through a number of mechanisms ranging from very informal (e.g., an individual from another organization participates in a W3C Working Group, or just follows its work) to mutual membership, to even more formal agreements. Liaisons are not meant to substitute for W3C membership.
>
> All liaisons must be coordinated by the [Team](https://www.w3.org/2023/Process-20231103/#team) due to requirements for public communication; patent, copyright, and other IPR policies; confidentiality agreements; and mutual membership agreements.
>
> […]
> Information about [W3C liaisons with other organizations](https://www.w3.org/2001/11/StdLiaison) [[LIAISON]](https://www.w3.org/2023/Process-20231103/#biblio-liaison) and the guidelines W3C follows when creating a liaison is available on the Web.

I struggle to see anything that:
* is enabled by this text, which we couldn't otherwise do
* is required by this text, which we would otherwise be free to skip

The middle paragraph comes closest, except that the lack of a definition for Liaisons makes it toothless. 

My inclination would be to:
* Remove these 3 paragraphs from the Process
* Let https://www.w3.org/2001/11/StdLiaison be our main documentation about Liaisons

**Comment by dwsinger** [comment]
I would prefer to define liaison relationship as something which gives and grants rights, has a process for establishing, and so on. Have a look at [ISO/IEC liaisons](https://www.iso.org/sites/directives/current/consolidated/index.html#_Toc134090804); there are rules about how they are set up, and what they grant and get. (We don't need the categories at W3C.) Typically, some sort of agreement of the WG, AC, and/or management would be needed; ability to work in and contribute to a WG; rules about how the patent policy applies; the right to attend and contribute to the reciprocal WG in the liaising organization, and so on.

**Comment by joshco** [comment]
Agree with keeping this section and expanding it.   On the website liaison page, there aren't links to the actual documents that describe the liaison and associated work items.   What also seems to be missing is a description of the process one must follow in order to create a liaison, what information needs to be provided, or the process for how it is approved (or not).

For another take on this, the DMTF calls these "alliances" and the relationship/work items are captured in a document called a "work register".  

The list of alliances and work registers can be found here:
> https://www.dmtf.org/about/registers#sdoalliances

As an example, here is the Work Register that defines the relationship and work items between DMTF and SNIA (A storage SDO):
> https://www.dmtf.org/sites/default/files/DMTF-SNIA_Work_Register_v1.5.pdf

The DMTF process defining alliances and how they are proposed, used is here:
> https://www.dmtf.org/sites/default/files/standards/documents/DSP4003_1.9.0.pdf

**Comment by TallTed** [comment]
Also, it should be (easily) possible for WG and CG chairs, if not all participants, to learn who is the liaison with any given liaised organization, and what to do to enlist them in some crossover issue (e.g., IETF has a number of RFCs that collide with various CRs, PRs, and even TRs; how are these collisions to be resolved?). I think it would be worth at least linking out from the Process to the relevant area or page in the W3C site where those liaisons are listed (optimally sortable/searchable by external organization, liaison name, liaised W3C groups, and maybe more).

**Comment by samuelweiler** [comment]
> Also, it should be (easily) possible for WG and CG chairs, if not all participants, to learn who is the liaison with any given liaised organization, and what to do to enlist them in some crossover issue (e.g., IETF has a number of RFCs that collide with various CRs, PRs, and even TRs; how are these collisions to be resolved?). I think it would be worth at least linking out from the Process to the relevant area or page in the W3C site where those liaisons are listed (optimally sortable/searchable by external organization, liaison name, liaised W3C groups, and maybe more).

That table is at https://www.w3.org/liaisons/  IMHO, it does not belong in the Process.  The Process need not be an index to the w3.org website, especially for not-Process things.

**Comment by dwsinger** [comment]
agreed, the table should not be in the process. but it existing is good
