### ISSUE TITLE
W3C Membership should be as simple as Google Individual Contributor License Agreement: "real name" is not defined or restricted in W3C documentation

### ISSUE THREAD

**Issue by guest271314** [w3c/w3process#426]
Some time ago Web Speech API changed ownership from W3C to WICG. Was advised to sign up for Membership in W3C and WICG in order to make substantive contributions to that repository, and similarly, to Native File System repository.

After  signing up to become member of W3C and WICG  the claim was made that "guest271314" was not a "real name" and summarily Membership in W3C  and WICG was revoked, TL;DR https://lists.w3.org/Archives/Public/public-wicg/2019Oct/0000.html. Have still yet to locate _any_ official W3C documentation defining the term "real name", so am not sure what the individuals in the above communication are actually referring to re "real name".

While running https://github.com/GoogleChromeLabs/web-audio-samples noticed that `Atomics.wake()`, which is deprecated per  is being used in the code instead of `Atomics.notify()`. Filed a PR to update the code https://github.com/GoogleChromeLabs/web-audio-samples/pull/198. A message appeared linking to a CLA, which autographed

> Agreement | Name | Date Signed | Manage
> 
> Google Individual CLA | guest271314 | Jul 19, 2020 07:51 PDT | Edit Contact Information

There was no sensationalism by the bot about the real name "guest271314" being used to sign the agreement.

W3C process for Membership, and "IPR" for the ability to make substantive changes to W3C repositories should be as simple as the "Google Individual Contributor License Agreement" https://cla.developers.google.com/about/google-individual.

After a modicum of research found a W3C publication authored by a user, Editor, with a "real name" similar to "guest271314". 

> WebAssembly JavaScript Interface
> Editor’s Draft, 13 July 2020
> This version:
> https://webassembly.github.io/spec/js-api/
> Latest published version:
> https://www.w3.org/TR/wasm-js-api-1/
> Issue Tracking:
> Inline In Spec
> GitHub Issues
> Editor:
> Ms2ger (Igalia)
> Copyright © 2020 W3C® (MIT, ERCIM, Keio, Beihang). W3C liability, trademark and permissive document license rules apply.
> 

![Screenshot_2020-07-19_15-16-16](https://user-images.githubusercontent.com/4174848/87878377-5b951200-c9d3-11ea-9c15-ccb8239a39a3.png)

Either an exception was made for that individual, which is also not clear how that occurred, or W3C was simply mistaken by characterizing "guest271314" as not being a "real name". Important: This is not intended to in any way change or disparage the status of the Editor in the above linked document with regard to W3C, merely to point out that on its face the revocation of Membership in W3C and thus WICG could be viewed as hypocritical, or selective discrimination based on what one or more individuals happen to consider a "real name", without reference to an official document verifying such a narrow interpretation of the term "real name".

The change to a simple CLA, similar to how Google processed the CLA in seconds, will avoid problems with W3C Members or Management attempting to claim "guest271314" is not a "real name", where, again, have not yet located anywhere the term "real name" clearly defined, and thus not restricted, by any W3C documentation.

**Comment by guest271314** [comment]
cc @Ms2ger Mentioning your name so notifying you about the reason therefor

**Comment by guest271314** [comment]
A recent Issue https://github.com/w3c/mediacapture-fromelement/issues/86#issuecomment-655486961 closed due to "IPR" issues

> I think this passes the limit for "substantive contribution", which we cannot accept from someone who has not agreed to the IPR rules for the WG. Closing.

where had to file a PR just to get W3C to clearly indicate "IPR" was intended to be an acronym for "Intellectual Propery Rights" https://github.com/w3c/ash-nazg/pull/162.

If W3C is going to use acronyms, those acronyms need to be clearly linked to the full corresponding definition of the letters. If W3C Members or Management are going to make the claim that _any_ name is not a "real name" then W3C needs to clearly define "real name", else, individuals are merely relying on hearsay and folklore as to what "real name" means, or worse, akin to the historical events of invading armies colonizing native peoples and claiming they did not have "Christian" names, therefore they must be renamed "John Smith" or "Jane Doe", as an extreme example of those historical events, the 330,000 individuals supposedly shipped to the British Colonies that would become the U.S., from Africa, were forbidden from speaking their native tongue, given "Christian" names, resulting in few if any of the descendants in 2020 speaking their native tongue, essentially brainwashing that population - for their own good, of course, per the U.S. Supreme Court in Scott v. Sandford, 60 US 393 (1857)

> They had for more than a century before been regarded as beings of an inferior order, and altogether unfit to associate with the white race either in social or political relations, and so far inferior that they had no rights which the white man was bound to respect, and that the negro might justly and lawfully be reduced to slavery for his benefit. He was bought and sold, and treated as an ordinary article of merchandise and traffic whenever a profit could be made by it. This opinion was at that time fixed and universal in the civilized portion of the white race. It was regarded as an axiom in morals as well as in politics which no one thought of disputing or supposed to be open to dispute, and men in every grade and position in society daily and habitually acted upon it in their private pursuits, as well as in matters of public concern, without doubting for a moment the correctness of this opinion.
> 
> And in no nation was this opinion more firmly fixed or more
> 
> Page 60 U. S. 408
> 
> uniformly acted upon than by the English Government and English people. They not only seized them on the coast of Africa and sold them or held them in slavery for their own use, but they took them as ordinary articles of merchandise to every country where they could make a profit on them, and were far more extensively engaged in this commerce than any other nation in the world.

In essence, by claiming that "guest271314" is not a "real name", W3C is claiming that a different name be used for the individuals' (or corporate person W3C) own benefit. 

Another example is the artist Prince using the symbol 
![800px-Prince_logo svg](https://user-images.githubusercontent.com/4174848/87878968-3efad900-c9d7-11ea-9585-46bbde90fc26.png)

following a contractual dispute. 

Individuals possess the Natural Right to determine their own name.

**Comment by fantasai** [comment]
I will note that, despite having never been published, Ms2ger's legal name was known by the limited set of people necessary to handle required legal paperwork. As for the legal requirements, I defer to @wseltzer ; outside of them, however, there should be no Process limitations on using a dedicated pseudonym, and I don't believe there are any.

**Comment by wseltzer** [comment]
W3C's [royalty-free patent policy](http://www.w3.org/Consortium/Patent-Policy/) and CGs' [CLA](https://www.w3.org/community/about/process/cla/) depend on an assurance that the person making contributions to a W3C specification has the rights and authority to make royalty-free licensing commitments, and can stand behind those assertions. W3C can accept stable public pseudonyms if we have that assurance though another channel, such as by an employer vouching for a member-representative, or by the person's communication with a member of W3C's management. 

This is not an issue of "real names" but rather legal commitment.

**Comment by guest271314** [comment]
> W3C's royalty-free patent policy and CGs' CLA depend on an assurance that the person making contributions to a W3C specification has the rights and authority to make royalty-free licensing commitments, and can stand behind those assertions.

Frankly, W3C, nor any other organization has anything I want or need. Already have all that I need: knowledge of self. 

Am not interested acquiring any fiat currency or other item of value from W3C.  Am interested in contributing to certain repositories or group discussions; adding on, not taking away - unless the language in a specification needs to be repealed. Here to add on, not take away.

Am a natural person with natural rights, possessing full authority to make own decisions, unencumbered by any other legal obligations. Yes, stand behind every word that type, word is bond, here. Have done so consistently across multiple platforms for a number of years now. Stand behind and in front of every moral, historical, scientific and technical or other document that have published, which all cite primary sources, or self, when applicable; to the degree that have been banned from multiple platforms, without recanting or shunning the responsibilities concomitant to publishing primary source facts and conclusions reached using the scientific method. If any individual on this planet contests the above, prove me wrong by repudiating the facts that have published on the record.

> W3C can accept stable public pseudonyms if we have that assurance though another channel, such as by an employer vouching for a member-representative

The industries that practice my professions in outside of reasearch and technology are far removed from this domain. When am not working for self in still other industries, the multiple employers that do have by necessity understand that am engaged in multiple disciplines, if only because one or more have to coordinate and get in  line for the work that I do. Those employers are not in the technology domains, though, if necessary beyond the signature of /guest271314/ could probably draft a note to describe work ethic, blunt unwavering honesty, consistency, and commitment to getting the job done, in conditions that can be both perilous and physically demanding, while still requiring careful thought to complete the given task intended to last at least 30 years.

>  or by the person's communication with a member of W3C's management.


> or by the person's communication with a member of W3C's management.

@jeffjaffe can at least attest to that fact am a real natural person. We had a discussion recently where that individual fulfilled their duties as Ombuds professionally. As advise them at the time, everything that post is PUBLIC DOMAIN. Will not claim some part and parcel of some words that print in order to gain something of value, or at least what some might consider valuable via some patent claim. That is not what am here for. Own own trademark and wrote own patent claim. Gather the domain, and again, am not interested in aspect of contributing to specifications. Just  trying to provide a different perspective to avoid myopic policies and outcomes.

Do we need to schedule a one-on-one or conference call to, again, prove that am a real natural person? When you hear my voice you will immediately understand that do not play games, do not tolerate intellectually lazy individuals, and keep my word. No one on the interwebs can refute those facts. In fact, no one can even answer some of the questions that have posed to the entire world, due to the extent to which developed expertise in certain subject matter; e.g., as a matter of both logic and law, I defy any individual to answer the questions presented at [The theory of “Black” “race” in the United States: “black racial groups of Africa” do not exist](https://medium.com/@guest271314/the-theory-of-black-race-in-the-united-states-black-racial-groups-of-africa-do-not-exist-d056f5ef82b8) and [The theory of “White” “race” in the United States: “North Africa” and “Middle East” do not exist.](https://medium.com/@guest271314/the-theory-of-white-race-in-the-united-states-north-africa-and-middle-east-do-not-exist-72026901591d), which will ultimately reveal the person behind the articles when those same questions are filed in the Supreme Court of the United States to finally get rid of the fraud of "race" theory and the absurb theories of "black" "race" and "white" "race" in the United States.

If you want to verify any of the above, we can make an appointment to conference call, and will reiterate the above.

> This is not an issue of "real names" but rather legal commitment.

Yes, gather that. /guest271314/ is sufficient globally for an autograph or signature. No one else uses that name, and no one can imitate the decades of studying that have performed and continue to perform.

**Comment by guest271314** [comment]
I am certain that we have concluded that the claim of /guest271314/ not being a "real name" in the linked mailing list discussion is baseless, not backed by any W3C documentation, pure conjecture promulgated by the agents of W3C that made such baseless claims.

Should not have to fill out any Membership applications again. The ones that did fill out should be binding now, given the reason given for revocation of Membership, specifically that /guest271314/ is not a "real name" is not true and correct, legally. 

Correct your own error.

**Comment by dwsinger** [comment]
> Despite having never been published, I do believe Ms2ger's legal name was known by the limited set of people necessary to handle required legal paperwork. As for the legal requirements here, I defer to @wseltzer ; outside of them, however, there should be no Process limitations on using a dedicated pseudonym, and I don't believe there are any.

Indeed, and not only was ms2ger's real name known, the entity taking on the IPR agreement is clear: Igalia, with whom there is a clear reciprocal agreement that they are employed.

> Editor: Ms2ger (Igalia)

**Comment by dwsinger** [comment]
Expecting to close, as the document that this group manages, the [W3C Process](https://www.w3.org/2019/Process-20190301/) has no mention of names (personal, real, legal, or any other) and hence there is nothing actionable for the Process CG.

**Comment by guest271314** [comment]
> Expecting to close, as the document that this group manages, the W3C Process has no mention of names (personal, real, legal, or any other) and hence there is nothing actionable for the Process CG.

Did you actually take the time to read the OP and attached documents?

Already signed up for W3C Membership so as to join WICG. 

One or more official agents or individuals acting in a capacity of agent of W3C revoked Membership in W3C citing specifically that /guest271314/ is not a "real name".

"Process" is prima facie "Due Process" subject matter. 

You are precisely correct. Given "real name" is not defined the revocation of W3C Membership based on that claim, and directly adversely impacted the "process", both W3C process, by agents or individuals acting in capacity of W3C agents acting on behalf of W3C, acted deliberately to invent an arbitrary scheme to deny /guest271314/ Membership in W3C; in this case using the term "real name" as the exact reason for revoking the W3C Membership that W3C had already officially granted to /guest271314/, violating Substantive and Procedural Due Process - of your own organization. 

The very fact that you state there is no mention of names should give you pause. One or more individuals in your organization, acting under W3C process or practice, representing W3C, revoked the officially time-stamped Membership. Yet, your post ignores that fact. Perhaps you do not have confidence in the integrity of your organization, or you simply expect such false claims using your organization as a vehicle to deny process to a Memeber as something for someone else to deal with, or not deal with at all, because you do not care in the least, except for what you deem important. Where individuals have no moral integrity as to their work, who they work for, or what someone else in the organization does. Not your problem. That is the clear indication of a corrupt organization. 

Who knows how many other individuals have invented fraudulent claims as to the "process" of joining W3C? You don't care, "name" is not a term used in the language in Process document. That means you do not really care about W3C integrity. Good to know.

At some point either the individuals that suggested themselves to join the organization, or some other agents of the organization don't like how direct I talk, without apologies, and citing primary sources, or whatever contrived reason they might have conjured, that they simply did not want /guest271314/ in W3C, so, under the auspices of being an agent of W3C, said /guest271314/ is not a "real name"? 

Good enough ain't good enough.

**Comment by guest271314** [comment]
@dwsinger 

> W3C membership is open to all entities, as described in "How to Join W3C"; (refer to the public list of current W3C Members). Organizations subscribe according to the Membership Agreement. The Team must ensure that Member participation agreements remain Team-only and that no Member receives preferential treatment within W3C.

**Comment by dwsinger** [comment]
Please do not attribute motives to others, or use derogatory language, including for example describing actions as "fraudulent", or make accusations against people.

This issue will close unless there is a suggestion that the document this group manages needs revision.

**Comment by guest271314** [comment]
@dwsinger You do not get it. 

Evidently your organization as a whole does not get it. 

Instead of actually gathering the issue raised and doing something about it, you make some mention about "deragatory language". Well, English is an equivocal language. Any individual can pick any word and assign some value to it that someone else has full discretion to reject. In this case reject your characterization of "fraudulent" as being "derogatory language". 

And yes, based on the evidence, the exact motives are unknown, what is known is there was was not malice based on the fact no such term as "real name" is found in your documents, there was at least gross incompetence, followed by non-action here.

You do not own the English language. 

The behaviour was fraudulent. Deceptive. Misleading. Incorrect. 

Yes, will directly accuse any individual or institution of fraudulent behaviour when the empirical evidence demands such attribution, until proven otherwise. What is revelaing is you do not state that what occurred to me was incorrect, or that you have any inclination to remedy the error internally. What you are suggesting is that accusing the U.S. of genocide and being a "white supremacist", clearly evident per the Dred Scott case, military organization, would be improper, irrepsepctive of the over 200 years of historical evidence that proves was the case at inception and is the case now. Take for example, the Indian Removal Act of 1831. You cannot remove the title of that Act from history. The U.S. actually debated, thought about, the genocide they were going to perpetuate, and gave the bill the appropriate title to fit their thrust for conquest at the expense of the Sovereign People of Turtle Island. But, you would cite the correct attribution of terrorist, military organization as "deragtory". Well, yes, the behaviour is the opposite of non-deragatory.

In this case a fraudulent reason was contrived to revoke Membership in W3C. I have no evidence that the error was merely a mistake, because nobody in your organization has corrected the error. Thus, your entire organization is fraudulent in nature, for neglecting to correct a clear error. You change that assessment by acknowing the error and fixing the problem, not by trying to assert "fraudulent" is a "deragotory" word; a common distraction tactic. Don't perform fraudulent acts and the evidence will not be there to substantiate that claim. I have no evidence to the contrary, as the problem has not been fixed. I don't budge.

This issue has demonstrated that your organization simply does not posses the administrative personnell necessary to address this issue. All I want to do is file a PR, not fix your internal problems. Yet your internal problems are here so glaring that they cannot be ignored, just to post a PR.

Will save you the effort that you have not put forth anyway. Am far less than impressed by your inaction here. 

Cheers, /guest271314/
