### ISSUE TITLE
Clarify Process for Publishing Statements from the W3C 

### ISSUE THREAD

**Issue by wareid** [w3c/w3process#429]
https://www.w3.org/2014/01/PSGMatrix
https://github.com/w3c/idcg/issues/25

We don't have a clear process for how to get public-facing statements out from the W3C in a timely and process-friendly fashion. The PSG Matrix appears to be an incomplete document with little guidance for how to get an issue through necessary review before publishing. It also it not really clear on what members or groups can or cannot say, or how they can get something in front of the W3C for distribution. 

The issue from IDCG above is related to this as well as the process document, as we run into issues on how we manage comments, handle changes as they're offered, and then get those in front of the AC/AB/any body that needs to review. Right now it appears that the clock is essentially reset on each revision, which can be problematic for anything that needs to be timely. 

We ran into a similar issue with publishing the CEPC, where the group struggled with what to do about comments, wanting to respect the commenters' reviews while also release a long-awaited document (even more fraught when the suggestions are small but the process hurdle is big). 

In both scenarios, process has created roadblocks for us, it's been confusing and difficult to manage comments, and creates huge delays. I wanted to open this issue to ask the Process CG to look into where process can be clarified or amended to ensure we don't run into the same struggles again. 

Asks: 
* Clarify process for groups/individuals/the W3C to make public-facing statements 
* Clarify process for how comments are to be handled during AC review

**Comment by jeffjaffe** [comment]
Thanks @wareid for raising a timely topic.

Here is how W3M approached the IDCG statement.  We felt that any proposed statement should have the support of the Director and then go to AC review.  This is in line with anything "official" that W3C does (e.g. charters, recommendations, changes to process, changes to CEPC).

After the IDCG came up with their draft statement, and informed W3M of the urgency, W3M approved (with delegated authority from the Director) sending the statement for AC review.  Currently, the statement has gone to AC review.  As with any other AC review, we are looking for comments, consensus, and will need to deal with objections.

I don't know of any faster way to do this, but I think it is a good idea that you have teed up that question to the Process CG.

You also asked in this issue about guidance for Members making public statements.  Generally speaking, if Members are speaking for themselves, they can say whatever they want.  They cannot say things in the name of W3C, but they are not restricted from making their own statements.

The one exception would be anything related to Member confidential information.  That should not be shared publicly.  For example, if one Member comments on the current BLM survey, their comments should not be repeated publicly by others without their permission.

**Comment by fantasai** [comment]
AFAICT: Statements on behalf of W3C are out of scope for the Process, and are handled under delegation from the Director. Following standard W3C practices, W3M wanted to get AC approval for such a statement. The Director is responsible for responding to those comments prior to deciding on whatever final statement, if any, W3C will publish. The Director and W3M could decide to publish anything they want, including but not limited to what IDCG proposed, but will constrain themselves according to their good judgement informed by the comments of the IDCG and the AC.

**Comment by frivoal** [comment]
This issue has been partly answered by https://github.com/w3c/w3process/pull/489. See https://www.w3.org/Consortium/Process/Drafts/#memo for the current text, in context.

There is now a defined process for issuing a statement with the backing of W3C as a whole, as long as the statement you'd like to issue is within the scope of a WG, IG, TAG or AB. This is more intended to be used for things like the TAG's Ethical Web Principles or their Web Platform Design Principles than for political statements, but the Process itself only constrains how you create one of these, not what it is supposed to be about.

Also, given that the scope of the AB and TAG are largely self defined, these two groups can use the process to (propose to the AC to) issue statements on whatever topic they'd like to take up.

Now, if you'd like to issue a statement that is not in the scope of any WG or IG, and neither the TAG nor AB are willing to sponsor that work, the Process isn't covering it anymore. But as @fantasai said, the W3C staff can, within the limits imposed by their hierarchy (currently toped by the Director), put up material on the W3C website (and can ask the AC's advice along the way if they feel that would be appropriate).

Personally, I think this is sufficient. @wareid, do you agree to close the issue on that basis, or do you think there's more we ought to be looking at?

**Comment by tobie** [comment]
I think one of the key points of @wareid's initial request is to be able to issue such a statement in a *timely* fashion. Although #489 clearly provides a process for releasing statements, the requirements of this process imply that actually publishing it will take weeks if not months.

This leaves W3C enable to take a stand and lead on critical issues that affect the Web and the broader tech ecosystem. This creates the unfounded impression that W3C is out of touch and that the future of the Web lies elsewhere.

No amount of process that requires broad review and AC approval prior to making a statement will enable the kind of agility necessary to provide real leadership in today's world. Only a strong set of shared values and a framework to apply them to relevant current events can do that.

The good news is that we're really starting to have this conversation about values beyond the TAG and into the AB and AC. The bad news is this will take a substantial amount of time until we're able to turn these conversations into a full resolution to the original issue.

  \* * *

Concretely, #489 solves part of this problem (when the response doesn't need to be timely), but not the whole of it. Solving the whole problem is broader than just figuring out process or it. I believe the following would need to be determined:

1. what values the organization holds,
2. how can these values inform a process that lets the organization make timely comments to relevant issues without broad consultation of its membership,
3. what body is responsible for approving such comments,
4. how are these decisions audited, and
5. how that body is held accountable for them.

I'm not too sure *where* this discussion should take place (AB? AC?). I'm of the opinion that once that's figured out and a corresponding issue is filed there (and linked from here) this issue could be closed. I'm not the one who opened that issue however, nor am I a member of this CG, so please don't act on my opinion alone.

**Comment by jeffjaffe** [comment]
> Now, if you'd like to issue a statement that is not in the scope of any WG or IG, and neither the TAG nor AB are willing to sponsor that work, the Process isn't covering it anymore. But as @fantasai said, the W3C staff can, within the limits imposed by their hierarchy (currently toped by the Director), put up material on the W3C website (and can ask the AC's advice along the way if they feel that would be appropriate).

Just to clarify, the W3C staff is also limited by W3C's Public Speaking Guidelines (https://www.w3.org/2014/01/PSGMatrix)

**Comment by frivoal** [comment]
> Concretely, #489 solves part of this problem (when the response doesn't need to be timely), but not the whole of it. Solving the whole problem is broader than just figuring out process or it.

I agree. There's more to it than #489, but my impression is that #489 is as much as we can do about it *as far as the Process is concerned*. My suggestion is merely to close it as an issue against the Process, not end the overall discussion. But if you or @wareid thinks it should stay open, I have no issue with that.

**Comment by tobie** [comment]
> My suggestion is merely to close it as an issue against the Process, not end the overall discussion.

I think you and I are in agreement about this. What I'm seeking advice for is _where_ to open this conversation so that it doesn't get accidentally abandoned.

**Comment by frivoal** [comment]
I'd say AB + AC. Given how full the AB's plate has been lately, I am unsure that we'll be able to make quick progress on it in, but we'll probably get to it eventually. But if the AC makes progress first, the AB can probably take up proposed any solutions that emerges, and see if we can roll it out.

**Comment by dwsinger** [comment]
Proposing to close as we now have W3C Statements in the Process, and if another mechanism is needed for 'political issues', it's not ours.

**Comment by tobie** [comment]
> if another mechanism is needed for 'political issues', it's not ours.

That makes sense. Do we have an idea where to track this? It feels like it would be good for the organization to be able to be more reactive in certain cases than it can be now.

**Comment by dwsinger** [comment]
closed as handled
