### ISSUE TITLE
(Minor) Substantive changes *must not* be made... (in PR)

### ISSUE THREAD

**Issue by iherman** [w3c/w3process#43]
The current draft says, in 6.1.2:

> Substantive changes *MUST* not be made to a Proposed Recommendation

I believe the correct RFC2119 should be:

> Substantive changes *MUST NOT* be made to a Proposed Recommendation

**Comment by chaals** [comment]
Yep. I doubt I will get to it until next week, so feel free to file a PR, or to wait for me to self-assign which I will do as a sign that I expect to resolve it...

**Comment by xfq** [comment]
It seems to be fixed by #46. Closing.
