### ISSUE TITLE
Candidate Recommendation Snapshots, Review Snapshots

### ISSUE THREAD

**Issue by plehegar** [w3c/w3process#439]
In the paragraph describing the definition of the new [Candidate Recommendation Snapshot](https://www.w3.org/2020/06/DRAFT-Process2020.html#candidate-recommendation-snapshot), there are multiple terms used to represent this concept that apparently mean the same thing. For example: the terms "Candidate Recommendation Review Snapshot" and "Review Snapshot" seem to be synonyms with "Candidate Recommendation Snapshot". Given the introduction of so many new terms as part of this Process change, we would like for the editors to be crisp in their usage of these new terms and pick one of these terms and use it consistently.

**Comment by travisleithead** [comment]
Thanks for filing this @plehegar

**Comment by travisleithead** [comment]
Super. Thanks!
