### ISSUE TITLE
Proposed Recommendation must not have any substantive changes from the previous Snapshot

### ISSUE THREAD

**Issue by plehegar** [w3c/w3process#440]
In [Transition to Proposed Recommendation](https://www.w3.org/2020/06/DRAFT-Process2020.html#transition-pr). a new bullet is introduced, but its phrasing does not match the subject of all the other bullets in the list which are in relation to a Working Group or the W3C. The bullet starting "must not have any substantive changes since…" thus reads that it is the Working Group or the W3C that must not have any substantive changes... This bullet needs to be rephrased to clarify that it is referring to the Working Group or W3C's *Candidate Recommendation Snapshot*, and not "substantive changes" to the working group itself.

**Comment by travisleithead** [comment]
Thanks for filing @plehegar

**Comment by travisleithead** [comment]
Super!
