### ISSUE TITLE
Relations with IETF

### ISSUE THREAD

**Issue by plehegar** [w3c/w3process#441]
[raised by the 2020 AC Review]

There is often overlap with IETF on technical standards. Modifying the process to specifically explain how the W3C process works with the IETF would help. New members of the W3C may be often confused over where a technical standard should be developed or discussed. Examples include; cookies, tracing or client hints. There seems to be no requirement for issues and comments raised or discussed within the W3C to be passed to the IETF for consideration.

Whilst the IETF is the closest adjacent organization there are others that might similarly benefit from engagement in other fields.

**Comment by jeffjaffe** [comment]
@plehegar would you advocate this in the process, in /Guide, or on our Liaisons page?

**Comment by frivoal** [comment]
Seems to me that the process already calls for talking to a Working Group's identified Liaisons as part of wide review, but I'm not sure this is commonly done or enforced during transition calls.

Maybe the process is fine, but we should adjust our practice to be more proactive about reaching out to liaisons?

**Comment by dwsinger** [comment]
yes, I think that the team contact and the assigned liaison rep. (if any) should be responsible for making sure that liaisons are aware of formal transitions and especially wide review deadlines and opportunities.

**Comment by michaelchampion** [comment]
This seems like a top-level W3C strategy issue, not a Process Document issue. What is the scope of W3C's mission, and where does its members think the boundaries between its scope and that of IETF, WHATWG, TC39, etc.?  

 Or perhaps there are no boundaries per se, and W3C's scope transcends its traditional scope and that of IETF, WHATWG, TC39. A plausible mission for a restructured and (hopefully) revived W3C might be to be the venue where all come together to address common problems such as security violations, fraud, misinformation as well as universal access to the internet/web.  Whose imprimatur those eventual standards have is much less important than whether W3C has achieved its mission of improving the web.

**Comment by samuelweiler** [comment]
I agree with @michaelchampion - this is not a Process issue.  It _might_ be documentation issue. 

> There seems to be no requirement for issues and comments raised or discussed within the W3C to be passed to the IETF for consideration.

I'm not sure where it's documented, but the W3C Comm team routinely sends proposed charters to the IETF's new-work mailing list.

**Comment by fantasai** [comment]
@samuelweiler Vaguely falls under the first paragraph of https://w3c.github.io/w3process/#Liaisons I guess.

**Comment by samuelweiler** [comment]
Propose to close, consistent with August comment.

**Comment by plehegar** [comment]
The practice of sending charters to IETF is documented in section 5.1 of https://www.w3.org/Guide/process/charter.html

The practice of checking that a Group did ask external orgs listed in their charter dependencies is documented within the note related to "must show that the specification has received wide review" in https://www.w3.org/Guide/transitions?profile=CR&cr=new

W3C ongoing liaisons are listed in https://www.w3.org/2001/11/StdLiaison .

I concur that the Process is not the right place to discuss the scope of W3C versus the scope of IETF.

+1 to closing this issue.

**Comment by dwsinger** [comment]
closing, as no comment has been received since the proposal to close a month ago.
