### ISSUE TITLE
Horizontal/Wide review for IG/CG/BGs?

### ISSUE THREAD

**Issue by xfq** [w3c/w3process#447]
Currently, only wide review for specs in a Working Group is mentioned in the process, and IG/CG/BG is not mentioned. I wonder whether documents in these groups need to be reviewed (and whether we need to mention them in the process).

For example, some CG specs are pretty fully baked before entering a WG, so review may be needed at the CG stage. (i18n WG reviewed a few CG drafts recently and I heard that PING also tracks some documents in CGs.) For IGs, some proposals are incubated (but not published, because the proposal is usually rough and CG/WG has a better patent policy) in the group before entering a CG/WG. I'm not sure about BGs.

**Comment by dwsinger** [comment]
I think that this falls into the AB project to look at whether we've incubated the idea of incubation enough, and look at making it clear what it is and how it's done. I agree, the "wild west" of CGs are great a lot of the time, but we need more guidance when they feed W3C work.

**Comment by chaals** [comment]
I don't think it makes sense to tell CGs that they can add to the burden on HR groups without some process for working out how to manage the expectations for those groups. When CGs were instituted, they were advertised as not having W3C commitment - a situation that has drifted far from reality.

It makes more sense to tell people whose CG work has got past the "does this idea have legs or will it just fail" that if they want to work on standardising it, they should do it properly, with a WG - that is set up for horizontal review (and procedural fairness, proper care taken to meet anti-trust requirements, etc etc).

**Comment by samuelweiler** [comment]
Yes, docs from IGs (at least) need review, and that is generally reflected in the IGs' charters. 

I don't know what, if anything, needs to be in the Process about that.

(I'm declining to comment on CGs' documents, given chaal's excellent points above.)

**Comment by dwsinger** [comment]
IGs get Wide Review if they want to elevate a Note to Statement, and we think that CGs and BGs are not in this Process. Does that address this? Agree with @samuelweiler on having the charter express what review will be sought for Notes.

**Comment by dwsinger** [comment]
On CGs, see also #409 and the discussion about CGs that are related to W3C operations.

**Comment by frivoal** [comment]
Also, groups can ask for wide review of Notes if they want, they just aren't required to (unless mandated by charter). I do not think a general mandate for wide review of Notes would be appropriate, given that Notes are meant to reflect the consensus of the Group producing them, not of the whole community (there are different documents for that).

**Comment by dwsinger** [comment]
closed by consensus

**Comment by frivoal** [comment]
@xfq, could you confirmed you are OK with how this issue was closed?

**Comment by xfq** [comment]
Yes, I'm satisfied.

The HR groups can review these drafts themselves, but I agree that we don't need to mention that in the Process.
