### ISSUE TITLE
Should the Process normatively reference RFC 8890 "The Internet is for End Users" ?

### ISSUE THREAD

**Issue by michaelchampion** [w3c/w3process#448]
I see from @mnot https://www.mnot.net/blog/2020/08/28/for_the_users that RFC 8890 has been officially published by  the Internet Architecture Board.  Should the Process Document normatively reference it, perhaps in https://w3c.github.io/w3process/#Policies?

 There are a couple of W3C documents such as https://w3ctag.github.io/design-principles/#priority-of-constituencies that express the same sentiment, but AFAIK they are not normative documents the Process could reference, and the TAG Design Principles document references a draft of RFC 8890.  And RFC 8890 has benefitted from quite a bit of information-sharing and consensus building, and the more times I read it, the more wisdom I find.

The section of RFC 8890 that seems most relevant to the W3C Process is Section 4.  
- Responsibility to consult with the greater internet community /  engage with specifically affected communities when making decisions  that might affect them
- Responsibility to try to identify negative end-user impact
- Handling *conflicting* end user needs.  
>  There may be cases where genuine technical need requires compromise.
>  However, such trade-offs are carefully examined and avoided when
>  there are alternate means of achieving the desired goals.  If they
> cannot be, these choices and reasoning ought to be thoroughly
> documented.
- De-prioritizing internal needs.   Much discussion in W3C is about maintaining the *organization*,  this could be called out as a lower priority concern when drafting the Process or technical specs.

Of course, the W3C Process Document (or TAG, or AB, or perhaps management) could state an authoritative W3C position on these matters, but it would seem to be a better use of scarce bandwidth to normatively reference RFC 8890.

Treat this as a strawman proposal to stimulate discussion, not a firm proposal I'm ready to argue for or offer a pull request to implement.

**Comment by dwsinger** [comment]
I don't think statements of principle belong in the process; the process is about how we work.

I _do_ think we need to get better on deciding, adopting, publishing, and promoting principles.

**Comment by michaelchampion** [comment]
Well, the Process does say "Consensus is a core value of W3C. To promote consensus, the W3C process requires Chairs to ensure that groups consider all legitimate views and objections, and endeavor to resolve them."  And WHATWG does have an authoritative Principles document https://whatwg.org/principles that we found useful to start with and refer to when drafting the process, governance, and legal changes a few years ago.

 I'm uncomfortable paying lip service to the principle if it won't actually be put into practice, such as by referencing https://dev.w3.org/html5/html-design-principles/#priority-of-constituencies as if it were an authoritative W3C document. 

RFC 8890 has some text I think is useful about *implementing* consensus seeking to make sure it's not jut the people in the WG, or in the formal horizontal review groups, whose interests are being considered.  My thought was that incorporating the IAB's thinking by reference into the Process document would be an efficient way to put this elaboration on the consensus principle into WG deliberations.

I'd be OK with a conscious decision to NOT adopt the "internet is for end users" principle if cannot be turned into concrete process guidance for W3C. Arguably this principle is more important for IETF  than W3C given that they don't have a membership structure or voting system and (nominally) everyone participates as an individual. But it seems worth some discussion here, especially since @mnot has participated here would have an informed perspective.

**Comment by dwsinger** [comment]
Right, consensus is a value that affects how we make decisions that directly affect our products – the recommendations etc.  So it's directly related to the process of development.

At the opposite extreme, a value for respecting the planet and minimizing power consumption affects the _contents_ of some standards but probably has no effect on the _process_.

So we can have values that support/explain the process as it is, and we can have other values that are not process-related.

I think "the web is for users" is closer to the second; I don't think it affects the _way_ we make decisions.

**Comment by michaelchampion** [comment]
> I think "the web is for users" is closer to the second; I don't think it affects the way we make decisions. 

I don't really agree: IETF seems to have incorporated it into the way they may decisions.  And a supposed principle that has no operational impact is a platitude or marketing slogan, like "leading the web to its full potential" or "don't be evil."  But I don't plan to push that point of view unless others think this issue is worth pursuing.  So feel free to close this issue in a week or two if there's no further discussion.

FWIW I also think it's worth discussing whether sustainability SHOULD be a core value to be considered in spec review alongside A11Y/I18N/Privacy/Security going forward, but that's definitely a governance-level issue, not a Process issue at this point in time.

**Comment by frivoal** [comment]
I agree that the web is for end users, and I think it would be worth having that go through a formal AC ballot in some form or other, and have it influence our decisions (for example, if a formal objection is based on a tradeoff, have that inform how we should rule on that tradeoff).

So, my view is that we should push (in https://github.com/w3c/AB-memberonly/issues/35) for the TAG (and possibly other bodies like the AB) to be able to publish formal documents ratified by the AC, and that something like https://www.rfc-editor.org/rfc/rfc8890.html or https://w3ctag.github.io/design-principles/#priority-of-constituencies should be put through it, and then used as a basis for deciding on things.

But I don't see how that changes the mechanics of voting or elections or of transition requests, so I don't quite see what it would do in the Process.

Note this does not mean that I am opposed in principle to the Process including this. I support this principle, and thing we should abide by it, so if putting it in the Process achieves something, no problem by me. But it feels like the wrong document.

**Comment by jeffjaffe** [comment]
> I see from @mnot https://www.mnot.net/blog/2020/08/28/for_the_users that RFC 8890 has been officially published by the Internet Architecture Board. Should the Process Document normatively reference it, perhaps in https://w3c.github.io/w3process/#Policies?

RFC 8890 is an _informational_ RFC so it would be odd to _normatively_ reference it in W3C.  It certainly has good ideas just as the TAG's design-principles has good ideas.  But I agree with @frivoal it makes more sense to find a path to ratify the TAG's excellent document.

**Comment by TzviyaSiegman** [comment]
I do not think it is a good idea to try to dictate what the consensus at which groups arrive at should be.

**Comment by cwilso** [comment]
I'm not sure I understand your comment, @TzviyaSiegman.  I do think we should take on formalizing the priority of constituencies - but I agree that it likely doesn't belong (directly) in the Process.

**Comment by TzviyaSiegman** [comment]
@cwilso Yes, that's what I meant. I think we should formalize the priority of constituencies, but it does not belong in the Process.

**Comment by michaelchampion** [comment]
Closing this issue since there's clearly no support for it, and opposition from the CEO and much of the AB. 

But this discussion raises the question: Where are W3C's principles maintained as the world evolves, if not in the Process?  I hope the Legal Entity discussions resolve this question, or W3C will lose relevance as new problems are created by the answers to old ones.
