### ISSUE TITLE
CRD may be followed by a Proposed Recommendation

### ISSUE THREAD

**Issue by plehegar** [w3c/w3process#450]
[[
A Candidate Recommendation Draft is published on the W3C’s Technical Reports page [TR] to integrate changes from the previous Candidate Recommendation Snapshot that the Working Group intends to include in a subsequent Candidate Recommendation Snapshot.
]]
https://www.w3.org/2020/Process-20200915/#candidate-recommendation-draft

However, one can go directly from CRD to Proposed Recommendation if no substantive changes were made since the most recent snapshot. So, it's not necessirely included in a subsequent CRS.

How about:
[[
A Candidate Recommendation Draft is published on the W3C’s Technical Reports page [TR] to integrate changes from the previous Candidate Recommendation Snapshot that the Working Group intends to include in a subsequent update.
]]

cc @dontcallmedom

**Comment by frivoal** [comment]
I'm a little unsure. On the one hand, you're right, CRD->PR is possible in this case. On the other hand, it seems to me that the current text is clearer about the general intent, by naming what kind of update we're talking about, and it just so happens that we have an exception that allows you to skip CRS and go straight to PR if you've only made editorial changes. Should we go for clarity of intent, or for precision? Or should we find yet another wording that gives us both?

While we're on that, I'm not sure that "subsquent *update*" is quite the right word anyway. A new CR(S) would be an update, but is PR really an update?

**Comment by fantasai** [comment]
- Let's remove “on the W3C’s Technical Reports page [TR]”, that will at least shorten the sentence.
- Agree with @frivoal’s concerns about “update” being a bit too vague. We could write out ”Candidate Recommendation Snapshot or Proposed Recommendation” in full (especially after deleting that other bit ;) or just accept the slight inaccuracy.

**Comment by plehegar** [comment]
well, PR is an update since it has a new date at the minimum. Spelling it out while we're trying to make the SOTD the SOTD shorter backward to me.

**Comment by fantasai** [comment]
@plehegar I mean, I'd be OK with dropping the entire “that the Working Group intends to include in a subsequent Candidate Recommendation Snapshot” phrase. But a CRD is also an “update” so the phrase is a bit nonsensical if we just replace “Candidate Recommendation Snapshot” with “update” here.

**Comment by fantasai** [comment]
Proposed wording: “A Candidate Recommendation Draft is published to solicit review of intended changes from the previous Candidate Recommendation Snapshot.”
