### ISSUE TITLE
qualify _unfinished_ technical reports in 6.2.12.1

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/w3process#453]
Arising from https://github.com/w3c/w3process/issues/262#issuecomment-693259494:

In  [6.2.12.1](https://www.w3.org/Consortium/Process/Drafts/#abandon-draft) which concerns unfinished technical report, change

> Any technical report no longer intended to advance or to be maintained, and that is not being rescinded, should be published as a Working Group Note.

to qualify that this applies only to unfinished technical reports, i.e.

> Any **unfinished** technical report no longer intended to advance or to be maintained, and that is not being rescinded, should be published as a Working Group Note.

So that the text matches the intention declared in the heading.

**Comment by dwsinger** [comment]
I'm fine with this. But (of course) it raises new questions. How could an _unfinished_ report be rescinded?

**Comment by frivoal** [comment]
Rescinded is a term invoked by the patent policy (see point 10 of https://www.w3.org/Consortium/Patent-Policy-20200915/#sec-Requirements), and it can apply not only to RECs, as defined in https://www.w3.org/2020/Process-20200915/#rec-rescind, but also to CRs, as defined in https://www.w3.org/2020/Process-20200915/#rescind-cr, which is the paragraph imediately after the one under discussion in this issue.

Maybe we should add a note to https://www.w3.org/2020/Process-20200915/#rescind-cr to point out that this has patent policy implications?

**Comment by dwsinger** [comment]
OK, let's leave it. Given that the patent policy famously only kicks in on finishing, it puzzled me. But let's leave it alone.

**Comment by nigelmegitt** [comment]
> OK, let's leave it. Given that the patent policy famously only kicks in on finishing, it puzzled me. But let's leave it alone.

But still add the "unfinished" qualifier before "technical reports" in this section, right? Just checking the scope of the "let's leave it alone" statement.

**Comment by dwsinger** [comment]
Yes, sorry, leave my new question alone but copy the word from the section title into the text

**Comment by plehegar** [comment]
isn't this resolved in Process 2021?

**Comment by frivoal** [comment]
Sorry, yes, this is done, this section got a substantial update, and the particular phrasing problem raised in the original comment is no more. Somehow failed to close this issue, but it was addressed. Closing now.
