### ISSUE TITLE
Maturity Level is a weird term

### ISSUE THREAD

**Issue by fantasai** [w3c/w3process#455]
While we're talking about editorial fixes... "maturity levels" is weird, and "maturities" weirder. Maybe we can use a different term like "maturity stages" which can be shortened to the much more normal "stages"?

**Comment by jeffjaffe** [comment]
While I don't disagree with @fantasai 's argument, I don't see the value in changing a word that has been with us for decades.

**Comment by nigelmegitt** [comment]
I don't feel there's much semantic difference between "level" and "stage" in this context, and "maturity" seems like a reasonable qualifier word to set the context.

**Comment by fantasai** [comment]
@jeffjaffe The value is making the process easier to describe and talk about. We generally don't use "levels" outside the Process document itself, because it is awkward and unhelpful, and so we haven't standardized on terminology to talk about the various phases of the REC track.  Other standardization groups such as TC39 do use "stages", so aligning with them would help us explain what we're doing better. I'm open to other suggestions (I've used "phases" before when explaining the REC track) but "levels" seems less than helpful here, as evidenced by its lack of adoption by our community.

**Comment by samuelweiler** [comment]
"maturity level" is [common](https://tools.ietf.org/html/rfc6410) [in the](https://tools.ietf.org/html/rfc4897) [IETF](https://tools.ietf.org/html/rfc2026#section-4.1).  If we want to be [welcoming to participants](https://github.com/w3c/w3process/issues/456) from that SDO, we don't need to change this.

**Comment by dwsinger** [comment]
(Part of a broader discussion about nomenclature, especially on our web site).

**Comment by plehegar** [comment]
"Maturity stages" is the chosen term. Please object here to use that term before July 20.

**Comment by fantasai** [comment]
Note that TC39 uses stages also.

**Comment by plehegar** [comment]
I do not see any objection to use maturity stages".

Resolved: let's use maturity stages.

@frivoal , I believe the next step is to make a pull request.

**Comment by frivoal** [comment]
Closed by merging https://github.com/w3c/w3process/pull/612
