### ISSUE TITLE
Elevating a TAG document to W3C Approved Status

### ISSUE THREAD

**Issue by jeffjaffe** [w3c/w3process#461]
The AB and TAG have discussed that there should be a method for a TAG document to be elevated to W3C Approved Status.  For example, the TAG might want certain TAG findings to become official W3C documents.  We don't have a formal procedure of review to achieve that.  The proposal is to create a review process that results in W3C endorsement of TAG documents.

**Comment by michaelchampion** [comment]
What's wrong with the Recommendation process for this?  https://www.w3.org/TR/webarch/ is a Recommendation created by the TAG.  It's not clear to me why they couldn't do the same for other work they want to get published as "official W3C documents."

**Comment by jeffjaffe** [comment]
Thanks @michaelchampion .  I didn't say there was anything wrong with the Recommendation process.  We could use it as is, or tweak it.  Today, formally, it only applies to WGs.  https://www.w3.org/2020/Process-20200915/#Reports

**Comment by dwsinger** [comment]
There is substantial discussion of this in the [member-visible AB Repository](https://github.com/w3c/AB-memberonly/issues/35#issuecomment-722566134), including a suggested resolution (which this link points to) and some refinement following that. It would probably help to take that as a starting point, or even to ask the community to comment there and avoid forking the conversation.

**Comment by jeffjaffe** [comment]
> even to ask the community to comment there and avoid forking the conversation.

Just a reminder that public participants in the Process CG community may not have member access to https://github.com/w3c/AB-memberonly/issues/35#issuecomment-722566134

**Comment by chaals** [comment]
Speaking as an AC representative, I believe we should use the AC review process for this.

It's not clear that we need a Candidate Recommendation phase unless the TAG decides to advise doing things that no WG has actually done and made into a Recommendation. So there are some potential differences we might consider, especially to avoid more process work than necessary.

On the other hand the Recommendation track incorporates the Patent Policy, whereas the TAG freelancing on proposals without any corresponding obligations on anyone regarding IPR might be a bad idea.

(For clarity, it's also why I think there is potentially merit in a charter for the TAG, but only so long as that is periodically reviewed and specifically describes deliverables, otherwise we might as well just define the TAG in the Process only, but that's  really a different issue).

**Comment by dwsinger** [comment]
My proposal in the other thread is (a) the TAG is not allowed to make implementable recommendations (for all sorts of reasons including patent policy) (b) can ask that they make a document that has W3C Consensus (not just TAG consensus) and (c) we basically use the AC-review/wide-review/Director-approval process for getting that consensus (essentially hitching a ride on the existing mechanism) and (d) we call such consensus non-implementable documents something new, eg W3C Report.

I think this reflects what @chaals is saying too. Does it?

**Comment by chaals** [comment]
@dwsinger I think our proposals are on parallel lines. The differences are:
- I don't think we should say "non-implementable" because I think it will cause more work than it saves to decide what that means and explain it. 
- I do think it makes sense to charter the TAG so proposed deliverables are floated to the AC before a lot of effort is spent delivering them. (You may agree with this, but I don't think you said so explicitly).

**Comment by dwsinger** [comment]
@chaals Yes, I'm using non-implementable as a shorthand, but I do think it has to be a real restriction as I cannot see how the TAG can issue a document that invokes and carries licensing commitments, which is one of the main characteristics of a Recommendation. These documents need a new name, and status, (I suggest W3C Report, in contrast to W3C Recommendation) which make this clear.

I am not a fan of a charter for the TAG; approving or disapproving a charter for an elected body gets us into all sorts of hard what-ifs. I am, however, supportive of the concept of what you're saying; that if the TAG feels the need to develop something that they intend to achieve W3C consensus status, it would be prudent and courteous to say that early on, so arguments of the kind "we should not publish a document of that type" can be raised before they do a lot of work.

**Comment by samuelweiler** [comment]
> My proposal in the other thread is .... (b) can ask that they make a document that has W3C Consensus (not just TAG consensus) and (c) we basically use the AC-review/wide-review/Director-approval process for getting that consensus (essentially hitching a ride on the existing mechanism) ...

Asking a broader question: how do we want to determine W3C Consensus in a post-director world?  

I'm used to an SDO where the whole community can weigh in on consensus calls, and that makes asking the AC - and implicitly not the rest of our community - feel weird.  It seems like it excludes many voices.  If we're actually asking everyone ("wide review"), then why are we _separately_ asking the AC?  Can't we instead _only_ ask _everyone_?

Having asked everyone, who's going to judge that consensus?

(I'm also accustomed to having the IAB, arguably IETF's TAG equivalent, routinely publishing RFCs under their own name.  They usually ask for community input (in part by publishing as internet-drafts first, and in part by explicitly asking) but they don't constrain themselves to only publishing with "IETF Consensus".)

**Comment by fantasai** [comment]
@samuelweiler “Asking a broader question: how do we want to determine W3C Consensus in a post-director world?” is a separate issue, please file it separately.

**Comment by jwrosewell** [comment]
I'm in favor of Process simplification and the removal of anomalies. Placing TAGs responsibilities in an Interest Group seems worth exploring as a remedy.

**Comment by chaals** [comment]
@jwrosewell wrote

> Placing TAGs responsibilities in an Interest Group seems worth exploring as a remedy.

To me it seems like an idea that can be dismissed out of hand, so I am curious what problem it solves and why you think it seems worth exploring. Can you expand a bit on that?

**Comment by frivoal** [comment]
Let's keep issues focused. This is largely orthogonal to the initial problem, so if you want to discuss changing the TAG into an ordinary IG, I suggest you open a separate issue for that.

**Comment by Iluta32** [comment]
.

**Comment by dwsinger** [comment]
So, modulo maybe needing a better name than "W3C Note" for a document that has W3C consensus status but that is not a Recommendation (i.e. not a spec.), my proposal is

- Only chartered groups (hence, formed of members) can make W3C Recommendations. Elected groups cannot.
- Rename Note to Group Note, and mandate that it clearly document its subtype and status (e.g. 'this is an abandoned attempt at a Rec.', 'this is a Finding of an answer to a specific question', 'this is a guidance document on considerations on XXX (e.g. accessibility)', and so on).
- Require that a document called a Note cannot specify implementable technology; the W3C requires that all such documents be Recommendations.
- Allow both chartered and elected groups to produce Group Notes (though I doubt the AB will), without a requirement that they be mentioned in the charter
- Allow any group that produced a Group Note to request elevation to W3C Note status; that triggers wide review, AC Review and Director assent.
- Drop the TAG charter; it's not maintainable and adds no value, and means something quite different from the usual 'should we have a group with this charter?' as the TAG always exists
- Make sure we address the styling question (which is separate, but this would raise its importance).

I don't want to get into the details of styling, but we need to differentiate:
* W3C consensus from group consensus from individual work
* recommendation track and note track are different
* finished work is different from work-in-progress

**Comment by fantasai** [comment]
@dwsinger Nice list. One issue I have with it is “Require that a document called a Note cannot specify implementable technology; the W3C requires that all such documents be Recommendations.” -- many of our notes specify implementable tech, because they're discontinued or exploratory designs for implementable tech or suchlike. :) So I don't think we can make this a requirement. But we can require that elected groups cannot publish notes that specify implementable tech. And we can also require that groups should not publish notes specifying tech that they want to *recommend* for implementation. (Distinguishing here between a document that describes tech that *can* be implemented vs one that we *recommend* be implemented.)

Wrt naming, maybe using the more formal “W3C Memorandum” instead of “W3C Note” would work and help differentiate the increased status better?

**Comment by fantasai** [comment]
Wrt clearly distinguishing NOTEs, btw, there's https://github.com/w3c/w3process/issues/342 which seems worth taking up.

**Comment by plehegar** [comment]
+1 to NOT require "that a document called a Note cannot specify implementable technology; the W3C requires that all such documents be Recommendations."
Here are examples of [Notes](https://www.w3.org/TR/?status=note) that specify implementable technologies:
- https://www.w3.org/TR/2020/NOTE-css-2020-20201222/
- https://www.w3.org/TR/2020/NOTE-lpf-20200319/
- https://www.w3.org/TR/2020/NOTE-json-ld11-streaming-20200507/
- https://www.w3.org/TR/2020/NOTE-merchant-validation-20201208/

**Comment by dwsinger** [comment]
doh, yes of course, stupid oversight

* A document intended to be a Note should not specify implementable technology, 
* A Note does not receive a Patent License under the Patent Policy;
* A Group Note specifying implementable technology cannot be elevated to W3C status.

**Comment by fantasai** [comment]
> A document intended to be a Note should not specify implementable technology,

A document intended to be a Note should not specify technology the group recommends for implementation,

**Comment by fantasai** [comment]
RESOLVED: Accept proposal for W3C-approved NOTEs, they SHOULD NOT specify implementable tech--if so transition request MUST include rationale for not being on REC track

**Comment by fantasai** [comment]
RESOLVED: Go with Memorandum in the PR for now, bikeshed the name later.

**Comment by nigelmegitt** [comment]
Sorry, a bit late to this party, and I may have missed a discussion, but this proposed requirement about not specifying implementable technology in a Note sems to have two problems:

1. It implies the need for a definition of "specify implementable technology". I don't think it is a workable requirement.

For example, a WG might write as a Note a guidance document about possible implementation approaches for a separate Rec. The Rec specifies the normative requirement, the Note adds more informative detail, but it could be perceived as "specifying implementable technology". 

For example https://www.w3.org/WAI/WCAG21/Techniques/ is informative and though it doesn't make clear if it is a Note or not, I assume it is one. It includes specific techniques that implementers may use to meet the requirements. I doubt it is anyone's intent to suggest that it shouldn't be allowed.

This seems like a terminology rabbit-hole we should avoid.

On the other hand, it would be redundant to say that a Note must not include any normative provisions, since that is already true by definition.

2. It seems to contradict the Process

>* `RESOLVED:: proposal for W3C NOTE SHOULD NOT specify implementable tech, transition request MUST include rationale for not being on REC track`

Further, doesn't the resolution contradict the Process, in that the Process requires that abandoned Rec track work is published as a Note? Seems odd if the Process requires one thing and also says "SHOULD NOT" about that same thing somewhere else.

**Comment by dwsinger** [comment]
@nigelmegitt Yes, we need to make it clear that though implementable technology can be discussed, or documented as abandoned Rec-track work, it is (a) not Recommended for implementation and (b) receives no license under the Patent Policy.

We're saying that Group Notes that nonetheless contain implementable tech will not, in the normal course of events, be elevated to W3C Memorandum status (the correct vehicle for a W3C-consensus document of implementable tech. is a Recommendation), and if a group wants to elevate an implementable Group Note to W3C Memorandum, they're going to have to justify that in the request to elevate to W3C Memorandum status.

**Comment by dwsinger** [comment]
Putting it all together, one more time

- Only chartered groups (hence, formed of members) can make W3C Recommendations. Elected groups cannot.
- Rename Note to Group Note, and mandate that it clearly document its subtype and status (e.g. 'this is an abandoned attempt at a Rec.', 'this is a Finding of an answer to a specific question', 'this is a guidance document on considerations on XXX (e.g. accessibility)', and so on).
- Both chartered and elected groups may produce Group Notes, without a requirement that the Notes be mentioned in the charter
- Introduce a new class of W3C consensus publication, called a W3C Memorandum
- Allow the group that produced a Group Note to request elevation of that Note to W3C Memorandum status; that triggers wide review, AC Review and Director assent.
- Neither a Group Note nor W3C Memorandum receive a Patent License under the Patent Policy; the document status must clearly state that this;
- A document intended to be a Note should not specify technology the group recommends for implementation;
- A Group Note specifying implementable technology should not be elevated to W3C Memorandum status; if it does, the transition request MUST include rationale for why it should be elevated, and why it is not on the Recommendation track.

Separately, we recommend:
- Drop the TAG charter; it's not maintainable and adds no value, and means something quite different from the usual 'should we have a group with this charter?' as the TAG always exists
- Address the document styling question (which is separate, but this would raise its importance), to differentiate:
  * W3C consensus from group consensus from individual work
  * Recommendation track from Note/Memorandum track
  * Finished work (final rec, final Group  Note, final W3C Memorandum, etc.) from work-in-progress

**Comment by nigelmegitt** [comment]
@dwsinger , that doesn't seem to match up with your previous comment, so I'm not sure I've understood. Should:

> A document intended to be a Note should not specify technology the group recommends for implementation;

instead be:

> A document intended to be a **Memorandum** should not specify technology the group recommends for implementation;

?

**Comment by nigelmegitt** [comment]
> Drop the TAG charter

I have no issues with this _per se_, but I think there _is_ value in documenting the remit and requirements of the TAG in _some_ document. Maybe a "Terms of Reference", say?

[NB I'm not making this comment with any organisational backing, just my own view as an occasional flyer with TAG]

**Comment by dwsinger** [comment]
> @dwsinger , that doesn't seem to match up with your previous comment, so I'm not sure I've understood. Should:
> 
> > A document intended to be a Note should not specify technology the group recommends for implementation;
> 
> instead be:
> 
> > A document intended to be a **Memorandum** should not specify technology the group recommends for implementation;
> 
> ?

No, I am trying to say that if you **start off** with the intention of producing a Group Note, don't include implementable tech.

If you started with the intention of making a Rec., and ended up publishing it as an abandoned work Group Note, that's different.

**Comment by dwsinger** [comment]
> > Drop the TAG charter
> 
> I have no issues with this _per se_, but I think there _is_ value in documenting the remit and requirements of the TAG in _some_ document. Maybe a "Terms of Reference", say?
> 
> [NB I'm not making this comment with any organisational backing, just my own view as an occasional flyer with TAG]

The TAG is characterized and its remit described in the Process. Does the charter add anything of value? It's old, we rarely revise it, and seems out of place.

**Comment by nigelmegitt** [comment]
> Does the charter add anything of value? It's old, we rarely revise it, and seems out of place.

Age and lack of revision aren't reasons to consider it not useful - maybe it's just well written and does its job well? I'm now puzzled by the motivation to remove the document.

It contains a lot of stuff beyond what's in the Process that grants its existence. For example the membership size, which is extremely important!

If the TAG Charter is a misnamed document, rename it. 
If the contents are wrong, fix them. 
If you haven't felt the need to change it for a while, fine, why is action needed?

**Comment by dwsinger** [comment]
Maybe no-one has even looked at it in 16 years (last revised 2004, and prior to that 2001, 2000, and that seems the origin)?

> "For example, W3C has adopted an architectural principle that XML should be used for the syntax of Web formats unless there is a truly compelling reason not to"


really? JSON? HTML?

> "The primary activity of the TAG is to develop Architectural Recommendations. An Architectural Recommendation is one whose primary purpose is to set forth fundamental principles that should be adhered to by all Web components. Other groups within W3C may include cross-technology building blocks as part of their deliverables, but the TAG's primary role is to document cross-technology principles. Like other groups within W3C, the TAG will follow the W3C Recommendation track process for its Recommendations (including public draft requirements and Proposed Recommendations to the Advisory Committee); refer to section 7 of the Process Document."


This is deeply problematic as the TAG does not (correctly, IMHO) operate under the patent policy, and Recommendations do. Though there is a section later suggesting that it does.

> "The TAG will hear appeals by Advisory Committee representatives of Member Submission requests rejected for reasons related to Web architecture. The Team will establish a process for such appeals that ensures the appropriate level of confidentiality."


seems like a Process provision which should be in the Process document, if it's true.

> "The TAG is expected to evolve with experience, and its charter may be revised as its role and W3C change. The Director must propose any non-editorial changes to the charter to the W3C Advisory Committee for a four-week review. After the end of the review, the Director must announce the disposition of the review to the Advisory Committee.
> 
> W3C may publish a revised version of the TAG charter to make minor clarifications, error corrections, or editorial repairs, without following the Advisory Committee review process. The Team must notify the Advisory Committee when an editorial revision of the TAG charter has been published."


Likewise, we have processes for formal charters. The charter goes on to replicate the process about TAG structure. And so on.

It's clearly not looked at, or maintained. If the TAG wants to maintain a document, then I suggest it do so, but that it remove normative provisions that belong in the process, that it be brought up to date, and maintained, probably by re-publication after every election.

**Comment by nigelmegitt** [comment]
@dwsinger Well those seem like good reasons to motivate a review of the TAG Charter! 

Perhaps TAG should be required to review its Charter (or whatever you want to call it) on a more regular basis so it can't become outdated, and there should be a formal review process, I guess by AC. Regular WG Charters typically come up every 2 years.

**Comment by fantasai** [comment]
Please move the discussion about whether or not the TAG should have a charter to https://github.com/w3c/AB-memberonly/issues/49 or open a new issue on it. This is off-topic for this issue. It is really hard to manage discussions when people jumble multiple issues into one issue.

**Comment by nigelmegitt** [comment]
@fantasai thanks for the pointer

**Comment by Iluta32** [comment]
Yes

**Comment by chaals** [comment]
I continue to disagree with the way this works. In particular:
- I think it is a bad idea for the TAG to continue producing some kind of W3C documents with no obvious pathway for member review. 
- Creating new categories of document is generally confusing, so we should have a **really** good reason to do so, and I don't see one here.
- (Separate issue, but I believe TAG should have a charter as well as Process doc definition)

As a separate takeaway, the idea of making WCAG techniques documents notes was that they were merely advice about some things you could do, expected to be a general pattern not a one-off (they were developed alongside 3 accessibility recommendations setting a pattern sort of expected to inform e.g. TAG when it was created). Turns out, that wasn't the way things turned out, and it makes more sense to produce them as Recommendations. IMHO...

**Comment by frivoal** [comment]
> I think it is a bad idea for the TAG to continue producing some kind of W3C documents with no obvious pathway for member review.

I don't understand. Isn't creating a pathway for TAG documents to get member review exactly what we're doing here?

**Comment by torgo** [comment]
I agree the TAG should have a charter. I also agree with being very careful before creating new categories of documents. Why not just stick with *Note* if we're not comfortable with TAG publishing Recs? Or simply note in the front matter of the Rec that this document, while a recommendation, is outside of the patent policy as it does not describe a new technology (which would apply to everything coming out of the TAG)?

**Comment by nigelmegitt** [comment]
@torgo as per https://github.com/w3c/w3process/issues/461#issuecomment-755891260 you might want to mention that you would advocate _for_ the existence a TAG Charter at https://github.com/w3c/AB-memberonly/issues/49

**Comment by LeaVerou** [comment]
One issue with Notes is that they have no meaning and no implied endorsement. They span from things like TAG publications to abandoned, obsolete specifications. I think it's confusing and sends mixed messages to the public to use the same document type for best practices (i.e. _things that should be followed_) and obsolete technologies (i.e. _things that should be avoided_). 

Furthermore, I agree it would be beneficial to have a document type that TAG can publish which implies W3C endorsement, for some definition of W3C endorsement. Recommendations already have a lot of gravitas behind them, but as it was mentioned by several commenters, they are not suitable here for a variety of reasons. 

What about defining a new type of "TAG Recommendation" which is defined essentially as a sub-type of Recommendation with certain key differences?

> Wrt naming, maybe using the more formal “W3C Memorandum” instead of “W3C Note” would work and help differentiate the increased status better?

I think "Memorandum" is fairly confusing, as its usage in the wild is all over the place. Also, it's a word non-native speakers are unlikely to be familiar with.

**Comment by dwsinger** [comment]
> I agree the TAG should have a charter. I also agree with being very careful before creating new categories of documents. Why not just stick with _Note_ if we're not comfortable with TAG publishing Recs? Or simply note in the front matter of the Rec that this document, while a recommendation, is outside of the patent policy as it does not describe a new technology (which would apply to everything coming out of the TAG)?

As others have noted, we have a focused issue on the TAG charter.

Um, we are sticking with Notes; they are the consensus product of any group, including the TAG.

We're looking for a way to give some Notes, at the request of the originating group, some W3C consensus status.

@LeaVerou The word is a puzzle. Recommendation has a well-defined meaning today; Recommendations specify technology and carry a license. I'd prefer not to mix that up. I hear your concern about Memorandum; I still quite like Report, which (to me) sounds like an approved Note that is not a specification...

**Comment by LeaVerou** [comment]
> I hear your concern about Memorandum; I still quite like Report, which (to me) sounds like an approved Note that is not a specification...

To me, "Report" (just like "Note" sounds informative), not prescriptive and I'm not sure the word communicates any approval by anyone. Given that these are mostly (exclusively?) guidelines that people are *encouraged* to follow, the name needs to reflect this. What about something like "TAG Guidance", "W3C Guidelines" or something along these lines? 

On the other hand, maybe the name doesn't matter that much after all, since words acquire meaning based on actual usage (e.g. "RFC"). 🤷🏽‍♀️

**Comment by caribouW3** [comment]
FWIW, "Report" is used for documents produced in CGs, I'm not sure it's a good idea to reuse the term.

**Comment by cwilso** [comment]
Just chiming in to say I don't think "Note" is the necessarily a consensus product of a group.  Back in the day, we would publish Notes that were essentially proposals from various vendors as a Note. (Trolling https://www.w3.org/TR/?status=note toward the bottom of the page.)

**Comment by dwsinger** [comment]
'Guidance' is a synonym in the online [thesaurus](https://www.thesaurus.com/browse/recommendation). I don't see many helpful words in the listing for [report](https://www.thesaurus.com/browse/report). Communique has the same problem as Memorandum (it's a mouthful) and has an additional problem that non-english speakers will find it hard to pronounce and type…

Just like Notes, we'd expect the document to have a sub-type, e.g. a Finding (on a question). They should be labeled something like this, and have a distinct look. 

> W3C Guidance: Finding on the question of finding findings by looking
> 
> This Guidance was produced by the Technical Architecture Group and approved by the W3C for publication as a W3C Guidance.

**Comment by dwsinger** [comment]
> Just chiming in to say I don't think "Note" is the necessarily a consensus product of a group. Back in the day, we would publish Notes that were essentially proposals from various vendors as a Note. (Trolling https://www.w3.org/TR/?status=note toward the bottom of the page.)

I think that the group has to have consensus to _produce_ the Note; I think it's fine if the Note itself is a documentation of an inability to reach consensus, of opinions that were interesting but did not get traction, or the like.

**Comment by frivoal** [comment]
> Why not just stick with Note

The TAG's ability to produce Notes despite the Process for producing notes not including the TAG is a bug we need to fix (by fixing the process, not by disallowing the TAG to produce notes)

> if we're not comfortable with TAG publishing Recs

I want it to be possible for W3C as a whole to endorse documents made by the TAGs. RECs give you that **plus** a hook into the patent policy. That hook doesn't actually work properly, as it is designed to apply to WGs, and making the patent policy apply to the TAG isn't the goal of this exercise. Hence needing a new class of documents which is roughly "Note+AC Review"

I've just introduced https://github.com/w3c/w3process/pull/489 to do these two things.

**Comment by fantasai** [comment]
> Only chartered groups (hence, formed of members) can make W3C Recommendations. Elected groups cannot.

Specified in the Process already: only Working Groups are allowed to do the things on the REC-track.

> Rename Note to Group Note,

We actually call these group notes already. Or more specifically, "Working Group Note", "Interest Group Note" etc.

> and mandate that it clearly document its subtype and status (e.g. 'this is an abandoned attempt at a Rec.', 'this is a Finding of an answer to a specific question', 'this is a guidance document on considerations on XXX (e.g. accessibility)', and so on).

I think this is the responsibility of the Abstract and SOTD, and not something we particularly need to require in the Process. For abandoned REC track documents specifically, the requirement already exists in https://www.w3.org/2020/Process-20200915/#abandon-draft (but see also #342).

> Both chartered and elected groups may produce Group Notes, without a requirement that the Notes be mentioned in the charter

Specified in https://github.com/frivoal/w3process/commit/8d37bfa555f23544a19d7a488c30c13c9d2c60be.
Do you particularly want to mention the bit about the charter (in light of complaints about the process doc being too long ;) ?

> Introduce a new class of W3C consensus publication, called a W3C Memorandum
> Allow the group that produced a Group Note to request elevation of that Note to W3C Memorandum status; that triggers wide review, AC Review and Director assent.

Drafted in https://github.com/frivoal/w3process/commit/168d7efdbe731eaa99b1b292b3fa3a38707d47aa

> Neither a Group Note nor W3C Memorandum receive a Patent License under the Patent Policy

This is already clearly specified in the Process and the Patent Policy, however...

> the document status must clearly state that this;

We need to update the templates. They are absolutely not clear about this, and in fact often contain references to the Patent Policy in the SOTD identical to the ones in the REC-track SOTDs. :/ Filed https://github.com/w3c/specberus/issues/1092

> A document intended to be a Note should not specify technology the group recommends for implementation;
> A Group Note specifying implementable technology should not be elevated to W3C Memorandum status; if it does, the transition request MUST include rationale for why it should be elevated, and why it is not on the Recommendation track.

Done in https://github.com/w3c/w3process/commit/dae9fdb43e78e3e17132c1b59a23f39707351087

**Comment by frivoal** [comment]
On the bikeshedding side of things, since few people love the term "W3C memorandum", how about:
* W3C Statement
* W3C Position

**Comment by torgo** [comment]
> On the bikeshedding side of things, since few people love the term "W3C memorandum", how about:
> 
> * W3C Statement
> * W3C Position

I think both are better than Memorandum. I favour **Position** as it seems like it could cover a broader class of things.

**Comment by nigelmegitt** [comment]
> I favour **Position** as it seems like it could cover a broader class of things.

I was going to say I favour **Statement** for exactly the same reason! Position sounds like a consensus 'opinion' but Statement could be that, or could be some other declaration.

**Comment by LeaVerou** [comment]
Basically, what @torgo said. Both are much better than Memorandum, slight preference for **Position** as it seems to better represent a larger percentage of the class of things we are trying to describe.

**Comment by dwsinger** [comment]
I started with Report, which I still kinda like.

'Position' is generally when there is a question, often with a spectrum of opinion or possible response. I am not quite sure whether that is broad enough.

But I love the brainstorming, keep it going!

**Comment by jeffjaffe** [comment]
While I don't love Communiqué, it is both distinctive and sounds very important.  Perhaps too officious.

**Comment by frivoal** [comment]
This has been resolved by CG resolution by merging https://github.com/w3c/w3process/pull/489
