### ISSUE TITLE
Registries Survey

### ISSUE THREAD

**Issue by fantasai** [w3c/w3process#466]
To help resolve a few of the major open questions on Registries, @frivoal and I suggest surveying the chairs. Proposed survey:

> Dear Chairs,
> 
> This survey asks follow up questions to 
> https://www.w3.org/2020/10/TPAC/talk/Process2021#talk If you haven't watched 
> it or read the transcript yet, you might want to do that first.
> 
> <em>Please answer on behalf of your Working Group.</em>
> 
> Does your Working Group maintain a registry of some kind?
> * Yes, we maintain one or more
> * No, but we wanted to
> * No, and this is not needed in our group
> [textarea for additional comments]
> 
> The W3C Process CG and Advisory Board are drafting a process for maintaining 
> registries as formal technical reports, similar to other REC-track documents. 
> The registry would consist of both a formal definition of its format and 
> update process, as well as the tables of values (which could be published in 
> separate file(s) in human- and/or machine-readable format).
> 
> Does your group think registries would benefit from both a CR (testing) and PR 
> (AC approval) phase, or should registries skip CR? (See 
> https://www.w3.org/2020/10/TPAC/talk/Process2021#reg-cr-pr )
> 
> * Registries should have a CR phase to experimentally validate the WD before 
> requesting AC approval.
> * Registries do not need a CR phase to experimentally validate the WD before 
> requesting AC approval.
> * No opinion
> [textarea for additional comments]
> 
> Does your group think we should define registries as being on the W3C 
> Recommendation Track, or should they have their own separate W3C Registry 
> Track (which clearly detaches them from the W3C Patent Policy)? (See 
> https://www.w3.org/2020/10/TPAC/talk/Process2021#reg-track )
> * Separate track is better
> * Re-using Recommendation Track as-is is better
> * No opinion
> 
> Does your group think your registries benefit from the ability to publish 
> definitions and tables separately? (Not just separate files within the same 
> publication on /TR, but under completely separate /TR shortnames?) (See 
> https://www.w3.org/2020/10/TPAC/talk/Process2021#reg-must-together and 
> https://www.w3.org/2020/10/TPAC/talk/Process2021#reg-td-separate )
> * We need this
> * We'd use it if it was available but can live without
> * We would not use this
> * We think it's harmful
> [textarea for additional comments]
> 
> What else would you like us to know as we design a formal process for 
> maintaining registries at W3C?
> [textarea]
> 
> Thanks!

**Comment by jeffjaffe** [comment]
LGTM

**Comment by dwsinger** [comment]
> To help resolve a few of the major open questions on Registries, @frivoal and I suggest surveying the chairs. Proposed survey:
> 
> > Dear Chairs,
> > This survey asks follow up questions to
> > https://www.w3.org/2020/10/TPAC/talk/Process2021#talk If you haven't watched
> > it or read the transcript yet, you might want to do that first.
> > _Please answer on behalf of your Working Group._
> > Does your Working Group maintain a registry of some kind?
> > 
> > * Yes, we maintain one or more
> > * No, but we wanted to
> > * No, and this is not needed in our group
> >   [textarea for additional comments]
> > 

OK

> > The W3C Process CG and Advisory Board are drafting a process for maintaining
> > registries as formal technical reports, similar to other REC-track documents.
> > The registry would consist of both a formal definition of its format and
> > update process, as well as the tables of values (which could be published in
> > separate file(s) in human- and/or machine-readable format).
> > Does your group think registries would benefit from both a CR (testing) and PR
> > (AC approval) phase, or should registries skip CR? (See
> > https://www.w3.org/2020/10/TPAC/talk/Process2021#reg-cr-pr )

That's not quite the question. Should we make a separate process (and thereby lengthen the process document) for documents which contain purely registries, which skips CR? Is there a value of signalling to the community "we think we're done, please check, before we ask for a PR transition" even though pure registries do not have a "please implement".

> > 
> > * Registries should have a CR phase to experimentally validate the WD before
> >   requesting AC approval.
> > * Registries do not need a CR phase to experimentally validate the WD before
> >   requesting AC approval.
> > * No opinion
> >   [textarea for additional comments]
> > 
> > Does your group think we should define registries as being on the W3C
> > Recommendation Track, or should they have their own separate W3C Registry
> > Track (which clearly detaches them from the W3C Patent Policy)? (See
> > https://www.w3.org/2020/10/TPAC/talk/Process2021#reg-track )
> > 
> > * Separate track is better
> > * Re-using Recommendation Track as-is is better
> > * No opinion
> > 
> > Does your group think your registries benefit from the ability to publish
> > definitions and tables separately? (Not just separate files within the same
> > publication on /TR, but under completely separate /TR shortnames?) (See
> > https://www.w3.org/2020/10/TPAC/talk/Process2021#reg-must-together and
> > https://www.w3.org/2020/10/TPAC/talk/Process2021#reg-td-separate )

That's not quite the question either. "The common industry practice is to publish the registry tables separately from the definitions; we plan to allow publishing them together, as well, but should we disallow normal industry practice and require that the registry tables be published as, and in, the document containing the registry definitions?"


> > 
> > * We need this
> > * We'd use it if it was available but can live without
> > * We would not use this
> > * We think it's harmful
> >   [textarea for additional comments]
> > 
> > What else would you like us to know as we design a formal process for
> > maintaining registries at W3C?
> > [textarea]
> > Thanks!

**Comment by fantasai** [comment]
@dwsinger I think your first question alteration is helpful, but I think the second one is quite judgemental and I oppose such a wording change.

**Comment by frivoal** [comment]
> That's not quite the question. Should we make a separate process (and thereby lengthen the process document) for documents which contain purely registries, which skips CR? Is there a value of signalling to the community "we think we're done, please check, before we ask for a PR transition" even though pure registries do not have a "please implement".

I don't think I want to ask "Should we make a separate process[…]". Whether people want the extra phase or not is the key. After that, it's our job to figure out how to tweak the process to make that happen. (A separate process vs not isn't that much of a difference in text length anyway). As for asking about the extra phase, I agree about updating the text to use your phrasing.

> That's not quite the question either. "The common industry practice is to publish the registry tables separately from the definitions; we plan to allow publishing them together, as well, but should we disallow normal industry practice and require that the registry tables be published as, and in, the document containing the registry definitions?"

Maybe the wording we proposed isn't perfect, but your version is an extremely leading question. We're trying to find out whether this common practice is legacy baggage that isn't worth repeating, or whether it comes from a genuine need. You're convinced there's a need. We're not. I don't think it's useful to ask people what they think normal industry practices should be or whether we want to copy some other standards organization’s process, but rather to ask them what they actually need and plan to use.

With that said, if you think the way we asked the question is biased in some way, we should fix that, but I don't see it.

**Comment by fantasai** [comment]
Survey with updated wording on the second question:

> Dear Chairs,
> 
> This survey asks follow up questions to 
> https://www.w3.org/2020/10/TPAC/talk/Process2021#talk If you haven't watched 
> it or read the transcript yet, you might want to do that first.
> 
> <em>Please answer on behalf of your Working Group.</em>
> 
> Does your Working Group maintain a registry of some kind?
> * Yes, we maintain one or more
> * No, but we wanted to
> * No, and this is not needed in our group
> [textarea for additional comments]
> 
> The W3C Process CG and Advisory Board are drafting a process for maintaining 
> registries as formal technical reports, similar to other REC-track documents. 
> The registry would consist of both a formal definition of its format and 
> update process, as well as the tables of values (which could be published in 
> separate file(s) in human- and/or machine-readable format).
> 
> Would your group find value in signalling to the community in a CR phase
> to ask “we think we're done, please check, before we ask for a PR transition”
> even though pure registries do not have a “call for implementations”,
> or should we give registries a process that skips CR?
> (See https://www.w3.org/2020/10/TPAC/talk/Process2021#reg-cr-pr )
> 
> * Registries should have a CR phase to experimentally validate the WD before 
> requesting AC approval.
> * Registries do not need a CR phase to experimentally validate the WD before 
> requesting AC approval.
> * No opinion
> [textarea for additional comments]
>
> Does your group think we should define registries as being on the W3C 
> Recommendation Track, or should they have their own separate W3C Registry 
> Track (which clearly detaches them from the W3C Patent Policy)? (See 
> https://www.w3.org/2020/10/TPAC/talk/Process2021#reg-track )
> * Separate track is better
> * Re-using Recommendation Track as-is is better
> * No opinion
> 
> Does your group think your registries benefit from the ability to publish 
> definitions and tables separately? (Not just separate files within the same 
> publication on /TR, but under completely separate /TR shortnames?) (See 
> https://www.w3.org/2020/10/TPAC/talk/Process2021#reg-must-together and 
> https://www.w3.org/2020/10/TPAC/talk/Process2021#reg-td-separate )
> * We need this
> * We'd use it if it was available but can live without
> * We would not use this
> * We think it's harmful
> [textarea for additional comments]
>
> What else would you like us to know as we design a formal process for 
> maintaining registries at W3C?
> [textarea]
> 
> Thanks!

**Comment by plehegar** [comment]
are we going to rewrite for question1 and 3 today? I'll prepare the WBS over the week end.

**Comment by dwsinger** [comment]
yes. somehow we have to mention what the actual choice is in question 3, that some feel that normal industry practice should not be allowed. I don't know how to do that without making it a leading question.

**Comment by dwsinger** [comment]
So, question 1 (do you operate a registry) is one we have repeatedly asked. I see neither harm nor point in asking again.

Question 2 simply balances whether there is value in having a slightly longer process document in exchange for a slightly streamlined process. It's something that we should be able to resolve in the CG, but I can't seem to get people to engage on it.

Question 3 is about stopping the W3C from following normal practice, that registries are distinct, and different from, the specifications that define, embed, or use them. They are maintained differently, they have different approval status, and the normal practice is that they are published separately in order to make maintenance easier and the difference in status more apparent. Not permitting separate publication will enlarge the hurdle for those with quasi-registries, as well. Against these considerations I nonetheless offered to compromise and allow them to be published together, but again we have had very little input from others on whether we should even allow it, let alone require it. We're asking to settle a point of design principle by looking at a handful of existing responders, and I can't see how those responses will help illuminate whether we should *disallow* something.

I don't think it's worth sending this out; it just causes delay, and I doubt we'll learn anything, and I don't think it's worth my time trying to improve a survey that I doubt will yield anything and asks questions we ought to be able to resolve in the CG.

Philippe, I abstain. Do what you think best.

**Comment by plehegar** [comment]
I drafted https://www.w3.org/2002/09/wbs/34786/registries-chair-survey/ , taking into account as many things as possible and adding additional text to put things a bit more in context. I favor sending it to Chairs unless we think it's harmful.
@dwsinger @fantasai @tantek , unless I hear otherwise by Wednesday, I'll send it to chairs, with a deadline of February 10.

**Comment by dwsinger** [comment]
> This questionnaire is not yet open. It will open on 2021-01-13. Inform your Team contact if you think it should already be open.

**Comment by plehegar** [comment]
It's not open yet indeed. Will be open on Wednesday.

**Comment by dwsinger** [comment]
The point is that you appear to be asking us to review it, but we can't…

**Comment by plehegar** [comment]
oh, I thought you could at least read it, even if you can't answer it (which is what I get). I apologize if you can't even read the poll.

So, I opened the poll even if it's not announced yet, so that folks can read it:
  https://www.w3.org/2002/09/wbs/34786/registries-chair-survey/

**Comment by dwsinger** [comment]
thanks, that's fine...

**Comment by frivoal** [comment]
I still cannot read it.

**Comment by fantasai** [comment]
Results are posted at https://www.w3.org/2002/09/wbs/34786/registries-chair-survey/results
Closing this issue.

**Comment by nigelmegitt** [comment]
Just want to note, on reviewing the results, that it looks like question 2 was differently interpreted by different responders. Some responded to the detail part of the question which was about the Registry _Definition_, whereas others appear to have responded about the Registry values themselves. I think it's clear that the Registry values don't need a CR, but we need to take care interpreting the results about the Registry Definitions.

In retrospect, it is unfortunate that the wording of the options did not match the detailed description, i.e. the question said "Registry Definition" but the options just said "Registries".
