### ISSUE TITLE
What should be the effect of voting for No Other Candidate

### ISSUE THREAD

**Issue by michaelchampion** [w3c/w3process#47]
Section 2.5.2 of the Process Document https://www.w3.org/2017/Process-20170301/ states:
"The Advisory Board and a portion of the Technical Architecture Group are elected by the Advisory Committee, using a Single Transferable Vote system. An election begins when the Team sends a Call for Nominations to the Advisory Committee. Any Call for Nominations specifies the number of available seats, the deadline for nominations, details about the specific vote tabulation system selected by the Team for the election, and operational information such as how to nominate a candidate."  

In the most recent AB election, the Team added an option to the ballot "No (other) candidate" that could be ranked along with the listed nominees. But there appears to be no definition of what it means to rank this option above actual candidates.  

Should the Process Document define what happens if "No (other) candidate" gets enough votes by the team-selected STV vote tabulation system to have "won" one or more of the open seats?  Alternatively, should the Process Document specify that only actual nominated candidates appear on the ballot?  

Strawman proposal if there is a consensus to keep this option on future ballots: The Process Document should stipulate that no one getting less support than "No (other) candidate" would be seated, and those seats would remain open until the next election.   This would allow members to vote AGAINST candidates that they consider to be unsuitable, and in the presumably unlikely event that a candidate garners such strong opposition that "nobody" is preferred by the AC, that candidate would not be seated.

Adopting this approach might suggest removing the text in 2.5.2 after  "If, after the deadline for nominations, the number of nominees is" specifying  "Equal to the number of available seats, those nominees are thereby elected."  Arguably, an election could be held to determine whether any of the nominees get so much opposition that the AC would prefer the seat to remain vacant.

**Comment by dwsinger** [comment]
I think Michael is right; if there is such an option in the election, then once "and no other candidate" is elected, that seat and all subsequent seats are vacant. This corresponds to the voters' choice. This, by the way, has another consequence: even if the number of candidates is equal to or less than the available seats, the election must be held, in case the electorate prefers "and no other candidate".

We could certainly makes these changes to the Process.

However, this raises two major questions:
1) We are a 'small community'. The effect of telling some number of candidates "the membership thinks that leaving the seat vacant is better than having you elected" has to be assessed. This could easily be seen as insulting, and is likely to have a discouraging effect on standing in the first place; some are already offput by simply losing, and losing to an empty seat is much worse.
2) What happens next? Is another election called, or are the seats vacant until the next regularly scheduled election? If another election is called, is it presumed that the rejected candidates would not stand again, or are they barred from re-standing for the same vacancy? How many rounds of re-try do we do?

The first is a community management question; the second is policy, and both well outside the remit of the Process CG. I think they should be referred to the AB (who might, in turn, choose to refer them to the AC).

There is a question about what should happen at elections until such time as these questions are answered. Should the option remain on the form in the absence of defined handling and in the absence of guidance on how to use it, and what it means, to the electorate (the AC)? I think it should not -- formal processes should not have the possibility of branching onto an undefined road. I am not sure whether it's the Process CG's job to give such advice to the team (remove the option until its meaning and handling, and the consequences of using it, are defined, understood, and accepted); I rather think that's the AB's job.

**Comment by swickr** [comment]
When the "[TAG/AB election experiment on voting](https://lists.w3.org/Archives/Member/w3c-ac-members/2014JulSep/0047)" was announced to the Membership in September 2014 the "no other candidate" choice was described as follows:

> Both STV ballots will include a "No (other) candidate" choice (see [4]). 
 A vote for "No (other) candidate" is a vote for a hypothetical alternative. 
 With this option, any candidate with fewer votes than the hypothetical 
 alternative would not win - but since this is  experimental data not the 
 official election, it will not affect the actual outcome.
 ...
>[4] http://en.wikipedia.org/wiki/None_of_the_above

**Comment by dwsinger** [comment]
And indeed as part of the experiment it had the possibility to teach us something. As part of the official ballot where we don't have a process that causes "any candidate with fewer votes than the hypothetical alternative" not to win, that's a problem.

**Comment by dwsinger** [comment]
fwiw, "no other candidate" is marked as having withdrawn prior to tabulation, to cause the tabulation software to elect candidates to fill seats; thus, it isn't tabulated and we don't even learn something (that we'd prefer not to know, anyway)

**Comment by dwsinger** [comment]
The AB may ask us to make this option effective, i.e. if "no other candidate" wins a seat, the election leaves that and all other unfilled seats, vacant. We would need to work out what then happens. The TAG/AB remains one member short until the next election, or is there an immediate other election? And so on.

**Comment by chaals** [comment]
I would suggest that the seat is vacant and that another election is called. There are only two elected bodies - the AB and the TAG, and I believe it is helpful to fill the seats. 

Note that this implies removing the procedure whereby if there are as many candidates as seats an election is not held.

I also note that the only way to reach this outcome is to have a candidate that more people *really* don't want than there are voters prepared to accept, and to have only as many candidates as seats in the first place.

I doubt that this situation will occur much in practice - hopefully never, and it seems likely that this will be true. But if it is considered necessary by the membership, it is a useful thing to have.

**Comment by michaelchampion** [comment]
Whether or not it occurs in practice, we need to either take it out of the election form or add processing No Other Candidate votes to the process.

The simplest way forward would be to leave the seat vacant and call another election if No (other) Candidate wins. 

Or leave it vacant until the next scheduled election if we believe the AC will get election fatigue or that that the election captured their intention to prefer an empty seat to the candidates who got less support than No (other) candidate.  I think I lean toward waiting until the next election ... since these are advisory roles not formal governance roles, nobody is disenfranchised because they have no representative in in a legislative body.   Also waiting allows time for emotions that might have driven AC members to blackball some candidate to cool down.

**Comment by dwsinger** [comment]
fwiw, if this route is taken, it's only worth doing if it is expected it might be used and have effect. And then all the outcomes need consideration (not just the immediate formal process ones), including the effects on the rejected candidate(s), their companies, their culture, and the effect on the likelihood of other possible candidates not standing as a result of observing the humiliation. I would expect to formally object to introducing use of this.

**Comment by michaelchampion** [comment]
This looks like another issue that may or not reflect a real problem, and there is no obvious consensus on how to solve it if it is a problem.  I suggest the Process CG to advise the AB to advise the Team to remove "No (other) candidate" from the election form.  We have plenty of real problems that might possibly have consensus solutions to address.

**Comment by dwsinger** [comment]
I have tried multiple times to get it removed from the ballot, and 3 times failed to get consensus on that at the AB.

**Comment by dwsinger** [comment]
Closing, and requesting the team to remove the option from the ballot

**Comment by cwilso** [comment]
This is quite unfortunate, as I believe this is relatively easy to implement with process changes, and would show clarity in support.
