### ISSUE TITLE
Independence of chairs

### ISSUE THREAD

**Issue by jwrosewell** [w3c/w3process#470]
Whilst a chair can be expected to recuse themselves when a conflict of interest becomes apparent their affiliation might limit participants willingness to raise matters with the chair privately where such matters may relate to the activities of their affiliated organisation.

Every Community, Interest, Working or Business group must have a W3C team contact authorised to handle such matters. The group charter and summary web page must make it clear how issues can be raised.

This is important to further ensure that the W3C is not used as a channel for illegitimate collusion, or to facilitate anticompetitive conduct.

**Comment by chaals** [comment]
Working Groups and Interest groups have a chair and a team contact. Business Groups and Community Groups are not constrained, and are not a formal part of the process (in practice Business Groups do have a chair and contact). This bears on issue #17 

All groups are also covered by the code of conduct and the ombuds structures that are designed to ensure there is a neutral party to whom participants can raise specific concerns.

**Comment by LJWatson** [comment]
It is also the case that most WG have at least two chairs, and often that those chairs come from different types of organisation, so there are checks and balances.

**Comment by dwsinger** [comment]
We make it clear that the chairs are there to operate the group, and in general that is what they do (very well, IMHO, overall). Usually, chairs are careful to ensure that their co-chair handles matters of direct interest to them, and/or that they have a colleague present and argue such matters. If you are aware of examples where the chair is not being even-handed, indeed, a conversation with that chair and/or team member in question would be a good place to start.

**Comment by jwrosewell** [comment]
Thank you. I will consult the W3C Team when I observe issues.
