### ISSUE TITLE
Bias of W3C team members

### ISSUE THREAD

**Issue by jwrosewell** [w3c/w3process#471]
W3C team members must be impartial, however this has not been observed in practice. A method is needed in the process and the membership agreement to sanction W3C team members that demonstrate bias.

This is important to further ensure that the W3C is not used as a channel for anticompetitive conduct or collusion.

**Comment by wseltzer** [comment]
Team are all committed to the W3C [Code of Ethics and Professional Conduct](https://www.w3.org/Consortium/cepc/) and to provide a fair and vendor-neutral environment. Team are also invited to contribute their technical and professional expertise. 

Both the Ombuds and W3C management are available to any participant who feels a team member has acted inappropriately.

**Comment by dwsinger** [comment]
If you have a complaint about specific actions, please bring it to the attention of the appropriate people (which would depend on the nature of the complaint).

**Comment by jwrosewell** [comment]
We have had [a recent example](https://lists.w3.org/Archives/Member/w3c-ac-forum/2021JanMar/0000.html) that certain members disparage an entire industry and W3C Team have not yet intervened. There are previous examples that @wseltzer is aware of which I will not raise again.

This can be seen as bias. There are issues with all aspects of industry in their ability to achieve public benefit – and some businesses may find their position more challenging than others, I hope that focus on the issues (such as on-line fraud, or abuse of privacy or child protection), and specific evidence concerning the source of the issues will help to avoid this issue in the future.

The fact that there are specific requirements for ethical behaviour and vendor neutrality are helpful but may not address the issue of non-evidence based generalized preferences or bias against entire industries though. This issues has now been raised through different channels and I will close it.
