### ISSUE TITLE
Appeal process for proposals 

### ISSUE THREAD

**Issue by jwrosewell** [w3c/w3process#478]
Group chairs will make the initial decision should a complaint be received relating to the scope of a proposal fulfilling the goals of the W3C as defined in the membership agreement (see issue [459](https://github.com/w3c/w3process/issues/459)) within 7 elapsed days. Such complaints may be received publicly or provided privately to the chair or the group W3C team representative. 

Should disagreement remain, the General Counsel of the W3C will be asked to intervene by at least one member to seek to obtain consensus within 7 elapsed days.

Should consensus still not be possible a majority vote of the AC, or whatever body at the time represents W3C members, will make the final decision within 7 elapsed days. In the event of a tie arbitration shall be used to resolve the matter.

**Comment by chaals** [comment]
I think this proposal is ill-considered. Among the flaws I see:

For complex issues in an international organisation that generally takes years to complete a work item, seven days is too short for thoughtful consideration by hundreds of companies.

Expecting the General Counsel to resolve issues in this way is far too expensive for the existing financial and procedural structure of W3C.

There is no functional mechanism to hold a vote of the AC within 7 elapsed days, and the proposal fails to specify who is responsible for the vote, when the question must be put, how much time is available to the AC to consider and cast their vote, and other indispensable details.

A quick consideration of the number of discussions in W3C about whether a particular proposal is legitimate, and the time taken, suggests that trying to involve the AC in all those that endure beyond 14 days is at best foolhardy and disrespectful of the time that members have to devote to procedural decisions.

"Arbitration" is not defined here to make it actionable. (As an extreme example to demonstrate the problem, I propose that the clause be replaced with "The Excelentisimo Ayuntamiento y Alcalde de Maraña, León, in the Kingdom of Spain, shall be paid at prevailing commercial rates by the party originally raising the complaint to make a binding determination on the question". They are certainly cheaper than W3C's general counsel.)

**Comment by chaals** [comment]
Note that a more productive approach to addressing issues like this might be to propose concrete changes to [section 3](https://www.w3.org/2020/Process-20200915/#Policies) of the Process Document - especially sections 3.3 and following.

**Comment by dwsinger** [comment]
I don't understand the context of this, and whether it's intended to replace the existing Formal Objections or Appeals process, or augment it, and if the latter, for what cases?

**Comment by jwrosewell** [comment]
This relates to an appeals process where a proposal is considered out of scope by a proposer or is challenged by another. It relates to [476](https://github.com/w3c/w3process/issues/476) and might be combined with it. This issue is only relevant if we can agree the need to ensure fit with the W3C purpose, mission, goals, etc at inception.

I'm not sure the Formal Objections or Appeals process would be appropriate or desirable in every instance. A lighter weight method may be needed before reaching these stages.

**Comment by dwsinger** [comment]
> I'm not sure the Formal Objections or Appeals process would be appropriate or desirable in every instance. A lighter weight method may be needed before reaching these stages.

Ah, I'm sorry. Indeed, before resorting to formal appeals, one would expect that concerns have been raised and not adequately addressed. For example, formal deliverables of the W3C (Recommendations) are identified in charters of working groups. When rechartering is under way, the general practice is that the WG discusses the draft, and a notice of the intent to revise is often sent to the AC. Yes, one would expect members of the WG to raise concerns about the scope of work in the WG discussion, and AC members to comment and raise concerns with the chair and team contact. The charter then goes to formal ballot, and formal objections can then be raised, but it's not great if there were opportunities to address concerns earlier that weren't taken (but we understand that not everyone can see all preliminary work).

Similarly, if someone feels that a draft Recommendation is stepping outside the scope that it was described as having in the charter, or outside the scope of the WG that owns it, or outside the scope of the W3C, we'd hope that that concern would also start in the WG, and only raise to the level of formal objections or appeals if it couldn't be resolved in debate and consensus.

**Comment by plehegar** [comment]
(move to w3c/guide?)

**Comment by frivoal** [comment]
@jwrosewell as we're wrapping up this process cycle and you filed this issue, I would like to ask for confirmation.

In summary:
* Intervals of 7 days are too short an interval for appeal process steps, both for administrative reasons, and for substantive reasons, as @chaals outlined in https://github.com/w3c/w3process/issues/478#issuecomment-747099158
* "Adding" an appeal process would be redundant with existing appeal processes. From expressing disagreement when a proposal is initially made, to [registering dissent](https://www.w3.org/Consortium/Process/Drafts/#managing-dissent), to having [FOs processed by the Council](https://www.w3.org/Consortium/Process/Drafts/#addressing-fo), to having the ability to file an [AC Appeal](https://www.w3.org/Consortium/Process/Drafts/#ACAppeal), there's already a path to express and escalate disagreement, and no decision is final until these are all exhausted. I'll also note that, as in your proposal, this escalation chain ends with a majority vote of the AC (the AC appeal).
* The ability to provide feedback and complaints privately to the chairs or to the team or through formal objections already exists, it is therefore not something we can add.
* It may be useful to have better documentation (as discussed in https://github.com/w3c/w3process/issues/478#issuecomment-947736225) to make sure everybody understands their role, rights, and responsibilities, but that is a documentation question, not a Process question.

Despite your specific proposal being rejected, do accept the conclusion of this discussion, or do you wish to register disagreement?

**Comment by jwrosewell** [comment]
Please see the attached letter which covers these points and many more. I wish to see the issue raised in this letter addressed by W3C Inc before progressing any changes to the process including the appeals process.

[2023.01.25_W3C-Letter_W3C-redacted-version (2).pdf](https://github.com/w3c/w3process/files/10965347/2023.01.25_W3C-Letter_W3C-redacted-version.2.pdf)

**Comment by fantasai** [comment]
Hi @jwrosewell, that letter is largely off-topic for this specific issue. Can you please respond directly and articulately to https://github.com/w3c/w3process/issues/478#issuecomment-1453030404? Thanks~

**Comment by jwrosewell** [comment]
The question from @frivoal which I was responding to was "Despite your specific proposal being rejected, do accept the conclusion of this discussion, or do you wish to register disagreement?"

I'm registering disagreement.

The issues associated with the Process can not be adequately addressed without first addressing the systemic issues associated with W3C. Overall work on the Process should be halted until this is done.

There needs to be a mechanism and an environment willing entertain the rejection of any proposal at inception. For example; the Private Advertising Community Group, the TAG, or the Privacy Community Group host many proposals that fall foul of the W3C Antitrust Guidelines as they expressly seek to restrict competition by limiting data transfers and established standards in practice of interoperability. The W3C Antitrust Guidelines are not enforced. Why not? These have been appealed to the previous General Counsel who advised on multiple occasions that issues associated with antitrust should not be raised.

If you are suggesting that I should raise Formal Objections concerning the decision to continue these groups then I'd be happy to do so. However I believe that this would be a waste of time in practice. A Council will be formed, the Council would reject the Formal Objection as it's made up of people who are long time W3C participants and believe the current way is the only way, the decision will go to an absent Director who will also reject the Formal Objection.

@frivoal Is this your understanding?

**Comment by frivoal** [comment]
> I'm registering disagreement.

Thank you for the clarification.

> If you are suggesting that I should raise Formal Objections concerning the decision to continue these groups then I'd be happy to do so. However I believe that this would be a waste of time in practice. A Council will be formed, the Council would reject the Formal Objection as it's made up of people who are long time W3C participants and believe the current way is the only way, the decision will go to an absent Director who will also reject the Formal Objection.
> 
> @frivoal Is this your understanding?

I am not suggesting anything either way. You may file formal objections if you think this is appropriate, and I expect any such objection to be handled fairly according to the then current Process. Per the Process, if you disagree with the chartering (or rechartering) of any particular group, or with decisions regarding the publication of a document, filing a formal objection is a potential recourse.
