### ISSUE TITLE
Whistle blower

### ISSUE THREAD

**Issue by jwrosewell** [w3c/w3process#481]
A whistle blower process should be in place to ensure that higher authority can be called in to deal with abuses and disputes concerning governance and an escalation on processes and governance should be available at a level above groups.

This will help to ensure that members follow the membership agreement, and that discussions do not veer away from the creation of competitively neutral standard making.

**Comment by chaals** [comment]
There are already several processes to do this - the set up of groups including charter reviews, the facility for appeal of decisions, the ombuds structure that provides a general avenue for relief.

It isn't obvious what problem this issue is addressing, nor what further structure would improve the ability to do what is asked - as far as I can tell that is already provided for in multiple ways.

**Comment by TzviyaSiegman** [comment]
In terms of human interaction all W3C groups, email lists, repos etc operate under https://www.w3.org/Consortium/cepc/

**Comment by dwsinger** [comment]
We have various ways to escalate, as noted:

* [Code of ethics](https://www.w3.org/Consortium/cepc/), and the availability of people to help
* The ability to file formal objections, which can be team confidential
* The ability to appeal formal decisions

In addition, the team (including counsel), the TAG, and the AB all remain available to hear of concerns of any kind.

Can you be more specific, please?

**Comment by TzviyaSiegman** [comment]
Note that this exists https://techworkerhandbook.org/

**Comment by frivoal** [comment]
This should probably move to the AB, or possibly to the Board once there is one, but it's out of scope for this CG. @TzviyaSiegman @cwilso, can you move this to an AB repo?

**Comment by frivoal** [comment]
The board has adopted a whistleblower policy. https://www.w3.org/Member/bod/policies/whistleblower

This issue should be closed. If there are any issues about the policy that the board adopted, those should be reported to the Board.
