### ISSUE TITLE
Proposed additions?

### ISSUE THREAD

**Issue by plehegar** [w3c/w3process#483]
[[
Identify the specific candidate amendments under review as proposed amendments (proposed corrections/proposed addition).
]]
https://w3c.github.io/w3process/#proposed-corrections

Why not "(proposed corrections/proposed additions)" (plurial on addition) toi make it consistent?

**Comment by frivoal** [comment]
Good catch. This is accidental, and a trivial editorial fix, so I am accepting it without a need for CG consensus.
