### ISSUE TITLE
Stop staggering AB/TAG election cycles

### ISSUE THREAD

**Issue by chaals** [w3c/w3process#486]
The current Process has about half of available seats up for election in any given year. The rationale is to ensure some carryover providing some "institutional memory".

I propose that instead we continue to use STV voting to elect the entirety of each body for two-year terms, with the AB and TAG elections taking place around the end of the year in alternating years. The transition strategy would be to have an AB elected under the current system sitting for an extra six months.

Rationale:

Institutional memory

I value institutional memory in those bodies very highly. However, I don't think the rolling elections are the right way to achieve the goal. We generally see a fair amount of continuity across elections. Many serving members are prepared to serve multiple terms, and there is an observable apparent "incumbency advantage": Ordinarily, candidates standing for re-election are more likely to win than new candidates.

It is also the case that the AB, and even more so the TAG, have several Team members or appointees who can provide an institutional memory (indeed, to my mind that is one of the core functions of the Team, and a criterion by which I make my personal assessments of whether they are doing a good job).

There has been one instance of a complete turnover (over two years), which was a change of the TAG. 

In my opinion (I don't have access to all the data, and it would not be conclusive anyway, but I have watched W3C elections carefully for a couple of decades), had we used STV for a full set of candidates, we would instead likely have elected some TAG members whose primary interests were related to those of the "old TAG", a majority much like the current majority, and perhaps a candidate or two with a more direct interest in an area such as privacy or accessibility. In other words, my analysis of that situation is that the staggered election didn't preserve a significant amount of institutional memory, and the plurality voting system we then used actively suppressed it by allowing a new largest minority to determine all elected positions over a 12-month period.

Disruption

The TAG requested, until the AC agreed, a Process change that meant a member who became ineligible would continue to sit until the next ordinary election. The specified reason was the disruption caused by the change in membership. My own decade-odd experience of the AB is that there is a notable productivity cost after each election, as people who led particular pieces of work were no longer members, while new members took some time to learn how to be productive.

Giving each body a full two-year term will halve the number of disruptions, allow for longer timescales to plan and complete work items. Even in the unlikely event that we again see no sitting member returned to a body, an all-new AB or TAG will presumably consist of enough people who have followed the work through reading minutes and paying attention that they can still be productive within a relatively short time.

Diversity

Under plurality voting, we essentially expect the bodies to represent the largest single voting bloc. Typically, in W3C, this skews toward organisations with a particular technical or commercial focus, rather than diversity as considered in terms of demographics. (The TAG turnover is a case in point). The staggered terms mean that we amplify that effect, whatever the voting system.

Transparency

There are some added twists, to do with the nomination of invited experts, so currently one member cannot have two employees on the same body, one member can nominate two invited experts, or one employee and one invited expert. While I think this is not a terrible practical problem, it does violate some obvious principles of fairness and transparency. Removing the staggered terms would put each nominating member back onto a slightly more level playing field.

**Comment by LJWatson** [comment]
Your reasons for changing the cadence of elections seem to be arguments for using STV. Setting aside STV for the moment, given that we've been using it for some time now, it isn't clear what the rationale for changing the lection pattern might be?

**Comment by chaals** [comment]
@LJWatson wrote

> Your reasons for changing the cadence of elections seem to be arguments for using STV ... what the rationale for changing the election pattern might be?

The arguments are not reasons to use STV. The proposal is to keep doing that, but without the split cycle.

The major reason to elect the whole body at once is that the split cycle actively restricts diversity of representation.

The strongest reason to retain the current split election cycle is to ensure some stability, allowing for institutional memory to be handed down. I don't think, in practice, that is a problem that needs solving.
- A **complete** turnover is significantly less likely under STV than the old Plurality system.
- We only saw one "complete turnover" in about two decades of plurality voting anyway.

The other reason to have the groups stable over two years is to minimise disruption to work. In a decade-plus on the AB my experience suggests it takes some months for most AB members to be really getting productive. When half the people who are working together on projects can disappear each year, that makes for a very unstable environment and a lot of things get dropped before completion, *partially* as a result of the instability. Two years of stability seems likely to provide better accountability for work undertaken, for both the TAG and AB. 

The TAG explicitly argued a few years ago that membership disruption caused problems, which led to the weakening of the requirement that one W3C member could not employ 2 of the 5 elected members.

**Comment by TzviyaSiegman** [comment]
I'm a little confused about what the proposal here is. Is the proposal to change the elections to bi-annual but make them for the whole AB/TAG? (Leaving election method out of this as I think it's a separate issue).

**Comment by dwsinger** [comment]
That's my understanding; chaals might correct me. We currently elect half the TAG at the year-turn, and half the AB mid-year. As I understand it, we'd elect the whole TAG in each year-turn election, and the whole AB mid-year, i.e. a possibility of complete turn-over.

**Comment by fantasai** [comment]
I'm strongly against this change. I think there are a number of benefits to staggering the elections:
- Some subset of the AB is guaranteed to persist through the election, making it easier to plan on continuing work.
- Smaller cohorts mean each representative needs to have a stronger backing from the Membership; in a consensus-based organization with STV voting, unstaggering elections risks increased factionalization, which is unhealthy.
- Staggered cohorts means that the AC can recruit and elect their candidates for this year in consideration of candidates remaining from the previous, allowing for a more informed choice and deliberate distribution of elected members' skills and perspectives.
- Yearly cycles allow more opportunities to recruit new people, and more opportunities for people who aren't doing this as a career to step in for a few years when it lines up with their life schedule and work goals. If you care about diversity, this matters, too.
- Yearly (rather than bi-annual) cycles allow our membership to more precisely tune our AB and TAG representation to what's needed and what's happening at W3C.

As a concrete example, there's a reasonable chance I would not be on the AB if we were in bi-annual election cycles: I'm here for these two years to address a very specific set of circumstances around necessary Process changes and the LE transition, and would not have run if I didn't have the availability or hadn't been convinced it was critical at this time. Eric also was recruited for very specifically timed needs.

> There are some added twists, to do with the nomination of invited experts

If this is a serious concern, file a separate issue against the Process to disallow nominating anyone in this cycle if you already have a nominated person persisting through the election. Addressing this does not require anything more than such a rule.

**Comment by chaals** [comment]
@fantasai wrote

> [quoting me...]
> >There are some added twists, to do with the nomination of invited experts
>
> If this is a serious concern, file a separate issue against the Process to disallow nominating anyone in this cycle if you already have a nominated person persisting through the election. Addressing this does not require anything more than such a rule.

Sure. There are a small number of cases where this happens, that aren't obviously a big problem in practice. It's about having a sense that the rules are clear and fair and apply fairly. Given the ease of finding another nominator to stop even the perception of a problem, I am not sure if it's worth fixing on its own.

**Comment by chaals** [comment]
@dwsinger wrote

> [quoting me]
> > the split cycle actively restricts diversity of representation
>
> I don't see this, and hence don't agree.

@fantasai wrote

> Smaller cohorts mean each representative needs to have a stronger backing from the Membership; in a consensus-based organization with STV voting, unstaggering elections risks increased factionalization, which is unhealthy.

You guys should talk about this aspect :)

(I don't buy the argument that "increased diversity of representation", even if called factionalization, is unhealthy for the body that is meant to represent the broader membership the W3C team).

**Comment by LJWatson** [comment]
The major reason to elect the whole body at once is that the split cycle actively restricts diversity of representation.

The TAG and AB have both made improvements in organisational and demographic diversity in recent years. It is almost entirely because of a concerted effort to nominate more diverse candidates, and it is not at all clear how changing the election cycle would make any difference. 

>The strongest reason to retain the current split election cycle is to ensure some stability, allowing for institutional memory to be handed down. I don't think, in practice, that is a problem that needs solving.

If it is not a problem that needs solving then it is not an argument for changing the election cycle. If, as you say, some of each group will always be re-elected, then the election cycles won't make any difference - but staggered cycles do protect against the possibility of 100% turnover, and it seems better to have that protection in place and not need it, than the reverse.

**Comment by chaals** [comment]
> If, as you say, some of each group will always be re-elected, then the election cycles won't make any difference - but staggered cycles do protect against the possibility of 100% turnover, and it seems better to have that protection in place and not need it, than the reverse.

I actually said that historically there is only one case where there wasn't re-election of some candidates, and it seems unlikely to recur.

However, if the membership thinks that a 100% turnover is warranted, I think forcing it to take a year to do is unhelpful. I have been in groups where one part of the group doesn't really see the other part as legitimate participants, and I don't think it is a productive work environment.

**Comment by chaals** [comment]
Tzviya wrote:

> I'm a little confused about what the proposal here is. Is the proposal to change the elections to bi-annual but make them for the whole AB/TAG?

Yes. Because that retains the default two-year term for each elected member. Changing that is a separable issue, and one I don't think it worthwhile so haven't raised it myself.

**Comment by cwilso** [comment]
To go on the record: I also think that this would be a Bad Idea.  I think the thrash of changing the entire group at one go is odd; I would also point out that in contrast to the point above, if the membership thinks replacing the entire group is warranted, it would be forced in half the cases to take MORE than a year to do it (depending on where you are in the election cycle); as least with staggered elections you could vote out half the offenders.  Realistically, I don't see this as a remotely possible or interesting scenario, but I do think what we have is good enough, and would not be improved by a change of this type.

**Comment by dwsinger** [comment]
I think this is a policy question, rather than implementation, and would like to know from the AB whether to pursue this.

**Comment by cwilso** [comment]
I would note it appears to be the consensus of the AB to close this issue. (we briefly discussed it, and there was no dissent.)

**Comment by cwilso** [comment]
Indeed, we have now put this consensus in our minutes.

**Comment by dwsinger** [comment]
without AB support I do not see we should discuss this or consider acting on it; I would suggest any who disagree to take this up with the AB.

**Comment by chaals** [comment]
@dwsinger:

I am not disputing the apparent resolution of this issue beyond noting that I disagree - but it seems I am in a small minority and that's how things go.

But it is difficult to participate in a public group, and simply be told "the AB says No" - given that the AB discussion and minutes are not public, that leaves people guessing how the higher powers decided, which seems like a bad approach to inclusivity.

I realise the AB has that power, as the group that proposes a new Process document to the AC, but I hope that the reasons the AB said no will be explicitly given in the public issue, so we know that participating in this group is worthwhile because input here is actually taken into account.

**Comment by LJWatson** [comment]
> But it is difficult to participate in a public group, and simply be told "the AB says No" - given that the AB discussion and minutes are not public, that
leaves people guessing how the higher powers decided, which seems like a bad approach to inclusivity.

Essentially, the AB collectively agreed with the opinions of the six AB members who've commented on this issue.

**Comment by cwilso** [comment]
@chaals the minutes WILL be public, and @swickr has taken an action item to add a pointer to the minutes here when they are public.  But I will note (as @LJWatson just said) that everything substantive was said in comments here already; the AB chair for the meeting (that's me) just checked for consensus and asked if there was any dissent.

**Comment by chaals** [comment]
Thank you.

**Comment by swickr** [comment]
The [minutes](https://www.w3.org/2021/04/01-ab-minutes.html#t06) (Member-only) were published yesterday.

**Comment by LJWatson** [comment]
Now the minutes have been referenced, this issue can be closed per AB consensus.
