### ISSUE TITLE
Deadline for the council to process FOs

### ISSUE THREAD

**Issue by frivoal** [w3c/w3process#491]
As documented in https://www.w3.org/mid/db8a03dc-5da1-778d-7ccf-9e0499947306@inkedblade.net, the TAG resolved: 
> If FO not resolved in X days, chair MUST report status to AC.
> Report MAY be public. Suggest 90 < X < 180.

Do we want to agree with the TAG and fold that in the Director free branch?
If so, what is the value of X?

Note: We currently specify that the Team has 45 days from the FO being filed to try to resolve the issue and report to the Council. This issue is about a deadline on the Council itself.

**Comment by jeffjaffe** [comment]
AB+TAG is doing a post-mortem on a Council experiment.  I suggest we ask them as part of that analysis to propose a value for X.

**Comment by chaals** [comment]
45 days is a long time to leave the AC wondering what happened when a group was proposed and a charter reviewed, or a spec was apparently ready to go to Rec. 90 days - three months - feels like it starts to leave people with difficulties in planning. I agree with @jeffjaffe that we should hear about the post-mortem on an actual experiment, but *a priori* I would suggest 30 < X < 60 in general...

**Comment by dwsinger** [comment]
I think 30 days is a fine number to require a status update (we need to say from when; from when it was formally convened, I think)

**Comment by dwsinger** [comment]
I'm not in favor of a hard deadline for a decision, but perhaps after a certain time has expired, there are people who can insist on a decision?

**Comment by chaals** [comment]
@dwsinger wrote:

> I'm not in favor of a hard deadline for a decision, but perhaps after a certain time has expired, there are people who can insist on a decision?

 No, I think we judge the council on their ability to reach a decision (since we elect most of them, there is more accountability than we see from the team), but they should be capable if reaching their own decision and I don't think we need, or should have, a forma forcing function.

**Comment by frivoal** [comment]
[Current Draft](https://www.w3.org/Consortium/Process/Drafts/director-free/) has 45 days, @chaals suggested as low as 30. What do we want to do?

**Comment by chaals** [comment]
4 1/2 months of radio silence, with no constraints on when something will follow a statement "we're working on it, stay tuned", is a terrible approach to transparent decision making. That's [what the current draft says](https://www.w3.org/Consortium/Process/Drafts/director-free/#addressing-fo).

 I propose that we require a status report every 30 days (including during the Team's 90-day window), which SHOULD outline any points of agreement reached to that time.  This is likely to be a 5-line email with a couple of bullet points, linking to the list of objections (although a bullet might be "council and objector have not yet managed to agree what the objection is").

**Comment by jeffjaffe** [comment]
> This is likely to be a 5-line email

I suggest that it be posted in some public place, rather than more email.

**Comment by chaals** [comment]
> I suggest that it be posted in some public place, rather than more email.

Email is the Consortium's default way of notifying members of things, and emails streams are easy to process for many (and archived in public already for the rest). If the email points to something on the web (e.g. an update to the page that describes the status), that's OK.

**Comment by frivoal** [comment]
Resolved by merging the director-free branch.
