### ISSUE TITLE
Should we make it explicit that participation in the Council does not require travel?

### ISSUE THREAD

**Issue by frivoal** [w3c/w3process#492]
As documented in https://www.w3.org/mid/db8a03dc-5da1-778d-7ccf-9e0499947306@inkedblade.net, the TAG resolved:
> Council participation cannot require F2F participation.

Do we agree with the idea? Do we believe the idea needs to be written into the Process or should it just be a guideline/expectation?

**Comment by TzviyaSiegman** [comment]
Please make no travel required explicit.

**Comment by dwsinger** [comment]
@TzviyaSiegman I think that's fine. "Members must be able to participate fully in the council without being required to travel."?

**Comment by cwilso** [comment]
"Council participation will not require travel."

**Comment by dwsinger** [comment]
@cwilso you make it a statement of fact, whereas I think it needs to be a requirement on those setting up the operation of a council instance…hence my formulation

**Comment by frivoal** [comment]
This is now covered in https://www.w3.org/Consortium/Process/Drafts/director-free/.
