### ISSUE TITLE
Clarify Team Amendments

### ISSUE THREAD

**Issue by fantasai** [w3c/w3process#493]
When dropping Amended Recommendations (in https://github.com/w3c/w3process/pull/428), we added a paragraph saying that the Team can make editorial changes to a REC including adding candidate corrections:

> If there is no Working Group chartered to maintain a Recommendation, the Team may republish the Recommendation with such changes incorporated, including errata and candidate corrections.

The tricky thing about candidate corrections is that they *are covered by the Patent Policy* (as Working Draft material), but the Team making changes without a Working Group can't invoke the Patent Policy.

So I think we need to distinguish corrections made by the Team (as opposed to the WG) more clearly, and to clarify in the Process that such corrections are not covered by the Patent Policy. I suggest calling them “Team Corrections” to make this clear and adding some text defining that these aren't covered by the Patent Policy.

Note: We do require in 6.1.5 that the team be explicit that they authored these corrections, but there's currently no dedicated label to identify them.

**Comment by wseltzer** [comment]
@dwsinger and I made similar comments in the PR https://github.com/w3c/w3process/pull/494

**Comment by frivoal** [comment]
Closed by #494
