### ISSUE TITLE
Requirements for advancement to Recommendation

### ISSUE THREAD

**Issue by plehegar** [w3c/w3process#496]
For transitioning to Recommendation, the Process points to the requirements for advancement. The first item in the list of requirements is "must record the group’s decision to request advancement." Since no substantive are made to move to Proposed Recommendation, is it required to record a new Group decision to move to Recommendation or is the group decision to move to Proposed Recommendation enough?

**Comment by nigelmegitt** [comment]
Good shout @plehegar this has always been an odd thing when we've been wanting to transition to Rec.

One possible solution is to define a "document owner" for the document which is the WG at WD and CR stages, but then transfers to the Director at PR. Then it's the _document owner_ who must record the decision to advance.

This may pave the way for a nice change for specs that are developed in a CG and then transferred to a WG, in that the document owner would change, and it would be clear who owns it.

**Comment by frivoal** [comment]
Since the only purpose of going to PR is to go to REC, I think a group decision to request PR is also a group decision to (attempt to) go to REC. Maybe we can clarify in the Process if there's any doubt, but I don't think this should cause any problem in practice.
