### ISSUE TITLE
Anonymous formal objections

### ISSUE THREAD

**Issue by jeffjaffe** [w3c/w3process#497]
There are circumstances where an objector feels the need for anonymity.  We need to discuss how the W3C Council approach would work in that case.

Recently there were 5 formal objections raised to a transition to FPWD and 4 of them were raised anonymously.   The chairs protected the anonymity behind the anonymous objections and attempted to address the objections before taking forward the transition request [1].  The chairs were unable to satisfy the objections and the objections were taken forward to the Director.  PLH, acting for the Director overruled three of the objections and left one open - but did not allow the objections to block the transition to FPWD [2].

If the Council were to dive into the details of the objection at the level done by the chairs and PLH, I'm quite certain that they would have needed to hear about these objections.  But given the size of the Council, that would have broken anonymity.

[1] https://lists.w3.org/Archives/Public/w3c-wai-gl/2020OctDec/0190.html

[2] https://github.com/w3c/transitions/issues/303#issuecomment-763920337

**Comment by dwsinger** [comment]
How would "The person or entity making a Formal Objection may request anonymity, and brief a Team Member, who will present the Formal Objection to the Council, and answer questions." I.e. the FOer is either given or selects a proxy, work?

Obviously there may be something about the very nature of the objection that reveals the source. I think we can only ask that the Team Member Proxy (TMP) work with the FOer to minimize this risk and present the objection in a suitably anonymized way.

**Comment by dwsinger** [comment]
Mind you, anonymity on the big red STOP handle is kinda strange. Maybe we should work on why they are needed, because it somewhat disturbs me.

**Comment by jeffjaffe** [comment]
To protect anonymity, I can't go too much nto specifics.  But in some cases, it might not be possible for a third party to represent an objector.  A Team Member as an intermediary, may indeed address some cases.

**Comment by chaals** [comment]
We don't have a mechanism for making a formal objection without telling the team. And from a practical perspective we don't have any real insight into what confidentiality in the team means - there are 50-odd people, and almost everything about how information flow among them is limited relies on processes that are not visible to those of us outside.

In any event, the nature of an objection normally needs to be clear, if not who made it. I can imagine mechanisms for actual anonymous objection (that's he sort of thing we work on), but in practice I think the obligation should fall on the team. @jeffjaffe is there any case you can imagine where that would not be possible?

**Comment by jeffjaffe** [comment]
Thanks, @chaals 

In terms of the WAI objections listed above, I believe that the team was able to process the formal objection while preserving anonymity.

The formal objection needed to be handled by the Director.  Since the Director is only one person, it was not difficult to further protect anonymity when the objection went to the Director.  It meant involving only one additional person.  That person (PLH) decided that in this case, he needed to hear directly from those raising the objection.

The new director-free concern that I raised is if in "director-free" the norm is to have a committee with many people ruling on objections, it would be useful if we also designed a mechanism to continue to protect anonymity.

**Comment by fantasai** [comment]
I think using a Team member (or someone else) as an intermediary is pretty do-able, and afaict doesn't need any real formalization. The Team member can forward the contents of emails back and forth, can summarize and present info in either direction by text or speech, and can even invite the objector to an IRC session of the Council under a pseudonym. None of these are banned by the Process, and imho none of them need to be encoded into it either.

As for if the nature of the objection is intrinsically revealing, there is really not much we can do about that. The Council is bound to respect the appropriate level of confidentiality for an objection, but I don't think there is any reasonable way to withhold the contents of an objection from the full Council if it comes to the point of being decided by the Council.

**Comment by wseltzer** [comment]
Anonymity has a different (and I'd suggest smaller) role in multistakholder decision processes than it does in an adversarial contest. In multistakeholder decisions, *whose* stake is being poked is an element of evaluating the position. So it seems fair that participants who nonetheless choose to objections anonymously have those objections addressed on their face, without the further dialogue that they'd get if they participated with an individual or group identity.

**Comment by plehegar** [comment]
See also #291

**Comment by dwsinger** [comment]
this might interact with e.g. conflict of interest and dismissal; the nature of the objection might strongly suggest the source.

**Comment by dwsinger** [comment]
This connects with team-only responses to AC review

**Comment by jeffjaffe** [comment]
Today we discussed how we might address this.

Something like:

"There may be circumstances where an objector wants complete anonymity when raising their objection.  That would be difficult given that objections are evaluated by a large council.  In that case, the Team may be asked by the objector to anonymously raise the objection.  Depending on the nature of the objection, the Team may not be able to fully represent the objection - but will do the best they can."

**Comment by jeffjaffe** [comment]
Now that we have opened #618, I wonder if that is a cleaner way to address this issue.

**Comment by dwsinger** [comment]
agreed, one possible reason to defer is that the Council realizes that they cannot process the FO while respecting anonymity (and we should say that). Not necessarily true for all anon FOs, of course.

**Comment by frivoal** [comment]
@jeffjaffe, with #618 resolved, do you think we are good to close?

**Comment by jeffjaffe** [comment]
> @jeffjaffe, with #618 resolved, do you think we are good to close?

+1
