### ISSUE TITLE
TAG appointment committee should exclude those also up for re-appointment

### ISSUE THREAD

**Issue by dwsinger** [w3c/w3process#498]
This

> 2 participants of the current TAG, randomly selected from those who are not running for election

should read something like

> 2 participants of the current TAG, randomly selected from those whose terms are not expiring

except that's wrong, we don't need to exclude someone whose term is expiring but who isn't standing.

> 2 participants of the current TAG, randomly selected from the elected members who are not running for election and from the appointed members whose terms are not expiring.

**Comment by nigelmegitt** [comment]
Why would a member whose term is not expiring be running for election?

**Comment by dwsinger** [comment]
we're talking about members of the appointment committee, not candidates. 

Those whose terms are expiring, and hence might be candidates for appointment, probably shouldn't serve on the appointment committee. So maybe "those whose terms are not expiring" is right, as someone might decide not to run but instead get appointed. hm. would a simpler fix be to say that members of the appointment committee cannot be appointed?

**Comment by nigelmegitt** [comment]
Okay, if I've understood right,
> 2 participants of the current TAG, randomly selected from those who are not running for election

allows for selection (twice) of any member of current TAG who is `[continuing as a member] OR [not continuing AND not running for election]`. As you suggest, if the decision to run for election might be made _after_ choosing the appointment committee, then that's a problem, and it is worth saying "if your membership of TAG is ceasing and you accept a place on the appointment committee, you may not then stand for election".

**Comment by dwsinger** [comment]
…and you may not be appointed by the appointment committee on which you are serving.

Though I wonder why it's a problem to have someone serve on the appointment committee while also running for election?

**Comment by nigelmegitt** [comment]
> Though I wonder why it's a problem to have someone serve on the appointment committee while also running for election?

I think you may reasonably be open to suggestions of rigging the election in your favour if, as a member of the appointment committee, you encourage other candidates to stand, where the choice of those candidates is somehow tactically arranged to give you a benefit.

**Comment by dwsinger** [comment]
The appointment committee has no say in the election; it's filling, after the election, seats that currently the Director appoints to.

**Comment by nigelmegitt** [comment]
Then why not create the committee after the election from a now-stable group of TAG members?

**Comment by dwsinger** [comment]
Timing; we want the appointments made asap after the terms end. But I think more to the point, we want to work out what rules are needed about those whose term is ending, service on the appointments committee, and the appointments it makes.

**Comment by nigelmegitt** [comment]
Right, thanks for explaining @dwsinger, apologies if these are already-answered questions.

One consequence of arranging the appointments committee before the election, and saying that those standing for election cannot be on that committee, is that newly elected members won't ever be on the committee. Arguably that could slightly limit too-rapid change, which feels like a nice-to-have to me.

Specifically it prevents the pattern: new member elected to TAG (maybe with controversial/radical views?), lands on the appointment committee, which then appoints someone else to TAG who shares those controversial/radical views. I'm not sure if preventing this pattern is pro- or anti-democratic!

**Comment by fantasai** [comment]
I think the idea of putting TAG members on the committee was to give it a good understanding of what the TAG needs. A newly-elected member wouldn't bring that experience...

**Comment by frivoal** [comment]
By AB resolution (and with support from the TAG), there is no longer a TAG Appointment Committee. Instead, the Team is asked to seek input from the community and make an appointment, subject to ratification by the incoming TAG (which doesn't include those potential appointees).
