### ISSUE TITLE
remove "adopted draft"

### ISSUE THREAD

**Issue by samuelweiler** [w3c/w3process#500]
Let's remove the requirement that the ["Adopted draft" line appear under some work items in charters](https://www.w3.org/2020/Process-20200915/#WGCharter).  The link to the current doc will already be present (in the header for that work item), and the substance re: IPR is already covered by "exclusion draft".

"Adopted draft" is cluttering charters, which are much too cluttered already.

**Comment by dwsinger** [comment]
If you could look at the history of why this was done, and suggest an alternative that addresses the concerns, I would appreciate it.

**Comment by samuelweiler** [comment]
I'm delighted to look at the history, but I would appreciate your pointers to it.  My search returned a somewhat cursory issue (which I reopened, since it appears to me to not be fully resolved).

**Comment by dwsinger** [comment]
Roughly, this was addressing the problem that the PP was written at a time when it could be presumed that a spec was written in the lifetime of a single charter; it documents the life of a spec., where it came from, and what exclusion opportunities happened on it, and who therefore has an opportunity (e.g. on group join).

**Comment by frivoal** [comment]
As far as I can tell (and I did spend a whole bunch of time thinking about it in detail), the addition of "Adopted Draft" doesn't actually do anything yet. The reason to have them is Patent Policy related to deal with Drafts live through multiple WGs, but the Patent Policy has not yet been revised to take advantage of this, so as of now, I don't believe this tracking actually achieves anything beyond being informatively useful.

That said, I do feel reasonably confident that if we ever do update the Patent Policy to address this problem, we're quite likely to use the concept of Adopted Draft, and may be very happy that we did document them properly.

**Comment by dwsinger** [comment]
I think PSIG wanted this explicit tracking and it was a hard discussion that got us here.

**Comment by frivoal** [comment]
I think the tracking is healthy, and should be taken up by a revision of the Patent Policy. I don't think the Patent Policy as it exists today does anything with it.

**Comment by jeffjaffe** [comment]
I agree with @dwsinger 's recollection that this was a specific ask provided by PSIG.  I suggest that if anyone wants to change this, the proper place for that discussion is PSIG, and we should follow their guidance.

**Comment by samuelweiler** [comment]
As someone who was trying to write a charter (for a recharter), I don't fully understand what the words mean, nor where to find that data (again, for an existing charter, where that wasn't tracked before).  So if there's any good way to clarify this instruction here, that would be great.  

That said, I'll also accept the redirect to PSIG and ask them re: the necessity.

**Comment by fantasai** [comment]
@samuelweiler The data should be available on https://www.w3.org/TR/ I'm not sure how to search by Working Group, but I believe there's an API available.
