### ISSUE TITLE
Abandoning a Note

### ISSUE THREAD

**Issue by plehegar** [w3c/w3process#501]
In the current Process, anything that gets abandoned from the REC-track becomes a Note. The Note itself may get marked as 'retired' in our systems:
[[
Indicate if the publication is the result of stopping work on a specification (aka "retired").
]]
https://www.w3.org/Guide/transitions?profile=WG-NOTE

The draft process says:
[[
Discontinued Draft
   A technical report representing the state of a Recommendation-track document at the point at which work on it was discontinued. See § 6.2.12.1 Abandoning an Unfinished Technical Report.
]]
https://www.w3.org/Consortium/Process/Drafts/#discontinuedREC

The [new Note track](https://www.w3.org/Consortium/Process/Drafts/#note-track)  doesn't mention anything about abandoning a Note but I would assume we would simply allow Groups to indicate if the Note is the result of stopping work as we do today. Unless we think the Process needs to be explicit about that.

From the public perspective, I guess we would still display all of those cases under
  https://www.w3.org/TR/?status=ret

**Comment by dwsinger** [comment]
perhaps we should say in the Note Track that a Note may be marked as Retired upon a consensus request of the owning WG?

**Comment by frivoal** [comment]
Not a very strong opinion from me here, but I suspect no Process complexity is needed to support that use case: A group can change a publish a note by mere consensus, so a group can change and publish a note to say that it is retired by mere consensus. Update the status section, delete all of its content, at bleak warnings... whatever. Moreover, the Team has shown that it was willing to style that sort of notes distinctively already, despite the fact that they were never a separate category in the process.

If we wanted, we could formally allow notes to transition to (and back from?) a official discontinued status, but for this category of document, it's not clear to me that this would achieve much other than adding a paragraph or two to the Process.

So, if I understand PLH correctly, I agree: existing practice can continue, no need for additional rules.

**Comment by dwsinger** [comment]
I think I may have confused two things here, that are perhaps not always correlated:
1. A Note that documents 'abandoned' or 'inactive' Rec-track work, but that may nonetheless be of continuing relevance as a Note
2. A Note that is itself no longer relevant, and has been Retired

We should probably have a status of Retired Note in [6.3](https://www.w3.org/2020/Process-20200915/#Note)

**Comment by frivoal** [comment]
1. we have now have that, not quite as a note, but in the form of a [Discontinued Draft](https://www.w3.org/Consortium/Process/Drafts/#discontinuedREC). And if you didn't mean to discontinue the document itself, merely the rec-trackiness of it, just switch tracks, and as a note, it's not discontinued
2. We could have a status for that. I suspect we don't need one, as you can get largely the same effect by republishing in place and stating in the status section that the document is retired (and possibly, but not necessarily, collapsing the body of the document to "this is retired, but you may look at historical versions if you care about seeing what the content used to be"). But if you really think it's needed, I have no principled opposition to it. It probably takes about 1 short paragraph of process text to define that.

**Comment by dwsinger** [comment]
Ah right. We _no longer_ switch discontinued work to Notes. Good.

I agree, we could simply Note that the sub-type of a WG note can be changed to indicate it's no longer 'active', by the WG. 

But retiring a W3C Statement should probably take the same effort as Retiring a recommendation, no? Likewise, revival?

**Comment by nigelmegitt** [comment]
I don't think it makes sense to retire a W3C Statement. As I imagine it, a W3C Statement represents some declaration at a specific single point in time, and the fact that such a declaration was made can't be revised after the event.

Possibly it would make sense to allow metadata on a Statement so that people reviewing it later can see a pointer "A related W3C Statement was published on [some later date]".

**Comment by frivoal** [comment]
> But retiring a W3C Statement should probably take the same effort as Retiring a recommendation, no? Likewise, revival?

Updating a W3C Statement to make it say "I am no longer relevant, never mind" takes the same effort as it takes to publish it in the first place, or to retire a REC: making the edit, and pushing it through an AC review. I feel that's enough without a dedicated status. If you don't, we could introduce a such a distinction, but to be honest, I'd rather wait and see.

> As I imagine it, a W3C Statement represents some declaration at a specific single point in time

I think this may vary. Even when this is true, while we certainly don't want to be able to unpublish it and pretend it never happened, we may want to be able to updated one, either to refine or update some position of ours, or to retract it.

> Possibly it would make sense to allow metadata on a Statement so that people reviewing it later can see a pointer "A related W3C Statement was published on [some later date]".

This is should be be achievable through this sentence in section [6.3.3](https://www.w3.org/Consortium/Process/Drafts/#revising-memo)

> Given a recorded group decision to do so, groups can request publication of a W3C Statement with editorial changes

**Comment by 420anguiano** [comment]
I do not want to work with groups i want my work private

**Comment by dwsinger** [comment]
Surely all we need is a short note in 6.3.3 that a revision can be a declaration that a statement is no longer relevant or active, and the document is being maintained for historical reasons?

**Comment by frivoal** [comment]
I don't know if we need that statement, as it is an ok thing to do even if we don't state it explicitly, but if you think it's helpful, I don't have an objection.

**Comment by dwsinger** [comment]
Sorry, yes, I should have said "surely at most we need" because it's stating something that's already true. I suppose we can/should state it if it's a common question…

**Comment by dwsinger** [comment]
closing no action
