### ISSUE TITLE
Naming discussion: W3C Statements

### ISSUE THREAD

**Issue by frivoal** [w3c/w3process#508]
When we agreed to merge PR https://github.com/w3c/w3process/pull/489 which created W3C Statements, we did not have a firm conclusion on what they should be called, and when with W3C Statements as a provisional term, expecting to discuss some more whether that was the right word do use. Is it?

Previously mentioned alternatives (from https://github.com/w3c/w3process/issues/461):
* W3C Memorandum
* W3C Position
* W3C Communiqué
* W3C Report
* W3C Guidance
* W3C Guidelines

Their pros and cons have been subject to discussion in #461 already.

Any body has a better idea?

Personally, I'm fine with things as they are, and I am not particularly looking for change, but we said we'd discuss, so here's an issue for doing so.

**Comment by nigelmegitt** [comment]
For me (may not an organisational view), I think W3C Statement is better than any of the alternatives listed above.

**Comment by frivoal** [comment]
I think the name we landed on "W3C Statements" is fine, and I'd like to close with no change. Either way, if we want to change, the time is now, before we roll out the new process, so agenda+

**Comment by dwsinger** [comment]
close with no change
