### ISSUE TITLE
Switching Tracks

### ISSUE THREAD

**Issue by frivoal** [w3c/w3process#509]
We now have 3 tracks: the Rec Track, the Note Track, and the Registry Track. One thing we said we wanted to look into is the ability for a document to switch tracks.

We could disallow track-switching except through copy-and-paste and starting a new document with the same content.

However, I suspect that's probably too stringent, and I think there are valid cases for wanting to switch tracks.

**Comment by frivoal** [comment]
I'd suggest adding a paragraph or so saying that you can switch tracks, with a few restrictions. Maybe something like:

> Given a [=Group decision=] to do so,
> [=Working Groups=] can republish a [=technical report=]
> on a different track than the one it is on,
> under the following restrictions:
> * A [=technical report=] that was previously on the [=Recommentation Track=]
>   and that has already switched tracks
>   cannot not switch back to the [=Recommentation Track=]
>   (unless it was a [=Recommendation Track=] [=technical report=]
>    discontinued into a [=Note=] under a pre-2021 version of the Process).
> * A [=technical report=] that is or was
>   a [=W3C Recommendation=], [=W3C Statement=], or [=Patent Review Draft=]
>   cannot switch tracks.
>
> [=Technical reports=] that switch tracks start
> at the initial [=maturity level=] of the new track.

**Comment by dwsinger** [comment]
The last sentence basically says "slide down the snake to the start square again" which is exactly what you'd do in the absence of anything, i.e. copy-paste and start again, no?

**Comment by frivoal** [comment]
Almost. The only (intended) nuance is that you get to keep your identity: same url, same shortname, etc.

**Comment by dwsinger** [comment]
s/Recommentation/Recommendation/

**Comment by TallTed** [comment]
> Almost. The only (intended) nuance is that you get to keep your identity: same url, same shortname, etc.

In that case, I would change the last paragraph to say so --

> [=Technical reports=] that switch tracks start at the 
> initial [=maturity level=] of the new track, while
> retaining any established identity (url, shortname, etc.).

**Comment by frivoal** [comment]
@TallTed This sounds like a useful clarification. A bit of an annoyance is that url or shortname are implied by the process rather than actually clearly defined anywhere, but I think that as a parenthetical, it works out OK, as the main sentence is clear on its own.

Happy to include that if others are in support as well.

**Comment by frivoal** [comment]
Based on comments above and discussions during the call, here's updated proposed wording:

> Given a [=Group decision=] to do so,
> [=Working Groups=] can republish a [=technical report=]
> on a different track than the one it is on,
> under the following restrictions:
> * A [=technical report=] that is or was
>   a [=W3C Recommendation=], [=W3C Statement=], or [=Patent Review Draft=]
>   cannot switch tracks.
> * A [=technical report=] should not switch away from the [=Recommendation Track=]
>   without due consideration of the Patent Policy implications
>   and approval of the W3C’s legal counsel
>   if the Working Group envisions a likelihood of returning to it later.
>
> [=Technical reports=] that switch tracks start at
> their new track’s initial [=maturity level=],
> while retaining any established identity (url, shortname, etc.).
