### ISSUE TITLE
Keep or remove Note about delegation from CEO/Director to Team

### ISSUE THREAD

**Issue by frivoal** [w3c/w3process#513]
This is currently marked as an issue inline in the draft. We need to decide if we want it in or out.

https://www.w3.org/Consortium/Process/Drafts/#team-decision

IIRC, this was introduced at the request of @swickr, but @wseltzer would rather not have a note.

Personally, I think the note is fine, but I don't particularly need it here either, so I'm not taking sides. But I do want a decision for or against the note, we cannot publish the process with open inline issues.

**Comment by jeffjaffe** [comment]
I am studiously neutral on this issue.

If we cannot mediate between @swickr and @wseltzer then I would drop it based on the imperative to keep the document shorter.

**Comment by dwsinger** [comment]
I am not a fan of this note and would be happy to see it go.

**Comment by chaals** [comment]
If the CEO needs to be reminded about this by the process, I think there are deeper problems to solve and this group isn't the one to solve them. If the CEO does follow this practice, I don't see why it needs to be advertised - that would be normal in any functional organisation. So I would prefer to see the note go.

**Comment by dwsinger** [comment]
We expect to remove this at the end of March 2021 absent strong objection to removal.

**Comment by TallTed** [comment]
> If the CEO needs to be reminded about this by the process, I think there are deeper problems to solve and this group isn't the one to solve them. If the CEO does follow this practice, I don't see why it needs to be advertised - that would be normal in any functional organisation. So I would prefer to see the note go.

Why is this read as a reminder to the CEO?  Rather, I would think this a reminder to the potential delegates, i.e., the Team members and *their* (potential) delegates -- who may indeed sometimes need such a reminder, i.e., that delegated responsibilities and associated authorities may be revoked by the delegator, commonly at any time and for any reason.

I don't know the circumstances that caused this Note to be requested (@swickr — can you shed any light, including a pointer to the actual requester, if it was not you?), but it seems worth researching *that* before deleting it.

**Comment by frivoal** [comment]
> Why is this read as a reminder to the CEO?

Because that's why it was introduced (source: I was part of drafting it): to avoid giving the impression to a potential future CEO that they were supposed to decide everything personally.

> We expect to remove this at the end of March 2021 absent strong objection to removal.

End of march has passed, no strong objection to remove was formulated. Removing.
