### ISSUE TITLE
Improve AB Chairing text

### ISSUE THREAD

**Issue by cwilso** [w3c/w3process#514]
The AB has been discussing Chairing for the AB.  It's been clear that the chairing text is a bit loosely defined.  The AB resolved last week that:
1) the AB should issue a standing invitation to the CEO to attend its meetings (it was noted the CEO isn't explicitly invited to participate if they are not the Chair, and they should be)
2) We should ensure the AB can (and generally should) have 2 co-chairs but MAY have just one
3) one AB co-chair can be from inside or outside the AB, the Team appoints the initial chair with the advice of the AB and that appointee chooses a cochair from within the AB
4) the appointment of AB chair should be ratified by the Advisory Board every year, after any potential new AB members are seated, by a 2/3rds majority of the AB.

**Comment by cwilso** [comment]
I would suggest this text:

"The Advisory Board consists of nine to eleven elected participants and one Chair.  The Team appoints the Chair of the Advisory Board, subject to ratification by a two-thirds majority of the Advisory Board members, at the beginning of each AB term.  The Chair should choose a co-chair who must be an elected member of the Advisory Board. The team also appoints a Team Contact, as described in § 5.1 Requirements for All Working and Interest Groups. The CEO and Team Contact have a standing invitation to all regular Advisory Board sessions."

**Comment by jeffjaffe** [comment]
The mechanism of having the Team appoint a Chair and be ratified (and potentially rejected) feels a bit anti-collaborative.  I would prefer an approach where the Team collaborates with the AB on the appointment of the Chair.

**Comment by dwsinger** [comment]
@jeffjaffe I think that's the precise intended effect of a ratification; the effect is that the team spends time to propose someone for whom ratification is a formality. It's much easier to write it this way than to struggle with softer wording and particularly the difficulty of the "or-else". "The team works with the AB to appoint a chair" — and if they don't, or don't enough?

**Comment by mnot** [comment]
Point of data: The Internet Architecture Board elects its own Chair, every year. It is very far from being anti-collaborative. 

I'd suggest that you change 'should be ratified... every year' to 'should be elected after a nomination period every year.'

Having the Team select a chair is a conflict of interest; if the AB's mission is to effectively act as a voice of the Membership to W3M, it needs to have the freedom to set its own agenda and make its own decisions.

What the Team can (and should) supply to the AB is administrative support to help it achieve its mission. With effective support, a single chair should be sufficient.

**Comment by cwilso** [comment]
@mnot I would disagree that it's a conflict of interest, given that the Team would not get to unilaterally appoint a Chair; the AB has to be be pretty bought in.  I've also been thinking of the dynamics of chairing quite a bit, and I think the potential for causing bad feelings by forcing an election in a small group might be... unfortunate.  I'd rather blame the Team.  :P

**Comment by frivoal** [comment]
I agree with the intent of the text, and I think the proposed wording comes quite cose, but it does have several issues:
 * It does not incorporate the resolution that both of the chairs are subject to ratification.
 * Since it says "11 elected participants and one chair", without further clarification, it appears to imply that the chair is supposed to be someone else than the elected participant. The resolution was that it could be someone else, but didn't have to.
 * The way it's phrased, it's not clear whether "at the beginning of each AB term" applies to the ratification only, or the the apointment, and also seems to imply that we cannot apoint/ratify new chairs mid-term even if the current chairs were to resign, which seems unfortunate.
 * The AB resolution explicitly included the idea that the appointment would be made with the advice of the AB, to address Jeff's concern in https://github.com/w3c/w3process/issues/514#issuecomment-805110183 and tilt the interpretation towards a collaborative appointment; it might be worth mentioning that as well (although as @dwsinger explains in https://github.com/w3c/w3process/issues/514#issuecomment-805114899 it's not strictly necessary).

Here's a possible rephrasing the tries to stay as close to what you proposed as possible, but with these issues fixed:

> The Advisory Board consists of nine to eleven elected participants and one Chair (who may be one of the elected participants). With the input of the AB, the Team appoints the Chair, who should choose a co-chair among the elected participants. The Chair(s) are subject to blind ratification by two-thirds of the AB upon appointment and at the start of each AB term. The Team also appoints a Team Contact, as described in § 5.1 Requirements for All Working and Interest Groups. The CEO and Team Contact have a standing invitation to all regular Advisory Board sessions.

**Comment by frivoal** [comment]
BTW, I have a preference for not introducing a hierarchy among the chairs by having one choose the other, so would prefer the following rephrasing:

> With the input of the AB, the Team appoints the Chair(s) of the Advisory Board, at most one of whom may be someone other than an elected participant.

But I'm willing to live with Chris's formulation. :)

**Comment by dwsinger** [comment]
@frivoal I actually have the opposite preference; that there are (rare) occasions when it needs to be clear where the buck stops, where the action of a singular person is needed, and most importantly, the ability to make a call and move ahead if two people disagree. So a slight formal hierarchy can occasionally be helpful, and when chairs are working well, is not harmful.

**Comment by fantasai** [comment]
The wording in https://github.com/w3c/w3process/issues/514#issuecomment-806002855 works for me. I might consider whether having a co-chair is a SHOULD vs MAY in the Process itself: current AB prefers co-chairs, and I think we all generally agree that's better, but I'm not sure we want the Process to be the one pushing for it. (That said, either way is acceptable.)

**Comment by dwsinger** [comment]
[#514 (comment)](https://github.com/w3c/w3process/issues/514#issuecomment-806002855) is good enough for sure. A minor logic problem is the 'and' in the first sentence, in that if the appointed chair **is** one of the elected participants, we end up double-counting. But I can't see how to re-phrase it to remove the logical inelegance without getting into contorted language that would be worse (…and the possible addition of a chair from outside the elected membership, except inasmuch as heretofore the chair has been…). summary: It's clear enough to be usable.

**Comment by cwilso** [comment]
We could amend the first sentence to be "The Advisory Board consists of nine to eleven elected participants and one Chair (who may or may not be an elected participant). "

**Comment by mnot** [comment]
> @mnot I would disagree that it's a conflict of interest, given that the Team would not get to unilaterally appoint a Chair; the AB has to be be pretty bought in. 

If the intent is that the AB is to be representative of the Membership, I think the best you could do is to say that having the Team choose its chair is merely paternalistic. It turns what should be self-governance into the Team controlling what option is available to the AB; the best candidate is likely not to be chosen in this process.

> I've also been thinking of the dynamics of chairing quite a bit, and I think the potential for causing bad feelings by forcing an election in a small group might be... unfortunate. I'd rather blame the Team. :P

If a group of professionals who share a common goal can't elect a chair for their business without "bad feelings," it seems like there's something seriously wrong going on here, culturally.

**Comment by chaals** [comment]
A proposal:

> The Advisory Board consists of nine to eleven elected participants. At the first meeting of a newly elected AB, the board elects a chair who may be one of the elected participants, and MAY elect a co-chair from among the elected participants. The Team appoints a Team Contact, as described in § 5.1 Requirements for All Working and Interest Groups. The CEO and Team Contact have a standing invitation to all regular Advisory Board sessions except where the topic of discussion is the CEO or Team Contact, respectively.

I would suggest that as a matter of course, the AB should schedule at least one such discussion every year with the intention of providing a review of issues and suggestions to the W3C. From time to time I would expect additional such meetings to which the CEO/Team Contact are explicitly invited, too.

**Comment by frivoal** [comment]
@cwilso I'd be weakly against changing "may" to "may or may not". The process announces that it uses words like may in their RFC2119 sense, we mark all instances of the word "may" as `<em class=rfc2119>may</em>`. "may not" is not an RFC2119 term. I'd rather skip it.

**Comment by dwsinger** [comment]
re: "invitation to all regular Advisory Board sessions except where the topic of discussion is the CEO or Team Contact, respectively" 

the entire point of using the word "regular" is so that we don't have to enumerate the reasons to go into closed sessions.

**Comment by nigelmegitt** [comment]
Re https://github.com/w3c/w3process/issues/514#issuecomment-806002855 I'd have a minor editorial preference to remove the parenthesis in the first sentence, because the information in the parenthesis is no less important than anything else in the sentence e.g. change:

> The Advisory Board consists of nine to eleven elected participants and one Chair (who may be one of the elected participants).

to:

> The Advisory Board consists of nine to eleven elected participants and one Chair, who may be one of the elected participants.

or even:

> The Advisory Board consists of nine to eleven elected participants and one Chair. The Chair may be one of the elected participants.

**Comment by mnot** [comment]
Chaals' proposal is closest to what I was thinking. The only modification I'd suggest is changing 'co-chair' to 'co-chair or vice chair', as that opens up another leadership model.

**Comment by cwilso** [comment]
I think requiring any chair of the AB to be an elected participant is a bad idea, and would be a noticeable and negative change from what we have today.  The CEO has been the chair for a number of years; the former Chair was appointed, not an elected member, and had been Chair for a number of years as well.  Chair continuity (if they have the confidence of the AB) is important.  

The W3C Team also has the ability (currently) to appoint anyone they want to as Chair (elected member or not). Pragmatically, although the Chair of the TAG must be a member of the TAG, the Director has been appointing the same two people into appointed positions in the TAG in order to appoint them as Chairs; effectively, this is the same as appointing a Chair.  The TAG does not elect their chair internally; nor are the TAG chairs elected to the TAG by the AC.

My objections to the whims of the STV elections at the W3C are well-documented, so I'll avoid replicating them here.  However, I think the Chair(s) need(s) to be able to work closely with the W3C Team, as the AB needs to advise the Team; I don't think just having a local election of that role every year from the available, informed and willing AB participants will result in good chairing, good communication and relationship with the Team, or continuity across terms.

(I do, of course, believe that the Chair(s) must have the confidence of the AB itself, which is why I proposed introducing a constraint that we don't have today - that the Chair(s) must be ratified by the AB yearly.)

**Comment by LJWatson** [comment]
> The only modification I'd suggest is changing 'co-chair' to 'co-chair or vice chair', as that opens
up another leadership model.

I caution against introducing this model. The co-chair model is well understood at W3C, but more importantly a vice-chair implies that one chair is senior to the other - and that undermines the need for the chairs to be able to act as bias counterbalance for each other.

**Comment by michaelchampion** [comment]
Some thoughts as a former AB member:
- The power of the "chairs" should be spelled out.  I don't recall if this is written down in authoritative W3C documents, but as I understand it, the role of chairs is to a) set the agenda for meetings; b) facilitate / mediate consensus on topics being discussed; c) determine the extent of consensus at the end of a discussion and record that in the published minutes.  
- Strongly agree the AB should choose the chairs, preferably by consensus to ensure that all elected members can "live with" the chairs.   If that is impossible, a 2/3 majority is the bare minimum.
- A team member *might* be an appropriate chair, a knowledgeable outside person *might* be an appropriate chair, the AB should have flexibility to choose whomever they can get consensus on.  But no chair who is not an elected member gets a "vote" in actual deliberations.  
- Irrespective of whether a team member is an agreed-upon chair, the CEO or a delegate should attend AB meetings and be empowered to present the team's perspective.  
- Be sure to select chairs who have demonstrated they can "take off their advocate hat and put on their chair hat".  That is, find chairs who enough independence to resist pressure from the team, employers, election supporters, etc. to favor one position in any discussion they're chairing.

**Comment by dwsinger** [comment]
I think that we are unlikely to change the formal process text this cycle, and that anyway changing from team-appointed to AB-elected chair is a "bridge too far" for now. I'd rather work towards that; the mode of establishing consensus over a team appointment will, I think, inform how we could do fully in-AB chairs. The advantage of having the team _own_ the responsibility is that it moves us out of flat "it's everyone on the AB's job to help find a chair" which makes it no-one's job.

But I agree with Mike; having a chair who sees their job as making the committee work well is the right mental model.

**Comment by michaelchampion** [comment]
To be clear, I'm neutral on whether the AB "elects" a chair, "ratifies" a team-nominated chair, or whatever. I do think it's important for the Process to reflect, as soon as possible, that the AB MUST have a role that ensures the chair(s) have the confidence of a supermajority of the AB.  The smallest change that  can implement that in 2021 is fine with me; in the longer term, the role of the AB relative to both the team and Board of Directors needs to be sorted out.

**Comment by dwsinger** [comment]
Yes, long term we need to keep iterating. The reasons I like what Chris proposed? (a) it's an improvement on the status quo (b) it's not formally at odds with the process text today, so we're not barred from doing it and thus don't need new text and (c) it's a step in the right direction and (d) I think it strikes a balance of achievability today, doesn't pull 'too far' ahead of our thinking and understanding.

**Comment by michaelchampion** [comment]
@dwsinger I understand. I need to get "the best is the enemy of the good" tattooed on my brain and stop arguing with people I basically agree with ...

**Comment by mnot** [comment]
> I caution against introducing this model. The co-chair model is well understood at W3C, but more importantly a vice-chair implies that one chair is senior to the other - and that undermines the need for the chairs to be able to act as bias counterbalance for each other.

We should probably sit down over a beverage at some point to discuss the tradeoffs there. This is a relatively small consideration overall; I agree absolutely with Michael that getting _some_ motion here soon is critical.

**Comment by fantasai** [comment]
It seems like we're all in general agreement that https://github.com/w3c/w3process/issues/514#issuecomment-806002855 is an acceptable improvement to the status quo. Can we get agreement to add this into the Process 2021 draft so we can move forward somewhat? :)

**Comment by mnot** [comment]
No - I strongly prefer @chaals's text to that, for reasons explained.

**Comment by cwilso** [comment]
Sigh.  I'd hoped to actually improve the state of affairs by moving the needle; however, I'm starting to despair of that happening at all.  I should be clear; I believe @chaals' proposal that the AB elect their own chair(s) every year is very underspecified (how are nominations made, how are elections run, how long is this going to take, etc.), and is likely to cause significant rifts within the AB, cause significantly less progress to be made, and also lead to chairs who are potentially unacceptable to the Team.  That might seem like a goal, but for a group who is intended to advise the Team, it seems like a mistake to pull the Team out of any role in selecting those chair(s). 

Today, the AB itself has NO input into who chairs the AB.  I'd hoped to change that.  Having been on the AB for a number of terms, and also losing a couple of elections, and being co-chair of a few WG and CGs, I'm well aware of both the pitfalls of chairing and the vagaries of elections.  I think it is important the chair(s) have the confidence of the AB members each year; I also think it's important they have the confidence of the team. 

I am not supportive of @chaals' proposal, as I believe it is actually a worse outcome for the functioning of the AB and the W3C.  If the options are that text or leaving the Process as it is, I prefer to do nothing and leave it as it is; I do not consider it an improvement (so would not resolve the issue that I filed. :) .  I also believe that leaving this unimproved would be a mistake.

**Comment by mnot** [comment]
If @fantasai's text is a step in the direction of the AB choosing its Chair, I can get behind that; what I want to avoid is the notion that 'oh, we've addressed that, no need for further action/discussion down the road.'

**Comment by chaals** [comment]
I agree that my proposal is lightly specified. This was deliberate, as I expect the AB to learn to make decisions fairly fast, and if a given AB can't figure out how to select a chair I suspect it will need to resolve that before it usefully takes on much more.

My own preference would be to remove the constraint that the co-chair must be an elected member, but I copied that from the previous suggestion because it seemed the current AB likes that model. (To be clear, I would strongly prefer that neither the chair nor co-chair were AB members, but that seems to be a minority opinion).

It isn't hard to write a proposal that includes more details of how the chair is chosen, and I am happy if someone does so.

I find it hard to imagine how a chair is "unacceptable" to the team, other than for significant or repeated violation of CEPC, in which case there is already a procedure for removing such a chair. And my preference is for the AB rather than the team to choose the chair.

**Comment by chaals** [comment]
> But I agree with Mike; having a chair who sees their job as making the committee work well is the right mental model.

I agree with this (but didn't agree with other stuff in the comment).

**Comment by LJWatson** [comment]
> It seems like we're all in general agreement that https://github.com/w3c/w3process/issues/514#issuecomment-806002855 is an acceptable improvement to the status quo. Can we get agreement to add this into the Process 2021 draft so we can move forward somewhat? :)

I strongly support this, with emphasis on @cwilso's https://github.com/w3c/w3process/issues/514#issuecomment-810656079 on making progress. I also recognise @mnot's https://github.com/w3c/w3process/issues/514#issuecomment-810695659 and agree that we should not regard this as "done", but as a first iteration.

**Comment by samuelweiler** [comment]
I support the idea of the AB electing their own chair(s), and I would expect them to be able to handle that without further Process guidance.

As for that chair(s) being other than an elected member, should we instead allow the AB to appoint (up to some limit, maybe 2?) additional members, at their own discretion?  So they could then appoint an other-than-elected person as a member _and_ select them as (co-)chair.  (Opening the question of whether to say something special about the CEO and/or Team Contact(s), perhaps permitting them to be (co-)chair without further appointment.)

**Comment by cwilso** [comment]
@mnot I don't ever consider any bit of Process "done", and this can certainly be refined (or possibly completely changed) in the future.

I believe we are coalescing around Florian's edited proposal:

The Advisory Board consists of nine to eleven elected participants and one Chair (who may be one of the elected participants). With the input of the AB, the Team appoints the Chair, who should choose a co-chair among the elected participants. The Chair(s) are subject to blind ratification by two-thirds of the AB upon appointment and at the start of each AB term. The Team also appoints a Team Contact, as described in § 5.1 Requirements for All Working and Interest Groups. The CEO and Team Contact have a standing invitation to all regular Advisory Board sessions.

@samuelweiler I do not think that the AB can handle that without further process guidance.  Is it a majority vote?  Highest count?  Is there a threshold of acceptable?  Are the details of those machinations clear to the AC?  All of these things are arguable, and with a number of AB terms under my belt, I can guarantee the AB would argue them.  (I might not want the discussion of how suitable I am as a chair made public, e.g.)

Similarly, I do not think it is trivial to add the ability for the AB to appoint additional members - this seems like a can of worms waiting to explode.  And a chair can always ask someone else to manage a meeting (e.g. as Jeff has been doing with the AB for a while), but that is not the same as being a co-chair.

**Comment by dwsinger** [comment]
I agree with @cwilso's comments on @samuelweiler's comments; I think that while these are all good things to keep in mind, they raise too many questions now. We want to improve; we don't expect this to be perfect, or the last word, but an informative step in a good direction. The text we seem to be coalescing around seems to have improvement, while managing a lack of ambiguity and a lack of a need for formal process changes, or even AC consensus.

**Comment by tantek** [comment]
👍🏼

(Originally published at: https://tantek.com/2021/090/t1/)

**Comment by mnot** [comment]
Looking good. Is 'blind ratification' defined precisely anywhere?

**Comment by dwsinger** [comment]
I wondered about that. I think it means secret ballot, so people can vote their conscience and not be influenced by who is watching or how others vote. why not say that?

**Comment by LJWatson** [comment]
> I wondered about that. I think it means secret ballot, so people can vote their conscience and not be influenced by who is watching or how others vote.
why not say that?

Good idea. It's much clearer when described that way. It also avoids any sensitivity around use of the word "blind" in this context. Not a thing I find troublesome myself, but I'm aware that other people feel differently.

**Comment by samuelweiler** [comment]
> @samuelweiler I do not think that the AB can handle that without further process guidance. Is it a majority vote? Highest count? Is there a threshold of acceptable? Are the details of those machinations clear to the AC? All of these things are arguable, and with a number of AB terms under my belt, I can guarantee the AB would argue them. (I might not want the discussion of how suitable I am as a chair made public, e.g.)

@cwilso Thank you.  That's disappointing to hear; I would have expected the AB to be better at self-governance.

> Similarly, I do not think it is trivial to add the ability for the AB to appoint additional members - this seems like a can of worms waiting to explode. And a chair can always ask someone else to manage a meeting (e.g. as Jeff has been doing with the AB for a while), but that is not the same as being a co-chair.

I am also concerned about the can of worms, though I thought the idea was worth floating.

I just read the [relevant bits of the IAB's charter,](https://www.rfc-editor.org/rfc/rfc2850#section-3.1) and I see some interesting ideas in them.  I won't quote them here, but I encourage taking a look.  The relevant bits are short.
