### ISSUE TITLE
[minor wording] accessibility = people with disabilities

### ISSUE THREAD

**Issue by shawna-slh** [w3c/w3process#525]
In [3.7 Tooling](https://www.w3.org/Consortium/Process/Drafts/#tooling)
>  All reports, publications, or other deliverables produced by the group for public consumption should follow best practices for accessibility with regards to internationalization and for persons with disabilities. Network...

We prefer for the term "accessibility" to be used specifically related to people with disabilities.

Idea for editing above (which also simplifies the wording :):
> All reports, publications, or other deliverables produced by the group for public consumption should follow best practices for internationalization and for accessibility to people with disabilities. Network...

**Comment by frivoal** [comment]
This is both worth doing and sufficiently editorial that I don't think any group discussion is needed. Used editorial discretion and just made the fix.
