### ISSUE TITLE
Updating a WG Note when a Group is closed

### ISSUE THREAD

**Issue by plehegar** [w3c/w3process#532]
We received a request from the Dataset Exchange Working Group to update an example in a Working Group previously published by the Data on the Web Best Practices:
https://www.w3.org/TR/2016/NOTE-vocab-dqv-20161215/#ExpressConformanceWithPolicy

The reuse of ODRL shown in the example of the DWBP-DQV Group Note is not up to date with the latest ODRL spec, as ODRL spec was still underway when the original Group published DQV (See also https://github.com/w3c/dxwg/issues/5)

Process 2020 doesn't seem to authorize the Team to republish the Note (unlike Recommendations), assuming the change would get reviewed through pull requests/mailing list announcement. Moving the Note to the DXWG for doing such update seems an overkill since DXWG isn't interested in full ownership of the Note.

1. Any suggestion on how to update the Note using Process 2020?
2. Does Process 2021 provide a way to address this use case?

**Comment by frivoal** [comment]
The team has always felt empowered to change the styling of documents, or to add flashy warnings in the about the existence of a newer version of a document, or that sort of things. I think it would be perfectly fine for the team, under P2020 or P2021, to add that kind of warning saying "No Working Group is currently chartered to maintain this Note; we advise caution when reading it as it may contain unaddressed or unreported issues".

But beyond that, I agree that the Team isn't currently allowed by the Process 2020 to change the content of Notes.

For P2021, it's probably not allowed either, but it is a little bit ambiguous: The definition of the Note track doesn't include the Team in the list of people who can publish a Note, but the definition of [Team Correction](https://www.w3.org/Consortium/Process/Drafts/#team-correction) is written in a generic way that can apply to any kind of technical report. This could be read as an allowance for doing it in Notes as well, but that's not 100% clear.

I think we should lift this ambiguity, and be explicit in the Note track that for Notes that do not have a chartered working group, the Team can do [class 1](https://www.w3.org/Consortium/Process/Drafts/#correction-classes) changes and [Team Correction](https://www.w3.org/Consortium/Process/Drafts/#team-correction), but not other types changes.

As for why we should disallow the rest: any change to a Note can be deemed to be editorial, so if we let the Team make editorial changes in the general sense, they could potentially change anything and everything, in a document that still claims to be the consensus of some (past) working group. That doesn't seem appropriate.

**Comment by dwsinger** [comment]
I think we should lift the ambiguity by making it clear that editorial and Team Corrections can be done to any Publication.

**Comment by frivoal** [comment]
@dwsinger As I just said, I think Team corrections are ok (and so are class 1 changes), but I don't think editorial corrections in the broad sense are OK for notes:

> any change to a Note can be deemed to be editorial, so if we let the Team make editorial changes in the general sense, they could potentially change anything and everything, in a document that still claims to be the consensus of some (past) working group. That doesn't seem appropriate.

If you disagree, as your last comment seems to suggest, could you say why?

**Comment by swickr** [comment]
@frivoal wrote
>  I think it would be perfectly fine for the team, under P2020 or P2021, to add that kind of warning saying "No Working Group is currently chartered to maintain this Note; we advise caution when reading it as it may contain unaddressed or unreported issues".

This is analogous to Retiring a Recommendation Track document.   The [draft P2021 Note Track](https://www.w3.org/Consortium/Process/Drafts/#note-track) does not appear to provide guidance on taking such action.  Though that question is orthogonal to this issue (which is about incorporating an erratum to a Note), it also seems worth addressing.

**Comment by frivoal** [comment]
The lack of ability for the Team to go fix things in a Note is indeed unfortunate, but it's not new. P2020 had the same issue. I've checked as far back and P2017, and it was already that way. So I think we should fix it, but it's not as urgent as if we were introducing a new problem.

> The definition of "editorial" is not that it's non-normative, but that it doesn't make any difference to the technical content.

The common-sense definition might be that, but the [process definition](https://www.w3.org/Consortium/Process/Drafts/#editorial-change) is:
> * No changes to text content
> * Corrections that do not affect conformance

Nothing in a Note affects conformance, so allowing editorial changes (without being more specific) allows rewriting the entire Note. We don't want that. We probably need a better definition of “editorial change” that makes sense to apply to documents other than Rec-track documents, but that's a separate issue (at least partly covered in #28)...

Until we get that better definition, I suggest just allowing class 1 changes and Team Corrections, by adding the following sentence to the Note Track section:

> If a Note produced by a [=Chartered Group=] is no longer in scope for any group,
the Team may republish the Note with class 1 changes incorporated,
as well as with [=errata=] and [=Team corrections=] annotated.

Once we have a sensible definition of editorial, we can replace it with

> If a Note produced by a [=Chartered Group=] is no longer in scope for any group,
the Team may republish the Note with [=editorial changes=] incorporated,
including annotations of [=errata=] and [=Team corrections=].

**Comment by frivoal** [comment]
Open https://github.com/w3c/w3process/issues/536 to work on the fact that we don't have a good definition of Editorial outside of the REC track that we could use here.

With that open, I think we can close this one.
