### ISSUE TITLE
AB Composition tweaks

### ISSUE THREAD

**Issue by plehegar** [w3c/w3process#540]
The Chair of the AB may be an elected participant. We also say "With the exception of the Chair, the terms of all Advisory Board participants are for two years." I believe that sentence should say instead "The terms of all Advisory Board elected participants are for two years." (ie, if the Chair is an elected participant, the term of 2 years still applies).

By the way, we have a paragraph that says "The remaining nine to eleven Advisory Board participants ". Not sure what the word "remaining" refers to. I suggest removing it.

**Comment by frivoal** [comment]
Thanks. As this is editorial / obvious bugfix, I've just fixed it, I don't think it needs any discussion.
