### ISSUE TITLE
Duplicate sentences in Chapter 6

### ISSUE THREAD

**Issue by xfq** [w3c/w3process#55]
> Please note that *publishing* as used in this document refers to producing a version which is listed as a W3C Technical Report on its Technical Reports page https://www.w3.org/TR.

This sentence is in both [6.1](https://w3c.github.io/w3process/#rec-advance) and [6.2](https://w3c.github.io/w3process/#requirements-and-definitions). Is it intentional?

**Comment by chaals** [comment]
Whoops! No it isn't - thank you. Fixed.
