### ISSUE TITLE
Ensure all specs & standards have published user research? [from TAG process repo]

### ISSUE THREAD

**Issue by torgo** [w3c/w3process#551]
Hi folks -  @edent opened up [an issue in our TAG process repo](https://github.com/w3ctag/process/issues/26) on this topic (text below). 

> I am concerned about the number of specifications which rely on private user research. Would it be possible to add something to the process that all research conducted on a proposal be published in the open?
> 
> Without wishing to put the spotlight on any specific proposals, it appears that several have either done no user research (in which case, I think TAG should not approve) or have research which is private (in which case, it should be published before TAG can review).
> 
> Without this step, W3C risks endorsing standards which are not suitable for user needs. Or, disproportionately favours the
 authors.
> 
> I appreciate that there may be a privacy element to this. I'm not proposing that video interviews with users be made public. But rather the typical summary that would accompany any project. For example: number of people interviewed, age ranges, responses, qualitative and quantitative feedback, etc.
>
>This would be a simple and useful way to make sure that any new proposal meets users' needs, and that all implementers of a proposal are able to understand the research behind it.
> 
> Thanks

As discussed in our [plenary call today](https://github.com/w3ctag/meetings/blob/gh-pages/2021/telcons/06-28-agenda.md), we are planning to make some changes to the [design review](https://github.com/w3ctag/design-reviews/issues) issue template and and our "[explainer explainer](https://w3ctag.github.io/explainers)" to address this issue as far as TAG process goes (by encouraging specification developers to publish user research or the results of user research it that research has informed the design of a proposed new web technology). However, we also think this is a wider W3C topic that may need to be incorporated into the general w3c process. Hence I am opening up this issue here as well.

**Comment by fantasai** [comment]
Strongly agree with @leaverou's comment in https://github.com/w3ctag/process/issues/26#issuecomment-870648739 that it's not realistic to require user studies, but that it would be good to encourage publication of any such information--or at least archive it at W3C (even if that's just sending to an archived mailing list) to the extent that it can be shared with the rest of the community.

That said, I'm not sure this requires Process changes, maybe just documentation in /Guide that such user studies should be made available? Although it does point out that attachments to WG discussions (like slides and other documents) need to be archived along with the discussions, and maybe we need to clarify that more in the proposed tooling policy in Process 2021: https://www.w3.org/Consortium/Process/Drafts/#tooling

**Comment by dwsinger** [comment]
If there is a process text issue here, could someone clarify?

**Comment by dwsinger** [comment]
closing, lacking specific proposal
