### ISSUE TITLE
Archiving discussion attachments

### ISSUE THREAD

**Issue by fantasai** [w3c/w3process#552]
The Process 2021 draft requires:

> Official meeting minutes and other records of decisions made must be archived by W3C for future reference; and other persistent text-based discussions sponsored by the group, pertaining to their work and intended to be referenceable by all group members should be. This includes discussions conducted over email lists or in issue-tracking services or any equivalent fora.

But in https://github.com/w3c/w3process/issues/551 it came up that we aren't very clear about whether documents referenced in those discussions, like slide decks and proposals, ought to be archived as well. To the extent that a discussion doesn't make sense without it, they probably should (but not MUST), I think. Do we want to make a clarification about that?

**Comment by dwsinger** [comment]
This could easily be a long discussion, and I am hesitant to put it in the process. Some decisions stand alone:

* Decided to advance the 27th June Draft of Whatits and Thingummies to FPWD

Others need the supporting material:
* Decided to adopt Göthe GMBH proposal for the solution to the 2nd problem

needs a copy of the proposal and identification of what the 2nd problem is.

How we say this in process text I am not sure.

**Comment by fantasai** [comment]
@dwsinger Something like “Materials referenced from discussions and necessary to understand them should be available at a stable URL at the same level of confidentiality as the discussion minutes.” ?

**Comment by dwsinger** [comment]
maybe we just need to add to the end of the paragraph that the records should be sufficiently complete to be comprehensible?

**Comment by samuelweiler** [comment]
I think this adds unnecessary verbiage and we should just skip it.

**Comment by dwsinger** [comment]
it's important that official records are complete enough to be an effective record. decided to adopt X where X cannot be found any more is not an effective record

**Comment by dwsinger** [comment]
We ought to be able to make a requirement that the records are complete enough to be comprehensible. Small edit?
