### ISSUE TITLE
ToC/document mismatches

### ISSUE THREAD

**Issue by xfq** [w3c/w3process#56]
Section in the expanded table of contents, but not in the document:

* 6.2.2.1 Substantive Change

Sections in the document, but not in the expanded table of contents:

* 2.1.2.1 Membership Consortia
* 2.1.2.2 Related Members
* 2.1.3.1 Advisory Committee Mailing Lists
* 2.1.3.2 Advisory Committee Meetings
* 5.2.1.1 Member Representative in a Working Group
* 5.2.1.2 Member Representative in an Interest Group
* 5.2.1.3 Invited Expert in a Working Group
* 5.2.1.4 Invited Expert in an Interest Group
* 5.2.1.5 Team Representative in a Working Group
* 5.2.1.6 Team Representative in an Interest Group

Title mismatches between ToC and document:

* 6.2.5 "Classes of Changes to a Recommendation" vs. "Classes of Changes"
* 10.4 "Rejection of a Submission Request" vs. "Rejection of a Submission Request, and Submission Appeals"

Reference mismatch:

In [6.7.1 Errata Management](https://www.w3.org/2017/Process-20170301/#errata), there's a reference to "7.2.5 Classes of Changes", but it should be "6.2.5 Classes of Changes".

Version checked: Process Document 1 March 2017

(I haven't checked the latest Editor's version, but I think it would suffer from at least some of the problems above.)

Automatically numbered and generated ToC/references would be great.

**Comment by xfq** [comment]
@chaals Thank you for fixing the Table of Contents!

BTW, would you please also fix the "7.2.5 Classes of Changes" reference? (See my original post for details.)

**Comment by xfq** [comment]
I'll submit a PR.

**Comment by chaals** [comment]
Oh, sorry I missed that - and thank you for the PR :)
