### ISSUE TITLE
Definition of obsolete

### ISSUE THREAD

**Issue by LJWatson** [w3c/w3process#57]
The first sentence of the definition of an obsolete specification is difficult to read:
>"An Obsolete Recommendation is a specification that W3C does not believe has sufficient market relevance to continue recommending that the community implement it, but does not consider that there are fundamental problems that require the Recommendation be Rescinded.">

Could it be simplified? Perhaps:
>"An obsolete Recommendation is a specification that the W3C believes no longer has enough market relevance to continue recommending it for implementation, but does not have fundamental problems that would require it to be rescinded.">

**Comment by jeffjaffe** [comment]
Also combine with Issue #36.
