### ISSUE TITLE
All previews are 404

### ISSUE THREAD

**Issue by darobin** [w3c/w3process#577]
This [preview](https://www.w3.org/Consortium/Process/Drafts/) and all the others seem to be dead.

**Comment by frivoal** [comment]
Looks fine from here… Either this was some temporary hick-up, or there's something different between your set-up and mine.

**Comment by mnot** [comment]
I saw it too, but agree that it's now working.

**Comment by jeffjaffe** [comment]
CSAIL has been having major networking issues today, so that could be the cause.
