### ISSUE TITLE
Director responsibilities in the technical development process

### ISSUE THREAD

**Issue by jeffjaffe** [w3c/w3process#578]
The team performs certain duties on behalf of the Director in the middle of the technical development process.  Some of those involve checking that the work from the Working Group was done properly - e.g. normative references and horizontal reviews.  We need to document how that works in director-free.

**Comment by michaelchampion** [comment]
What Process language describes Director duties covering "checking that the work from the Working Group was done properly - e.g. normative references and horizontal reviews"?  I couldn't find any from a quick scan.

**Comment by jeffjaffe** [comment]
It's fine to call it process project management.  Question is to find the right "hook" for that in director-free.

Today, the hook is that the Director will not approve transitions without that process project management.  In director-free we need to document how transitions get approved and where the process project management comes in.

**Comment by frivoal** [comment]
This was addressed in https://github.com/w3c/w3process/pull/586
