### ISSUE TITLE
Sufficient time for Council Members to give decisions their full attention

### ISSUE THREAD

**Issue by jeffjaffe** [w3c/w3process#581]
With potentially three Councils simultaneously being explored this fall, a concern has been raised whether full attention can be given to multiple councils.  (Noting that the concern was raised in a non-public AB discussion https://lists.w3.org/Archives/Group/ab/2021OctDec/0099.html)

**Comment by frivoal** [comment]
It seems that the Council Process is mostly struggling with the processes leading up to the convening of the Council, not with Council deliberations themselves. So I think this can be closed.

**Comment by frivoal** [comment]
Agreed to close in the 2022/10/28 Process-CG meeting.
