### ISSUE TITLE
Unintentional definitite article "the group"

### ISSUE THREAD

**Issue by SteveALee** [w3c/w3process#583]
In [this sentence](https://github.com/w3c/w3process/blob/main/index.bs#L172)

"Team representatives both contribute to the technical work and help ensure the group’s proper integration with the rest of W3C."

"the group" in question has not been defined. Neither has the concept yet been introduced. Groups appear in the next paragraph.

**Comment by frivoal** [comment]
Good catch, thanks. Now fixed in https://github.com/w3c/w3process/commit/636277cbbdb057bfffcb4b3dee299e9dc457c50b
