### ISSUE TITLE
Moving from Draft Registry to Candidate Registry

### ISSUE THREAD

**Issue by plehegar** [w3c/w3process#584]
[Process 2021](https://www.w3.org/2021/Process-20211102/#reg-pub) says:
* Rules for advancement on the Registry Track are identical to that of the Recommendation Track (with some exceptions)
* The equivalent of Working Draft is called Draft Registry.
* The equivalent of Candidate Recommendation is called Candidate Registry.
* an Advisory Committee Review is started upon publication of **each** Candidate Registry Snapshot.

On the Recommendation track, the next forward step for a Working Draft is a Candidate Recommendation Snapshot.

This would mean one can only do Draft Registry (DRY) -> Candidate Registry Snapshot (CRY).

But this triggers an AC Review right away. Which would make the purpose of Candidate Registry Draft (CRYD) irrelevant, since the expectation would be to publish a Registry after the AC Review.

So, I believe our intent should either be:

* option 1: keep DR -> CRY, to provide Director's oversight over the transition, but don't *require* AC Review on that first snapshot
* option 2: allow DR -> CRYD, but do require Director's oversight for the first publication of the CRYD.

cc @swickr

**Comment by fantasai** [comment]
This was deliberate. We combined AC review and the CR phase for registries because the expectation was that there would not be any significant changes for most registries after completing the DR phase, so having the extra separate phase seemed to be more busywork than useful. Are there are groups that believe they need an implementation phase prior to AC review?

**Comment by fantasai** [comment]
See https://www.w3.org/2002/09/wbs/34786/registries-chair-survey/results

**Comment by fantasai** [comment]
Maybe we should have called it "Proposed Registry" instead of "Candidate Registry". Not sure I recall why we did it this way around...

**Comment by frivoal** [comment]
So in practice, to hit CRY, you need to match a bunch of criteria that the Team will verify, then you get a CRY, which starts and AC review. If you are sucessful with your AC review, one more decision to advance will take you to the fully mature registry, but you can also keep it there for a little while while you gather more feedback / experience the operating the registry. If everything's fine and no new issue is discovered, you can go to the end state. But if you want, you can spin another cycle, going through CRYDs and more CRYSs along the way.

**Comment by frivoal** [comment]
> Maybe we should have called it "Proposed Registry" instead of "Candidate Registry". Not sure I recall why we did it this way around...

I don't think so, that would imply that you cannot stay at that maturity and put out a series of PR-Drafts and PR-Snapshots (cause those aren't a thing).

**Comment by plehegar** [comment]
So, my interpretation would be:

1. don't move to CRY unless you're ready to move to RY
2. if you need to tweak the registry rules following the AC review, you're welcome to do some CRYD before doing another CRY
3. if the AC review went well and you're still happy with your rules, just move to RY

Makes sense?

**Comment by frivoal** [comment]
Yes, I think as a general guideline, that's the way to go. In my understanding, step 3 is not automatic, you have to make a decision to take it, so there could be cases where for some reason you decide to wait, but typically, you should not, and what you said makes sense.
