### ISSUE TITLE
Cite Horizontal Review in Sec. 6.4.3

### ISSUE THREAD

**Issue by JaninaSajka** [w3c/w3process#587]
It is my understanding that elevating Notes to W3C Statements requires horizontal review, however this is not explicitly enumerated as a step under Sec. 6.4.3. While it may be implicit from requirements enumerated elsewhere in the Process publication, should it not be explicitly called out in Sec. 6.4.3? My thought is that horizontal review for W3C Statements is critical and should be explicitly stated.

**Comment by frivoal** [comment]
It is a requirement for elevating notes to statements that they have received wide review (first bullet point in [6.4.3](https://www.w3.org/2021/Process-20211102/#memo)), and wide review is documented (in [6.2.2.1](https://www.w3.org/2021/Process-20211102/#wide-review)) to include Horizontal Review.

The phrasing “must show that the document has received wide review" is identical to the way it is phrased for the equivalent transitions on the recommendation track, so from an enforcement point of view, the requirement for Horizontal review is just as strong for Notes as it is for CRs or PRs.

That said, if you have editorial suggestions to make that clearer, I think we certainly ought to consider them.

**Comment by plehegar** [comment]
@JaninaSajka , I concur with @frivoal . It's already there, indirectly. Making it more explicit would add wording to the Process. Do you concur?
