### ISSUE TITLE
Superfluous information requirement in 4.5 “Charter extension”

### ISSUE THREAD

**Issue by koalie** [w3c/w3process#598]
Hi!

I doesn't make sense to me that the [section 4.5 “Charter extension”](https://www.w3.org/2021/Process-20211102/#charter-extension) of the process document requires to include in the extension announcement who the chairs and staff contacts are and how the group can be joined. This seems superfluous.

**Comment by dwsinger** [comment]
This pre-dates most of us; it's not in [1999](https://www.w3.org/Consortium/Process/Process-19991111/) but is in [2001](https://www.w3.org/Consortium/Process-20010208/groups.html#GroupsWG), as part of the general rules for creating, modifying, etc.

anyone have any insight?

**Comment by plehegar** [comment]
I believe this was due to a rewrite in early 2001. The September 2000 version rewrote 4.2. It remained untouched until January 2001. Then the February 2001 version consolidated 4.1.1 into 4.2:
[[
4.2.1: Working Group and Interest Group Creation and Modification. Merged old section 4.1.1 here. Now talks more clearly about creation, modification, and extension.
]]
https://www.w3.org/Consortium/Process/Plan/process-changes.html#changes-20010119

So, while we intended for the announcement of a Group creation to be that detailed, I don't think we intended for charter modifications to be also detailed.

**Comment by chaals** [comment]
Strictly speaking I agree it is superfluous. But as an AC rep, every so often an extension notice starts me n the quest to see if I can find someone to participate. Especially if a group is sorting out rechartering, or finalising a piece of work. Or, it makes me write to the chairs or contact to talk about it.

Having the information right there is handy. Cutting it back to a general pointer to the WG home page where the information is already clearly presented would be OK though.

**Comment by dwsinger** [comment]
@chaals but do we have a consistent concept of a "WG home page where the information is already clearly presented"?

**Comment by koalie** [comment]
> @chaals but do we have a consistent concept of a "WG home page where the information is already clearly presented"?

We totally do! That was one of the goals of the [group pages](https://www.w3.org/groups/) to present the same information type in the same places.
The Charter template has been update to requires the link to the group to be that [but it may take several months for this to be fully used everywhere]. The few groups that have their own distinct homepage (with different looks and information available in a non-predictable way) can make that link available from the group page.

**Comment by dwsinger** [comment]
@koalie hm, then I must be doing something wrong. I log on to w3.org, go to [Participate](https://www.w3.org/participate/), [Groups](https://www.w3.org/groups/), [Working Groups](https://www.w3.org/groups/wg/), pick a random WG – Audio WG in this case, twist down and click on [Summary](https://www.w3.org/groups/wg/audio), and then [Homepage](https://www.w3.org/2011/audio/). You might not like that last page.

this is far from unusual. what am I missing?

**Comment by koalie** [comment]
> @koalie hm, then I must be doing something wrong. I log on to w3.org, go to [Participate](https://www.w3.org/participate/), [Groups](https://www.w3.org/groups/), [Working Groups](https://www.w3.org/groups/wg/), pick a random WG – Audio WG in this case, twist down and click on [Summary](https://www.w3.org/groups/wg/audio), and then [Homepage](https://www.w3.org/2011/audio/). You might not like that last page.
> 
> this is far from unusual. what am I missing?

The "summary" pane has all the info @chaals brought up as an example. That's what I had in mind. (I plan to tackle later whether and what kind of specific homepage groups should put together as the group pages are pretty good now and probably specific homepages should be moot.)

**Comment by chaals** [comment]
The summary page is indeed the thing I want. I think the homepage should be pointing to the summary and not what's there right now - I agree that needs to be fixed.

**Comment by Jotr38487** [comment]
I would think maybe to promote the charter. Give everyone some competitive spirit maybe. Equal opportunity employment at its best!

**Comment by plehegar** [comment]
So, the sentence in [4.5. Charter Extension](https://www.w3.org/2021/Process-20211102/#charter-extension) :
[[
The announcement must indicate the new duration. The announcement must also include rationale for the extension, a reference to the [charter](https://www.w3.org/2021/Process-20211102/#WGCharter), the name(s) of the group’s [Chair](https://www.w3.org/2021/Process-20211102/#GeneralChairs)(s), the name of the [Team Contact](https://www.w3.org/2021/Process-20211102/#TeamContact), and instructions for joining the group.
]]

could read instead:
[[
The announcement must indicate the new duration. The announcement must also include rationale for the extension, a reference to the [charter](https://www.w3.org/2021/Process-20211102/#WGCharter), and the Group homepage (which includes at least the name(s) of the group’s [Chair](https://www.w3.org/2021/Process-20211102/#GeneralChairs)(s), the name of the [Team Contact](https://www.w3.org/2021/Process-20211102/#TeamContact), and instructions for joining the group).
]]

It leaves the requirements to have the info available but push the info into the Group homepage.

**Comment by koalie** [comment]
> So, the sentence in [4.5. Charter Extension](https://www.w3.org/2021/Process-20211102/#charter-extension) : [[ The announcement must indicate the new duration. The announcement must also include rationale for the extension, a reference to the [charter](https://www.w3.org/2021/Process-20211102/#WGCharter), the name(s) of the group’s [Chair](https://www.w3.org/2021/Process-20211102/#GeneralChairs)(s), the name of the [Team Contact](https://www.w3.org/2021/Process-20211102/#TeamContact), and instructions for joining the group. ]]
> 
> could read instead: [[ The announcement must indicate the new duration. The announcement must also include rationale for the extension, a reference to the [charter](https://www.w3.org/2021/Process-20211102/#WGCharter), and the Group homepage (which includes at least the name(s) of the group’s [Chair](https://www.w3.org/2021/Process-20211102/#GeneralChairs)(s), the name of the [Team Contact](https://www.w3.org/2021/Process-20211102/#TeamContact), and instructions for joining the group). ]]
> 
> It leaves the requirements to have the info available but push the info into the Group homepage.

Yes, that would work for me, @plehegar

**Comment by plehegar** [comment]
The change to address this issue was merged, so closing.

Feel free to reopen if you believe some parts of the issue remain.

@koalie , I don't think anyone would object if you start implementing the change in announcement without the new Process approved. And if someone do object, that's good information to know before we approve the new Process.
