### ISSUE TITLE
Should appeal request be shared with the Membership?

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/w3process#603]
https://www.w3.org/2021/Process-20211102/#ACAppeal only requires that
> An [Advisory Committee representative](https://www.w3.org/2021/Process-20211102/#advisory-committee-representative) initiates an [appeal](https://www.w3.org/2021/Process-20211102/#advisory-committee-appeal) by sending a request to the [Team](https://www.w3.org/2021/Process-20211102/#team).

But since that request needs to be shared with the Membership during the process, it would be make more sense if that appeal request be sent to the team but in a member-visible space.

**Comment by frivoal** [comment]
I think we should make it clear that the person filing the appeal, if willing, is allowed and encouraged to share their appeal request and its reasoning with the AC. Need to draft a pull request to do that, feel free to beat me to it.

**Comment by frivoal** [comment]
@dontcallmedom  I've made a pull request for this, let us know if this is what you meant: #676
