### ISSUE TITLE
Recording council disagreements

### ISSUE THREAD

**Issue by frivoal** [w3c/w3process#605]
Forking off https://github.com/w3c/w3process/issues/278#issuecomment-986043959, from a comment @msporny made:

> Last I heard, the final tallies for/against would be made available, but not how individuals on the FO Council voted. I understand the reasoning to hide the votes -- so no one gets "bullied" into voting a certain way. That said, I don't think that concern is outweighed by the transparency of the process.

From this part of the [draft process](https://www.w3.org/Consortium/Process/Drafts/director-free/#addressing-fo):
> Decision of the [W3C Council](https://www.w3.org/Consortium/Process/Drafts/director-free/#w3c-council) should be unanimous. If despite careful deliberation the [W3C Council](https://www.w3.org/Consortium/Process/Drafts/director-free/#w3c-council) is unable to reach consensus, the [Chair of the W3C Council](https://www.w3.org/Consortium/Process/Drafts/director-free/#chair-of-the-w3c-council) may instead resort to voting. In that case, the decision is made by simple majority, with the [Chair of the W3C Council](https://www.w3.org/Consortium/Process/Drafts/director-free/#chair-of-the-w3c-council) breaking ties.
>[…]
> A rationale supporting the decision must be provided as well. In the case of non-unanimous decisions, members of the [W3C Council](https://www.w3.org/Consortium/Process/Drafts/director-free/#w3c-council) who disagree with the decision may write a Minority Opinion explaining the reason for their disagreement. [Minority Opinions](https://www.w3.org/Consortium/Process/Drafts/director-free/#minority-opinion) must be included in the announcement of the decision.

As long as the decision is unanimous, you don't need the names of people who voted, since they all support the decision. In case of a majority-only decision, the minority opinion gives you insights into what the the disagreement was. It may be worth stating explicitly that the authors of the minority opinion should/must identify themselves. It's also interesting to wonder: If people didn't support the decision, are they required to write a minority opinion, or can we just have a non-unanimous decisions, but with no further insights on who disagreed and why?

**Comment by msporny** [comment]
> As long as the decision is unanimous, you don't need the names of people who voted, since they all support the decision. In case of a majority-only decision, the minority opinion gives you insights into what the the disagreement was. It may be worth stating explicitly that the authors of the minority opinion should/must identify themselves. It's also interesting to wonder: If people didn't support the decision, are they required to write a minority opinion, or can we just have a non-unanimous decisions, but with no further insights on who disagreed and why?

Historically, IIRC, FO decisions have often been provided with an explanation of the logic that led up to the decision. I've found these write-ups insightful and compelling. I've often changed my position (e.g., EME) after reading the FO decision prose. I imagine we'll keep this mechanism going forward.

The thing that changes in this new director-free approach is that it is possible for there to be dissent on the decision, and it seems as if that dissent needs to be documented as well. "We came to a decision through a simple majority vote, here's the rationale on that... and here is the rationale from those that dissented." Documenting dissent is an important exercise in any governing body... it helps the organization remember that some decisions were problematic.

I will also note that simple majority is a terrible outcome... For example a 49%-51% vote signals almost perfect disagreement -- it's the worst sort of divisiveness in a body -- maximized disagreement (in other words, you literally couldn't do worse than the outcome you came to!) :). If an FO comes to that -- it signals a larger problem. We might want to entertain the possibility of "failure to resolve an FO" reconvening a different group if we end up in a situation such as that, or that the FO finding is a set of recommendations that would make the decision less controversial... or backing off to support for REC? What I'm trying to say is that we might want to have a better exit than to use the result of a simple majority vote. 

Perhaps we should consider a 75%+ supermajority vote in the case where there is a failure to come to consensus?

**Comment by dwsinger** [comment]
@msporny whether a bias is a good idea depends on the direction of the original decision. so, for example, if the chair of a WG had decided that the WG did not have consensus to publish, and you wanted to object to that decision, the bias would have been the other way. In other words, a bias towards leaving the original decision standing is not always the right way. The council needs to make a decision, just as the Director does. We do not want automated processes making decisions on our behalf.

**Comment by frivoal** [comment]
> Regardless of the outcome, a majority/minority opinion would be available to the membership and general public?

Yes. I base this on:
> A record of each [Formal Objection](https://www.w3.org/Consortium/Process/Drafts/director-free/#FormalObjection) must be [publicly available](https://www.w3.org/Consortium/Process/Drafts/director-free/#confidentiality-change).

> Decisions of the [W3C Council](https://www.w3.org/Consortium/Process/Drafts/director-free/#w3c-council) must have the same level of confidenntiality as the object of the [Formal Objection](https://www.w3.org/Consortium/Process/Drafts/director-free/#FormalObjection).


pushing a REC or adopting a charter are public things, so council decisions must be public as well. Including minority opinions, if any. Source for that is:

> [Minority Opinions](https://www.w3.org/Consortium/Process/Drafts/director-free/#minority-opinion) must be included in the announcement of the decision.

Process also says:
> A record of each [Formal Objection](https://www.w3.org/Consortium/Process/Drafts/director-free/#FormalObjection) must be [publicly available](https://www.w3.org/Consortium/Process/Drafts/director-free/#confidentiality-change).

So maybe we can even simplify this must have the same level of confidentiality, and simply go with must be public.


> I will also note that simple majority is a terrible outcome... For example a 49%-51% vote signals almost perfect disagreement
> […]
> Perhaps we should consider a 75%+ supermajority vote

Agree that 51/49 is close to a worst case scenario. But we do have:

> Decision of the [W3C Council](https://www.w3.org/Consortium/Process/Drafts/director-free/#w3c-council) should be unanimous.

So the council is not meant to be happy that it reached 51/49, and the chairs are expect to try and get the group to unanimity if possible, or near unanimity if not. I think that's deeply ingrained in the w3c, so I am not too worried that we'll go for 51/49 when 99/1 would be achievable.

But it remains an interesting question about what to do in the cases where we cannot do better than simple majority. So far, the idea is that decision by simple majority, with an explained rationale, and a documented minority opinion, and the possibility of an AC appeal, is better than no decision. But it is a hard question, in particular because it's not typical, so it's hard to reason about given that we don't have a lot of experience of that sort of situation to go by.

**Comment by frivoal** [comment]
Most of this is covered in the https://www.w3.org/Consortium/Process/Drafts/director-free/ branch, but the AB needs to decide on whether:
* vote totals must/may/must not be reported
* individual positions must/may/must not be reported by name

**Comment by plehegar** [comment]
"resolved:  Individual positions MUST NOT be attributed in the Council Report"
"resolved: "May" "
- AB - October 20, 2022

**Comment by frivoal** [comment]
> "resolved: "May"

This lacks the context of the full AB minutes to be understandable. That "may" is about the council reporting vote totals (when there is a vote rather than a decision by consensus).
