### ISSUE TITLE
Include Membership input ahead of MoU decision

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/w3process#606]
The current Process delegates full authority to the Director in making decision to sign Memoranda of Understanding; the only option for the Membership to disagree is through the appeal process. In particular, the process doesn't call for any prior engagement from the Team with the Membership prior to signing such an MoU.

As we're moving towards Director-free, and given recent experience where the Membership has indicated interest in greater involvement in these discussions, the Process should probably consider whether having a required advance notice or even a formal AC Review before reaching such a decision would satisfy this need.

**Comment by OR13** [comment]
I'm in favor of AC (Member) review, I worry about relying on Director / AB / TAG review.

I think the AC needs to be held more accountable, and allowing the AB to speak for them could easily land us right back where we are today, this appeals to decisions that should have been made by members first, and then approved / rejected / communicated by W3C leadership.

**Comment by dwsinger** [comment]
Indeed, it would have been good if the earlier decision that this was "just another MoU" had been surfaced to the AC, as it's not obvious that joining an org. is

**Comment by albertoEnstein** [comment]
A

**Comment by npdoty** [comment]
+1 for advance notice. 

Formal AC review seems good too, if we think there will be a substantial fraction of members which will review/vote, but if we'll just add another vote that isn't getting much response, then that could be an indicator that the actual decision making is better delegated to staff (as long as there's notice).

**Comment by jeffjaffe** [comment]
I'm not convinced that the embargo argument is compelling.  In the past, sooner or later, we have always gone to the Membership.  It is true that getting Membership input ahead of MoU decisions could add a few more weeks, but no more than that.  I can't recall a case where this would have been a problem.
