### ISSUE TITLE
Does the Council need the ability to defer decisions to someone else under some (rare) circumstances?

### ISSUE THREAD

**Issue by dwsinger** [w3c/w3process#618]
On rare occasions, Council may realize that they need an employee, officer, or even the Board, to make a final decision (e.g. if a legal question arises, Counsel or the Board may be the best to issue the decision).

We should consider adding something like "The Chair may propose, and a Council may agree by majority decision, to ask that the formal decision on the specific question in hand be made and issued by (a) an officer; (b) or an employee; (c) or by the Board."

**Comment by frivoal** [comment]
I agree that there's an need for something other than the Council to handle legal questions. But I'd make it a hard rule, not at the discretion of the chair. I've proposed doing so in https://github.com/w3c/AB-memberonly/issues/131. I encourage you to read that issue.

Other than legal questions though, do you see a reason to enable the council to defer to someone else? So far, I don't.

**Comment by dwsinger** [comment]
I'm aware of [issue 131](https://github.com/w3c/AB-memberonly/issues/131); I am concerned that there may be circumstances that we currently don't imagine, in which deferral to someone else is appropriate, and that no, or only a tight specific, provision of such an escape may leave us in an awkward spot. We don't have to take advantage of it, but if we find we want it and don't have provision…

Legal is only one case. I can see circumstances in which the Council feels that
* a specific person, e.g. the CEO or Counsel, (employee or officer), issue a Decision
* it's more appropriate for a formal authority such as the Board issue the Decision

so, it's a concern. I hope it's minor, and I am not insistent.

**Comment by TallTed** [comment]
@fantasai -- 

> aside from legal questions which should be pre-empted by W3C Council in the first place and not reach the Council

I am guessing that the "W3C Council" should be some other entity, perhaps "W3C [legal] Counsel"?

**Comment by Alexleeys** [comment]
Check Good luck

**Comment by dwsinger** [comment]
The AB agreed at the August F2F

**Comment by jwrosewell** [comment]
A "supermajority" would need to be defined in the W3C Process document.

**Comment by dwsinger** [comment]
@jwrosewell I agree, it would, but thinking about it, I don't think we should use supermajority. If a _majority_ of the Council feels that the Council should not make a decision, yet that falls short of a supermajority, and we then convene the Council, there is a good chance we'll have a decision in which the majority abstains or even renounces – which would be a weak result. So I conclude a majority decision to defer would be enough.

Having said that, if a majority feels that they should defer, I have to believe the rest would tend to concur (i.e. "ok, we won't force you to make a decision") so it'll tend to tip pretty naturally into a consensus decision.

**Comment by frivoal** [comment]
This is resolved by the AB, and is now folded in in the https://www.w3.org/Consortium/Process/Drafts/director-free/ branch, which will be proposed for merging soon.
