### ISSUE TITLE
can the AB/TAG chair ask for a special election in *advance* of a known upcoming vacancy?

### ISSUE THREAD

**Issue by dbaron** [w3c/w3process#62]
[Section 2.5.3 Advisory Board and Technical Architecture Group Vacated Seats](https://w3c.github.io/w3process/#AB-TAG-vacated) says:

> When an elected seat on either the AB or TAG is vacated, the seat is filled at the next regularly scheduled election for the group unless the group Chair requests that W3C hold an election before then (for instance, due to the group's workload). The group Chair should not request an exceptional election if the next regularly scheduled election is fewer than three months away.

It seems to me that, since some vacancies are known in advance of when they occur, it ought to be possible for the Chair to ask for the election when an upcoming vacancy is known even if the seat is not yet vacant (much like regular elections are held before the terms expire), so that the vacant seat can be filled from the result of a special election more quickly.

It's not clear to me whether the above text allows this.  I tend to think it should be clarified so that it does allow it.

**Comment by dwsinger** [comment]
I'm reading 2.5 and not finding anywhere that (a) stops a member of TAG or AB from announcing that they are resigning as of a future effective date or (b) given that, stops the Director from announcing and holding the election prior to that date. Maybe I am missing something? Does anyone see any reason this wouldn't be OK? Perhaps we need a line saying explicitly that it is?

**Comment by jeffjaffe** [comment]
dbaron is raising a good point.  The only problem would be if we think we know that someone will resign, but then they don't.  Someone could signal an intention to resign because their organization is leaving W3C; but then their organization might stay or they may transfer to a different company that is in W3C.  So there could be some small confusion in some scenarios if we vote before the formal resignation.

**Comment by dwsinger** [comment]
This can't be an intention, it has to be a resignation. "I resign my seat as of 1st September 2017 upcoming." (e.g. in the case we're handling now, when their membership expires). If they get re-hired by a member, well, they'll have to re-nominate (which actually, we need, as we need the statement of intent to support).

**Comment by dbaron** [comment]
What's not precise enough (to me) about the current text is that "When [a seat] is vacated" could be interpreted as "When a seat becomes vacant" (i.e., the resignation has taken effect) or as "When a seat is declared to be vacant now or in the future" (i.e., when the resignation is known).  (The process doesn't specifically describe resignation as of a future date, so it's not clear what wording it would use to describe that.)  I think somebody who had a reason to want to argue for the former interpretation could argue for it in a reasonable way.

**Comment by dwsinger** [comment]
OK, so some clarity edits to the text might be in order. Can you suggest?

**Comment by dbaron** [comment]
One way to clarify would just be by adding an extra sentence to the second list item, such as:
> The group Chair MAY request an exceptional election based on knowledge that a seat will be vacated at a future date.

(I tried to word that so it doesn't introduce any new terminology.)

**Comment by jeffjaffe** [comment]
Seems reasonable.

**Comment by chaals** [comment]
This is starting to sound good. I note that Jeff's hypothetical actually applied to me recently, albeit not in regards to the AB, and I know of other lasst-minute reversals of plan. But if someone formally resigns, that's done. They can always renominate for their own vacated place...

**Comment by dwsinger** [comment]
LGTM.  I agree with Chaals, resignation is not reversible -- you re-stand.
