### ISSUE TITLE
Should potential appointees to the TAG be required to stand for election, to be eligible for another term?

### ISSUE THREAD

**Issue by dwsinger** [w3c/w3process#622]
Both the TAG, as represented by the [comment](https://github.com/w3c/w3process/pull/611#issuecomment-1196692082) in the pull request, and the AB in conversation, have wondered whether we should ease people from appointment into election, by requiring that they stand for election to be eligible for appointment to a second term.

Such a requirement would mean, if you wish to serve on the TAG:
term 1: you can be appointed
term 2: you must stand and can be elected or appointed (if you are not elected)
term 3: you are term limited on appointment, you must stand and be elected to serve

**Comment by TallTed** [comment]
Possibly clearer --

term 1: you MAY stand for election; if not elected, you CAN be appointed
term 2: you MUST stand for election; if not elected, you CAN be appointed
term 3: you MUST stand for election; if not elected, you CANNOT be appointed
term 4: reset to term 1

**Comment by fantasai** [comment]
@dwsinger I'd rather continue this discussion in 613, as the context is already there. That issue explicitly covered both methods of breaking continuity, and as Florian points out, there are some awkward interactions between the two if we adopt both. IImho splitting out this half of the issue makes the discussion harder to follow.
