### ISSUE TITLE
Updates to sections 5.2.2 and 2.1.3.1

### ISSUE THREAD

**Issue by koalie** [w3c/w3process#63]
This is related to #38 and #39 and is intended to reflect what has been done in practice since announcement in December 2014, namely, that AC reviews (of charters, Proposed Recommendations) have had the option to be "Public and send email to both w3c-ac-forum and public-new-work".

Proposed changes in bold:

> 5.2.2 Working Group and Interest Group Charter Development
>
> W3C creates a charter based on interest from the Members and Team. The Team must notify the Advisory Committee when a charter for a new Working Group or Interest Group is in development. This is intended to raise awareness, even if no formal proposal is yet available. Advisory Committee representatives may provide feedback on the [Advisory Committee discussion list](https://www.w3.org/2017/Process-20170301/#ACCommunication) **and make their review public**.

> 2.1.3.1 Advisory Committee Mailing Lists
>
> The Team must provide two mailing lists for use by the Advisory Committee:
>
>    1. One for official announcements (e.g., those required by this document) from the Team to the Advisory Committee. This list is read-only for Advisory Committee representatives.
>    2. One for discussion among Advisory Committee representatives. Though this list is primarily for Advisory Committee representatives, the Team must monitor discussion and should participate in discussion when appropriate. Ongoing detailed discussions should be moved to other appropriate lists (new or existing, such as a mailing list created for a Workshop).
>
> An Advisory Committee representative may request that additional individuals from their organization be subscribed to these lists. Failure to contain distribution internally may result in suspension of additional email addresses, at the discretion of the Team.
>
> **In addition, the Advisory Committee may share reviews of charters, Proposed Recommendations
on a public mail archive.** 

For those who refer to the Process Document, it would be useful to point to https://lists.w3.org/Archives/Public/public-new-work/ but I see that the mail archives for w3c-ac-members and w3c-ac-forum are not part of the process itself.

**Comment by chaals** [comment]
> In addition, the Advisory Committee may share reviews of charters, Proposed Recommendations
on a public mail archive.

I object to this bit. It suggests that someone can share confidential reviews and needs to be tightened up.

**Comment by dwsinger** [comment]
I think it should be "In addition, an Advisory Committee Representative may share their review of a charter, or Proposed Recommendation, on a public mail archive."

**Comment by michaelchampion** [comment]
@dwsinger your proposed text should at least say something like "so long as their review does not reference the position of another member, unless that position is already public."

I'd be more comfortable just not going down the path toward having a public discussion of charters being balloted.  Openness is a great principle, but recent experiences with social media polarizing discussions rather than informing them don't give me much hope that W3C will be different.

**Comment by dwsinger** [comment]
If the option is to send the comments immediately to a public list, then we have no way to enforce what they quote. We can *ask* the AC Reps that choose "public" to be careful in what they quote, but I think you (and Chaals) have pointed out an unfixable flaw/asymmetry here. Perhaps this change is not as innocent as it looks. I am also not super happy with having too many options on this form, and I'd strongly oppose the default being 'public'.

**Comment by dwsinger** [comment]
Of course, nothing today stops an AC Rep from opening a discussion on public-new-work manually, either...
the fact that they'd have to do it manually might cause them to think about what they say and what they are making public...

**Comment by chaals** [comment]
For now I will not make any change unless explicitly stemming from a Resolution of the CG.

**Comment by koalie** [comment]
Replying to @chaals earlier [comment](https://github.com/w3c/w3process/issues/63#issuecomment-324397174) on proposed addition for section 2.1.3.1 :
 >>   In addition, the Advisory Committee may share reviews of charters, Proposed Recommendations on a public mail archive.
>>
>I object to this bit. It suggests that someone can share confidential reviews and needs to be tightened up.

Given this is about the (wbs) mechanism, I'd propose a more specific wording:
"In addition, the review mechanism lets the Advisory Committee share reviews of charters, Proposed Recommendations on a public mail archive."

**Comment by dwsinger** [comment]
Hi Coralie, one of the concerns is that AC Reps tend to quote other replies, in their reply, and if they quote something that was member confidential, then their reply should not be public. We have no way to enforce this.  Also, it should be clear that it's not that they can share *any* reviews, but that they can share their *own* review -- if we go there.

**Comment by koalie** [comment]
Thanks, @dwsinger I see, but I have yet to see AC reps quoting others' input in *their own WBS responses* for charter reviews or spec reviews, which is what this is about.

What has been done in practice since announcement in December 2014, is that AC reviews (of charters, Proposed Recommendations) have had the option to be "Public and send email to both w3c-ac-forum and public-new-work".

I withdraw my proposed addition to section 2.1.3.1; this appears to be difficult to spell-out and hinges on #39 which is controversial.

However I maintain my [initial proposal to amend 5.2.2](https://github.com/w3c/w3process/issues/63#issue-247769822).

**Comment by dwsinger** [comment]
I could live with adding "and may make their own review publicly visible." I think, to clarify that the permission extends only to their own content (and re-insert the may to indicate it's a permission).

Others?

**Comment by chaals** [comment]
That works for me in the scenario where we are going to authorise public charter reviews. But I still don't want us on that track...

**Comment by dwsinger** [comment]
You are right, it's kinda odd to make public comments on a document that is not, itself, public. Coralie?

**Comment by chaals** [comment]
The charter often is public, and must end up so (albeit perhaps modified after comments).

**Comment by dwsinger** [comment]
Agreed, final charters are publicly visible, but I can't tell from recent announcements whether the drafts were also, and the process is silent (it merely says operational charters are publicly visible). So I am OK with public comments as long as the draft charter itself is publicly visible. Like chaals, I am not soliciting public input, however.

**Comment by wseltzer** [comment]
Yes, draft charters are currently shared publicly.

**Comment by koalie** [comment]
> Note: Starting in January 2007, W3C makes all charters public during Advisory Committee review.
cf. https://www.w3.org/Guide/Charter

**Comment by frivoal** [comment]
We've decided to close #39, which is the same issue as this. It probably means we should close this one too.

**Comment by dwsinger** [comment]
handling with #38

**Comment by dwsinger** [comment]
address via #526
