### ISSUE TITLE
Allow CEO to delegate position on the Council

### ISSUE THREAD

**Issue by fantasai** [w3c/w3process#633]
@jeffjaffe as a CEO was a reasonable person to include in the Council, since he was engaged in W3C activities at a level where it would be appropriate to include him. But it's possible future W3C CEOs might not have an interest in being involved at this level, and instead be focusing on other aspects of running W3C. We might want to let the CEO delegate their position on the Council to an appropriate Team member.

Proposed edit:
```
the CEO <ins>or their delegate</ins>
```

**Comment by hober** [comment]
Can the CEO delegate this seat to someone not on the Team?

**Comment by chaals** [comment]
(Disclaimer: I'm opposed to the CEO being a formal member of the board in the first place)

If the CEO has a seat on the board, it's part of their job to be there. Like the AB and TAG, it should not be OK to delegate the seat to someone else.

**Comment by fantasai** [comment]
@hober No, I think the goal of the seat is to have some perspective from the Team.

**Comment by cwilso** [comment]
@chaals this is about Formal Objection Councils, not the Board of Directors.  The CEO seat on the BoD is an entirely different issue. (this one, in fact: https://github.com/w3c/le-governance/issues/57)

I agree with @fantasai that the goal of the CEO being included in the Council is to include the Team's perspective (in addition to the Team writing the report); I think the CEO should be able to delegate that responsibility to someone else on the Team (but not someone NOT on the Team).  As @fantasai says, a different CEO might not be the right person to sit on an FO Council, but the Team's perspective should be represented.

**Comment by hober** [comment]
> @hober No, I think the goal of the seat is to have some perspective from the Team, particularly any considerations that wouldn't be represented by the TAG (technical expertise) or AB (process expertise).

in that case, the text should constrain delegation to within the Team.

**Comment by chaals** [comment]
@cwilso if the CEO is formally on the council (i.e. with a vote), then I think the CEO has an obligation to fulfil that role.

If s/he asks someone on the team to tell her/him what to think and how to vote, that's what will happen, but the formal responsibility belongs to the CEO.

If the council agrees that some other team member's perspective is important, and the CEO wants to suppress that perspective I suppose it might be possible in principle (given the employment relationship) but I would expect the council to be able to work around that pretty easily. But in the converse case, where the CEO thinks a particular team member's input is valuable, I see no barrier to the perspective being presented. The council can ask people for input, no?

**Comment by dwsinger** [comment]
There's a difference between being in the room, and providing input to someone who's in the room.

**Comment by chaals** [comment]
@dwsinger sure. There's also a difference between taking responsibility, and delegating it. In the formal objection case, it is often unclear to most people whether in practice TimBL took the decision, delegated the work but then made it in his name, or delegated the task entirely and washed his hands of it. I think has caused significant angst and ill-will to build.

Conversely, I think when it has been clear that Tim has taken a decision and owned it personally, people have generally been more willing to accept the outcome, whether they agree or not.

I think it is incumbent on members of the council to take personal responsibility for their role. This allows members to choose not to elect someone e.g. whose employer drags them from W3C Councils or who just doesn't turn up, and the Board (who hires the CEO) to hold the CEO accountable on behalf of the organisation as a whole. (It's not as good as knowing up front that someone wasn't up to the job, but since we don't it's an essential check).

**Comment by palemieux** [comment]
>  think it is incumbent on members of the council to take personal responsibility for their role.

+1

I do not think members of the Council should be able to delegate their role.

**Comment by fantasai** [comment]
> I do not think members of the Council should be able to delegate their role.

I agree with this in general, it's just that the CEO has a position ex officio and depending on the exact composition of the Team and capabilities of the CEO at any point, someone else on the Team might be a better person to fulfil the role of sitting on Councils, and we might want to give them that flexibilty.

I'm also okay with running the Process as-is until there's a CEO who would be a bad fit for the Council, and amending it then if needed, but while we're on the topic seems reasonable to pre-emptively address now.

I'll clarify the original proposal:

```
the CEO <ins>or their chosen Team delegate</ins>
```

**Comment by plehegar** [comment]
"the CEO is allowed to delegate their seat" - AB - October 20, 2022
(also ensuring the delegate go through dismissal)
