### ISSUE TITLE
Improving the definition of consensus

### ISSUE THREAD

**Issue by frivoal** [w3c/w3process#634]
(Moved from #314)

"consensus", in the Process is currently defined as the lack of Formal Objection.

This doesn't always work great, as we occasionally want to speak of consensus in contexts where making formal objections would not be appropriate (such as in the W3C Council addressing formal objections, in a potential appointment committee, or in this catch 22 https://github.com/w3c/w3process/issues/624).

So FOs isn't quite what we're trying to measure here. Consider this section about the Council where we are locally overriding the definition:

> […] in this section, the terms “consensus“, “unanimity”, and “dissent” have slightly different meanings compared to the rest of this document: dissent—and therefore the lack of consensus—occurs when a member of the [W3C Council](https://www.w3.org/Consortium/Process/Drafts/director-free/#w3c-council) opposes a tentative conclusion, even though they cannot register a [Formal Objection](https://www.w3.org/Consortium/Process/Drafts/director-free/#FormalObjection).

I think the better solution may actually be to adjust the general definition of consensus. Beside its formal definition of a lack of formal objection, consensus is a term frequently used in our community to refer to a lack of sustained disagreement. Clearly, filling a formal objection is a sign of sustained disagreement, but in common usage, it isn't necessary to escalate things that much. For instance, we often say that the AB makes decisions by consensus, and often conclude that we do not have consensus when some people indicate that they disagree, yet that doesn't involve Formal Objections.

Note that this would not prevent chairs from making decisions where they can today. The process states:
> In some cases, even after careful consideration of all points of view, a group might find itself unable to reach consensus. The [Chair](https://www.w3.org/Consortium/Process/Drafts/director-free/#GeneralChairs) may record a decision where there is [dissent](https://www.w3.org/Consortium/Process/Drafts/director-free/#def-Dissent) […] so that the group can make progress

I've gone through the Process, and I think the one case where we do want to necessarily gate consensus on the absence of formal objection is AC reviews.

So here's my proposal: 
1. Adjust the definition of consensus (respectively, of dissent) to be based on the lack of (resp. presence of) sustained disagreement, rather than of Formal Objection specifically. An FO always indicates sustained disagreement, but as per current practice, an FO isn't necessary to express dissent. (Mere dislike for a proposed decision, however, doesn't constitute sustained disagreement, as one could still be willing to accept the compromise).
2. Indicate in the section about AC Reviews that in that particular context, Formal Objections are the way to express sustained disagreement.
3. Note in the sections about the TAG choice of chair, and about the Council that Formal Objections aren't available in those contexts.

If that sounds plausible, I'll make a pull request to show how that'd work in detail.

**Comment by dwsinger** [comment]
@frivoal Yes, this is a good direction.

I would note the definition of Consensus at [3GPP](https://www.3gpp.org/ftp/Information/Working_Procedures/3GPP_WP.htm) (see Annex A):

> Consensus:  General agreement, characterized by the absence of sustained opposition to substantial issues by any important part of the concerned interest and by a process that involves seeking to take into account the views of all parties concerned and to reconcile any conflicting arguments. (Note: consensus need not imply unanimity).

As Florian says, this allows someone to say "I don't agree, but I won't block consensus (by sustaining my objection)". It also allows the chair to declare consensus in the absence of unanimity, if they feel all the views have been taken into consideration and that the opposition is small enough, and from a source that is not key, not to be an 'important part', and that a decision is needed.

This is along-winded way of saying I think you're on the right lines.

**Comment by dwsinger** [comment]
So, unanimous means everyone in the body agrees (not even abstains). Consensus allows for both abstention and non-sustained objection.

**Comment by jeffjaffe** [comment]
> 3\. Note in the sections about the TAG choice of chair, and about the Council that Formal Objections aren't available in those contexts.

It seems that the reason that we associate FOs with dissent is because the Process Document is built around the concept of a "decision", so the way you express dissent to a decision is with a FO.

I'm curious why that doesn't work for some of the items above.  For example, I imagine the TAG choice of chair might be viewed as a "decision", so one could use a FO to express dissent.

For the Council, you can't use FOs because the whole purpose of the Council is to resolve FOs.  But one can simply state that the Council attempts to decide via Consensus, but if there are objections then it decides via majority.

I don't have any sustained objection to introducing the new term, but it is not clear to me why it is really needed.

**Comment by frivoal** [comment]
> For example, I imagine the TAG choice of chair might be viewed as a "decision", so one could use a FO to express dissent.

Actually, upon reflection, I agree, and did not include that restriction in the pull request.

**Comment by dwsinger** [comment]
The confusion comes when people want to indicate sustained objection to a proposal; they don't file an FO and initiate a Council, since there is not yet a decision, but they do need to indicate that there is no consensus

**Comment by LJWatson** [comment]
I agree with the general direction but have a mild concern that the absence of "sustained objection" opens up the possibility of progress being blocked based on persistence rather than technical merit.

We may also want to take this opportunity to caution against unanimity becoming anything stronger than an ideal outcome?

**Comment by jeffjaffe** [comment]
> We may also want to take this opportunity to caution against unanimity becoming anything stronger than an ideal outcome?

This is a great point.  I always thought this definition was strange because I'm not aware of any circumstance that we require unanimity.  Can we simply remove that definition?

**Comment by michaelchampion** [comment]
I agree with Florian's basic point that the definition of "consensus" needs improving.  Furthermore, the concept of a "formal objection" is an anachronism harking back to the days of an expert,  authoritative, engaged Director to appeal to.  At a minimum,  I'd suggest replacing it with something like "sustained disagreement to the proposed consensus" in most contexts (except perhaps AC ballots, assuming the FO Council idea eventually works out better in practice than we have seen so far).   

Following @dwsinger 's pointer to 3GPP's definition I'd recommend W3C adopt something like https://www.3gpp.org/ftp/Information/Working_Procedures/3GPP_WP.htm#Article_25

> [groups] shall endeavour to reach consensus on all issues ... Informal methods of reaching consensus are encouraged (e.g., a show of hands). If consensus cannot be achieved, the Chair can decide to take a vote. The vote may exceptionally be performed by a secret ballot... A proposal shall be deemed to be approved if 71% of the votes cast are in favour

In other words, W3C should adopt https://en.wikipedia.org/wiki/Consensus-seeking_decision-making
> .When consensus is deemed to be unattainable, either the "presenter" of a proposal or the "facilitator" of the deliberations is empowered to choose the closing option of a fallback vote. Other possible closing options may include "refer to committee", "test for stand-asides", and "withdraw the proposal".

We could debate whether a simple majority or supermajority is needed to decide on a proposal, and in which contexts.  In general I believe something like a 2/3 , 3/4 (or 71% splitting the difference) supermajority is appropriate but there may be contexts in which a simple majority is sufficient to end discussion and move on.  ("When should we break for lunch" is the canonical example I believe ;-) )

**Comment by palemieux** [comment]
> "consensus", in the Process is currently defined as the lack of Formal Objection.

I agree this is far from ideal.

Consensus is not unanimity, thus the mere existence of a minority opinion or of an outstanding Formal Objection should not invalidate the consensus of a group and stop work.

The general definition of Consensus could be as simple as: _twice as many in favor as those opposed_.

As suggested by @michaelchampion, although Consensus (and in fact unanimity) are always desirable, it might not be desirable to require Consensus for every decision, e.g. "should we break for lunch?".

Instead Consensus could generally reserved for those decisions that would result in a modification of W3C deliverables, including specification, charters, process documents, etc.

Consensus could be explicitly required for certain decisions.

**Comment by fantasai** [comment]
> The general definition of Consensus could be as simple as: twice as many in favor as those opposed.

This is not consensus, this is a supermajority in favor, and it is not how we work at W3C.

I'd like to interrupt this conversation to point out more clearly that there's a PR to fix this here: https://github.com/frivoal/w3process/commit/1cb4db2d844e9525d609e9ec7aa51dd14ebded16
and it would be helpful if people would review the specific wording being proposed.

**Comment by palemieux** [comment]
@fantasai Based on your definition of consensus:

- a chair can make decisions without the consensus of the group (i.e. in the presence of sustained objection(s))
- a group can operate indefinitely without consensus (i.e. in the presence of sustained objection(s))
- a [vote](https://pr-preview.s3.amazonaws.com/w3c/w3process/635/2dfe1d2...frivoal:1cb4db2.html#Votes) cannot be used to reach consensus since it cannot cure sustained objection(s)
- the only recourse for objectors is to file a Formal Objection

Is my understanding correct?

**Comment by fantasai** [comment]
@palemieux 

* Yes, a chair can call for a formal vote in place of consensus. Chairs should not do so except as a last resort.
* Yes, objections do not stop work. But at any point an objector can raise a formal objection to escalate to the Council.
* A vote cannot be used to reach consensus, but it can be used to make a decision without consensus.
* If they would like to escalate the issue, yes.

**Comment by palemieux** [comment]
Ok. Thanks for confirming. A significant drawback of the current approach is that a group does not have a procedure to dispose of dissent, which causes dissent to persist. In my experience, the longer dissent persists the more expensive it is to fix -- just like bugs.

Has W3C considered a method (of last resort to use your term above) by which a group can formally dispose of dissent, and thus achieve consensus -- without having to file an FO, which is time-consuming, disruptive and hands the responsibility of curing the issue to a separate group?

**Comment by nigelmegitt** [comment]
> So, unanimous means everyone in the body agrees (not even abstains).

Er, this appears to be what the Process says, but it's wrong.

Unanimity means that everyone has the _same_ view, but that could be in favour or against, or indeed neither. 

Suggest changing "unanimity" to "unanimous approval" in this case.
