### ISSUE TITLE
Clarify usage of types of CR in Rec Track Diagram

### ISSUE THREAD

**Issue by gsnedders** [w3c/w3process#636]
https://www.w3.org/Consortium/Process/Drafts/#rec-track currently contains a diagram showing transitions to "CR" and "CRD", however "CR" per the below encompasses all forms of Candidate Recommendation and "CRD" is undefined.

Presumably what is intended is a transition to "Candidate Recommendation Snapshot" and then the loop to/from "Candidate Recommendation Draft" (but, again, neither of these have defined abbreviations in Process).

**Comment by frivoal** [comment]
This is true. I am not particularly good at diagrams, so if you (or someone else) could supply an improved diagram, I would very much appreciate.
