### ISSUE TITLE
Mid-term Chair Appointment for TAG and AB

### ISSUE THREAD

**Issue by fantasai** [w3c/w3process#641]
Currently the AB, and soon the TAG (see https://github.com/w3c/w3process/issues/310), are to appoint their chairs at the start of each term. What if there is either a) a vacancy or b) a problem with the chair mid-term? They should be able to resolve these problems.

**Comment by hober** [comment]
Yeah, it seems to me like the Process text should simply state that the AB and the TAG [chuse](http://federali.st/constitution#a1s2c5) their Chairs, and not specify when they do so. They should be able to change Chairs whenever necessary.

**Comment by fantasai** [comment]
@hober We wanted the chairs to be reconfirmed at least after every election, so that it doesn't become extraordinary process to replace them as the membership of the group changes (or changes its mind). So we need to *add* the whenever necessary bit.

**Comment by cwilso** [comment]
It's unfortunate that the first term with the new AB chair process ended up being a weird one.  Yes, we should say the process to choose chairs can be re-run at any point if 1) one or more of the chairs resign from chairing or 2) more than X percent of the relevant body (AB/TAG) ask them to step down.

**Comment by hober** [comment]
> @hober We wanted the chairs to be reconfirmed at least after every election, so that it doesn't become extraordinary process to replace them as the membership of the group changes (or changes its mind). So we need to _add_ the whenever necessary bit.

Ahh. In that case, you only need to define the floor of when they must choose new chairs. They should be able to choose new chairs whenever they want *beyond* that, though.
