### ISSUE TITLE
Chair appointments

### ISSUE THREAD

**Issue by mnot** [w3c/w3process#652]
The `director-free` branch currently has the Team appointing WG chairs, but there isn't a clear mechanism for disputes; the FO process does not apply to these decisions, as I read it.

Should there be a process for disputing a Team decision like this?

First raised in #316.

**Comment by frivoal** [comment]
I believe there is a path already:
* The Process does not limit the types of decisions that can be formally objected to, so I see no reason why you couldn't Formally Object to chairing appointments / changes / reappointment / removals
* Initial appointment of chairs is done via charter creation / adoption, and these are subject to AC reviews, which clearly people can formally object to.
* Says https://www.w3.org/2021/Process-20211102/#cfp “Advisory Committee representatives may initiate an [Advisory Committee Appeal](https://www.w3.org/Consortium/Process/Drafts/#ACAppeal) against the decision to create or substantially modify a Working Group”. Changing a chair is a substantial modification of a working group.

All in all, these are fairly heavy handed approaches, and I suspect that for personnel issues, expressing concerns in private to the Team is most effective, but if that fails, there are appeal paths.

We could discuss whether these mechanisms are ideal, but by my read, we do have the ability to dispute such decisions, so I don't see that as a pressing issue.

**Comment by dwsinger** [comment]
I would not _like_ to see FO used, but as I read it, anyone can FO any decision, and an appointment is surely a decision. Why do you think FO is not available? (I agree with Florian, I hope it can be resolved without such a heavy tool.)

**Comment by frivoal** [comment]
@mnot Are the responses from @dwsinger and I above sufficient to address you concern, or do you think we need to do something else?

**Comment by mnot** [comment]
I read [section 5.1](https://www.w3.org/Consortium/Process/Drafts/director-free/#decision-types) as constraining the types of decisions that can use the FO mechanism defined in [section 5.5]() to 'chair decisions', 'group decisions' and 'W3C decisions', the latter being defined as:

> determined by the [Team](https://www.w3.org/Consortium/Process/Drafts/director-free/#team) on behalf of the W3C community by assessing the consensus of the W3C Community after an [Advisory Committee review](https://www.w3.org/Consortium/Process/Drafts/director-free/#advisory-committee-review).

Since there is no AC review of the Team's [appointment of a chair](https://www.w3.org/Consortium/Process/Drafts/director-free/#ReqsAllGroups), this action doesn't seem to meet the 'after an AC review' qualification.

If the intent is to allow any decision to be formally objected to, we should either state that explicitly (perhaps by defining a fourth category of decision -- "Team Decision", perhaps?), or removing that qualification _and_ the qualification regarding assessment of consensus from the definition of 'W3C decisions'.

The sentence beginning section 5 probably needs to be modified or moved; currently it only addresses one kind of decision, and implicitly, which could be confusing to readers:

> Individuals who disagree strongly with a decision should register with the Chair any [Formal Objections](https://www.w3.org/Consortium/Process/Drafts/director-free/#FormalObjection).

**Comment by nigelmegitt** [comment]
@mnot I read it that way too. There seems to be a grey area where something that would ordinarily be called a decision is being made, but there's no group with a Chair: the presence of a Chair seems to be the common factor in §5.1 - even with a W3C Decision, where a Chair is not directly mentioned, there is one by implication since the AC has a Chair (who is currently a member of the team too).

**Comment by TallTed** [comment]
Perhaps the second sentence of §5, as flagged by @mnot, could be rephrased to (hopefully clearer, though rather longer) —
> Individuals who disagree strongly with a decision _SHOULD_ register any [Formal Objections](https://www.w3.org/Consortium/Process/Drafts/director-free/#FormalObjection) with the applicable Chair (for [Working Group](https://www.w3.org/Consortium/Process/Drafts/director-free/#GroupsWG), [Interest Group](https://www.w3.org/Consortium/Process/Drafts/director-free/#GroupsIG), or [Advisory Committee](https://www.w3.org/Consortium/Process/Drafts/director-free/#advisory-committee) decisions) or the CEO (for [Team](https://www.w3.org/Consortium/Process/Drafts/director-free/#team) decisions).

(Even if the above is not adopted, I would still strongly advise swapping the order of "any [Formal Objections](https://www.w3.org/Consortium/Process/Drafts/director-free/#FormalObjection)" and "with the Chair", to the more common American English phrase order.)

**Comment by frivoal** [comment]
[section 5.1](https://www.w3.org/Consortium/Process/Drafts/director-free/#decision-types) wasn't meant to be exhaustive, just to give easily referenced names to certain common types of decisions. No implications that other decisions weren't Decisions was implied.

I guess we could do either or both of:
* starting that section with something like "Common types of decisions include"
* Linking to the [definition of Team decision](https://www.w3.org/Consortium/Process/Drafts/director-free/#decision-types) or moving it here.

**Comment by mnot** [comment]
Best be explicit. 5.5 starts:

> In the W3C process, any individual may appeal a decision by registering a Formal Objection with the [Team](https://www.w3.org/Consortium/Process/Drafts/director-free/#team) when they believe that their concerns are not being duly considered.

This has a lot of words that are doing little work, without really addressing what a FO is and when it happens. How about:

> Any individual (regardless of whether they are associated with a Member) can appeal any decision (including both those described in Section 5.1 and other decisions made as part of this Process, such as Team decisions) by registering a Formal Objection with the [Team](https://www.w3.org/Consortium/Process/Drafts/director-free/#team).

**Comment by frivoal** [comment]
@mnot Does https://github.com/w3c/w3process/pull/674 work for you?

**Comment by mnot** [comment]
Looks good, thanks!

**Comment by mnot** [comment]
Q: is there any reason we can’t include this in the 2022 batch?

**Comment by frivoal** [comment]
> Q: is there any reason we can’t include this in the 2022 batch?

It is meant for inclusion in the current batch, which is the 2023 batch, as Q1 2023 is when we expect to be wrapping up. There is no 2022 batch, because we're taking a little bit over a year to complete this cycle.

**Comment by fantasai** [comment]
(As a clarification, I renamed the P2022 tag to P2023 yesterday for this reason.)
