### ISSUE TITLE
AB liaisons to the Board

### ISSUE THREAD

**Issue by fantasai** [w3c/w3process#668]
In resolving https://github.com/w3c/le-governance/issues/25#issuecomment-1129457054 @TzviyaSiegman noted that the [Board composition proposal adopted by GTF](https://github.com/w3c/le-governance/blob/main/board-composition/ab-plan-board-no-sponsors.md) (and later by the SC) includes up to two AB liaisons:
> The following have a right to attend Board meetings and access Board materials, but do not form part of the decision-making body, and may be excluded only by a decision of the Board:
> -  ...
> -  Up to two representatives from the Advisory Board (the AB may rotate these representatives as they find appropriate), to ensure good liaison between the Board and the AB, and facilitate operational/management consistency

Since the Bylaws can't define this role (they don't define the AB, and therefore can't reference it), we need to do it in the Process. Filing this issue to track.

**Comment by chaals** [comment]
Why can the bylaws not reference the Process doc and thus the AB?

Also, how do the by-laws of the incorporated organisation become subordinate to a process document written by that organisation?

I think this us upside-down. If the rules governing the BoD say "these people defined over there can attend meetings" that seems reasonable. But if the Process document is not mentioned in the ByLaws I am having trouble understanding how it can bind the BoD.

**Comment by jeffjaffe** [comment]
> I think this us upside-down. If the rules governing the BoD say "these people defined over there can attend meetings" that seems reasonable. But if the Process document is not mentioned in the ByLaws I am having trouble understanding how it can bind the BoD.

A relevant passage in the bylaws is: "the Consortium Members ... shall have the power, and shall have the exclusive right, to amend, modify, supplement, revise, and/or restate the Process Document pursuant to the terms of the Process Document itself.  "

**Comment by chaals** [comment]
> the Consortium Members ... shall have the power, and shall have the exclusive right, to amend, modify, supplement, revise, and/or restate the Process Document pursuant to the terms of the Process Document itself

does indeed mention the Process document. But it doesn't seem to say anything about how the Process document might have precedence over the Bylaws in determining who attends BoD meetings.

**Comment by dwsinger** [comment]
The Bylaws clearly have precedence. They are a formal construct. And we don't want the more formal Bylaws drawing from the less formal Process either, hence where we are.

**Comment by frivoal** [comment]
> Why can the bylaws not reference the Process doc and thus the AB?

Because the rules for revising the bylaws are distinct (and stricter, and governed by legal constraints) than those for revising the Process. Therefore, while the bylaws can mention the Process, they cannot have a normative dependency on it.

> how the Process document might have precedence over the Bylaws in determining who attends BoD meetings.

The Process isn't meant to have precedence. The bylaws give the board the power to invite people to its meetings. The Process (with this PR) would set an expectation about (some of) who they are supposed to invite. The Board could decide to ignore the Process, and still be in compliance with the bylaws (whether that'd be a wise thing to do is a different matter).

**Comment by fantasai** [comment]
To clarify, if the Board decides not to invite the AB liaisons to its meetings, it will be in compliance with the Bylaws but in violation of the Process. Legally, it _can_ do that. But it'd still be a violation of the Process.

**Comment by jeffjaffe** [comment]
> To clarify, if the Board decides not to invite the AB liaisons to its meetings, it will be in compliance with the Bylaws but in violation of the Process. Legally, it _can_ do that. But it'd still be a violation of the Process.

For this reason, it would seem prudent to bring this issue and associated PR to the attention of the BoD to get their input.

**Comment by dwsinger** [comment]
Yes, please.  But also, maybe we can phrase it so we don't get into violation territory. Something like that the AB should identify up to two liaisons, who the AB should offer to the Board to attend meetings in an observer capacity. (By observer, I mean that they would normally not speak much).

**Comment by dwsinger** [comment]
Just write the proposed text, and send it to Mark Nottingham and Koichi Moriyama as chairs of the Governance Committee, for them to handle in GovCom and the Board. With luck, the PR won't be controversial.

**Comment by chaals** [comment]
@fantasai wrote:

> To clarify, if the Board decides not to invite the AB liaisons to its  
> meetings, it will be in compliance with the Bylaws but in >violation of  
> the Process. Legally, it can do that. But it'd still be a violation of  
> the Process.
And that would be meaningless unless the Bylaws mention the process. If  
the AB wants formal recognition from the BoD, that should be written into  
an explicit agreement. If it is intended to be a general constitutive  
principle, it should be in the ByLaws. (They aren't that hard to change).

Otherwise it's just a request - and a request to the Board doesn't belong  
in the Process.

**Comment by dwsinger** [comment]
Not quite meaningless. Establishing that the AB can, and how it does, decide who would be offered to the Board as liaison makes some sense.

**Comment by cwilso** [comment]
It would seem like a moot exercise to go defining an official process for how to select* AB liaisons to offer to the Board, if the AB has not even a whisper of an idea if the Board will want to allow such liaisons in the room.

(* this does not seem that hard; "AB selects liaisons amongst themselves")

**Comment by frivoal** [comment]
> Yes, please. But also, maybe we can phrase it so we don't get into violation territory.

The intent is not to violate territory, but to enact a gov-tf resolution. Word tweaking that reduces friction is welcome.

However…

> Something like that the AB should identify up to two liaisons, who the AB should offer to the Board to attend meetings in an observer capacity. (By observer, I mean that they would normally not speak much).

That would be a departure from the gov-tf resolution. The resolution adopted a document which about non-voting participants, listed alongside with, and with the same expected level of participation as for instance the Founding Director (TImbl). Why reopen this now?

**Comment by jeffjaffe** [comment]
> That would be a departure from the gov-tf resolution.

The gov-tf resolution was a recommendation to the SC about how to set up the BoD.

At this point, the W3C Process Community needs to determine for itself whether it believes that the Process Document should weigh-in on how the BoD conducts its business.

**Comment by dwsinger** [comment]
@frivoal I don't think the Process can alter the Bylaws. So either we're asking the Board to invite these people, or asking the Board to modify the bylaws, or starting a member-initiated bylaws revision. I'm trying to find a way ahead that doesn't involve a bylaws revision right now.

**Comment by cwilso** [comment]
I don't think it's necessary or even an appropriate focus to modify the bylaws right now.  I do think the Board should establish and invite AB liaison, so the AB can select them; that seems like a very brief item for the Board to address in the near term.  I know it seems like this is unimportant while we still have an overlap in members, but I'd like to get that in place prior to the end of year, and get the liaison functional.

**Comment by chaals** [comment]
The Board can simply decide to ask the AB to nominate liaisons able to attend its meetings, and the AB can make a decision on how to do that. To fulfil the SC recommendation that this be expected behaviour, it should go into the Bylaws, but it doesn't feel like it needs to be an urgent change.

**Comment by frivoal** [comment]
>  it should go into the Bylaws

How do you make it go into the bylaws without the bylaws gaining a dependency on the Process?

**Comment by dwsinger** [comment]
The process can define that the AB offers liaisons to the Board and how they are chosen. The Bylaws can, at some point, be revised to say something vague about inviting two members of a committee tasked with defining the technical operation of the consortium. As Chaals says, I don't think it needs codifying urgently (I don't think it's urgent to put it into practice either; we should probably see how things evolve).
