### ISSUE TITLE
Clarify the handling contributions from guests, non-w3c members, and non-WG members

### ISSUE THREAD

**Issue by dwsinger** [w3c/w3process#67]
See also #12 and #18. We need to look at how 
a) public input
b) member submissions that also have non-W3C members as author/contributor
c) input to WGs from non-members of that WG

are handled from the point of view of IPR. This issue is being filed in order to keep the question alive, and #12 and #18 are being closed. The team is working on practice in this area, and we're holding until that's worked out, and then will consider what (if any) process changes are needed

**Comment by vfournier17** [comment]
Unless these non-member parties agree to the same IP terms as the W3C members, this could get tricky.  W3C could require all such non-members to agree to a CLA that binds them to applicable parts of the Patent Policy.  The important thing is to make sure that W3C has unfettered use of any contributions from such non-member parties.  We might be able to use the CG CLA as a starting point.

**Comment by dwsinger** [comment]
Strawman here for further discussion. Perhaps we need a new section in 6.2, 6.2.1 General requirements and definitions [for Technical Reports, which is the formal term for Rec-track documents]

6.2.X Contributor license grants

Contributions to a Technical Report made by members of the Working Group operating under a Charter that has that Technical Report as a Deliverable effectively have a contribution agreement as a result of the W3C Patent Policy.

For all other Contributions to a Technical Report, the team should seek an appropriate contribution license grant, granting terms from the contributor and in the contribution that are conformant with the W3C’s royalty-free license.

NOTE such contributions can come from a member of the consortium that is not a member of the Working Group (for example, during wide review or as a Member Submission), or from an external organization (for example, during Wide Review), or during the process of producing an Amended Recommendation (where is no Working Group associated with the Technical Report).

**Comment by dwsinger** [comment]
refined:

6.2.X Contributor license grants

Pursuant to Section 3.2 of the Patent Policy, agreeing to the W3C Royalty-Free (RF) Licensing Requirements set forth in Section 5 of the Patent Policy will create a RF licensing obligation under the Patent Policy.  As a matter of practice, if a contributor to a Technical Report falls into one of the following (or a similar) categories, the Team should seek an appropriate written license agreement from the contributor acknowledging applicability of the W3C Royalty-Free (RF) Licensing Requirements to the contribution:

Outside organization that contributes comments, e.g. during wide review.
W3C Member that contributes comments to a Working Group of which it is not a member, e.g., during wide review.
Contributors working on an Amended Recommendation, where there is no Working Group.

The Team reserves the right to reject such contributions in the event such a contributor is unwilling or unable to sign such a written license agreement.

**Comment by lynningalsbe** [comment]
W3m

**Comment by vfournier17** [comment]
This is being deferred to next year’s document, pending discussion with psig, as discussed in our meeting yesterday.


Best regards,

Virginia Fournier
Senior Standards Counsel
 Apple Inc.
☏ 669-227-9595
✉︎ vmf@apple.com <mailto:vmf@apple.com>






On Nov 2, 2017, at 2:17 AM, lynningalsbe <notifications@github.com> wrote:

W3m

**Comment by dwsinger** [comment]
we need some input from AB and PSIG

**Comment by wseltzer** [comment]
We currently request commitments for such contributions, and I believe we can improve that handling without Process change.

**Comment by dwsinger** [comment]
I think it would be good if the process says what is required in order to do what. for example, "The W3C should not use contributed material in a Rec track document without a contribution grant". and so on. we should have some short formulations of the requirements; ideally they happen to match current practice. This enables the team to say "sorry, but our formal process requires that we ask and that we not proceed in the absence of an answer"

**Comment by vfournier17** [comment]
I agree with @dwsinger, although I would phrase the requirement a bit differently so it doesn't look like the full onus is on W3C.  So, something like, "W3C will not accept material contributed to a Recommendation-track document without obtaining a recorded contribution grant from the proposed contributor."  Thoughts?

**Comment by delfiramirez** [comment]
agreed

**Comment by wseltzer** [comment]
A brief form of commitment: 

Non-Member Licensing Commitment from @@Organization@@ to W3C

On behalf of @@Organization@@, as its legal representative, I,
@@Representative@@,

a) have reviewed the @@WG@@ Working Group charter;

b) have reviewed the W3C Patent Policy, in particular the section on licensing obligations for Working Group Participants (section 3.1); and 

c) agree to comply with the Royalty Free licensing commitment of the W3C Patent Policy in the same manner as if @@Organization@@ were a @@WG@@ Working Group Participant.

Signed: ___________________

Date: _____________________

**Comment by dwsinger** [comment]
@wseltzer is that a proposal, or a reflection of current practice, or...?

**Comment by vfournier17** [comment]
Hi Wendy,

I think it would be better to have this (or a similar) document as a click-through agreement or somehow automated, rather than having folks have to print out a document and send it somewhere.  As we discussed at our November meeting, it has been a rare occurrence that someone would print out the document, sign it, and send it to someone.  I don’t think the odds are going to improve with another signed document.


Best regards,

Virginia Fournier
Senior Standards Counsel
 Apple Inc.
☏ 669-227-9595
✉︎ vmf@apple.com <mailto:vmf@apple.com>






On Feb 23, 2018, at 12:24 PM, David Singer <notifications@github.com> wrote:

@wseltzer <https://github.com/wseltzer> is that a proposal, or a reflection of current practice, or...?

**Comment by dwsinger** [comment]
Team and the CG to sort out (a) that the request for commitment is required and (b) make it easy to find the mechanism(s) and (c) that the team needs to handle a flexible way to give the commitment.

**Comment by wseltzer** [comment]
Discussed in PSIG, https://lists.w3.org/Archives/Member/member-psig/2018AprJun/0007.html

**Comment by wseltzer** [comment]
Possible addition: "When a contribution is received for a document under this policy from someone who is not already obligated under the Patent Policy, the team must request a patent commitment from the contributor. The WG chairs or team may reject contributions that do not have an associated patent commitment."

**Comment by dwsinger** [comment]
when I suggested that I got some words wrong...we should word-smith this with lawyers (@vfournier17  ?)

"When a contribution is received for a document under this process from someone who is not already obligated under the Patent Policy, the team must request a licensing commitment, that is congruent to the W3C Patent Policy, from the contributor. The WG chairs or team may reject contributions that do not have such an associated licensing commitment."

(They, or the WG, might reject the idea for other reasons, of course.)

**Comment by chaals** [comment]
This probably satisfies the lawyer in me, but the chair in me finds it very concerning.

First, what is the mechanism for rejecting a contribution? Does this involve flagging something as "subject to unacceptable IPR risk", and watching that it doesn't later get added by someone else? (If not, why not?) What is the time line between a request for patent commitment and rejection? Why is it optional to reject contributions?

Should there be explicit recognition of the difference between substantive and editorial contributions or is that supplied by the context?

**Comment by wseltzer** [comment]
I'm comfortable with no change to Process

**Comment by dwsinger** [comment]
We believe that his procedurally, and does not need any process change. expecting to close unless anyone (AB?) disagrees

**Comment by vfournier17** [comment]
We need to keep this issue open pending the outcome of the discussion in PSIG.  There are a number of issues embedded in this topic that PSIG is still discussing.  It may be that "the team must request a licensing commitment, that is congruent to the W3C Patent Policy, from the contributor" is not specific enough. @HeleneWorkman  I'll forward to other PSIG attorneys who aren't on this repo.

**Comment by chaals** [comment]
I think we need to get the wording right. But I also think it would be helpful to be clear in the process that contributions should be rejected if they don't come with a suitable IPR commitment - and more to the point we should be clear that getting someone else to submit content, or doing that on behalf of someone else, instead of providing a commitment, is a breach of the process because it cirucumvents the intent of the requirement.

**Comment by dwsinger** [comment]
Replying to some of Chaals' questions:

First, what is the mechanism for rejecting a contribution? Does this involve flagging something as "subject to unacceptable IPR risk", and watching that it doesn't later get added by someone else? (If not, why not?) What is the time line between a request for patent commitment and rejection? Why is it optional to reject contributions?

**Comment by dwsinger** [comment]
OK, We Apple folks have tried to get down to the nitty-gritty details. Here is a background and precise proposed text.

Outline (proposed text is below) and discussion:

1) Add to the process that whenever a contribution is received from a non-member of a WG, then the team must ask the contributor to grant a license (outline below), using a suitably simple means such as click-through. They may ask for all contribution classes (clause 6.2.5 of the process document), but must ask for classes 3 and 4 (a technical change).

2) if the license request is *not* granted, then:
a) if it’s class 1 or 2 correction (using the terms of 6.2.5), it’s WG/chair/editor discretion;
b) if it’s a class 3 (correction that does not add features), the WG chair or team contact may choose to accept the fix, but PSIG and TAG must be notified prior to acceptance, and have an opportunity to object.
c) if it’s a class 4 (new feature), then the contributor should be asked to join the WG and re-submit the contribution as a WG member. If the contributor still declines and the chairs determine that the contribution should be accepted nonetheless (because it’s important, obvious, the only way to go, etc.), the chairs may notify TAG of an intent to accept the contribution, and must obtain PSIG approval to accept it, due to the potential IP vulnerability; this exception approach should happen rarely, and preferably never. It is strongly preferred that contributions of features be made by members of the WG.
3) we ask that there be no proxy contributions, and no repeated contribution from the same organization to the same document

The license request is in the form of a click-through agreement that
* includes a representation that the person clicking is authorized to act on behalf of the entity making the contribution (W3C is not required to go investigate each of the accepters).
* grants a license to all claims owned by the contributor that become essential as a result of incorporating the contribution into the draft specification that existed at the time of the contribution, on terms that are defined in section 5 (W3C Royalty-Free (RF) Licensing Requirements) of the W3C Patent Policy.

The formal change is to Add new Section 6.2.6 (Non-Member Contributions) 

"When a contribution to a Technical Report is received from a non-member of a Working Group, the Team must request from the contributor a recorded license to all the contributor’s Essential Claims both in the contribution, and those that become the contributor's Essential Claims as a result of incorporating the contribution into the draft that existed at the time of the contribution, on the terms specified in section 5 (W3C Royalty-Free (RF) Licensing Requirements) of the W3C Patent Policy. 

The chairs MAY accept a contribution of [xlink 6.2.5 class 1 or 2] without a license. For classes 3 and 4, if the license is not granted, the contribution should not be accepted. 

The WG chairs MAY accept a [xlink 6.2.5 class 3] correction that does not add features without a license, if they determine that the correction is technically necessary, provided that they notify TAG and PSIG, and do not receive an objection within 10 working days following such notice. 

The chairs must not accept [xlink 6.2.5  class 4] contributions that add new feature(s) without a license unless they notify the TAG and obtain the explicit approval of PSIG via the PSIG chair (who will represent the consensus of PSIG) in advance.

In all cases, the non-member contributor should be the originator of the contributed material; contributions should not be transferred (e.g. to a member of the working group) in order to circumvent this license requirement. There should be only occasional contributions to a given document from a given non-member contributor; a second or subsequent contribution to the same deliverable of a WG should be made as a member of that WG.”

**Comment by dwsinger** [comment]
To be clear, we are suggesting that this all kicks in *after* the team has determined that a Pull Request or other proposal has come from a non-W3C member or non-WG member.

**Comment by wseltzer** [comment]
Thanks @dwsinger and @vfournier17 I think this is consistent with team practice. 

I propose a slightly-modified paragraph for addition to the Process; and suggest that the other explanatory material go into the Guidebook. In particular, I think we need more thinking on the appropriate reviewers for requests to accept material without a license; team-legal's default will be to reject substantive changes for which the contributor does not give a license. 

"When a contributor who is not a Working Group participant offers a substantive contribution (6.2.5, classes 3 or 4), Team shall request that the contributor make a Royalty-Free patent commitment. Such commitment should cover, at a minimum, all the contributor’s Essential Claims both in the contribution, and those that become the contributor's Essential Claims as a result of incorporating the contribution into the draft that existed at the time of the contribution, on the terms specified in section 5 (W3C Royalty-Free (RF) Licensing Requirements) of the W3C Patent Policy."

**Comment by vfournier17** [comment]
A couple of proposed additions to the above.
1.  The "royalty-free patent commitment" needs to be in writing or other recordable format.  Also, should we identify what the contribution is being made to (i.e., Technical Report? Recommendation-track document?)?
2.  Recommend automating the process to make it more objective.
3.  Need to state that the class 3 or 4 contribution will not be accepted if the contributor does not provide the patent commitment.  Otherwise, those who use or implement the spec could have IP vulnerability.

**Comment by wseltzer** [comment]
As discussed in PSIG: 
"When a contributor who is not a Working Group participant offers a substantive contribution (6.2.5, classes 3 or 4), Team shall secure from the contributor a recorded Royalty-Free patent commitment. Such commitment should cover, at a minimum, all the contributor’s Essential Claims both in the contribution, and those that become the contributor's Essential Claims as a result of incorporating the contribution into the draft that existed at the time of the contribution, on the terms specified in section 5 (W3C Royalty-Free (RF) Licensing Requirements) of the W3C Patent Policy."

**Comment by cwilso** [comment]
LGTM.

**Comment by wseltzer** [comment]
Updated PR https://github.com/w3c/w3process/pull/200
