### ISSUE TITLE
Grace period for contributing to specifications?

### ISSUE THREAD

**Issue by jyasskin** [w3c/w3process#672]
Process 2021 (#527) added a 45-day grace period for attending meetings:

> When a group is re-chartered, individuals participating in the [Working Group](https://www.w3.org/2021/Process-20211102/#GroupsWG) or [Interest Group](https://www.w3.org/2021/Process-20211102/#GroupsIG) before the new Call for Participation may attend any meetings held within forty-five (45) days of the Call for Participation even if they have not yet formally rejoined the group (i.e., committed to the terms of the charter and patent policy).

But this doesn't obviously apply to contributions to specifications or other non-meeting participation, and the IPR bot recently rejected a change (https://github.com/w3c/secure-payment-confirmation/pull/214) that happened 1 day after the [new charter](https://www.w3.org/Payments/WG/charter-2022.html) came into effect. (This was probably unintentional, but still highlights that the Process text isn't clear.)

This might need to be clear about which patent policy governs contributions made during the grace period, and maybe there's some finesse needed about how to do calls for exclusions during the grace period.

**Comment by fantasai** [comment]
The [W3C Patent Policy](https://www.w3.org/Consortium/Patent-Policy-20200915/), which applies to Working Groups (as opposed to CGs) is not contribution-based. It is participation-based. It doesn't matter who contributed material or when, it only matters who is a member of the group and what material that group publishes on /TR.

Roughly speaking:

Material is covered by the patent policy when it is published officially on /TR, and the IPR committed to it is the collective IPR of all the official participants of the group at the time of publication or thereafter.

You can't participate in a call for exclusions if you are not a member of the group. But if you join after an exclusion period has needed, you have an opportunity to exclude upon joining.

All of this is pretty clearly laid out in the patent policy.

As for the IPR bot, what it does is not covered by the Process. :) Its job is just to warn people when something is happening that might be problematic, but it's a very crude instrument for that. I think it would be reasonable to file a suggestion that it not flag members of the previously-chartered edition of the WG during the first 45 days, matching the 45-day grace period for meetings.

**Comment by fantasai** [comment]
I think the grace period is explicitly in the Process to avoid having chairs exclude participants from meetings during that time period.

Contributions to specifications, on the other hand, are not restricted only to members. Anyone can file a PR.

**Comment by TallTed** [comment]
> Contributions to specifications, on the other hand, are not restricted only to members. Anyone can file a PR.

But if they're not a member, they're not signed up to the patent policy and such, so such PRs should not be merged until/unless such agreement is secured.

**Comment by frivoal** [comment]
Yes, and that's covered by https://www.w3.org/2021/Process-20211102/#contributor-license, no?

To make a contribution, either you make yourself subject to the Patent policy by officially joining the group, or you follow those steps for people who're not already covered by the patent policy.

**Comment by fantasai** [comment]
@TallTed IANAL, but IIRC where patents are concerned, what matters isn't who submitted the PR, it's who came up with the idea. If the PR author isn't committed to the patent policy, but is only editing in proposals that were put together by members of the WG, there's no problem from a patent perspective. But if the spec editor is a member of the WG, and merges a PR documenting a proposal from a contributor who is *not* a member of the WG, then we have a patent licensing problem.

So the thing to pay attention to isn't who submitted the PR, and the IPR bot's shenanigans here are not particularly helpful because it makes people think that's what matters, and it's not.

**Comment by fantasai** [comment]
Anyway, closing as out of scope for the Process. But do file an issue on the IPR bot, and email me if you need support. :)

**Comment by frivoal** [comment]
@jyasskin as you opened the issue, I'd like to confirm: are you OK with this issue being closed, for the above reason?

**Comment by jyasskin** [comment]
I'd prefer that the Process treat meeting attendance and spec contributions the same, whether both mention a grace period or both don't. But this isn't a critical issue for me, so if y'all disagree, I'm happy for you to keep the issue closed. Thanks for checking in!

I think I messaged the IPR bot's owner for this issue, and I don't remember if a bug got filed, but I can cite this thread if it's ever a problem in the future.

**Comment by OrKoN** [comment]
I filed an issue for the bot based on this discussion https://github.com/w3c/ash-nazg/issues/268

**Comment by jyasskin** [comment]
In https://github.com/w3c/ash-nazg/issues/268, @dontcallmedom isn't sure whether the discussion here implies that the IPR bot should offer a grace period. My interpretation of @fantasai's comment is that the bot should offer a grace period, but if that's not correct, or not convincing enough to the bot maintainers, I'd appreciate if we could re-open this issue and come to a conclusive answer.

I'm also happy to elaborate further if anyone wants more explanation of why it's a problem for the IPR bot to fail on PRs 1 day after a charter is renewed.

**Comment by dwsinger** [comment]
I think that during the grace period you are clearly operating under all the prerogatives and obligations that came with your membership on the group before the re-charter. I can't see any other answer off the top of my head.
