### ISSUE TITLE
[Editorial] Where Formal Objection is defined, identify milder ways to express disagreement

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/w3process#680]
In section 5.5 (Registering Formal Objections) I think it would be valuable to clarify how a Formal Objection differs from other expressions of disagreement or lack of support. For example, changing this note:

Note: In this document, the term [Formal Objection](https://www.w3.org/Consortium/Process/Drafts/#FormalObjection) is used to emphasize this process implication: Formal Objections receive formal consideration and a formal response. The word “objection” used alone has its ordinary English connotations.

To:

Note: In this document, the term Formal Objection is used to emphasize this process implication: Formal Objections receive formal consideration and a formal response. In some situations, participants may wish to express "lack of support" without triggering formal consideration and response. To that end, W3C provides mechanisms so that participants can express viewpoints on the record such as “lack of support” or “disagreement” or “abstention," none of which require the same formal considerations as a Formal Objection. Because the phrase "Formal Objection" is a term of art in the W3C Process, the word "objection" on its own is considered distinct, with its ordinary English connotations.

**Comment by frivoal** [comment]
That's a good point. However we do have a longer discussion of this topic in an earlier section, so we just added a crosslink in 96d0f24 rather than duplicating text. Let us know if this addresses your concern.

**Comment by frivoal** [comment]
@ianbjacobs Not sure if you saw the message above. This is editorial, so I am assuming this isn't an big deal, and that you're probably happy about the solution taken, but if not, feel free to express your discontent here.
