### ISSUE TITLE
Broken link to suspension guidelines.

### ISSUE THREAD

**Issue by jyasskin** [w3c/w3process#684]
The "Refer to the [Guidelines to suspend or remove participants from groups](https://www.w3.org/Guide/process/banning.html)." link in https://www.w3.org/Consortium/Process/Drafts/#discipline goes to https://www.w3.org/Guide/process/banning.html, which is currently a 404.

**Comment by frivoal** [comment]
For me, https://www.w3.org/Guide/process/banning.html redirects (302) to https://www.w3.org/Guide/process/suspension.html, which does work. Not sure if you hit a transient error, of if someone fixed it since, but things seem fine now. Ok to Close?

**Comment by jyasskin** [comment]
Yep, it works for me too now. Thanks!
