### ISSUE TITLE
Mandate default custodianship for Registries if the specified custodian is no longer available

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/w3process#699]
Arising from the [TTWG's call on 2023-01-19](https://www.w3.org/2023/01/19-tt-minutes.html#t05) and discussion ongoing to create boilerplate for TTWG registries at w3c/ttwg#241, where the idea is to specify that TTWG is the custodian of its own registries, but if TTWG ceases to operate then custodianship would fall back to the Team:

The question arose: shouldn't the Process define a fallback custodian for all W3C Registries if the originally specified custodian is unable to operate? More broadly, if the Registry Definition's process for requesting changes to the Registry is defunct (perhaps the email address has been frozen, etc) what is the default fallback?

It seems unhelpful or impractical for a WG to have to define a process for what happens when the WG no longer exists.

**Comment by frivoal** [comment]
Having the Team as a fall back seems useful, though we probably want to let groups explicitly opt out of that if for some reason their registry has update criteria that wouldn't be appropriate to hand off to the Team.

Maybe we also want to give the Team the ability, when it inherits custody of something, to assign it to some other body, possibly with an AC review to confirm.

**Comment by TallTed** [comment]
> give the Team the ability, when it inherits custody of something, to assign it to some other body

Exactly what occurred to me on reading the OP.

> registry has update criteria that wouldn't be appropriate to hand off to the Team

I suggest that any group realizing such should nominate a few (3? 5? 10?) groups that are expected to endure sufficiently, which groups should then resolve their intent to serve as a potential fall back, among which I would think the Team could choose when needed ... or the nominating group could order their list by preference, which guidance I would think could be followed as with any creator's wishes about their output.

**Comment by dwsinger** [comment]
whoops, good catch. 

(A few years back I had a need to contact all the [Registration Authorities approved by ISO](https://www.iso.org/maintenance_agencies.html), and was unhappy to find how many dead pointers there were. We can and should do better.)

I think the ideal route is something like:
* if the operator of a Registration Authority wishes to retire, they tell us, and we manage the transition in conversation; if the authoring WG still exists, it goes back to them to revise the Rec-track document that defines the authority
* if we close a WG and we know that they are the approval/operator, we ask them to work out what to do before closure
* if nonetheless we end up with a 'dead pointer', yes, the team should have the authority both to become the operator and also the authority to find and assign a better if they wish (and if you don't want the team to do that, well, see steps 1 and 2 and it won't happen)

we need to work out whether such re-assignment should cause a full-track revision of the Rec-track defining document

**Comment by frivoal** [comment]
I suspect it would be OK for a specific registry to opt out of that fallback mechanism if it would be inappropriate for their use case, but as a default if nothing is specified, that does seem reasonable.
