### ISSUE TITLE
Chairs are asking for clarification for Wide Review

### ISSUE THREAD

**Issue by dwsinger** [w3c/w3process#7]
Transferred from https://www.w3.org/community/w3process/track/issues/144
State: Open

**Comment by dwsinger** [comment]
Looking for some analysis

**Comment by jeffjaffe** [comment]
@swickr  has been looking at this.

**Comment by dwsinger** [comment]
The AB discussed how painful it can be to track and document the requests, the comments, the responses by the group(s), the agreement to the response by the groups, the commenter's reaction to the response, and so on.

**Comment by caribouW3** [comment]
IMHO, the original issue was not about painful tracking specifically, but rather about 'have we contacted the right groups/communities/etc.' to get review. The tools for tracking are much easier to use than what was available in the early days of W3C, and that can't really be considered as a Process issue.

**Comment by dwsinger** [comment]
This seems more like an operational issue rather than process. Move to the team?

**Comment by dwsinger** [comment]
moving to the team to discuss as operational, closing.
