### ISSUE TITLE
export registry-related terms for ease of reference

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/w3process#713]
[§6.5.2 Publishing Registries](https://www.w3.org/2021/Process-20211102/#reg-pub) requires that registries link to [§6.5 The Registry Track](https://www.w3.org/2021/Process-20211102/#registries) defined as the term `registry` but does not export the definition `registry` which would make it much easier to reference.

Additionally the terms:
* custodian
* registry definition
* registry entries
* registry table

are useful for referencing when creating a registry definition.

Would it be possible to export those definitions?

**Comment by frivoal** [comment]
Accepted by Editor's discretion.

**Comment by nigelmegitt** [comment]
Many thanks!
