### ISSUE TITLE
Editorial: "W3C" as a proper noun

### ISSUE THREAD

**Issue by koalie** [w3c/w3process#728]
The W3C Comm Team is straightening how we refer to ourselves, which the re-launch as a legal entity gives us an excellent opportunity. Since the Process may be applicable several years, I'd rather fix it sooner than later starting if possible with Process 2023.

Please, replace "(T|t)he W3C" by "W3C" (which in its acronym form we are treating as a proper noun) every time it is not followed by a noun.

E.g., "the organizational structure of the W3C and processes," becomes "the organizational structure of W3C and processes," and "oversees the work of the W3C." becomes "oversees the work of W3C." etc.
(but "information about the W3C mission", or "The W3C Process promotes", etc. are fine)

Other acceptable forms, should you absolutely want to use a definite article, are: "(T|t)he World Wide Web Consortium" and "(T|h)e Web Consortium".

Thank you!

**Comment by frivoal** [comment]
Hi @koalie. I just went through the Process, and made https://github.com/w3c/w3process/pull/730 to fix it as you suggested. As far as I could find, the majority of the uses were with W3C functioning as as an adjective followed by a noun, but I (think I) fixed all the uses of W3C as a proper noun in the way you suggested.
