### ISSUE TITLE
Addressing formal objections before requesting advancement

### ISSUE THREAD

**Issue by jyasskin** [w3c/w3process#737]
https://www.w3.org/Consortium/Process/Drafts/snapshots/2023-04#registering-objections includes:

> Note: [Formal Objections](https://www.w3.org/Consortium/Process/Drafts/snapshots/2023-04#FormalObjection) against matter in a [technical report](https://www.w3.org/Consortium/Process/Drafts/snapshots/2023-04#technical-report) are required to be addressed before [requesting advancement](https://www.w3.org/Consortium/Process/Drafts/snapshots/2023-04#rec-advance) of the [technical report](https://www.w3.org/Consortium/Process/Drafts/snapshots/2023-04#technical-report).

First, a "Note" shouldn't introduce a requirement.

Second, this requirement seems to reverse the usual ordering of things. My understanding is that usually a working group calls for consensus to request advancement, some members might object, they get overruled by the group as a whole, which requests advancement, and then those members formally object to the Team, which follows the rest of the Process to handle the objection. The requirement in this note appears to say that if a member registers their objection to the Team before the end of the call for consensus, the request for advancement has to wait for the entire FO Council process to finish.

This text was introduced by #642, but I don't see discussion about it in that PR.

**Comment by chrisn** [comment]
A minor point, but "against matter in a technical report" could be improved to read "against the content of a technical report".

**Comment by jyasskin** [comment]
First, does the note need to be in this section if its content is already in [§6.3.3](https://www.w3.org/Consortium/Process/Drafts/snapshots/2023-04#transition-reqs)?

If it does need to be here, it would help to reword it in order to say what kind of "addressing" the objections need. The current wording implies to me that the objections need to be addressed using https://www.w3.org/Consortium/Process/Drafts/snapshots/2023-04#addressing-fo instead of the simpler process at https://www.w3.org/Consortium/Process/Drafts/snapshots/2023-04#formally-addressed. Perhaps:

> Before a [=Working Group=] [[#rec-advance|requests advancement]] of a [=technical report=], it needs to [=formally address=] any existing [=Formal Objections=] against matter in that [=technical report=].

**Comment by nigelmegitt** [comment]
That's probably a tidier way of saying what's in the note now @jyasskin.

**Comment by frivoal** [comment]
"formally addressed" and "fully addressed" are actually different things, so I think the rephrasing above would inadvertently make a normative change. Looking into a clarification may be worth doing, but this isn't it.

**Comment by jyasskin** [comment]
This remains a Note, and my suggestion removes the normative wording, so it can't make a normative change. Maybe it misstates the existing normative requirement that's somewhere else? But I used the same one of "formally" or "fully" as in the requirement that Nigel found, so which existing requirement are you thinking of?

**Comment by frivoal** [comment]
> First, a "Note" shouldn't introduce a requirement.

It doesn't introduce the requirement, it references a requirement already normatively established elsewhere. But editorially, it did look wrong. https://github.com/w3c/w3process/pull/803 will address this (and a few similar problems elsewhere in the document)

**Comment by fantasai** [comment]
The proposed replacement reads:

Note: [=Formal Objections=] against matter in a [=technical report=] <a href="https://www.w3.org/Consortium/Process/#adv-verif-reqs">are expected to be fully addressed</a> before <a href="https://www.w3.org/Consortium/Process/#rec-advance">requesting advancement</a> of the [=technical report=].

@jyasskin I think this change would address this issue, let us know if that works for you?

**Comment by jyasskin** [comment]
Yes, #803 is close. I left a [comment](https://github.com/w3c/w3process/pull/803#discussion_r1424405360) about the effect on my second concern in the [OP](https://github.com/w3c/w3process/issues/737#issue-1683979873). If y'all actually did mean to insert W3C Councils before FPWD, CR, and PR, this isn't the issue to question that, but I want to make sure it was intentional.

**Comment by fantasai** [comment]
@jyasskin If there are open FOs against the document, then, yes the Council needs to run before a FPWD/CR/PR/REC can be published. The initial publication of a WD/CR/PR/REC should have no unresolved FOs.

**Comment by frivoal** [comment]
Based on the above, I think this can be closed. @jyasskin, can you confirm?

**Comment by jyasskin** [comment]
Yep, looks resolved to me.

**Comment by frivoal** [comment]
resolved by #803
