### ISSUE TITLE
AC Review dissent requirement vs questionnaire options

### ISSUE THREAD

**Issue by jyasskin** [w3c/w3process#738]
https://www.w3.org/Consortium/Process/Drafts/snapshots/2023-04#ACReviewStart currently includes:

> For clarity, in the context of an [AC Review](https://www.w3.org/Consortium/Process/Drafts/snapshots/2023-04#advisory-committee-review), [dissent](https://www.w3.org/Consortium/Process/Drafts/snapshots/2023-04#def-Dissent) must be expressed as a [Formal Objection](https://www.w3.org/Consortium/Process/Drafts/snapshots/2023-04#FormalObjection).

The [AC Review questionnaire](https://www.w3.org/2002/09/wbs/33280/Process-2023/) (using the Process questionnaire as an example) includes the following options:

- [ ] supports adoption as the W3C Process as is.
- [ ] suggests changes, but supports adoption as the W3C Process whether or not the changes are adopted (your details below).
- [ ] does not support adoption as the W3C Process for the reasons cited in comments but is not raising a Formal Objection
- [ ] suggests changes, and only supports adoption as the W3C Process if the changes are adopted [Formal Objection] (your details below).
- [ ] suggests the document not be adopted as the W3C Process [Formal Objection] (your details below).
 abstains from this review.

The third option looks like a way of dissenting without filing a Formal Objection. Does Process 2023 intend to take away that option in the future?

**Comment by frivoal** [comment]
The third option is a way to express mild disagreement, without stopping the train. "I don't like it, but I can live with it". Process 2023 would not change the availability of that option.

**Comment by jyasskin** [comment]
To help with both this and with the terminology confusion around "sustain" identified in #740, I wonder if it would help to redefine dissent as something like

> At least one individual wishes to prevent the decision from being made. If all individuals are convinced that they can live with the decision, there is no longer dissent, even if some of those individuals would prefer a different decision.

This refocuses the term on the practical effects that people want, rather than their states of mind.

**Comment by nigelmegitt** [comment]
I'm not sure this change is worth the brain effort tbh @jyasskin . "wishes to prevent the decision made" opens up a bunch of other linguistic, semantic and philosophical questions in my head. I'd probably go with "wishes to prevent the proposal from being accepted as a decision" but immediately I then wonder if the thing being reviewed in an AC Review is classed as a "proposal".

**Comment by jyasskin** [comment]
I can buy that "does not support" isn't quite the same as having an objection. I don't support the idea that the Process should take advantage of that subtle distinction, but I don't object to it either. 😉

**Comment by fantasai** [comment]
The idea of not supporting, or even disagreeing with a decision, but also not objecting to it being made is pretty common (and is an important way of getting to consensus).

Afaict the form and afaict the Process are pretty consistent with each other about this? Propose to close no change; @jyasskin do you think I'm missing something here?

Note that “dissent” has a very specific meaning in the Process: https://www.w3.org/Consortium/Process/Drafts/snapshots/2023-04#def-Dissent

**Comment by jyasskin** [comment]
It's ok with me to close this with no change.

I'm still concerned that the language in the Process could be interpreted to mean that an organization can't register its disagreement with a decision through the AC Review without Formally Objecting to it. There is nuance between sustained non-support, sustained disagreement, and dissent (sustained objection), but the Process doesn't mention that nuance, so it could get lost in the future. That said, everyone seems aligned on the practical outcomes we want, so I don't expect problems from this in the next several years. If it looks like it might start being a problem, we can always amend the Process then.
