### ISSUE TITLE
Clarify where Submission Appeals go

### ISSUE THREAD

**Issue by jyasskin** [w3c/w3process#742]
https://www.w3.org/Consortium/Process/Drafts/snapshots/2023-04#Submission says

> If [rejected](https://www.w3.org/Consortium/Process/Drafts/snapshots/2023-04#SubmissionNo), the [Submitter](https://www.w3.org/Consortium/Process/Drafts/snapshots/2023-04#submitter)(s) may initiate a [Submission Appeal](https://www.w3.org/Consortium/Process/Drafts/snapshots/2023-04#SubmissionNo) to either the [TAG](https://www.w3.org/Consortium/Process/Drafts/snapshots/2023-04#technical-architecture-group) or the [Advisory Board](https://www.w3.org/Consortium/Process/Drafts/snapshots/2023-04#advisory-board).

but https://www.w3.org/Consortium/Process/Drafts/snapshots/2023-04#SubmissionNo says

> The procedure for handling Submission Appeals is the same as for [Formal Objections](https://www.w3.org/Consortium/Process/Drafts/snapshots/2023-04#FormalObjection)

where Formal Objections go to an FO Council, not the objector's choice of the TAG or AB.

**Comment by fantasai** [comment]
This is leftover text, so, just removed it. :)

**Comment by ASLE90** [comment]
0

**Comment by ASLE90** [comment]
> 0
