### ISSUE TITLE
Remove normative keywords from non-normative sections

### ISSUE THREAD

**Issue by jyasskin** [w3c/w3process#745]
Bikeshed has a [`Complain About: accidental-2119 yes`](https://speced.github.io/bikeshed/#metadata-complain-about) setting that points out when we've used the RFC2119 keywords (may, must, required, etc.) in non-normative areas like notes. Turning it on for the Process identifies a couple pages of instances. While the Process has a [Conformance](https://www.w3.org/Consortium/Process/Drafts/snapshots/2023-04#w3c-conformance) section saying that the keywords aren't normative when they appear in non-normative sections, it's best practice in specifications to avoid them anyway, to reduce confusion. It'd be good to go through the Process and either reword the keywords where they aren't adding requirements, or make them normative when they are.

I don't think this is needed for this year's Process.

**Comment by TallTed** [comment]
```
Note: For the purposes of the W3C Patent Policy an Obsolete or Superseded Recommendation
has the status of an active Recommendation, although it is not recommended for future
implementation; a Rescinded Recommendation ceases to be in effect and no new licenses
are granted under the Patent Policy.
```

This doesn't appear in #803, so I can't make this suggestion there (yet). Please compare character-by-character, so as not to miss the important inserted comma, among other things.

```
Note: For purposes of the W3C Patent Policy, an Obsolete or Superseded Recommendation
has the status of an active Recommendation, although future implementations are not
advised to follow it (they are advised to follow instead the active superseding or
obsoleting Recommendation); a Rescinded Recommendation ceases to be in effect and no
new licenses are granted under the Patent Policy.
```

**Comment by frivoal** [comment]
@TallTed that's not wrong, but that seems excessive. I think just going with "endorsed" instead of "recommended" would do the job fine (if we want to switch away from "recommended" in the first place).

**Comment by TallTed** [comment]
"endorsed" has a very different meaning than "recommended", in my mind. 

"advised" or "suggested" might work?

**Comment by TallTed** [comment]
(The inserted comma is still very important.)
