### ISSUE TITLE
Avoid using two different meanings of "sustain"

### ISSUE THREAD

**Issue by jyasskin** [w3c/w3process#746]
https://www.w3.org/Consortium/Process/Drafts/#def-Dissent, "At least one individual in the set sustains an objection." uses "sustain" to mean that an individual keeps doing something after discussion.

https://www.w3.org/Consortium/Process/Drafts/#sustain `<dfn>`s "sustain" as the thing a FO Council does when they agree with a Formal Objection.

Discussion in https://github.com/w3c/w3process/pull/740#issuecomment-1525465444 revealed that having both meanings is actively confusing people.

https://github.com/w3c/w3process/issues/738#issuecomment-1526349547 has some possible wording to avoid using "sustain" in the definition of "dissent", although it's not the only wording that could do so, and we'll also have to check all the other uses of "sustain".

**Comment by fantasai** [comment]
A few ideas:

- change the Council to “uphold”
- change the dissent to “maintain”

I think the first option is better...

**Comment by chrisn** [comment]
Previously, consensus was defined as "nobody in the set registers a Formal Objection", and now we have "there is no sustained objection from anybody", with a Note added.

Changing the Council to "uphold" would resolve the ambiguity, but the Note is very unclear what is expected to happen in the presence of a "sustained objection" (that is not a Formal Objection). It's also unclear to me what "some formal contexts" means - the example given is AC Review, but we should be explicit about which other contexts, if any.

I also note that in section 5.7.2 (part of "Advisory Committee Reviews") has:

> The announcement must indicate the level of support for the proposal (consensus or dissent), and specifically whether there were any Formal Objections.

but in an AC review "dissent must be expressed as a Formal Objection" so there isn't a dissent-but-not-FO option here.

Essentially, I'm not following why the idea of "sustained objection" has been added.

**Comment by frivoal** [comment]
@chrisn 

This is partly off topic and was discussed in https://github.com/w3c/w3process/issues/634, but here's a summary:

> the Note is very unclear what is expected to happen in the presence of a "sustained objection" (that is not a Formal Objection)

It means there's no consensus. But groups can still make a decision by a Vote, see https://www.w3.org/Consortium/Process/Drafts/#Votes

>  It's also unclear to me what "some formal contexts" means - the example given is AC Review, but we should be explicit about which other contexts, if any.

I don't think there are any other such contexts at the moment. The note was just trying to avoid accidentally contradict potential future evolutions of the Process. Maybe we should rephrase the note from "in some formal contexts such as AC Reviews" to "in the context of formal AC Reviews".

> Essentially, I'm not following why the idea of "sustained objection" has been added.

1. To make it clear that a sustained objection, even without a Formal Objection, prevents decision by consensus. (It might still be possible to take a decision, but it won't be a conensus decision, and also it won't automatically trigger the FO resolution process.)
2. To allow the definition of consensus to be re-used in contexts where FOs aren't possible (e.g. when making a Council decision).
3. The typical practice in working groups, when wanting to block a consensus decision, was not to actually file a formal FO, but to merely indicate that one objects to the decision, and that has been sufficient for chairs to identify that there is no consensus, even though an FO hasn't actually been filed. So the definition already used in practice wasn't "FOs have been filed" but "people have indicated that they cannot live with the proposed decision, and are likely to file an FO if we go ahead", which is what the updated definition captures.

**Comment by chrisn** [comment]
Thanks @frivoal, that's helpful. I'll file a PR for "formal contexts such as". Otherwise #762 looks good and I'll raise a separate issue if I have other concerns.
