### ISSUE TITLE
Dissent in AC review

### ISSUE THREAD

**Issue by mnot** [w3c/w3process#750]
> For clarity, in the context of an [AC Review](https://www.w3.org/Consortium/Process/Drafts/snapshots/2023-04#advisory-committee-review), [dissent](https://www.w3.org/Consortium/Process/Drafts/snapshots/2023-04#def-Dissent) must be expressed as a [Formal Objection](https://www.w3.org/Consortium/Process/Drafts/snapshots/2023-04#FormalObjection).

That means that the issues that I'm raising now will have to, in the future, each be Formal Objections, since the Process is now in AC Review. Is that really what we want?

**Comment by mnot** [comment]
(the underlying concern is that this makes AC review even more formalistic and adversarial)

**Comment by cwilso** [comment]
> That means that the issues that I'm raising now will have to, in the future, each be Formal Objections, since the Process is now in AC Review. Is that really what we want?

I don't think that's true.  If you, as a Member, would object to the Process being adopted without fixing these issues, then yes; but that *IS* a formal objection.  If you are submitting issues you think it would be nice to fix, then they are comments (and may or may not be addressed before the Process is adopted).

**Comment by mnot** [comment]
/me re-reads -- OK, I see. We seem to have overloaded the word _dissent_ in a very particular way...
