### ISSUE TITLE
Minority Opinions

### ISSUE THREAD

**Issue by mnot** [w3c/w3process#752]
What is the distribution (in particular, confidentiality) of a Minority Opinion? Where is it published -- e.g., is it a Note?

**Comment by frivoal** [comment]
https://www.w3.org/Consortium/Process/Drafts/#council-decision says that the Council report:
> must include the [Minority Opinion](https://www.w3.org/Consortium/Process/Drafts/#minority-opinion)(s), if any.

So the distribution and confidentiality is the same as that of Council Reports, since it's published in it, and it will end up being listed in https://beta.w3.org/about/council/

**Comment by mnot** [comment]
Ah - missed that, thank you.
