### ISSUE TITLE
Should there be good standing / supermajority criteria in authoritative ballots?

### ISSUE THREAD

**Issue by michaelchampion** [w3c/w3process#76]
Appeals of a Director decision are the only place in the W3C Process where voting is used to authoritatively decide issues. Some organizations use "good standing" criteria to help ensure that those voting on authoritative ballots are active members and can thus be assumed to understand the organization's culture and the details of what is being addressed in a ballot.  W3C itself once defined good standing criteria in WG ballots, although that was seldom enforced.  

A related question is whether a supermajority (often 2/3 of votes cast) should be required to overturn a Director's decision.

While consensus is highly unlikely in time for Process 2018, the Process CG, AB, and AC should investigate what criteria other organizations use in authoritative ballots, whether they could feasibly be applied to W3C, and whether it would be consistent with W3C's principles and culture to apply these criteria in appeal ballots.

**Comment by dwsinger** [comment]
see also #131 , super-majority for appeal.  we'll track this bug as being the good-standing/voting-criteria question.

see the questions at https://www.w3.org/wiki/Process2018#.2348_The_appeals_process_doesn.27t_actually_describe_how_an_appeal_finishes_2

**Comment by chaals** [comment]
IMHO we should close this issue, since it seems we are unlikely to reach consensus on such a change.

If that changes, we can re-open or make a new issue.

**Comment by jeffjaffe** [comment]
This should really be looked at more in the context of director-free.

**Comment by michaelchampion** [comment]
Closing, no discussion here for more than 2 years, and the AB seems to be discussing it in their private space.
