### ISSUE TITLE
New W3C Council and updated TAG Composition section errantly only includes Tim Berners-Lee...

### ISSUE THREAD

**Issue by tantek** [w3c/w3process#764]
While this is clearly not what the Experimental Formal Objection Council has been doing in practice, nor what was intended in Process 2023, the current language in the definition of the [W3C Council Composition](https://www.w3.org/Consortium/Process/Drafts/snapshots/2023-04#council-composition) only includes "_members_ of the Technical Architecture Group" (_emphasis_ added), and the only literal _member_ in the definition of the [Composition of the Technical Architecture Group](https://www.w3.org/Consortium/Process/Drafts/snapshots/2023-04#tag-participation) is Tim Berners-Lee, while the elected &amp; appointed are labeled _participants_. By using different terms "member" and "participant" for disjoint sets of people, a literal reading must treat these as separate sets, and thus references elsewhere in the Process to "members" cannot be assumed to include "participants". This is not just ambiguity, a literal reading of the current Process 2023 draft _forces_ an undesired composition of W3C Councils that only includes Tim Berners-Lee from the TAG in particular.

We believe the opposite was intended, and this can be fixed by using the term "member" in the Composition of the Technical Architecture Group section to refer to the elected &amp; appointed, and separately listing Tim as a "life-time invited participant, but not a member of the TAG for purposes of this document."

This requires a Pull Request (PR) and we will work on submitting one that we believe addresses this issue which we believe must be a blocker for Process 2023.

Similarly, for consistency and to reduce the chance of confusion, only the term "member" should be used to refer to those [elected to the Advisory Board](https://www.w3.org/Consortium/Process/Drafts/snapshots/2023-04#ABParticipation), rather than "participant". This can go in a separate PR, and we will work on providing this as well.

Label: Needs Proposed PR

Label: Director-free: FO/Council

(Originally published at: https://tantek.com/2023/143/b1/)

**Comment by fantasai** [comment]
This interpretation would rely on the notion that "participant" and "members" are distinct notions, and that if you're one, you're not the other. This is not the case, in fact the Process explicitly defines them as equivalent terms: 

> For the purposes of this Process, a W3C Group is one of W3C’s Working Groups, Interest Groups, Advisory Committee, Advisory Board, or TAG, and a participant is a member of such a group.

&mdash; https://www.w3.org/Consortium/Process/Drafts/#groups

As such, I believe this issue is invalid and as co-chair and co-editor I intend to close it as such in the Disposition of Comments. Please let me know if you have a compelling argument to the contrary.

**Comment by frivoal** [comment]
Also note that the Council experiments have been run according to the intended meaning of the text, where Timbl and elected TAG seats and appointed TAG seats are all part of the set that goes into the dismissal Process, with the non-dismissed people going on to form the Council—as you can see in Council Reports published after the requirement to list members was enacted:
* https://www.w3.org/2023/03/council-ttwg-report.html
* https://www.w3.org/2022/11/council-das-report.html

**Comment by tantek** [comment]
Thanks [@fantasai](https://github.com/fantasai), despite multiple reviews, somehow missed that [https://www.w3.org/Consortium/Process/Drafts/snapshots/2023-04#groups](https://www.w3.org/Consortium/Process/Drafts/snapshots/2023-04#groups) line:
&gt; … and a participant is a member of such a group.

This resolves the semantics of the first paragraph of this issue as invalid, leaving only potential editorial confusion from the use of multiple terms for the same thing, which is not a MUSTFIX (issue title adjusted accordingly).

(Originally published at: https://tantek.com/2023/144/t3/)

**Comment by tantek** [comment]
Thanks for the FO Council experiments reports citations [@frivoal](https://github.com/frivoal).

&gt; [https://www.w3.org/2023/03/council-ttwg-report.html](https://www.w3.org/2023/03/council-ttwg-report.html)
&gt; [https://www.w3.org/2022/11/council-das-report.html](https://www.w3.org/2022/11/council-das-report.html)

These two make it clear that Tim Berners-Lee was a member of at least two FO Council experiments, despite not participating in their final decisions.

From these examples, we retract the premise of the second paragraph of this issue that "We believe the opposite was intended", and thus also the specific fix in that paragraph.

We still think it would be better for the W3C Process for any "life member" of any group to be a non-voting member at most, however we will raise a separate new issue for that for consideration in the normal workflow of triaging &amp; handling Process CG issues.

Given the resolution of the semantics of the first two paragraphs for this issue, no Pull Request (PR) is necessary for those.

For the remaining "consistency and to reduce the chance of confusion" point, as noted, that can go in a separate purely editorial issue/PR and is thus unnecessary to resolve this specific issue.

Ok to close this issue without waiting for those separate issues/PRs to be filed.

(Originally published at: https://tantek.com/2023/144/t4/)
