### ISSUE TITLE
Normative prose for role of Chair / Team Contact cites informative reference for description

### ISSUE THREAD

**Issue by tantek** [w3c/w3process#765]
There are two sentences of normative prose that cite the informative [Art of Consensus](https://www.w3.org/Guide/) as [GUIDE] in the [Informative References](https://www.w3.org/Consortium/Process/Drafts/snapshots/2023-04#informative).

The two sentences are in the [Requirements for All Chartered Groups](https://www.w3.org/Consortium/Process/Drafts/snapshots/2023-04#ReqsAllGroups), specifically these two:

<blockquote>The role of the Chair [CHAIR] is described in the Art of Consensus [GUIDE].</blockquote>

...

<blockquote> The role of the Team Contact [TEAM-CONTACT] is described in the Art of Consensus [GUIDE]. </blockquote>

It is inconsistent and misleading for a normative sentence to claim that a description (implied to be normative from that context) is written in an informative reference.

It also seems like a bad practice to import via prose "is described in " and essentially upgrade-by-reference external informative content into normative context.

The relatively quick short-term fix would be to mark those quoted sentences of prose non-normative. E.g. move the above quoted sentences to their own class="note" role="note" paragraphs as:

<blockquote> Note: The role of the Chair [CHAIR] is described in the Art of Consensus [GUIDE]. </blockquote> <blockquote> Note: The role of the Team Contact [TEAM-CONTACT] is described in the Art of Consensus [GUIDE]. </blockquote>

respectively. That way the inline prose is clearly non-normative, consistent with the informative imports from and citations of the Art of Consensus [GUIDE]. We will work on a Pull Request to address this.

Label: Needs Proposed PR

(Originally published at: https://tantek.com/2023/143/b2/)

**Comment by frivoal** [comment]
I concur that turning these sentences into Notes would be better. That would match their intent, and would avoid the normative-informative tension you commented about.
