### ISSUE TITLE
Japanese translation of Process 2021

### ISSUE THREAD

**Issue by xueyuanjia** [w3c/w3process#767]
Hi,

Yoshikazu Takamura, a longtime contributor in W3C translators community, has [announced](https://lists.w3.org/Archives/Public/w3c-translators/2023AprJun/0014.html) a  [Japanese translation](http://takamu.sakura.ne.jp/mathml/w3c/Process-20211102-ja.html) for [Process 2021](https://www.w3.org/2021/Process-20211102/).

W3C [translations Database](https://www.w3.org/Translations/) only includes translations for technical reports, so I am forwarding the translation here (hoping it's the right place to raise this 😊) . 

Any chance the Process Task Force wants to have the translation linked somewhere and make it more visible?

Thank you!

**Comment by plehegar** [comment]
I'm sorry but this seems late unfortunately :(

We're getting close to adopt a new W3C Process for W3C, which is a major revision. It seems counter-productive at this time to point the community to Process 2021 or one of its translations, as we're just about to replace it...

**Comment by yonaomi** [comment]
Got them all. I'll contact Yoshikazu for the situations and upload his translation onto the Japanese page. Thanks Xueyuan for raising this up. Please close this issue.

**Comment by ytakamu** [comment]
Thanks for raising this issue and commenting here.
I am author of Japanese translation, and I understand present situation.
Please close this issue.

**Comment by xueyuanjia** [comment]
Many thanks @plehegar @yonaomi @ytakamu I'm now closing this issue then.

**Comment by frivoal** [comment]
At the same time, while there are some very important changes in (proposed) Process 2023, many parts of the Process do remain the same since 2021. It will need an update, but starting from a 2021 version means that most of the work is already done. I think having a 2023 version would be fantastic.
@ytakamu P2021年版お疲れ様でした。もし2023年版も作成する予定でしたら、質問がある場合、是非ご連絡ください！
