### ISSUE TITLE
Stop citing the "superseded" TAG charter

### ISSUE THREAD

**Issue by jyasskin** [w3c/w3process#794]
There are 2 references to the [TAG charter](https://www.w3.org/2004/10/27-tag-charter.html) from https://www.w3.org/2023/Process-20230612/#tag-role, but the TAG charter now says, "14 May 2023 status update: This charter has been superseded per resolution of the TAG and a similar resolution by the W3C Advisory Board. The W3C Process Document henceforth describes the role, composition, and other aspects of the TAG." Whatever bits of the TAG charter are still relevant should get moved into this section, or into another non-superseded document that this section can cite.

**Comment by frivoal** [comment]
Agreed. It is not clear to me that anything needs to be moved from that superseded charter to the Process. Unless someone identifies something that needs to be salvaged, I will soon make a pull request simply removing the references to it.

**Comment by plehegar** [comment]
The Revising W3C Process CG just discussed `#794`.

<details><summary>The full IRC log of that discussion</summary>
subtopic: #794<br>
florian: TAG had a charter and we agreed to supercede it. the Process still refers to it and we should remove those.<br>
... if something else needs to happen, file a separate.<br>
&lt;TallTed> +1 editorial<br>
Resolved: the editor will deal with #794 and solve it on their own.<br>
</details>
