### ISSUE TITLE
Unclear grammar in Abstract

### ISSUE THREAD

**Issue by LJWatson** [w3c/w3process#80]
It isn't clear who "they" is, in this sentence from the abstract:
>"The W3C Process Document describes the organizational structure of the W3C and the processes related to the responsibilities and functions they exercise to enable W3C to accomplish its mission.">

Might be:
>"The W3C Process Document describes the organizational structure of the W3C and the processes related to the responsibilities and functions its members exercise to enable W3C to accomplish its mission.">

Or perhaps:
>"The W3C Process Document describes the organizational structure of the W3C and the processes related to the responsibilities and functions it exercises to enable W3C to accomplish its mission.">

**Comment by chaals** [comment]
What about 

> The W3C Process Document describes the organizational structure of the W3C and the processes, responsibilities and functions that enable W3C to accomplish its mission

**Comment by LJWatson** [comment]
I have a fork/branch open with a couple of other minor things. Do you want me to include this?

**Comment by chaals** [comment]
Yes please, that would be great.
