### ISSUE TITLE
W3C Decision needs better cross-referencing

### ISSUE THREAD

**Issue by fantasai** [w3c/w3process#802]
A couple points:
* The dfn for W3C Decision isn't obviously referencing https://www.w3.org/2023/Process-20231103/#ACReviewAfter
* It's unclear whether the appeals process is included in a W3C Decision or if it's something else; which way this is clarified might make a difference in how it's invoked from other places.

**Comment by frivoal** [comment]
I added a cross-link in this editorial commit: dcd212d3cc2dbb3972b4c68deb730117513d0feb. I think that's enough to address the core of this issue.

**Comment by fantasai** [comment]
Added a PR to also improve the headings in the target section: https://github.com/w3c/w3process/pull/806

I think we also, as a group, should discuss the definition of “W3C Decision”, its relationship to “AC Appeals”, and how best to invoke all of this machinery from various places.
