### ISSUE TITLE
Duplicated links

### ISSUE THREAD

**Issue by LJWatson** [w3c/w3process#82]
Throughout the document there are links to external resources that are immediately followed by internal links that duplicate the original link. For example in 2.3 Advisory Board (AB), there is a link to the "Advisory Board homepage". It's followed by an internal linnk to "Pub30", which points to the 12.2 Public Resources section. The reference for "Pub30" is a link to "The Advisory Board homepage".

It seems that the references do not provide any further information, and therefore it's unclear what purpose the references sections provide in this situation? Meanwhile, the duplicated links reduce usability for keyboard only users, and readability for many people.

If the original intent of this approach was to include the full URL in the references section (to enable people printing the Process to know where links lead), it has at some point been abandoned. If this was so, a better way to solve the problem would be to insert the URL immediately after the link text when the document is printed (a short amount of CSS work), and then remove the internal links/references from the default/screen view.

**Comment by chaals** [comment]
I would prefer to keep the visual pointer that something is an external reference in the on-screen version. Maybe the best way to do this is to un-link it, or to use a `data-refname` and CSS to make it available. I'll think about the mechanics, and schedule this to be dealt with before the formal version for AC review.

**Comment by dwsinger** [comment]
@chaals do we have a fix for this for the published version?
