### ISSUE TITLE
Run link checker on Process Drafts

### ISSUE THREAD

**Issue by plehegar** [w3c/w3process#824]
Several documents have moved around in past 2 years and we need to update the links in the Process.

**Comment by yahyafurkann** [comment]
WE3 2004

**Comment by frivoal** [comment]
Is there some list of what replaces what, or do I need to try and follow all the links manually and see if any redirects?

**Comment by plehegar** [comment]
> Is there some list of what replaces what, or do I need to try and follow all the links manually and see if any redirects?

The [linkchecker](https://validator.w3.org/checklink?url=https://www.w3.org/Consortium/Process/Drafts/) reports several redirects.

**Comment by frivoal** [comment]
Fixed all those that come directly from the Process' source. The rest (https://www.w3.org/standards/types#CG-DRAFT -> https://www.w3.org/standards/types/#CG-DRAFT, https://www.w3.org/copyright/software-license/ -> https://www.w3.org/copyright/software-license-2023/) are bikeshed generated.
