### ISSUE TITLE
TAG appointment ambiguity about ratification by both AB and TAG

### ISSUE THREAD

**Issue by frivoal** [w3c/w3process#836]
https://www.w3.org/Consortium/Process/Drafts/#TAG-appointments has this sentence:

> The [Team](https://www.w3.org/Consortium/Process/Drafts/#team)'s choice of appointee(s) is subject to ratification by secret ballot by both the [AB](https://www.w3.org/Consortium/Process/Drafts/#advisory-board) and the [TAG](https://www.w3.org/Consortium/Process/Drafts/#technical-architecture-group), each requiring a two-thirds approval.

There was some confusions as to what "each" means, the two possible alternative being:
* each appointee must reach 2/3 approval (of the TAG+AB counted as one body)
* the TAG and AB must each separately reach a 2/3 approval threshold for the appointment to be ratified.

Based on the issue and commit that introduced this (https://github.com/w3c/w3process/issues/715 and https://github.com/w3c/w3process/commit/bcc08778105583c1cd8302db14e4af107b51d7c4), I think it is clear that the second meaning is intended.

We should clarify that to avoid confusion.

**Comment by martinthomson** [comment]
> The [Team](https://www.w3.org/Consortium/Process/Drafts/#team)'s choice of appointee(s) is subject to ratification by secret ballot by both the [AB](https://www.w3.org/Consortium/Process/Drafts/#advisory-board) and the [TAG](https://www.w3.org/Consortium/Process/Drafts/#technical-architecture-group), each requiring a two-thirds approval.

The word "each" here implies distribution of the statement following to multiple items in the preceding text.

I see four interpretations:

1. The approval needs to reach two thirds of the *ballot* for each *appointee*.
2. The approval needs to reach two thirds of the *ballot* for each *ratifying body*.
3. The approval needs to reach two thirds of the *sitting members* for each *appointee*.
4. The approval needs to reach two thirds of the *sitting members* for each *ratifying body*.

This issue covers one point of distribution here.  There, the question is whether the "each" applies to the bodies (TAG and AB) rather than the appointees.  I think that points to option 4, but this could be clearer still.

**Comment by frivoal** [comment]
For the "of the ballot vs of the ratifying body" question, see also https://github.com/w3c/w3process/issues/838

**Comment by TallTed** [comment]
Oh dear. There are additional interpretations. I don't think the intent has ever been for such approval votes as these to cover a *roster* of appointees (as interpretations 2 and 4 above imply), but rather to be held for *each* appointee (no matter their number).

5. The approval needs to reach two thirds of the _ballot_ of each _ratifying body_ for each _appointee_.
6. The approval needs to reach two thirds of the _sitting members_ of each _ratifying body_ for each _appointee_.

I think these are the live possibilities for this particular text segment. I don't think the 4 above are viable nor what was intended.

My _sense_ is that _ballot_ is how the existing text has been read, but it is entirely possible that _sitting members_ was the original intent. I could probably be convinced either way by folks who have a longer history of working on these documents.

**Comment by frivoal** [comment]
Made the proposed change, and pinged the TAG about it.

**Comment by torgo** [comment]
I agree this is less ambiguous. However, I think it's also less desirable. To be clear, I think the "each" should apply to each prospective appointee rather than within each group - though I recognise (now) that this isn't what the Process CG had in mind.

**Comment by TallTed** [comment]
> `RESOLVED: Change "each" to "from each" as described above, and ask if anyone can find an ambiguity in it`

Yes. There is remaining ambiguity. I think either of the changes represented below (I prefer the first) would resolve what remains and represents original intent.


<strike>`        The [=Team=]'s choice of appointee(s)`</strike>
**`        Each appointee chosen by the [=Team=]`**
`        is subject to ratification by secret ballot`
`        by both the [=AB=] and the [=TAG=],`
`        requiring a two-thirds approval from each.`

or
`        The [=Team=]'s choice of appointee(s)`
<strike>`        is subject to ratification by secret ballot`</strike>
`        is subject to ratification `
**`        of each appointee`**
`        by secret ballot`
`        by both the [=AB=] and the [=TAG=],`
`        requiring a two-thirds approval from each.`

**Comment by cwilso** [comment]
To be clear, when we (process cg) first developed this process, my clear recollection of the intent was to ratify as a whole, not individual appointees.  The idea was essentially that the Team would work with the TAG to understand the missing expertise and agree on appointees, then have the whole ratified.

**Comment by TallTed** [comment]
@cwilso — OK. Presuming that your recollection is confirmed, then this version removes the same ambiguity —

`        The [=Team=]'s choice of appointee(s)`
`        as a whole`
`        is subject to ratification by secret ballot`
`        by both the [=AB=] and the [=TAG=],`
`        requiring a two-thirds approval from each.`

**Comment by frivoal** [comment]
I'd prefer to have a separate issue about whether appointees should be confirmed individually or as a set, so that we can discuss the pros and cons about that prior to discussing the phrasing.

**Comment by martinthomson** [comment]
Suggestion:

> The Teams choice of appointee(s) is ratified separately by the TAG and by the AB.  The Team is required to run a secret ballot with each group, which passes if two thirds of the group (rounded up) approve.

Note that this addresses two concerns:
1. TAG and AB separately or together.
2. Whether the threshold is sitting members or ballots.

The third concern, whether each appointee is individual affirmed, is not addressed.  I personally have no opinion on that matter, though I might prefer to leave the decision to the Team as to whether the ratification is batched or per-appointee.  (Once resolved, I would ask that a sentence be added to memorialize that decision.  But that can happen later.)

**Comment by TallTed** [comment]
@frivoal — I'm fine with splitting out the questions of individual vs group confirmation, and of sitting members vs ballot casters. My comments since https://github.com/w3c/w3process/issues/836#issuecomment-2022906227 were based on —

> ask if anyone can find an ambiguity in it

**Comment by frivoal** [comment]
This narrow issue about ambiguity of phrasing is now closed through merging https://github.com/w3c/w3process/pull/837. The broader discussion of TAG appointments remains open in https://github.com/w3c/w3process/issues/809, https://github.com/w3c/w3process/issues/810, https://github.com/w3c/w3process/issues/811
