### ISSUE TITLE
Ambiguity about (super) majority thresholds: of those voting, or of those eligible to vote?

### ISSUE THREAD

**Issue by frivoal** [w3c/w3process#838]
There are a few couple of places in the Process which define a decision as being made by a majority or a super majority, without being clear about whether we consider the (super) majority of those who did vote, or of those who were eligible to vote regardless of whether they did. Some are also ambiguous about whether we how we count explicit "abstain" votes. We should disambiguate. The appropriate answer might differ case by case, and we might need to split this issue if some of these points turn out to be contentious, but here's a first pass at it.

1. https://www.w3.org/Consortium/Process/Drafts/#ABParticipation:
    > The Chair(s) are subject to ratification by secret ballot by two thirds of the AB upon appointment.

    I think the intent is two thirds or more of those eligible to vote (i.e., AB elected participants). Clarification might not be completely necessary here, but we could go with
    > […] two thirds of <del>the AB</del><ins>AB elected participants</ins> […]

    to make sure there is absolutely no doubt.

2. https://www.w3.org/Consortium/Process/Drafts/#TAG-appointments
    > The Team's choice of appointee(s) is subject to ratification by secret ballot by both the AB and the TAG, each requiring a two-thirds approval.

    This is the one I am least sure about. I'm tempted to go with ratification failing if 1/3 or more of those eligible to vote explicitly vote against.
     

3. https://www.w3.org/Consortium/Process/Drafts/#council-participation
    > each dismissal is decided by simple majority of those not abstaining.

    I used to think this was not ambiguous, because I thought that "abstaining" meant "not participating in a vote", but I have been told that native English speakers take it to mean "explicitly decline to take sides". I think we should go with

    > each dismissal is enacted if there are more ballots for than against

4. https://www.w3.org/Consortium/Process/Drafts/#council-deliberations
    > However, if despite careful deliberation a W3C Council is unable to reach consensus, the W3C Council Chair may instead resort to voting. In that case, the decision is made by simple majority, with the W3C Council Chair breaking any tie.

    Suggestion:
    > […]the decision is <del>made by simple majority</del><ins>approved if there are more votes in favor than against</ins>[…]

----
Note: Here are other cases of majority or super majority, which in my view, are already non ambiguous.

5. https://www.w3.org/Consortium/Process/Drafts/#council-delegation
    > A decision to delegate must be supported by a two-thirds supermajority vote (i.e., at least twice as many votes in favor as against).

6. https://www.w3.org/Consortium/Process/Drafts/#ABParticipation and https://www.w3.org/Consortium/Process/Drafts/#tag-participation
    > Chair selection must be run at least at the start of each regular term, as well as when a majority of the participants request it

**Comment by TallTed** [comment]
For (1), `Upon appointment, the Chair(s) are subject to ratification by secret ballot, requiring approval by two thirds of the elected participants.`

**Comment by fantasai** [comment]
For completion, here's the other options:
> Upon appointment, the Chair(s) are subject to ratification by secret ballot, requiring approval by two thirds of the elected AB participants.

> Upon appointment, the Chair(s) are subject to ratification by secret ballot, requiring approval by two thirds of the elected participants of the AB.

**Comment by TallTed** [comment]
For (3), `each dismissal is decided by simple majority of those voicing a preference`

**Comment by TallTed** [comment]
For all votes where abstention (no vote) and/or explicit-neither-yes-nor-no (vote submitted with voiced no preference) is ignored, probably need to be explicit about this ignoring.

**Comment by frivoal** [comment]
Landed [a commit](https://github.com/frivoal/w3process/commit/76ab28c830e7f7c1857f03957ac712ea98489b49) directly for case 1, since we had a resolution with explicit phrasing, and made [a PR for case 3](https://github.com/w3c/w3process/pull/841) as well as [one for case 4](https://github.com/w3c/w3process/pull/842).
