### ISSUE TITLE
Public Working Draft or Working Draft?

### ISSUE THREAD

**Issue by LJWatson** [w3c/w3process#84]
In 6.1.1 Recommendations and Notes, it says:
>"2. Publication of zero or more revised Public Working Drafts.">

Similarly, in 6.3 Working Drafts there is a reference to a Public Working Draft". There are other references to both Working Draft and Public Working Draft throughout - but if there is no material difference, it would be good to choose one term and use it consistently.

**Comment by dwsinger** [comment]
There have been WGs in the past that operated mostly in member-state. we discourage this but IIRC we don't disallow it (and we probably shouldn't)

**Comment by chaals** [comment]
Even in that case, their published Working Drafts on /TR were Public. Which is part of how the name got to include "Public".

I would be happy to harmonise everything to say "Working Draft". The Patent Policy tends to use that term - but "First Public Working Draft" for the relevant specific case.

**Comment by chaals** [comment]
@dwsinger can we get a resolution one way or another for the draft that goes for formal AC review please?

**Comment by LJWatson** [comment]
It seems that "First Working Draft" and "Working Draft" cover the use case, so suggest adopting those simpler terms instead of "First Public Working Draft" and "Public Working Draft".

**Comment by dwsinger** [comment]
We were also asking internally whether First Public Working Draft was a defined term of the process document (and hence capitalized) or only of the Patent Policy.

The Patent Policy is full of references to First Public Working Draft and refers to the Process to define that term. So let's not change that. The PP also has exactly one reference to "public working draft" that is not first.

*If* it is true that all drafts that a Working Group agrees are Working Drafts are always Public, then I would change every occurrence of "public working draft" that is not preceded by "first" to delete the word "public", and then revise 6.3's content:

A Working Draft is published on the W3C's Technical Reports page [PUB11] for public review, and for simple historical reference. For all Working Drafts a Working Group:

should document outstanding issues, and parts of the document on which the Working Group does not have consensus, and
may request publication of a Working Draft even if its content is considered unstable and does not meet all Working Group requirements.

**Comment by wseltzer** [comment]
Let's retain the term "First Public Working Draft," as it has become a known term even if there are no longer likely to be restricted Working Drafts that precede it.

**Comment by dwsinger** [comment]
No argument about retaining the term FPWD. The question is whether we need to distinguish Public and non-Public working drafts. It seems that member-only drafts are now rare but not explicitly disallowed, so I suggest close-no-change (keep the word in the process and other documents, as only Public working drafts count.)

**Comment by chaals** [comment]
I am not sure where a Working Draft is allowed not to be Public. It is defined as "a document published on w3.org/TR" which is public.

That said I don't care much what we call them - my preference to remove the word "Public" is barely worth the effort of this comment and a related commit if we decide that way :)

**Comment by dwsinger** [comment]
Agreed "A Working Draft is a document that W3C has published for review by the community, including W3C Members, the public, and other technical organizations." Therefore we could take 'public' out in all cases not preceded by "first" (because we need to keep FPWD as a term) but I really don't care if we do or not.

**Comment by xfq** [comment]
In https://www.w3.org/Guide/staff-contact, I found the phrase "internal Working Drafts".

I also found one such document here: https://www.w3.org/WAI/GL/Glossary/printable.html (and @chaals is one of its editors)

IIUC we don't produce this kind of document any more?

**Comment by chaals** [comment]
These are Editor's drafts, and we now have a style for them (we didn't have, many years ago when that glossary thing was being put together).

**Comment by xfq** [comment]
Thanks for the hint @chaals! I just submitted a PR in w3c/Guide#1.
