### ISSUE TITLE
Retire the "Streamlined Publication Approval" system

### ISSUE THREAD

**Issue by frivoal** [w3c/w3process#856]
I believe that [Streamlined Publication Approval](https://www.w3.org/Consortium/Process/Drafts/#streamlined-update) is unused. 

The motivation for this Process feature is described at the begining of the section:

> In order to streamline the publication process in non-controversial cases, verification of an [update request](https://www.w3.org/Consortium/Process/Drafts/#update-requests) is automatically granted without formal review when the following additional criteria are fulfilled: […]
> 
> Note: These criteria are intentionally stricter than the general requirements for an [update request](https://www.w3.org/Consortium/Process/Drafts/#update-requests). This is in order to minimize ambiguities and the need for expert judgment, and to make self-evaluation practical.

In practice, nobody has found it useful to place the additional burden on themselves to document that all additional criteria are fulfilled in order to save a little bit of time by spiking verification of the update request, nor requested improved tooling to make that easier. (@plh, could you confirm?)

We should admit that this is a failed experiment, and remove it from the Process. Rules about REC track transitions are complicated enough without confusing people with irrelevant clauses.

**Comment by nigelmegitt** [comment]
Data would certainly be helpful here. This is ringing tiny bells for me that we may once have either used it or relied on the possibility of using it, in order to make a decision.

**Comment by fantasai** [comment]
I think what's happened is that the standard process has been streamlined enough that we don't need to implement this additional system. :) So +1 to removing it.
