### ISSUE TITLE
Duplication of text

### ISSUE THREAD

**Issue by LJWatson** [w3c/w3process#86]
In 6.1.2 Maturity levels it says "Working Group Note, Interest Group Note (NOTE)". Is the "(Note)" needed?

**Comment by chaals** [comment]
It's the standard shorthand / abbreviation, as CR, REC, etc. Note that "(PR)" is missing, as are formal status for edited, obsolete and superseded Recs. We should fix this one way or another. My preference is to leave them **in** and mark them as `abbr` properly, but I'm not that fussed. Thoughts?

**Comment by dwsinger** [comment]
do we need an acronyms&terms section?

**Comment by nrooney** [comment]
Sent PR. Suggest we close this and open a new issue for acronyms&terms section.

Opened in #198

**Comment by nrooney** [comment]
Going to continue on issue #198
