### ISSUE TITLE
FPWD and joint deliverables—the process may be missing an exclusion opportunity

### ISSUE THREAD

**Issue by hober** [w3c/w3process#869]
Suppose the following happens:

1. Group A gets chartered to deliver Spec 1.
2. Group A goes to FPWD with Spec 1.
3. Group B gets chartered, and Group A re-chartered, to make Spec 1 a joint deliverable of both groups.
4. Time passes. Work on the spec progresses.
5. Spec 1 makes it to CR and then REC.

Now, suppose an organization in Group B leaves it before (5) occurs. I suspect there may be a hole in the current process here. Ideally, that organization would be on the hook for Spec 1, IPR-wise, but it seems like maybe they aren't? There has not been an [Exclusion Opportunity](https://www.w3.org/Consortium/Patent-Policy-20200915/#exclusion-opportunity).

The obvious remedy that springs to mind: when adding a spec to a working group as a joint deliverable with another WG, when that spec has already gone to FPWD in the original group, some kind of FPWD moment should be automatically triggered in the new group.

**Comment by fantasai** [comment]
That spec should be added to the charter of Group B as an Adopted Draft. The exclusion opportunity is then the same as joining Group A after it's been rechartered after the FPWD opportunity has passed.

**Comment by frivoal** [comment]
I concur with @fantasai. I think the Patent Policy could be a little more explicit about how rechartering / joint deliverable, but even if it's a little indirect about that aspect, I think the backing is given by https://www.w3.org/Consortium/Patent-Policy-20200915/#sec-join

Whether the FPWD was published by the same group or not is immaterial. It's a deliverable of that group, and people are joining the group.

**Comment by fantasai** [comment]
(This question really belongs to PSIG.)

**Comment by dwsinger** [comment]
It might belong to the team; it's possible that there was an exclusion opportunity that wasn't communicated?

**Comment by plehegar** [comment]
(cc @rigow)

I concur with @fantasai and @florian as well. The exclusion opportunity does exist.

Joining a Working Group with published Working Drafts listed as deliverables creates an exclusion opportunity (see
[4.3. Joining an Already Established Working Group](https://www.w3.org/Consortium/Patent-Policy-20200915/#sec-join)).  That opportunity is up to 150 days after the FPWD, or upon joining the group if the FPWD was published more than 150 days ago.

We do not currently send separate messages to remind folks about this.

Nowadays, the joint form simply indicates:
[[
have reviewed the W3C Patent Policy, in particular the section on licensing obligations for Working Group Participants ([section 3.1](https://www.w3.org/Consortium/Patent-Policy/#sec-W3C-RF-license)) (the Group Charter indicates the Patent Policy under which the group operates), and agree to all of the provisions of the W3C Patent Policy, including the commitment to comply with the W3C RF licensing requirements. (Required)
]]
