### ISSUE TITLE
Define "normally" in 6.2.2

### ISSUE THREAD

**Issue by LJWatson** [w3c/w3process#87]
In 6.2.2 Advancement on the Recommendation Track, it says:
>"Transition Requests to First Public Working Draft or Candidate Recommendation will not normally be approved while a Working Group's charter is undergoing or awaiting a Director's decision on an Advisory Committee Review.">

If not "normally" then under which circumstances might the transition be approved? If the exception(s) can't be clarified, suggest removing "normally" from the text.

**Comment by dwsinger** [comment]
I think the implication is that if you want to achieve something that's not normal, you'll have to ask/fight for it. I hesitate to spell this out in detail.

**Comment by chaals** [comment]
I believe we should close this - re-open if you think it is important please.
