### ISSUE TITLE
update graphics

### ISSUE THREAD

**Issue by chaals** [w3c/w3process#91]
Make sure they reflect the latest process version. See also #29

**Comment by dwsinger** [comment]
can we deal with #29 at the same time?

**Comment by chaals** [comment]
> yes...

**Comment by nrooney** [comment]
#29 is closed - can we close this too?

**Comment by dwsinger** [comment]
I think we're awaiting an edit to the diagrams that change (align) terminology (e.g. "minor changes" should be "editorial changes")

**Comment by chaals** [comment]
@frivoal I think you could close this - it's a generic reminder that we would like better stuff.
