### ISSUE TITLE
consider keeping 'other than to remove features explicitly identified as "at risk"'?

### ISSUE THREAD

**Issue by dbaron** [w3c/w3process#97]
I'm reviewing the [diff](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FConsortium%2FProcess%2F&doc2=https%3A%2F%2Fw3c.github.io%2Fw3process%2F) between the [operational Process](https://www.w3.org/Consortium/Process/) and the [editor's draft](https://w3c.github.io/w3process/), and I noticed that in the first sentence of 6.4.1 (Revising a Candidate Recommendation), the phrase:

> other than to remove features explicitly identified as "at risk"

was removed.  While it was repeating information available elsewhere, I think it does make things much clearer at a point where it's useful to make them clear.  That is, I think it helped with the goal of making it possible to read just the relevant part of the process rather than reading whole sections, and also with making the **must** statement a complete statement, rather than one patched elsewhere.

So I think it would be good to keep that bit.

**Comment by michaelchampion** [comment]
Agree with @dbaron -- some editorial changes are being made in with the goal of making the document more concise, but have the effect of making it harder to understand the process without grokking the whole document.

**Comment by chaals** [comment]
It was removed in clarifying how to publish a revised CR that didn't have **substantive** changes.

I believe the intent is that all revisions need to be approved (and in general announced), although removal of features at risk, like editorial changes, **should** be approved as straightforwardly as FPWDs are.

So I propose *not* to add the phrase back in - but we should look at this issue @dwsinger

**Comment by dwsinger** [comment]
We concluded that the document is mildly inconsistent without it and agreed on Nov 1st to put it back.

**Comment by dwsinger** [comment]
revert accepted, closing
