### ISSUE TITLE
changes section is incomplete

### ISSUE THREAD

**Issue by dbaron** [w3c/w3process#98]
I'm reviewing the [diff](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FConsortium%2FProcess%2F&doc2=https%3A%2F%2Fw3c.github.io%2Fw3process%2F) between the [operational Process](https://www.w3.org/Consortium/Process/) and the [editor's draft](https://w3c.github.io/w3process/), and I noticed that the changes section seems substantially incomplete.

At a glance (I didn't review exhaustively), it is missing the following substantive changes:
* the introduction of of the ability to request "extended review"
* the introduction of Amended Recommendation
* the introduction of Superseded Recommendation
* clarifications of the rules for AC appeals

**Comment by michaelchampion** [comment]
the removal of ‘In the case of Advisory Board and TAG elections, "one vote" means "one vote per available seat’  from 7.3 -- isn’t mentioned  in the changes section either

**Comment by chaals** [comment]
> the introduction of of the ability to request "extended review"

Mentioned for section 5.2.3 but I will add the explicit terminology

> the introduction of Amended Recommendation
> the introduction of Superseded Recommendation
> clarifications of the rules for AC appeals

Yep. I'll add these.
